### PR TITLE
Fix analysisd json null fields

### LINKED ISSUE #7486: Analysisd does not correctly change the option json_null_fields correctly
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0 | analysisd | Manager | Packages/Sources | CentOS Linux release 8.3.2011|

Analysisd does not correctly change the option json_null_fields (https://documentation.wazuh.com/4.0/user-manual/ruleset/ruleset-xml-syntax/decoders.html#json-null-field) correctly. After trying to change through the different options (string,discard,empty) I noticed that the discard option does not work. After investigation I reach the code that would do the flag setup of the option: https://github.com/wazuh/wazuh/blob/master/src/analysisd/decoders/decode-xml.c#L459. In this block of code is where the flags are setup, however, the flags do not come empty with predefined values being setup in https://github.com/wazuh/wazuh/blob/master/src/analysisd/decoders/decode-xml.c#L298. The values are defined in their headers having the following values setup:

|Option |Value|
|---|---|
|DISCARD|0|
|EMPTY|1|
|SHOW_STRING|2|
|CSV_STRING|4|
|JSON_ARRAY|8|

The default values set at https://github.com/wazuh/wazuh/blob/master/src/analysisd/decoders/decode-xml.c#L298 are **SHOW_STRING | JSON_ARRAY** this will rend the operation as 2+8=A(hex) then the code performs the necessary adjustments with the operation:

`pi->flags |= <DISCARD/EMPTY/SHOW_STRING>;
`
However being discard the NULL value the operation will never change its flag due to the bitwise operation:

`pi->flags |= DISCARD;
A |= 0 <=> A
`

Here are the values that are possible to get from the default setted A flag with the JSON_ARRAY:

|Option |Value (hex)|
|---|---|
|DISCARD| A |
|EMPTY|B |
|SHOW_STRING|A|

Values from patched code

Since the type of the flag value is **u_int8_t** maybe a better alternative is to use the most significant part for the JSON_ARRAY and CSV_STRING (since we either have one or another) and the least significant part for the rest so we can perform bitwise operations such as:

|Option |Value|
|---|---|
|CSV_STRING|16|
|JSON_ARRAY|32|

`pi->flags = pi->flags & 0x0f +<CSV_STRING/JSON_ARRAY> // (for the most significant bit, assuming the CSV_STRING JSON_ARRAY and  such as 16 and 32 to avoid overlapping, otherwise we need to shift the values to the left)
`

`pi->flags = pi->flags & 0xf0 +<DISCARD/EMPTY/SHOW_STRING> // (for the least significant bit)`

### PR DESCRIPTION
**Pull request by juliancnn**
|Related issue|
|---|
|Closes #7486 |

Hi team,

This PR solves the following bugs:

- Fix load config of element `json_null_field` and `json_array_structure`
- Treatment of JSON null fields
- Output in `archive.log`, `alerts.log` and `archive.json` files
- Remove the last `,` character when json_array_structure is treated as csv.

It also implements the following improvements:

- Case-insensitive in `json_null_field` and `json_array_structure` loading configuration.
- Replaces errors with warnings in case of misconfigurations, taking the default settings and continuing with the analysisd operation.
- Deprecate `empty` value in `json_null_field` option

#### Decoders

```xml
<decoder name="decoder_null_test">
  <program_name>^decoder_null_test</program_name>
</decoder>

<decoder name="decoder_null_test">
  <parent>decoder_null_test</parent>
  <prematch>123456 </prematch>
  <plugin_decoder offset="after_prematch">JSON_Decoder</plugin_decoder>
  <json_null_field>XXX</json_null_field>
  <json_array_structure>XXX</json_array_structure>
</decoder>
```

#### Rules

```xml
  <rule id="100015" level="4">
    <field name="fielA">hi</field>
    <description>test description var: $(null_tst)</description>
  </rule>
```
#### Log test

```
Dec 25 20:45:02 MyHost decoder_null_test[12345]: 123456 { "fielA" : "hi", "array_test" : ["AAA", "BBB", "CCC"], "null_tst" : null}
```

Embedded Json

```json
{
    "fielA": "hi",
    "array_test": [
        "AAA",
        "BBB",
        "CCC"
    ],
    "null_tst": null
}
```

#### Netcat test
Syslog tcp  port 600
```
echo 'Dec 25 20:45:02 MyHost decoder_null_test[12345]: 123456 { "fielA" : "hi", "array_test" : ["AAA", "BBB", "CCC"], "null_tst" : null}' | nc -v -w 0 192.168.0.35 600
```

### Bad config

```xml
<json_null_field>string1234</json_null_field>
<json_array_structure>csv1234</json_array_structure>
```

console output

```console
/var/ossec/bin/wazuh-control restart                                  
2021/03/02 15:46:34 wazuh-analysisd: WARNING: (7602): Invalid value 'string1234' in 'json_null_field' option (decoder `decoder_null_test`). Default value will be taken
2021/03/02 15:46:34 wazuh-analysisd: WARNING: (7602): Invalid value 'csv1234' in 'json_array_structure' option (decoder `decoder_null_test`). Default value will be taken
wazuh-clusterd not running...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
```

### Deprecated empty value

```xml
<json_null_field>empty</json_null_field>
```
console output
```console
╰─# /var/ossec/bin/wazuh-control restart                                                                                                                                                                                          130 ↵
2021/03/02 19:57:20 wazuh-analysisd: WARNING: (7603): Deprecated value 'empty' in 'json_null_field' option (decoder `decoder_null_test`). Default value will be taken
wazuh-clusterd not running...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
```

### String + CSV

```
<json_null_field>string</json_null_field>
<json_array_structure>csv</json_array_structure>
```
#### Alert.log
```
** Alert 1614708186.6376745: - local,syslog,sshd,
2021 Mar 02 18:03:06 MyHost->192.168.0.5
Rule: 100015 (level 4) -> 'test description var: null'
Dec 25 20:45:02 MyHost decoder_null_test[12345]: 123456 { "fielA" : "hi", "array_test" : ["AAA", "BBB", "CCC"], "null_tst" : null}
fielA: hi
array_test: AAA,BBB,CCC
null_tst: null
```
#### alert.json / archive.json
```json
{
    "timestamp": "2021-03-02T18:03:06.027+0000",
    "rule": {
        "level": 4,
        "description": "test description var: null",
        "id": "100015",
        "firedtimes": 1,
        "mail": false,
        "groups": [
            "local",
            "syslog",
            "sshd"
        ]
    },
    "agent": {
        "id": "000",
        "name": "35-u20-manager4"
    },
    "manager": {
        "name": "35-u20-manager4"
    },
    "id": "1614708186.6376745",
    "full_log": "Dec 25 20:45:02 MyHost decoder_null_test[12345]: 123456 { \"fielA\" : \"hi\", \"array_test\" : [\"AAA\", \"BBB\", \"CCC\"], \"null_tst\" : null}",
    "predecoder": {
        "program_name": "decoder_null_test",
        "timestamp": "Dec 25 20:45:02",
        "hostname": "MyHost"
    },
    "decoder": {
        "parent": "decoder_null_test",
        "name": "decoder_null_test"
    },
    "data": {
        "fielA": "hi",
        "array_test": "AAA,BBB,CCC",
        "null_tst": "null"
    },
    "location": "192.168.0.5"
}
```
#### archive.log
```
2021 Mar 02 18:03:06 MyHost->192.168.0.5 Dec 25 20:45:02 MyHost decoder_null_test[12345]: 123456 { "fielA" : "hi", "array_test" : ["AAA", "BBB", "CCC"], "null_tst" : null}
```

### Discard + array
```
<json_null_field>discard</json_null_field>
<json_array_structure>array</json_array_structure>
```

#### Alert.log
```
** Alert 1614708572.6679790: - local,syslog,sshd,
2021 Mar 02 18:09:32 MyHost->192.168.0.5
Rule: 100015 (level 4) -> 'test description var: '
Dec 25 20:45:02 MyHost decoder_null_test[12345]: 123456 { "fielA" : "hi", "array_test" : ["AAA", "BBB", "CCC"], "null_tst" : null}
fielA: hi
array_test: ["AAA", "BBB", "CCC"]
```
#### alert.json /  archive.json
```json
{
    "timestamp": "2021-03-02T18:09:32.555+0000",
    "rule": {
        "level": 4,
        "description": "test description var: ",
        "id": "100015",
        "firedtimes": 1,
        "mail": false,
        "groups": [
            "local",
            "syslog",
            "sshd"
        ]
    },
    "agent": {
        "id": "000",
        "name": "35-u20-manager4"
    },
    "manager": {
        "name": "35-u20-manager4"
    },
    "id": "1614708572.6679535",
    "full_log": "Dec 25 20:45:02 MyHost decoder_null_test[12345]: 123456 { \"fielA\" : \"hi\", \"array_test\" : [\"AAA\", \"BBB\", \"CCC\"], \"null_tst\" : null}",
    "predecoder": {
        "program_name": "decoder_null_test",
        "timestamp": "Dec 25 20:45:02",
        "hostname": "MyHost"
    },
    "decoder": {
        "parent": "decoder_null_test",
        "name": "decoder_null_test"
    },
    "data": {
        "fielA": "hi",
        "array_test": [
            "AAA",
            "BBB",
            "CCC"
        ]
    },
    "location": "192.168.0.5"
}
```
#### archive.log
```
2021 Mar 02 18:09:32 MyHost->192.168.0.5 Dec 25 20:45:02 MyHost decoder_null_test[12345]: 123456 { "fielA" : "hi", "array_test" : ["AAA", "BBB", "CCC"], "null_tst" : null}
```

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [ ] ~MAC OS X~
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [ ] Package upgrade
- [x] Review logs syntax and correct language
- [ ] ~QA templates contemplate the added capabilities~

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [ ] ~Dr. Memory~
  - [ ] ~AddressSanitizer~

- [x] Retrocompatibility with older Wazuh versions
- [x] Working on cluster environments
- [x] Configuration on demand reports new parameters
- [x] The data flow works as expected (agent-manager-api-app)

### CODE REVIEW

**Review by jnasselle — DISMISSED** [review]
LGTM!

**Review by JcabreraC — CHANGES_REQUESTED** [review]
When the value `cvs` is set to the `<json_array_structure>` label, the result has an extra comma at the end:
```
Dec 25 20:45:02 MyHost decoder_null_test[12345]: 123456 { "fielA" : "hi", "array_test" : ["AAA", "BBB", "CCC"], "null_tst" : null}
```

Alert.log:
```
** Alert 1614860495.582974: - null-test
2021 Mar 04 13:21:35 MyHost->/home/cabrera/logs/localfiles/test1.log
Rule: 100015 (level 4) -> 'test description var: null'
Dec 25 20:45:02 MyHost decoder_null_test[12345]: 123456 { "fielA" : "hi", "array_test" : ["AAA", "BBB", "CCC"], "null_tst" : null}
fielA: hi
array_test: AAA,BBB,CCC,
null_tst: null
```

Although it is not in the development scope, we could take advantage of the PR to fix it.

**Review by jnasselle — APPROVED** [review]

**Review by nmkoremblum — APPROVED** [review]
LGTM :D!

**Review by JcabreraC — APPROVED** [review]
LGTM !!

**Pull request merged**
