### PR TITLE
Extract debug info from executables.

### PR DESCRIPTION
**Pull request by aritosteles**
## Related issue
Implement debug symbol generation during the build process for Windows. #https://github.com/wazuh/wazuh/issues/21733

## Description
Modified generate_wazuh_msi.ps1 to scan for executable files and dlls and extract debug info from them using cv2pdb.
Compressed resulting pdbs into zip file.

## Configuration options
- Follow [Wazuh package generation guide](https://documentation.wazuh.com/current/development/packaging/generate-windows-package.html) until  you have obtained the zip with the compiled agent and copied it along with generate_wazuh_msi.ps1 script to the Windows host. 
- Make sure you have Visual Studio 2022 Community with the following components:
 
image

- Make sure you have a copy of cv2pdb.exe and add the folder in the PATH environment variable.
- Make sure you change the security policy to run Powershell scritps. To do this, open Powershell as Administrator and enter the command "Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Bypass -Force"
- Run the script in the Windows host.
- If you don't have Wix installed you will get an error indicating that candle.exe and light.exe are missing but by then the process of extracting the debug information from the executables should be completed. Check for debug-symbols.zip to be present in the folder where you ran the script (wazuh\wazuh-4.7.3\src\win32)
- Script output should look like this:
image

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [x] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

### CODE REVIEW

**Comment by tdrauncieal** [comment]
Please,
Assign yourself this PR and link it to the related issue in the Development section, on the right.

Also show some evidence related to the process and/or the files generated.

**Comment by aritosteles** [comment]
> Please, Assign yourself this PR and link it to the related issue in the Development section, on the right.

Done.

> Also show some evidence related to the process and/or the files generated.

Capture of the process console output:
image

**Review by ncvicchi — APPROVED** [review]
LGTM!

**Review by Leoquicenoz — APPROVED** [review]
LGTM!!

**Review by tdrauncieal — APPROVED** [review]
LGTM!

**Pull request merged**
