### PR TITLE
Registry UT: syscheck_config

### LINKED ISSUE #6339: Fim registry improvement unit tests, test_syscheck_config and test_syscheck files modify
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.0 | Syscheck | Agent | Sources | Windows |

## test_syscheck_config and test_syscheck

The tests **test_getSyscheckConfig_no_directories**, test_Start_win32_Syscheck_dirs_and_registry are failing, it is necessary to modify them.
It is necessary to add all the new registry features of the configuration to the test, to check that all the configuration related to the registries is tested.

### PR DESCRIPTION
**Pull request by antoniomanuelfr**
|Related issue|
|---|
|#6339|

## Description

After the development of #5576, the unit tests need to be adapted. This PR aims to adapt the tests in the file `test_syscheck_config.c`
Closes #6339

### Test syscheck_config
```
[==========] tests: Running 9 test(s).
[ RUN      ] test_Read_Syscheck_Config_success
[       OK ] test_Read_Syscheck_Config_success
[ RUN      ] test_Read_Syscheck_Config_invalid
[       OK ] test_Read_Syscheck_Config_invalid
[ RUN      ] test_Read_Syscheck_Config_undefined
[       OK ] test_Read_Syscheck_Config_undefined
[ RUN      ] test_Read_Syscheck_Config_unparsed
[       OK ] test_Read_Syscheck_Config_unparsed
[ RUN      ] test_getSyscheckConfig
[       OK ] test_getSyscheckConfig
[ RUN      ] test_getSyscheckConfig_no_audit
[       OK ] test_getSyscheckConfig_no_audit
[ RUN      ] test_getSyscheckConfig_no_directories
[       OK ] test_getSyscheckConfig_no_directories
[ RUN      ] test_getSyscheckInternalOptions
[       OK ] test_getSyscheckInternalOptions
[ RUN      ] test_SyscheckConf_DirectoriesWithCommas
[       OK ] test_SyscheckConf_DirectoriesWithCommas
[==========] tests: 9 test(s) run.
[  PASSED  ] 9 test(s).
```

### Test syscheck
```
[==========] tests: Running 11 test(s).
[ RUN      ] test_fim_initialize
[       OK ] test_fim_initialize
[ RUN      ] test_fim_initialize
[       OK ] test_fim_initialize
[ RUN      ] test_fim_initialize_error
[       OK ] test_fim_initialize_error
[ RUN      ] test_read_internal
[       OK ] test_read_internal
[ RUN      ] test_read_internal_debug
[       OK ] test_read_internal_debug
[ RUN      ] test_Start_win32_Syscheck_no_config_file
[       OK ] test_Start_win32_Syscheck_no_config_file
[ RUN      ] test_Start_win32_Syscheck_corrupted_config_file
[       OK ] test_Start_win32_Syscheck_corrupted_config_file
[ RUN      ] test_Start_win32_Syscheck_syscheck_disabled_1
[       OK ] test_Start_win32_Syscheck_syscheck_disabled_1
[ RUN      ] test_Start_win32_Syscheck_syscheck_disabled_2
[       OK ] test_Start_win32_Syscheck_syscheck_disabled_2
[ RUN      ] test_Start_win32_Syscheck_dirs_and_registry
[       OK ] test_Start_win32_Syscheck_dirs_and_registry
[ RUN      ] test_Start_win32_Syscheck_whodata_active
[       OK ] test_Start_win32_Syscheck_whodata_active
[==========] tests: 11 test(s) run.
[  PASSED  ] 11 test(s).
```

### CODE REVIEW

**Review by jesusjimsa — CHANGES_REQUESTED** [review]
test_syscheck_config failed in my computer:
```
[==========] Running 9 test(s).
[ RUN      ] test_Read_Syscheck_Config_success
[       OK ] test_Read_Syscheck_Config_success
[ RUN      ] test_Read_Syscheck_Config_invalid
[       OK ] test_Read_Syscheck_Config_invalid
[ RUN      ] test_Read_Syscheck_Config_undefined
[       OK ] test_Read_Syscheck_Config_undefined
[ RUN      ] test_Read_Syscheck_Config_unparsed
[       OK ] test_Read_Syscheck_Config_unparsed
[ RUN      ] test_getSyscheckConfig
[  ERROR   ] --- 0x0 != 0x4
[   LINE   ] --- /home/vagrant/wazuh/src/unit_tests/syscheckd/test_syscheck_config.c:310: error: Failure!
[  FAILED  ] test_getSyscheckConfig
[ RUN      ] test_getSyscheckConfig_no_audit
[       OK ] test_getSyscheckConfig_no_audit
[ RUN      ] test_getSyscheckConfig_no_directories
[       OK ] test_getSyscheckConfig_no_directories
[ RUN      ] test_getSyscheckInternalOptions
[       OK ] test_getSyscheckInternalOptions
[ RUN      ] test_SyscheckConf_DirectoriesWithCommas
[       OK ] test_SyscheckConf_DirectoriesWithCommas
[==========] 9 test(s) run.
[  PASSED  ] 8 test(s).
[  FAILED  ] 1 test(s), listed below:
[  FAILED  ] test_getSyscheckConfig

 1 FAILED TEST(S)
```

**Comment by antoniomanuelfr** [comment]
> _Read_Syscheck_Config_unparsed
> [ RUN      ] test_getSyscheckConfig
> [  ERROR   ] --- 0x0 != 0x4
> [   LINE   ] --- /home/vagrant/wazuh/src/unit_tests/sysch

This test is failing due to a typo in the function  `GetSyscheckConfig` #6451

**Review by jesusjimsa — APPROVED** [review]
LGTM!

**Review by Molter73 — CHANGES_REQUESTED** [review]
I just run the tests under Windows and the code coverage is way too low, please try to improve this by adding some more configurations and checking them in the existing tests.

imagen

[coverage-report.zip](https://github.com/wazuh/wazuh/files/5523454/coverage-report.zip)

**Review by Molter73 — APPROVED** [review]
LGTM!

**Pull request merged**
