### PR TITLE
Add CIS policy "Ensure XD/NX support is enabled" back for SCA

### PR DESCRIPTION
**Pull request by vikman90**
|Related issue|
|---|
|#7314|

As explained in #7314, this PR aims to restore the SCA policy "Ensure XD/NX support is enabled", which was removed because it produced a large output that made the agent consume too much memory.

In addition, the command rules were adapted to shell scripts, that SCA will be able to run after completing issue #3340.

## Tests

- [ ] Run the affected policy in CentOS 6.
- [x] Run the affected policy in CentOS 7. 
- [ ] Run the affected policy in Debian 10.

### CODE REVIEW

**Comment by jctello** [comment]
Due to the large nature of the files and that many white spaces have been removed in comparison to the master branch of the `wazuh-ruleset` (which I previously reviewed) I like to summarize the non-whitespace changes of this PR here:
```
$ diff -w wazuh/ruleset/sca/centos/6/cis_centos6_linux.yml wazuh-ruleset/sca/centos/6/cis_centos6_linux.yml 
615c615
<       - 'c:sh -c "dmesg | grep NX" -> r:NX \(Execute Disable\) protection: active'
---
>       - 'c:dmesg -> r:NX \(Execute Disable\) protection: active'
```
```
$ diff -w wazuh/ruleset/sca/centos/7/cis_centos7_linux.yml wazuh-ruleset/sca/centos/7/cis_centos7_linux.yml 
658,659c658,659
<       - 'c:sh -c "journalctl | grep \"protection: active\"" -> r:^kernel:\s+NX \(Execute Disable\) protection: active'
<       - 'c:sh -c "[[ -n $(grep noexec[0-9]*=off /proc/cmdline) || -z $(grep -E -i \" (pae|nx) \" /proc/cpuinfo) || -n $(grep \"\\sNX\\s.*\\sprotection:\\s\" /var/log/dmesg | grep -v active) ]] && echo \"NX Protection is not active\"" -> r:^$'
---
>       - 'c:journalctl -> r:^kernel:\s+NX \(Execute Disable\) protection: active'
>       - 'c:dmesg -> r:NX \(Execute Disable\) protection: active'
```
```
$ diff -w wazuh/ruleset/sca/debian/cis_debian7.yml wazuh-ruleset/sca/debian/cis_debian7.yml 
425c425
<       - 'c:sh -c "dmesg | grep NX" -> r:NX \(Execute Disable\) protection: active'
---
>       - 'c:dmesg -> r:NX \(Execute Disable\) protection: active'
```
```
$ diff -w wazuh/ruleset/sca/debian/cis_debian8.yml wazuh-ruleset/sca/debian/cis_debian8.yml 
502c502
<       - 'c:sh -c "dmesg | grep NX" -> r:NX \(Execute Disable\) protection: active'
---
>       - 'c:dmesg -> r:NX \(Execute Disable\) protection: active'

```
```
$ diff -w wazuh/ruleset/sca/debian/cis_debian9.yml wazuh-ruleset/sca/debian/cis_debian9.yml 
490c490
<       - 'c:sh -c "dmesg | grep NX" -> r:NX \(Execute Disable\) protection: active'
---
>       - 'c:dmesg -> r:NX \(Execute Disable\) protection: active'

```
```
$ diff -w wazuh/ruleset/sca/debian/cis_debian10.yml wazuh-ruleset/sca/debian/cis_debian10.yml 
586c586
<       - 'c:sh -c "journalctl | grep \"protection: active\"" -> r:NX \(Execute Disable\) protection: active'
---
>       - 'c:journalctl -> r:NX \(Execute Disable\) protection: active'

```
```
$ diff -w wazuh/ruleset/sca/rhel/6/cis_rhel6_linux.yml wazuh-ruleset/sca/rhel/6/cis_rhel6_linux.yml 
631c631
<       - 'c:sh -c "dmesg | grep NX" -> r:NX \(Execute Disable\) protection: active'
---
>       - 'c:dmesg -> r:NX \(Execute Disable\) protection: active'
3272a3273,3276
> 
> 
> 
> 

```
```
$ diff -w wazuh/ruleset/sca/rhel/7/cis_rhel7_linux.yml wazuh-ruleset/sca/rhel/7/cis_rhel7_linux.yml 
678,679c678,679
<       - 'c:sh -c "journalctl | grep \"protection: active\"" -> r:^kernel:\s+NX \(Execute Disable\) protection: active'
<       - 'c:sh -c "[[ -n $(grep noexec[0-9]*=off /proc/cmdline) || -z $(grep -E -i \" (pae|nx) \" /proc/cpuinfo) || -n $(grep \"\\sNX\\s.*\\sprotection:\\s\" /var/log/dmesg | grep -v active) ]] && echo \"NX Protection is not active\"" -> r:^$'
---
>       - 'c:journalctl -> r:^kernel:\s+NX \(Execute Disable\) protection: active'
>       - 'c:dmesg -> r:NX \(Execute Disable\) protection: active'
```

**Review by jctello — COMMENTED** [review]
I do not see any issues with this PR. 
However until https://github.com/wazuh/wazuh/issues/3340 is not resolved it is not possible to thoroughly test these changes.

**Comment by chemamartinez** [comment]
I've already tested the added commands over the changes introduced at https://github.com/wazuh/wazuh/pull/7307.

**Case 1**

- Command: `'c:sh -c "dmesg | grep NX" -> r:NX \(Execute Disable\) protection: active'`
- Log output:
```
2021/02/05 10:51:13 sca[525215] wm_sca.c:1567 at wm_sca_read_command(): DEBUG: Command 'sh -c "dmesg | grep NX"' returned code 0
2021/02/05 10:51:13 sca[525215] wm_sca.c:1833 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:NX \(Execute Disable\) protection: active)([    0.000000] NX (Execute Disable) protection: active) -> 1
2021/02/05 10:51:13 sca[525215] wm_sca.c:1836 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:NX \(Execute Disable\) protection: active)([    0.000000] NX (Execute Disable) protection: active) -> 1
2021/02/05 10:51:13 sca[525215] wm_sca.c:1623 at wm_sca_read_command(): DEBUG: Result for (r:NX \(Execute Disable\) protection: active)(sh -c "dmesg | grep NX") -> 1
2021/02/05 10:51:13 sca[525215] wm_sca.c:1088 at wm_sca_do_scan(): DEBUG: Command output matched.
```
- Result: the command works and the output matches as expected

**Case 2**

- Command: `'c:sh -c "journalctl | grep \"protection: active\"" -> r:^kernel:\s+NX \(Execute Disable\) protection: active'`
- Log output:
```
2021/02/05 10:51:13 sca[525215] wm_sca.c:1004 at wm_sca_do_scan(): DEBUG: Considering rule: 'c:sh -c "journalctl | grep \"protection: active\"" -> r:^kernel:\s+NX \(Execute Disable\) protection: active'
2021/02/05 10:51:13 sca[525215] wm_sca.c:1085 at wm_sca_do_scan(): DEBUG: Running command: 'sh -c "journalctl | grep \"protection: active\""'
2021/02/05 10:51:13 sca[525215] wm_sca.c:1561 at wm_sca_read_command(): DEBUG: Executing command 'sh -c "journalctl | grep \"protection: active\""', and testing output with pattern 'r:^kernel:\s+NX \(Execute Disable\) protection: active'
2021/02/05 10:51:14 sca[525215] wm_sca.c:1567 at wm_sca_read_command(): DEBUG: Command 'sh -c "journalctl | grep \"protection: active\""' returned code 0
2021/02/05 10:51:14 sca[525215] wm_sca.c:1833 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:^kernel:\s+NX \(Execute Disable\) protection: active)(nov 13 10:47:47 wazuh kernel: NX (Execute Disable) protection: active) -> 0
2021/02/05 10:51:14 sca[525215] wm_sca.c:1623 at wm_sca_read_command(): DEBUG: Result for (r:^kernel:\s+NX \(Execute Disable\) protection: active)(sh -c "journalctl | grep \"protection: active\"") -> 0
```
- Result: The command runs without any problem. However, the output does not match since the output of the `journalctl` command has the format `<timestamp> <hostname> kernel: ...` while the check looks for a line starting by `^kernel`. Removing the `^` at the start of the regex part should work. This error is not introduced by this PR.

**Case 3**


- Log output:
```
2021/02/05 11:20:38 sca[56938] wm_sca.c:1004 at wm_sca_do_scan(): DEBUG: Considering rule: 'c:sh -c "[[ -n $(grep noexec[0-9]*=off /proc/cmdline) || -z $(grep -E -i \" (pae|nx) \" /proc/cpuinfo) || -n $(grep \"\\sNX\\s.*\\sprotection:\\s\" /var/log/dmesg | grep -v active) ]] && echo \"NX Protection is not active\"" -> r:^$'
2021/02/05 11:20:38 sca[56938] wm_sca.c:1085 at wm_sca_do_scan(): DEBUG: Running command: 'sh -c "[[ -n $(grep noexec[0-9]*=off /proc/cmdline) || -z $(grep -E -i \" (pae|nx) \" /proc/cpuinfo) || -n $(grep \"\\sNX\\s.*\\sprotection:\\s\" /var/log/dmesg | grep -v active) ]] && echo \"NX Protection is not active\""'
2021/02/05 11:20:38 sca[56938] wm_sca.c:1561 at wm_sca_read_command(): DEBUG: Executing command 'sh -c "[[ -n $(grep noexec[0-9]*=off /proc/cmdline) || -z $(grep -E -i \" (pae|nx) \" /proc/cpuinfo) || -n $(grep \"\\sNX\\s.*\\sprotection:\\s\" /var/log/dmesg | grep -v active) ]] && echo \"NX Protection is not active\""', and testing output with pattern 'r:^$'
2021/02/05 11:20:38 sca[56938] wm_sca.c:1567 at wm_sca_read_command(): DEBUG: Command 'sh -c "[[ -n $(grep noexec[0-9]*=off /proc/cmdline) || -z $(grep -E -i \" (pae|nx) \" /proc/cpuinfo) || -n $(grep \"\\sNX\\s.*\\sprotection:\\s\" /var/log/dmesg | grep -v active) ]] && echo \"NX Protection is not active\""' returned code 1
2021/02/05 11:20:38 sca[56938] wm_sca.c:1833 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:^$)(EMPTY_LINE) -> 0
2021/02/05 11:20:38 sca[56938] wm_sca.c:1836 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:^$)(EMPTY_LINE) -> 0
2021/02/05 11:20:38 sca[56938] wm_sca.c:1623 at wm_sca_read_command(): DEBUG: Result for (r:^$)(sh -c "[[ -n $(grep noexec[0-9]*=off /proc/cmdline) || -z $(grep -E -i \" (pae|nx) \" /proc/cpuinfo) || -n $(grep \"\\sNX\\s.*\\sprotection:\\s\" /var/log/dmesg | grep -v active) ]] && echo \"NX Protection is not active\"") -> 0
```
- Result: the command result code is 1 since does not return any value. The regex `r:^$` is not matching with the output read by SCA `EMPTY_LINE` so the check fails.

_Note: tested in Ubuntu 20 and CentOS 7_

**Review by jctello — CHANGES_REQUESTED** [review]
Compiled the `master` branch of this repository on a CentOS 7 machine then added corresponding policy file:
```
https://raw.githubusercontent.com/wazuh/wazuh/7314-add-sca-nx/ruleset/sca/centos/7/cis_centos7_linux.yml
```
It shows up as failed even though running the first of the check's commands manually indicate that NX is enabled:
```
# sh -c "journalctl | grep \"protection: active\""
Feb 05 10:46:38 localhost.localdomain kernel: NX (Execute Disable) protection: active
```
The [previous version](https://raw.githubusercontent.com/wazuh/wazuh-ruleset/b1344b8/sca/centos/7/cis_centos7_linux.yml) of the check does correctly show as Passed on a centos/7 vagrant box.

**Review by chemamartinez — APPROVED** [review]
LGTM

**Review by jctello — APPROVED** [review]
LGTM! Sorry for the late reply!

**Pull request merged**
