### PR TITLE
Remove Vulnerability Detector references in the API and framework

### PR DESCRIPTION
**Pull request by mhamra**
|Related issue|
|---|
|#21461|

## Description
Remove Vulnerability Detector from API and Framework.

### CODE REVIEW

**Comment by mhamra** [comment]
## AIT TEST EXECUTION 

<details><summary>test_cluster_endpoints.tavern.yaml</summary>

```console
marcelo@vallese-w11:~/wazuh/wazuh/api/test/integration$  cd /home/marcelo/wazuh/wazuh/api/test/integration ; /usr/bin/env /home/marcelo/wazuh/wazuh/venv-3.10/bin/python /home/marcelo/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 46673 -- -m pytest -vv --nobuild /home/marcelo/wazuh/wazuh/api/test/integration/test_cluster_endpoints.tavern.yaml 
================================================================================================= test session starts =================================================================================================
platform linux -- Python 3.10.13, pytest-7.3.1, pluggy-1.3.0 -- /home/marcelo/wazuh/wazuh/venv-3.10/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.10.13', 'Platform': 'Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.31', 'Packages': {'pytest': '7.3.1', 'pluggy': '1.3.0'}, 'Plugins': {'aiohttp': '1.0.4', 'trio': '0.8.0', 'asyncio': '0.18.1', 'tavern': '1.23.5', 'metadata': '3.0.0', 'html': '2.1.1'}}
rootdir: /home/marcelo/wazuh/wazuh/api/test/integration
configfile: pytest.ini
plugins: aiohttp-1.0.4, trio-0.8.0, asyncio-0.18.1, tavern-1.23.5, metadata-3.0.0, html-2.1.1
asyncio: mode=auto
collected 49 items                                                                                                                                                                                                    

test_cluster_endpoints.tavern.yaml::GET /cluster/local/config PASSED                                                                                                                                            [  2%]
test_cluster_endpoints.tavern.yaml::GET /cluster/healthcheck PASSED                                                                                                                                             [  4%]
test_cluster_endpoints.tavern.yaml::GET /cluster/ruleset/synchronization PASSED                                                                                                                                 [  6%]
test_cluster_endpoints.tavern.yaml::GET /cluster/local/info PASSED                                                                                                                                              [  8%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes PASSED                                                                                                                                                   [ 10%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[master-node] PASSED                                                                                                                                      [ 12%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[worker1] PASSED                                                                                                                                          [ 14%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[worker2] PASSED                                                                                                                                          [ 16%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[ip] PASSED                                                                                                                                        [ 18%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[name] PASSED                                                                                                                                      [ 20%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[type] PASSED                                                                                                                                      [ 22%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[version] PASSED                                                                                                                                   [ 24%]
test_cluster_endpoints.tavern.yaml::GET /cluster/status PASSED                                                                                                                                                  [ 26%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration PASSED                                                                                                                                 [ 28%]
test_cluster_endpoints.tavern.yaml::GET /cluster/configuration/validation PASSED                                                                                                                                [ 30%]
test_cluster_endpoints.tavern.yaml::GET /cluster/api/config PASSED                                                                                                                                              [ 32%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration/{component}/{configuration} PASSED                                                                                                     [ 34%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[master-node] PASSED                                                                                                                             [ 36%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[worker1] PASSED                                                                                                                                 [ 38%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[worker2] PASSED                                                                                                                                 [ 40%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[master-node] PASSED                                                                                                                             [ 42%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[worker1] PASSED                                                                                                                                 [ 44%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[worker2] PASSED                                                                                                                                 [ 46%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary[worker1] PASSED                                                                                                                         [ 48%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary[worker2] PASSED                                                                                                                         [ 51%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/daemons/stats[master-node] PASSED                                                                                                                    [ 53%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/daemons/stats[worker1] PASSED                                                                                                                        [ 55%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/daemons/stats[worker2] PASSED                                                                                                                        [ 57%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[master-node] PASSED                                                                                                                            [ 59%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[worker1] PASSED                                                                                                                                [ 61%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[worker2] PASSED                                                                                                                                [ 63%]
test_cluster_endpoints.tavern.yaml::GET /cluster/wrong_node/stats PASSED                                                                                                                                        [ 65%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[master-node] PASSED                                                                                                                  [ 67%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[worker1] PASSED                                                                                                                      [ 69%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[worker2] PASSED                                                                                                                      [ 71%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[master-node] PASSED                                                                                                                     [ 73%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[worker1] PASSED                                                                                                                         [ 75%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[worker2] PASSED                                                                                                                         [ 77%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/remoted[master-node] PASSED                                                                                                                    [ 79%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/remoted[worker1] PASSED                                                                                                                        [ 81%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/remoted[worker2] PASSED                                                                                                                        [ 83%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/weekly[master-node] PASSED                                                                                                                     [ 85%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/weekly[worker1] PASSED                                                                                                                         [ 87%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/weekly[worker2] PASSED                                                                                                                         [ 89%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status[master-node] PASSED                                                                                                                           [ 91%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status[worker1] PASSED                                                                                                                               [ 93%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status[worker2] PASSED                                                                                                                               [ 95%]
test_cluster_endpoints.tavern.yaml::PUT /cluster/restart PASSED                                                                                                                                                 [ 97%]
test_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/configuration PASSED                                                                                                                                 [100%]

================================================================================================== warnings summary ===================================================================================================
```
<details>

**Review by GGP1 — CHANGES_REQUESTED** [review]
The API integration tests Tier 0-1 (located under `tests/integration/test_api`) are failing in this [PR](https://github.com/wazuh/wazuh/actions/runs/7584540828/job/20658419161?pr=21542) and in the related issue's [PR](https://github.com/wazuh/wazuh/actions/runs/7550651708/job/20556615366?pr=21454). Please apply the changes required to make them pass, you may need to change the base branch to `enhancement/21303-vuln-det-references`.

Also, make sure to check the tasks mentioned in the issue description after they have been completed.

tasks

**Comment by mhamra** [comment]
## UPDATE
Results of running the tier 0-1 test_api in a local environment. The `qa-integration-framework` branch used to run these tests is [remove/87-remove-vd-from-api](https://github.com/wazuh/qa-integration-framework/tree/remove/87-remove-vd-from-api)


```console
root@wazuh-master:/wazuh/tests/integration# python3 -m pytest --tier 0 --tier 1 test_api/
============================================================================================== test session starts ==============================================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.3.0
rootdir: /wazuh/tests/integration, configfile: pytest.ini
plugins: metadata-3.0.0, html-3.1.1
collected 61 items / 3 deselected / 58 selected

test_api/test_config/test_DOS_blocking_system/test_DOS_blocking_system.py .                                                                                                                               [  1%]
test_api/test_config/test_bruteforce_blocking_system/test_bruteforce_blocking_system.py .                                                                                                                 [  3%]
test_api/test_config/test_cache/test_cache.py ..                                                                                                                                                          [  6%]
test_api/test_config/test_cors/test_cors.py x.                                                                                                                                                            [ 10%]
test_api/test_config/test_drop_privileges/test_drop_privileges.py ..                                                                                                                                      [ 13%]
test_api/test_config/test_experimental_features/test_experimental_features.py ..                                                                                                                          [ 17%]
test_api/test_config/test_host_port/test_host_port.py ....                                                                                                                                                [ 24%]
test_api/test_config/test_https/test_https.py ..                                                                                                                                                          [ 27%]
test_api/test_config/test_jwt_token_exp_timeout/test_jwt_token_exp_timeout.py ..                                                                                                                          [ 31%]
test_api/test_config/test_logs/test_logs_format.py ........                                                                                                                                               [ 44%]
test_api/test_config/test_rbac/test_rbac_mode.py ..                                                                                                                                                       [ 48%]
test_api/test_config/test_request_timeout/test_request_timeout.py .                                                                                                                                       [ 50%]
test_api/test_middlewares/test_response_postprocessing.py ....                                                                                                                                            [ 56%]
test_api/test_middlewares/test_set_secure_headers.py .                                                                                                                                                    [ 58%]
test_api/test_rbac/test_add_old_resource.py ....                                                                                                                                                          [ 65%]
test_api/test_rbac/test_manage_admin_resource.py .......                                                                                                                                                  [ 77%]
test_api/test_rbac/test_policy_position.py .                                                                                                                                                              [ 79%]
test_api/test_rbac/test_remove_resource.py ....                                                                                                                                                           [ 86%]
test_api/test_rbac/test_remove_resources_relation.py ...                                                                                                                                                  [ 91%]
test_api/test_statistics/test_statistics_format.py .....                                                                                                                                                  [100%]

============================================================================ 57 passed, 3 deselected, 1 xfailed in 828.08s (0:13:48) ============================================================================
```

**Comment by pereyra-m** [comment]
Hi @mhamra !

The API test in https://github.com/wazuh/wazuh/pull/21454 passed, what do you think we need to have this PR in full green?

**Review by GGP1 — APPROVED** [review]
LGTM!

The API integration tests that failed in the checks where executed sucessfully in a local environment [here](https://github.com/wazuh/wazuh/pull/21542#issuecomment-1900752663).

> @pereyra-m the issue was on hold because the api tier 0-1 tests were failing, but I've just re-launched them and they passed.

**Review by Selutario — CHANGES_REQUESTED** [review]

**Review by Selutario — APPROVED** [review]

**Comment by Selutario** [comment]
The failing [API test - tier 0 and 1](https://github.com/wazuh/wazuh/actions/runs/7653987048/job/20857020988?pr=21542) is due to a known race condition that will be fixed here:
- https://github.com/wazuh/wazuh/issues/21623

The same test was run also in Jenkins and it passed successfully:
- https://github.com/wazuh/wazuh/pull/21542/checks?check_run_id=20858756113

**Pull request merged**
