### PR TITLE
Engine - Improve integration script

### PR DESCRIPTION
**Pull request by LucioDonda**
|Related issue|
|---|
|#16892|

## Description

After using the mentioned script, the different teams involved, have found several issues or points where the user experience can be improved, these are some of the items where the integration script needs to improve:

- [x]  Execute a rollback when the addition didn't result successfully. The user should be able to correct whether error occur and nothing else, meaning that the status of the store will remain the same after the erro.
- [x]  Allow execution outside the specific path, now it should be executed in it.
- [x]  Manage errors (avoid throwing Traceback on errors), print proper messages
- [ ] Unify methods from other _engine-..._ scripts, rename when necessary
- [x] Improve help messages in commands:
    - [x] Default parameter values

Nice to Have:
- [x]  Add Integration delete or Integration update in order to use it when an integration changes an must be updated

### CODE REVIEW

**Comment by LucioDonda** [comment]
```
─# engine-integration -h
usage: engine-integration [-h] [--version] [-v] {create,generate-doc,generate-graph,generate-manifest,add,delete,update} ...

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  -v, --verbose         Print traceback on error messages

subcommands:
  {create,generate-doc,generate-graph,generate-manifest,add,delete,update}
    create              Create a new integration project scaffold on the current directory
    generate-doc        Generate documentation for the integration, must be run from the integration directory
    generate-graph      Generate dot graph for the integration, must be run from the integration directory
    generate-manifest   Generate the manifest file of all assets of the currentintegration. Name of the integration is taken from the dname of thedirectory used
    add                 Add integration components to the Engine Catalog. If a step fails it will undo the previous ones
    delete              Delete integration components from the Engine Catalog. If a step fails it continue with the next
    update              Updates integration components to the Engine Catalog. If a step fails it will restore the asset to the previous state

```

Added rollback functionality to add command.
Delete command continues even if an exception occurs (like trying to delete a non existant asset)
Update creates KVDBs when possible and informs when trying to add an already existant one, but updates all present assets and adds the new ones.
Added error messages on various cases.

When testing PostgreSQL issue (timeout on connection) this message gets printed:
` "Catalog command [update] received an empty response."`

**Comment by LucioDonda** [comment]
added dry-run in order to print steps before applying:
```
╰─# engine-integration -v add --dry-run -p new-int                                      
Adding integration from: /home/vagrant/workspace/wazuh/src/engine/tools/new-int
[0]	Kvdbs [NEW_attributes] will be added
[1]	Kvdbs [agents_host_data] will be added
[2]	Kvdbs [another_win_trust_attributes] will be added
decoders[3] decoder/core-sca/0 will be added.
decoders[4] decoder/fim-new-dec/0 will be added.
outputs[5] output/file-output-2/0 will be added.
Finished test run.

```
```
╰─# engine-integration update -p new-int
Updating integration as defined in path: /home/vagrant/workspace/wazuh/src/engine/tools/new-int
Checking Kvdbs
Manually check for no missing data in "another_win_trust_attributes"
Updating decoders
Asset[0] decoder/core-sca/0 will be updated.
Asset[1] decoder/fim-new-dec/0 will be updated.
Updating rules
Updating outputs
Asset[2] output/file-output-2/0 will be added.
Updating filters
Asset[3] output/file-output-3/0 will be removed.
Executing N°0
Executing N°1
Executing N°2
Executing N°3
Succesfully updated assets. Updating integration.
Check if available file is up to date.
Updating integration [new-int] manifest...

```

```
╰─# engine-integration delete -h                                                                                                                                                                             130 ↵
usage: engine-integration delete [-h] [-a API_SOCK] [-n INTEGRATION-NAME] [--dry-run]

optional arguments:
  -h, --help            show this help message and exit
  -a API_SOCK, --api-sock API_SOCK
                        [default="/var/ossec/queue/sockets/engine-api"] Engine instance API socket path
  -n INTEGRATION-NAME, --integration-name INTEGRATION-NAME
                        Integration name to be deleted
  --dry-run             default False, When True will print all the steps to apply without affecting the store

```

**Review by JavierBejMen — APPROVED** [review]
LGTM

**Review by nbertoldo — APPROVED** [review]
LGTM!

**Review by JcabreraC — APPROVED** [review]
LGTM !

**Pull request merged**
