### PR TITLE
Fix wm_exec usages

### PR DESCRIPTION
**Pull request by JuantAldea**
|Related issue|
|---|
|#3350|

## Description
This PR fixes several usages of `wm_exec` and some potential leaks.

#### execd.c
- `wm_exec() < 0` does not produce output, hence there's nothing to release.

#### wcom.c
- Code generalized.

#### win_whodata.c
- `wm_exec()` error handling was based solely on the command return code.
- `wm_exec()` was requested for an output that was discarted without any further processing.
 
#### wm_aws.c
- Several `pthread_exit()` without performing any frees. 
- `free()` of ` line`, a reference to `output` string.
- Usage of  `strtok()`, which is not reentrant, on a thread.

#### wm_azure.c
- Several `pthread_exit()` without performing any frees. 

#### wm_ciscat.c
- Several `pthread_exit` without performing any frees. 
- command return code was not checked for errors.

#### wm_command.c
- Usage of `strtok()`, which is not reentrant, on a thread.

#### wm_docker.c 
- `output` could be released even when `wm_exec() < 0`
- Fix wm_exec retry code.

#### wm_keyrequest.c
- Unhandled  `wm_exec` timeout case.
- Release command output ASAP.

####  wm_oscap.c
- `pthread_exit` without memory release.
- Release several variables ASAP.
- Usage of `strtok()`, which is not reentrant, on a thread.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [ ] MAC OS X
- [x] Scan-build 
- Memory tests
  - [x] Valgrind report for affected components
  - [ ] RAM usage impact
- [x] Review logs syntax and correct language

### CODE REVIEW

**Comment by chemamartinez** [comment]
**Test 1:** Configuration validation in `ossec-execd`

**Remoted off**
```
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/manager/configuration/validation?pretty"
{
   "error": 1018,
   "message": "Wazuh is stopped. Start Wazuh before using the API. Current status is wazuh-modulesd->running, ossec-remoted->stopped, ossec-analysisd->running, ossec-execd->running,wazuh-db->running"
}
```

**Configuration OK**
```
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/manager/configuration/validation?pretty"
{
   "error": 0,
   "data": {
      "status": "OK"
   }
}
```

**Invalid configuration**
```
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/manager/configuration/validation?pretty"
{
   "error": 0,
   "data": {
      "status": "KO",
      "details": [
         "(1235): Invalid value for element 'protocol': icmp.",
         "(1202): Configuration error at '/var/ossec/etc/ossec.conf'."
      ]
   }
}
```

**_valgrind_ report while executing queries**
```
==75067== LEAK SUMMARY:
==75067==    definitely lost: 0 bytes in 0 blocks
==75067==    indirectly lost: 0 bytes in 0 blocks
==75067==      possibly lost: 272 bytes in 1 blocks
==75067==    still reachable: 144 bytes in 1 blocks
==75067==         suppressed: 0 bytes in 0 blocks
==75067== Reachable blocks (those to which a pointer was found) are not shown.
==75067== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```

**Comment by chemamartinez** [comment]
**Code of `wcom.c`** -> Just a refactor, no changes in the resources management.

**Comment by chemamartinez** [comment]
**Test 2:** The Windows who-data.

Changes affect to the function `set_policies()`, the execution of the commands with `wm_exec` works. Here we can see the Dr. Memory execution:

```
2019/06/13 14:53:39 ossec-agent: INFO: (6232): Registry integrity monitoring scan ended
~~Dr.M~~ Dr. Memory version 2.1.0
~~Dr.M~~ Running "auditpol /backup /file:"tmp\backup-policies""
~~Dr.M~~ WARNING: application is missing line number information.
El comando se ejecutó correctamente.
~~Dr.M~~
~~Dr.M~~ NO ERRORS FOUND:
~~Dr.M~~       0 unique,     0 total unaddressable access(es)
~~Dr.M~~       0 unique,     0 total uninitialized access(es)
~~Dr.M~~       0 unique,     0 total invalid heap argument(s)
~~Dr.M~~       0 unique,     0 total GDI usage error(s)
~~Dr.M~~       0 unique,     0 total handle leak(s)
~~Dr.M~~       0 unique,     0 total warning(s)
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of leak(s)
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of possible leak(s)
~~Dr.M~~ ERRORS IGNORED:
~~Dr.M~~      10 potential error(s) (suspected false positives)
~~Dr.M~~          (details: C:\Users\Administrador\Desktop\DrMemory-auditpol.exe.940.000\potential_errors.txt)
~~Dr.M~~       3 potential leak(s) (suspected false positives)
~~Dr.M~~          (details: C:\Users\Administrador\Desktop\DrMemory-auditpol.exe.940.000\potential_errors.txt)
~~Dr.M~~     171 unique,   171 total,  24316 byte(s) of still-reachable allocation(s)
~~Dr.M~~          (re-run with "-show_reachable" for details)
~~Dr.M~~ Details: C:\Users\Administrador\Desktop\DrMemory-auditpol.exe.940.000\results.txt
~~Dr.M~~ Dr. Memory version 2.1.0
~~Dr.M~~ Running "auditpol /restore /file:"tmp\new-policies""
~~Dr.M~~ WARNING: application is missing line number information.
El comando se ejecutó correctamente.
~~Dr.M~~
~~Dr.M~~ NO ERRORS FOUND:
~~Dr.M~~       0 unique,     0 total unaddressable access(es)
~~Dr.M~~       0 unique,     0 total uninitialized access(es)
~~Dr.M~~       0 unique,     0 total invalid heap argument(s)
~~Dr.M~~       0 unique,     0 total GDI usage error(s)
~~Dr.M~~       0 unique,     0 total handle leak(s)
~~Dr.M~~       0 unique,     0 total warning(s)
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of leak(s)
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of possible leak(s)
~~Dr.M~~ ERRORS IGNORED:
~~Dr.M~~       9 potential error(s) (suspected false positives)
~~Dr.M~~          (details: C:\Users\Administrador\Desktop\DrMemory-auditpol.exe.1296.000\potential_errors.txt)
~~Dr.M~~       3 potential leak(s) (suspected false positives)
~~Dr.M~~          (details: C:\Users\Administrador\Desktop\DrMemory-auditpol.exe.1296.000\potential_errors.txt)
~~Dr.M~~     172 unique,   172 total,  20212 byte(s) of still-reachable allocation(s)
~~Dr.M~~          (re-run with "-show_reachable" for details)
~~Dr.M~~ Details: C:\Users\Administrador\Desktop\DrMemory-auditpol.exe.1296.000\results.txt
2019/06/13 14:53:42 ossec-agent: INFO: (6017): Whodata auditing engine started.
```

And after the execution, _who-data_ works normally.

```
** Alert 1560440294.345981: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2019 Jun 13 08:38:14 (WinServer2012) any->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File 'c:\test\a.txt' checksum changed.
Size changed from '0' to '6'
Old md5sum was: 'd41d8cd98f00b204e9800998ecf8427e'
New md5sum is : '0b4e7a0e5fe84ad35fb5f95b9ceeac79'
Old sha1sum was: 'da39a3ee5e6b4b0d3255bfef95601890afd80709'
New sha1sum is : 'f7a9e24777ec23212c54d7a350bc5bea5477fdbb'
Old sha256sum was: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
New sha256sum is : 'ed02457b5c41d964dbd2f2a609d63fe1bb7528dbe55e1abf5b52c249cd735797'
Old modification time was: 'Thu Jun 13 07:43:58 2019', now it is 'Thu Jun 13 08:38:14 2019'
(Audit) User: 'Administrador (S-1-5-21-2619516049-860824440-897950152-500)'
(Audit) Process id: '2940'
(Audit) Process name: 'C:\Windows\System32\notepad.exe'

Attributes:
 - Size: 6
 - Date: Thu Jun 13 08:38:14 2019
 - User: Administradores (S-1-5-32-544)
 - MD5: 0b4e7a0e5fe84ad35fb5f95b9ceeac79
 - SHA1: f7a9e24777ec23212c54d7a350bc5bea5477fdbb
 - SHA256: ed02457b5c41d964dbd2f2a609d63fe1bb7528dbe55e1abf5b52c249cd735797
 - File attributes: ARCHIVE
 - Permissions:
   SYSTEM  (ALLOWED) - DELETE, READ_CONTROL, WRITE_DAC, WRITE_OWNER, SYNCHRONIZE, FILE_READ_DATA, FILE_WRITE_DATA, FILE_APPEND_DATA, FILE_READ_EA, FILE_WRITE_EA, FILE_EXECUTE, FILE_READ_ATTRIBUTES, FILE_WRITE_ATTRIBUTES
   Administradores  (ALLOWED) - DELETE, READ_CONTROL, WRITE_DAC, WRITE_OWNER, SYNCHRONIZE, FILE_READ_DATA, FILE_WRITE_DATA, FILE_APPEND_DATA, FILE_READ_EA, FILE_WRITE_EA, FILE_EXECUTE, FILE_READ_ATTRIBUTES, FILE_WRITE_ATTRIBUTES
   Usuarios  (ALLOWED) - READ_CONTROL, SYNCHRONIZE, FILE_READ_DATA, FILE_READ_EA, FILE_EXECUTE, FILE_READ_ATTRIBUTES
```

**Comment by chemamartinez** [comment]
### Module tests

**Test 3**: Running the rest of modules with different outputs (success or failed cases)

**SCA**

Created a custom policy for commands.

```yml
checks:
 - id: 1
   title: "Valid command"
   condition: any
   rules:
     - 'c:/sbin/ifconfig -> r:ens33;'
 - id: 2
   title: "timeout"
   condition: any
   rules:
     - 'c:sleep 120 -> r:^any$;'
 - id: 3
   title: "Invalid command"
   condition: any
   rules:
     - 'c:/sbin/ifconfig -g -> r:not recognized;'
```

Here the output for each command:
```
2019/06/14 07:13:14 sca[3713] wm_sca.c:1509 at wm_sca_read_command(): DEBUG: Command '/sbin/ifconfig' returned code 0.
2019/06/14 07:12:45 sca[3713] wm_sca.c:1513 at wm_sca_read_command(): DEBUG: Timeout overtaken running command 'sleep 120'
2019/06/14 07:12:45 sca[3713] wm_sca.c:1509 at wm_sca_read_command(): DEBUG: Command '/sbin/ifconfig -g' returned code 1.
```

**Command module**

Configured both valid and invalid commands:

```xml
<wodle name="command">
    <disabled>no</disabled>
    <tag>valid</tag>
    <command>/sbin/ifconfig</command>
    <interval>1m</interval>
    <ignore_output>no</ignore_output>
    <run_on_start>yes</run_on_start>
    <timeout>0</timeout>
  </wodle>

  <wodle name="command">
    <disabled>no</disabled>
    <tag>invalid</tag>
    <command>/sbin/fakebin</command>
    <interval>1m</interval>
    <ignore_output>no</ignore_output>
    <run_on_start>yes</run_on_start>
    <timeout>0</timeout>
  </wodle>
```

Output:
```
2019/06/14 07:25:12 wazuh-modulesd:command[3713] wm_command.c:176 at wm_command_main(): DEBUG: Starting command 'valid'.
2019/06/14 07:25:12 wazuh-modulesd:command[3713] wm_command.c:216 at wm_command_main(): DEBUG: Command 'valid' finished.
----------------------------------
2019/06/14 07:25:12 wazuh-modulesd:command[3713] wm_command.c:176 at wm_command_main(): DEBUG: Starting command 'invalid'.
2019/06/14 07:25:13 wazuh-modulesd[3713] wm_exec.c:438 at wm_exec(): DEBUG: Invalid command: '/sbin/fakebin': (2) No such file or directory
2019/06/14 07:25:13 wazuh-modulesd:command[3713] wm_command.c:197 at wm_command_main(): ERROR: Command 'invalid' failed.
2019/06/14 07:25:13 wazuh-modulesd:command[3713] wm_command.c:216 at wm_command_main(): DEBUG: Command 'invalid' finished.
```

**CIS-CAT**

Different invalid policies configured to scan:

```xml
<wodle name="cis-cat">
    <disabled>no</disabled>
    <timeout>20</timeout>
    <interval>1m</interval>
    <scan-on-start>yes</scan-on-start>

    <java_path>/usr/bin/java</java_path>
    <ciscat_path>/root/cis-cat/cis-cat-full</ciscat_path>

    <content type="xccdf" path="benchmarks/CIS_Google_Chrome_Benchmark_v1.2.0-xccdf.xml" />
    <content type="xccdf" path="benchmarks/CIS_Ubuntu_Linux_16.04_LTS_Benchmark_v1.0.0-xccdf.xml" />
    <content type="xccdf" path="benchmarks/CIS_CentOS_Linux_7_Benchmark_v2.1.1-xccdf.xml">
       <profile>fake_profile</profile>
    </content>
</wodle>
```

Output for each policy execution:
```
2019/06/14 08:42:01 wazuh-modulesd:ciscat[17289] wm_ciscat.c:593 at wm_ciscat_run(): INFO: Scan finished successfully. File: /root/cis-cat/cis-cat-full/benchmarks/CIS_Google_Chrome_Benchmark_v1.2.0-xccdf.xml
----------------------------------
2019/06/14 08:42:21 wazuh-modulesd:ciscat[17289] wm_ciscat.c:602 at wm_ciscat_run(): ERROR: Timeout expired executing '/root/cis-cat/cis-cat-full/benchmarks/CIS_Ubuntu_Linux_16.04_LTS_Benchmark_v1.0.0-xccdf.xml'.
----------------------------------
2019/06/14 08:42:23 wazuh-modulesd:ciscat[17289] wm_ciscat.c:596 at wm_ciscat_run(): ERROR: Ignoring content '/root/cis-cat/cis-cat-full/benchmarks/CIS_CentOS_Linux_7_Benchmark_v2.1.1-xccdf.xml' due to error (232).
2019/06/14 08:42:23 wazuh-modulesd:ciscat[17289] wm_ciscat.c:597 at wm_ciscat_run(): ERROR: OUTPUT: This is CIS-CAT-Pro Assessor version 3.0.43
An error occurred configuring the profile fake_profile selected for assessment.  Ensure the profile is valid for the selected benchmark.
CIS-CAT will now exit -- Error Code: ERR-CLI-0012
```

For the last execution (the fake profile), _valgrind_ reports a memory leak in the report parser that we have to investigate deeper:

```
==17289== 64 bytes in 1 blocks are definitely lost in loss record 38 of 90
==17289==    at 0x4C31B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17289==    by 0x183F75: wm_ciscat_txt_parser (wm_ciscat.c:719)
==17289==    by 0x183AEF: wm_ciscat_run (wm_ciscat.c:639)
==17289==    by 0x182D95: wm_ciscat_main (wm_ciscat.c:250)
==17289==    by 0x586E6DA: start_thread (pthread_create.c:463)
==17289==    by 0x5BA788E: clone (clone.S:95)
==17289==
==17289== 149 (128 direct, 21 indirect) bytes in 2 blocks are definitely lost in loss record 61 of 90
==17289==    at 0x4C31B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17289==    by 0x183F13: wm_ciscat_txt_parser (wm_ciscat.c:718)
==17289==    by 0x183AEF: wm_ciscat_run (wm_ciscat.c:639)
==17289==    by 0x182D95: wm_ciscat_main (wm_ciscat.c:250)
==17289==    by 0x586E6DA: start_thread (pthread_create.c:463)
==17289==    by 0x5BA788E: clone (clone.S:95)
----------------------------------
==17289== LEAK SUMMARY:
==17289==    definitely lost: 192 bytes in 3 blocks
==17289==    indirectly lost: 21 bytes in 2 blocks
==17289==      possibly lost: 5,464 bytes in 6 blocks
==17289==    still reachable: 429,771 bytes in 148 blocks
==17289==                       of which reachable via heuristic:
==17289==                         length64           : 223,896 bytes in 124 blocks
==17289==         suppressed: 0 bytes in 0 blocks
==17289== Reachable blocks (those to which a pointer was found) are not shown.
==17289== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```

**Docker module**

Configuration:

```xml
<wodle name="docker-listener">
    <attempts>2</attempts>
    <run_on_start>no</run_on_start>
    <disabled>no</disabled>
    <interval>1s</interval>
</wodle>
```

By adding `sys.exit(1)` to the launched script, we simulate the fail condition:

```
2019/06/14 08:04:57 wazuh-modulesd:docker-listener[6401] wm_docker.c:61 at wm_docker_main(): DEBUG: Launching command '/var/ossec/wodles/docker/DockerListener'.
2019/06/14 08:04:58 wazuh-modulesd:docker-listener[6401] wm_docker.c:78 at wm_docker_main(): WARNING: Returned exit code 1
2019/06/14 08:04:58 wazuh-modulesd:docker-listener[6401] wm_docker.c:79 at wm_docker_main(): ERROR: OUTPUT: {"integration": "docker", "docker": {"Wodle event": "Started"}}
2019/06/14 08:04:58 wazuh-modulesd:docker-listener[6401] wm_docker.c:84 at wm_docker_main(): WARNING: Docker-listener finished unexpectedly (code 1). Retrying to run it in 1 seconds...
2019/06/14 08:04:59 wazuh-modulesd:docker-listener[6401] wm_docker.c:57 at wm_docker_main(): INFO: Starting to listening Docker events.
2019/06/14 08:04:59 wazuh-modulesd:docker-listener[6401] wm_docker.c:61 at wm_docker_main(): DEBUG: Launching command '/var/ossec/wodles/docker/DockerListener'.
2019/06/14 08:04:59 wazuh-modulesd:docker-listener[6401] wm_docker.c:64 at wm_docker_main(): ERROR: Maximum attempts reached to run the listener. Exiting...
```

The correct execution lets the command running in background.

**AWS and AZURE modules**

In the same way for the Docker module, the correct executions work fine for both modules. To simulate the fail condition we tune the python wrapper.

_Expected results_

```
2019/06/14 07:12:12 wazuh-modulesd:aws-s3[3713] wm_aws.c:409 at wm_aws_run_s3(): DEBUG: Launching S3 Command: /var/ossec/wodles/aws/aws-s3 --bucket test-cloudtrail --access_key XXXX --secret_key XXXX --only_logs_after 2019-JAN-24 --type cloudtrail --debug 1
----------------------------------
2019/06/14 07:26:14 wazuh-modulesd:azure-logs[3713] wm_azure.c:314 at wm_azure_graphs(): DEBUG: Launching command: /var/ossec/wodles/azure/azure-logs --graph --graph_id XXXX --graph_key XXXX --graph_tenant_domain test.onmicrosoft.com --graph_tag azure-active_directory --graph_query 'activities/audit?api-version=beta' --graph_time_offset 100d
2019/06/14 07:26:14 wazuh-modulesd:azure-logs[3713] wm_azure.c:331 at wm_azure_graphs(): INFO: Finished Graphs log collection for request 'azure-active_directory'.
```

_Failure cases_

```
2019/06/14 09:05:38 wazuh-modulesd:azure-logs[19128] wm_azure.c:246 at wm_azure_log_analytics(): WARNING: azure-activity: Returned error code: '1'.
2019/06/14 09:05:38 wazuh-modulesd:azure-logs[19128] wm_azure.c:259 at wm_azure_log_analytics(): INFO: Finished Log Analytics collection for request 'azure-activity'.
----------------------------------
2019/06/14 09:05:38 wazuh-modulesd:azure-logs[19128] wm_azure.c:318 at wm_azure_graphs(): WARNING: azure-active_directory: Returned error code: '1'.
2019/06/14 09:05:38 wazuh-modulesd:azure-logs[19128] wm_azure.c:331 at wm_azure_graphs(): INFO: Finished Graphs log collection for request 'azure-active_directory'.
----------------------------------
2019/06/14 09:05:38 wazuh-modulesd:aws-s3[19128] wm_aws.c:425 at wm_aws_run_s3(): WARNING: Bucket:  -  Returned exit code 1
2019/06/14 09:05:38 wazuh-modulesd:aws-s3[19128] wm_aws.c:429 at wm_aws_run_s3(): WARNING: Bucket:  -  Unknown error.
----------------------------------
2019/06/14 09:05:39 wazuh-modulesd:aws-s3[19128] wm_aws.c:559 at wm_aws_run_service(): WARNING: Service: inspector  -  Returned exit code 1
2019/06/14 09:05:39 wazuh-modulesd:aws-s3[19128] wm_aws.c:563 at wm_aws_run_service(): WARNING: Service: inspector  -  Unknown error.
```

**Open-SCAP module**

Tested the failure case, here the used configuration:

```xml
<wodle name="open-scap">
    <disabled>no</disabled>
    <timeout>1800</timeout>
    <interval>1m</interval>
    <scan-on-start>yes</scan-on-start>
    <content type="xccdf" path="fake-policy.xml" />
</wodle>
```

Output:

```
2019/06/14 07:49:00 wazuh-modulesd:oscap[6028] wm_oscap.c:209 at wm_oscap_run(): DEBUG: Launching command: /var/ossec/wodles/oscap/oscap.py --xccdf fake-policy.xml
2019/06/14 07:49:00 wazuh-modulesd:oscap[6028] wm_oscap.c:217 at wm_oscap_run(): WARNING: Ignoring content 'fake-policy.xml' due to error (1).
2019/06/14 07:49:00 wazuh-modulesd:oscap[6028] wm_oscap.c:218 at wm_oscap_run(): DEBUG: OUTPUT: oscap: ERROR: Parsing file "wodles/oscap/content/fake-policy.xml". Details: "OpenSCAP Error: Document is empty [../../../src/source/oscap_source.c:301]".
2019/06/14 07:49:00 wazuh-modulesd:oscap[6028] wm_oscap.c:84 at wm_oscap_main(): INFO: Evaluation finished.
```

**Key polling module**

Using a custom python script we provoke the result statuses of success, failure and timeout.

Configuration

```xml
<wodle name="agent-key-polling">
    <enabled>yes</enabled>
    <timeout>5</timeout>
    <exec_path>/usr/bin/python /root/test.py</exec_path>
    <threads>1</threads>
    <queue_size>1024</queue_size>
    <force_insert>yes</force_insert>
</wodle>
```

Output:

```
return code = 127:
2019/06/14 09:50:06 wazuh-modulesd:agent-key-polling[19350] wm_keyrequest.c:283 at wm_key_request_dispatch(): WARNING: Cannot run key pulling integration (/usr/bin/python /root/test.py): path is invalid or file has insufficient permissions.
----------------------------------
forced timeout:
2019/06/14 09:51:56 wazuh-modulesd:agent-key-polling[19350] wm_keyrequest.c:278 at wm_key_request_dispatch(): WARNING: Timeout received while running key pulling integration (/usr/bin/python /root/test.py)
2019/06/14 09:51:56 wazuh-modulesd:agent-key-polling[19350] wm_keyrequest.c:433 at w_request_thread(): DEBUG: At w_request_thread(): Error getting external key
----------------------------------
return code = 1:
2019/06/14 09:52:55 wazuh-modulesd:agent-key-polling[19350] wm_keyrequest.c:273 at wm_key_request_dispatch(): WARNING: Key pulling integration (/usr/bin/python /root/test.py) returned code 1.
2019/06/14 09:52:55 wazuh-modulesd:agent-key-polling[19350] wm_keyrequest.c:433 at w_request_thread(): DEBUG: At w_request_thread(): Error getting external key
----------------------------------
return code = 0:
On success, no log is triggered until parsing the JSON output
2019/06/14 09:54:01 wazuh-modulesd:agent-key-polling[19350] wm_keyrequest.c:302 at wm_key_request_dispatch(): DEBUG: Error parsing JSON event.
```

_Memory result:_
On the last use case of the agent key polling module, _valgrind_ reported an `Invalid read` when the output is not the expected.
```
==19350== Invalid read of size 1
==19350==    at 0x4C32CF2: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19350==    by 0x5AE34D2: vfprintf (vfprintf.c:1643)
==19350==    by 0x140691: _log (debug_op.c:191)
==19350==    by 0x140EA9: _mtdebug1 (debug_op.c:313)
==19350==    by 0x1665CA: wm_key_request_dispatch (wm_keyrequest.c:302)
==19350==    by 0x166DCC: w_request_thread (wm_keyrequest.c:432)
==19350==    by 0x586E6DA: start_thread (pthread_create.c:463)
==19350==    by 0x5BA788E: clone (clone.S:95)
==19350==  Address 0xa51b640 is 0 bytes inside a block of size 1 free'd
==19350==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19350==    by 0x166582: wm_key_request_dispatch (wm_keyrequest.c:299)
==19350==    by 0x166DCC: w_request_thread (wm_keyrequest.c:432)
==19350==    by 0x586E6DA: start_thread (pthread_create.c:463)
==19350==    by 0x5BA788E: clone (clone.S:95)
==19350==  Block was alloc'd at
==19350==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19350==    by 0x5B239B9: strdup (strdup.c:42)
==19350==    by 0x114307: wm_exec (wm_exec.c:520)
==19350==    by 0x166394: wm_key_request_dispatch (wm_keyrequest.c:269)
==19350==    by 0x166DCC: w_request_thread (wm_keyrequest.c:432)
==19350==    by 0x586E6DA: start_thread (pthread_create.c:463)
==19350==    by 0x5BA788E: clone (clone.S:95)
```

### Tests summary

- **Every execution result is controlled for all the modules.**
- Found two **memory issues** during the tests:
  - Memory leak in the _CIS-CAT_ module when an invalid profile is set.
  - Invalid read in the _agent key polling_ module when an unexpected JSON output received from the script.
- The _valgrind_ report for the rest of the tests was clear.

**Comment by chemamartinez** [comment]
Investigating the _valgrind_ issues reported in the testing, the memory leak in CIS-CAT was due to allocating memory for `scan_info` before checking the existence of the report file. When that file is missing, the variable was not freed. It has been fixed at the branch [fix-ciscat-memleak](https://github.com/wazuh/wazuh/tree/fix-ciscat-memleak) in this commit d10a6ebf9da12b49730a519f0b49f4232685a213.

On the other side, the invalid read is introduced at this PR when freeing `output` here -> https://github.com/JuantAldea/wazuh/blob/3a6e29b5e393b8a1e1890da58a1a6aacde83382c/src/wazuh_modules/wm_keyrequest.c#L299. After that, calling to `cJSON_GetErrorPtr()` tries to access to that freed variable to print the line where the parsing failed.

**Comment by JuantAldea** [comment]
Upon a closer examination of Chema's findings, I have opened #3542.

**Pull request merged**
