### PR TITLE
OpenWRT decoder fixed and UFW decoder improved

### PR DESCRIPTION
**Pull request by nmkoremblum**
|Related issue|
|---|
|#11609|

## Description

This PR aims to fix what was previously exposed on the Issue #11609.

## Logs/Alerts example

```
# /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.3.0
Type one log per line

Dec 26 09:05:47 server01 kernel: [126140.629122] [UFW BLOCK] IN=eth0 OUT= MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=254.253.252.251 DST=191.192.193.194 LEN=52 TOS=0x02 PREC=0x00 TTL=128 ID=9209 DF PROTO=TCP SPT=17833 DPT=22 WINDOW=8192 RES=0x00 CWR ECE SYN URGP=0

**Phase 1: Completed pre-decoding.
	full event: 'Dec 26 09:05:47 server01 kernel: [126140.629122] [UFW BLOCK] IN=eth0 OUT= MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=254.253.252.251 DST=191.192.193.194 LEN=52 TOS=0x02 PREC=0x00 TTL=128 ID=9209 DF PROTO=TCP SPT=17833 DPT=22 WINDOW=8192 RES=0x00 CWR ECE SYN URGP=0'
	timestamp: 'Dec 26 09:05:47'
	hostname: 'server01'
	program_name: 'kernel'

**Phase 2: Completed decoding.
	name: 'kernel'
	parent: 'kernel'
	action: 'UFW BLOCK'
	dstip: '191.192.193.194'
	dstport: '22'
	protocol: 'TCP'
	srcip: '254.253.252.251'
	srcport: '17833'

**Phase 3: Completed filtering (rules).
	id: '4100'
	level: '0'
	description: 'Firewall rules grouped.'
	groups: '['firewall']'
	firedtimes: '1'
	mail: 'False'
```

`runtest.py`:
<details>
  <statement>Unit Tests</statement>

 ```
# ./runtests.py 
- [ File = ./tests/SonicWall.ini ] ---------
........

- [ File = ./tests/apparmor.ini ] ---------
.....

- [ File = ./tests/arbor.ini ] ---------
..

- [ File = ./tests/audit_lateral.ini ] ---------
......

- [ File = ./tests/audit_recon.ini ] ---------
..

- [ File = ./tests/audit_scp.ini ] ---------
.

- [ File = ./tests/aws_s3_access.ini ] ---------
.......

- [ File = ./tests/checkpoint_smart1.ini ] ---------
..................

- [ File = ./tests/cimserver.ini ] ---------
..

- [ File = ./tests/cisco_asa.ini ] ---------
........................................................................................

- [ File = ./tests/cisco_ftd.ini ] ---------
..........................................

- [ File = ./tests/cisco_ios.ini ] ---------
.................

- [ File = ./tests/cpanel.ini ] ---------
.......

- [ File = ./tests/dovecot.ini ] ---------
...............

- [ File = ./tests/dropbear.ini ] ---------
...

- [ File = ./tests/exchange.ini ] ---------
..

- [ File = ./tests/exim.ini ] ---------
.......

- [ File = ./tests/f5_big_ip.ini ] ---------
...........................................

- [ File = ./tests/fireeye.ini ] ---------
...

- [ File = ./tests/firewalld.ini ] ---------
..

- [ File = ./tests/freepbx.ini ] ---------
......

- [ File = ./tests/github.ini ] ---------
....................................................................................................................................................................................................................................................................................................................................

- [ File = ./tests/gitlab.ini ] ---------
.........................

- [ File = ./tests/glpi.ini ] ---------
...

- [ File = ./tests/huawei_usg.ini ] ---------
...

- [ File = ./tests/icinga.ini ] ---------
....

- [ File = ./tests/junos.ini ] ---------
...

- [ File = ./tests/kernel_usb.ini ] ---------
......

- [ File = ./tests/mailscanner.ini ] ---------
.

- [ File = ./tests/mcafee_epo.ini ] ---------
.

- [ File = ./tests/modsecurity.ini ] ---------
......

- [ File = ./tests/named.ini ] ---------
.....

- [ File = ./tests/netscreen.ini ] ---------
....

- [ File = ./tests/nextcloud.ini ] ---------
.......

- [ File = ./tests/nginx.ini ] ---------
............

- [ File = ./tests/office365.ini ] ---------
................................................................................................................................

- [ File = ./tests/openldap.ini ] ---------
.........

- [ File = ./tests/opensmtpd.ini ] ---------
.......

- [ File = ./tests/openvpn_ldap.ini ] ---------
..

- [ File = ./tests/oscap.ini ] ---------
................................

- [ File = ./tests/owlh.ini ] ---------
....

- [ File = ./tests/pam.ini ] ---------
.....

- [ File = ./tests/panda_paps.ini ] ---------
........

- [ File = ./tests/pfsense.ini ] ---------
..

- [ File = ./tests/pix.ini ] ---------
......................

- [ File = ./tests/postfix.ini ] ---------
..

- [ File = ./tests/proftpd.ini ] ---------
.......

- [ File = ./tests/rsh.ini ] ---------
..

- [ File = ./tests/samba.ini ] ---------
....

- [ File = ./tests/sophos.ini ] ---------
........

- [ File = ./tests/sophos_fw.ini ] ---------
..........

- [ File = ./tests/fortiauth.ini ] ---------
....

- [ File = ./tests/su.ini ] ---------
.....

- [ File = ./tests/syslog.ini ] ---------
......

- [ File = ./tests/systemd.ini ] ---------
..

- [ File = ./tests/win_application.ini ] ---------


- [ File = ./tests/fortiddos.ini ] ---------
.

- [ File = ./tests/unbound.ini ] ---------


- [ File = ./tests/vsftpd.ini ] ---------
....

- [ File = ./tests/web_appsec.ini ] ---------
...............................

- [ File = ./tests/web_rules.ini ] ---------
..........

- [ File = ./tests/api.ini ] ---------
............................

- [ File = ./tests/auditd.ini ] ---------
...

- [ File = ./tests/cloudlfare-waf.ini ] ---------
.............

- [ File = ./tests/doas.ini ] ---------
....

- [ File = ./tests/fortimail.ini ] ---------
......

- [ File = ./tests/gcp.ini ] ---------
...........

- [ File = ./tests/ossec.ini ] ---------
.....

- [ File = ./tests/sophos-utm-firewall.ini ] ---------
......

- [ File = ./tests/squid_rules.ini ] ---------
..

- [ File = ./tests/sshd.ini ] ---------
...........................................

- [ File = ./tests/sudo.ini ] ---------
........

- [ File = ./tests/sysmon.ini ] ---------
...

- [ File = ./tests/trendmicro-cloud-one.ini ] ---------
.................

- [ File = ./tests/vuln_detector.ini ] ---------
..

- [ File = ./tests/eset.ini ] ---------
........

- [ File = ./tests/fortigate.ini ] ---------
.............................................

- [ File = ./tests/paloalto.ini ] ---------
................

- [ File = ./tests/apache.ini ] ---------
............

- [ File = ./tests/iptables.ini ] ---------
.........
```
</details>

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

Best Regards, 

Mariano Koremblum

### CODE REVIEW

**Review by juliancnn — DISMISSED** [review]

**Review by fabamatic — APPROVED** [review]

**Review by juliancnn — APPROVED** [review]

**Review by JcabreraC — APPROVED** [review]
LGTM !

**Review by 72nomada — APPROVED** [review]
LGTM

**Review by 72nomada — APPROVED** [review]
LGTM

**Review by jmv74211 — APPROVED** [review]
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3422
- **Comments**: https://github.com/wazuh/wazuh-qa/issues/3422#issuecomment-1286737787

**Pull request merged**
