### PR TITLE
Fix agent's reported IP address

### LINKED ISSUE #14988: Agents are wrongly reporting IPv6 as primary IP
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.4 | wazuh-agentd - modulesd (wm_control) | Agent | - | Linux - macOS |

## Description

It was found that Wazuh agents are reporting IPv6 as their primary IP when this is not certainly true (See agent 002)

image

image

### Agent information
<details>
<summary> ip addr </summary>

```
pback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:e0:d0:46 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 metric 100 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 85426sec preferred_lft 85426sec
    inet6 fe80::a00:27ff:fee0:d046/64 scope link 
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:89:5d:9d brd ff:ff:ff:ff:ff:ff
    inet 192.168.56.2/24 brd 192.168.56.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe89:5d9d/64 scope link 
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:b0:e8:38:d8 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
```
</details>

<details>
<summary> ip route</summary>

```
default via 10.0.2.2 dev enp0s3 proto dhcp src 10.0.2.15 metric 100 
10.0.2.0/24 dev enp0s3 proto kernel scope link src 10.0.2.15 metric 100 
10.0.2.2 dev enp0s3 proto dhcp scope link src 10.0.2.15 metric 100 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.1.1 via 10.0.2.2 dev enp0s3 proto dhcp src 10.0.2.15 metric 100 
192.168.56.0/24 dev enp0s8 proto kernel scope link src 192.168.56.2 
```
</details>

<details>
<summary> agent keepalive</summary>

```
2022/09/22 01:26:08 wazuh-agentd[14156] notify.c:204 at run_notify(): DEBUG: Sending keep alive: #!-Linux |wazuh-dev |5.15.0-48-generic |#54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 |x86_64 [Ubuntu|ubuntu: 22.04 (Jammy Jellyfish)] - Wazuh v4.4.0 / ab73af41699f13fdd81903b5f23d8d00
4a8724b20dee0124ff9656783c490c4e merged.mg
#"_agent_ip":FE80:0000:0000:0000:0A00:27FF:FEE0:D046
```
</details>

<details>
<summary> sysinfo_test_tool --networks </summary>

```
{
  "networks": {
    "iface": [
      {
        "IPv4": [
          {
            "address": "172.17.0.1",
            "broadcast": "172.17.255.255",
            "dhcp": "unknown",
            "metric": "0",
            "netmask": "255.255.0.0"
          }
        ],
        "adapter": "",
        "gateway": " ",
        "mac": "02:42:b0:e8:38:d8",
        "mtu": 1500,
        "name": "docker0",
        "rx_bytes": 0,
        "rx_dropped": 0,
        "rx_errors": 0,
        "rx_packets": 0,
        "state": "down",
        "tx_bytes": 0,
        "tx_dropped": 0,
        "tx_errors": 0,
        "tx_packets": 0,
        "type": "ethernet"
      },
      {
        "IPv4": [
          {
            "address": "10.0.2.15",
            "broadcast": "10.0.2.255",
            "dhcp": "unknown",
            "metric": "100",
            "netmask": "255.255.255.0"
          }
        ],
        "IPv6": [
          {
            "address": "fe80::a00:27ff:fee0:d046",
            "broadcast": "",
            "dhcp": "unknown",
            "metric": "",
            "netmask": "ffff:ffff:ffff:ffff::"
          }
        ],
        "adapter": "",
        "gateway": "10.0.2.2",
        "mac": "08:00:27:e0:d0:46",
        "mtu": 1500,
        "name": "enp0s3",
        "rx_bytes": 76521242,
        "rx_dropped": 0,
        "rx_errors": 0,
        "rx_packets": 62473,
        "state": "up",
        "tx_bytes": 5095582,
        "tx_dropped": 0,
        "tx_errors": 0,
        "tx_packets": 25562,
        "type": "ethernet"
      },
      {
        "IPv4": [
          {
            "address": "192.168.56.2",
            "broadcast": "192.168.56.255",
            "dhcp": "unknown",
            "metric": "0",
            "netmask": "255.255.255.0"
          }
        ],
        "IPv6": [
          {
            "address": "fe80::a00:27ff:fe89:5d9d",
            "broadcast": "",
            "dhcp": "unknown",
            "metric": "",
            "netmask": "ffff:ffff:ffff:ffff::"
          }
33        ],
        "adapter": "",
        "gateway": " ",
        "mac": "08:00:27:89:5d:9d",
        "mtu": 1500,
        "name": "enp0s8",
        "rx_bytes": 2436384,
        "rx_dropped": 0,
        "rx_errors": 0,
        "rx_packets": 8871,
        "state": "up",
        "tx_bytes": 7687108,
        "tx_dropped": 0,
        "tx_errors": 0,
        "tx_packets": 12317,
        "type": "ethernet"
      }
    ]
  }
}
```
</details>

## Possible cause
Wazuh agent daemon/module retrieve this information from wm_control module, that internally use Sysinfo (data_provider) to get primaryIP. 
When an interface with a valid gateway is found, IPv6 information has precedence over IPv4 (see L64)

https://github.com/wazuh/wazuh/blob/b678c56bc9824883cc458b76b5beb7adfdaf3a80/src/wazuh_modules/wm_control.c#L44-L106

## Definition of done
- [x] RCA
- [x] Define the expected behavior with the PO
- [x] Get changes traceability to get possible affected modules
- [x] Fix development
- [x] Unit tests
- [x] CICD checks
- [x] QA Coverage test - https://github.com/wazuh/wazuh-qa/issues/3590

### PR DESCRIPTION
**Pull request by jnasselle**
|Related issue|
|---|
|Closes #14988|

## Description

This PR aims to solve #14988 by changing the approach used to retrieve the agent's IP address.

Agent's IP is sent by agent every [`notify_time`](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#notify-time) seconds within other information like `merge.mg` hash. This information is stored in `global.db` and could be retrieved from different ways

- Wazuh Dashboard
- Wazuh API
- Wazuh CLI tools

Agent IP is retrieved in the next ways depending on the OS
- Linux, Solaris, FreeBSD, OpenBSD: `wazuh-agentd` request such information to `wazuh-modulesd`, in specific to `control` module
- Windows: since there's only one process, information is retrieved internally using `win_utils` function
- Others (HP-UX, AIX)

## Change proposal

Currently, Wazuh picks the first address of the interface that has the gateway (no matter the IP type of this), having IPv6 addresses priority over IPv4, leading to unwanted behavior.

The proposed fix implements the next approach
- IPv4 gateway? try to get any listed IPv4 address. If there's no IPv4, try any IPv6 address listed
- IPv6 gateway? try to get any listed address. If there's no IPv6, try any IPv4 address listed

In cases like no gateway, no IP addresses, etc, behavior it's still the same

NOTE: currently there's no Sysinfo support for IPv6 gateways (feature request [here](https://github.com/wazuh/wazuh/issues/11614) and [here](https://github.com/wazuh/wazuh/issues/11615)). The current fix contemplates this scenario for the future

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [ ] MAC OS X
- [x] Source installation
- [x] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [x] Scan-build report
  - [ ] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [x] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [x] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [x] The data flow works as expected (agent-manager-api-app)
- [x] Added unit tests (for new features)
- [ ] Stress test for affected components

### CODE REVIEW

**Review by jftuduri — APPROVED** [review]
LGTM!

**Review by sebasfalcone — APPROVED** [review]
LGTM!

**Review by vikman90 — APPROVED** [review]

**Review by cborla — APPROVED** [review]
LGTM

**Review by jmv74211 — APPROVED** [review]
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3611
- **Comments**:  https://github.com/wazuh/wazuh-qa/issues/3611#issuecomment-1329295536

**Pull request merged**
