### PR TITLE
FIMv2: Take Windows 4659 Events (deferred delete) into account

### PR DESCRIPTION
**Pull request by Molter73**
|Related issue|Wazuh QA Issue|
|---|---|
|#4670|wazuh/wazuh-qa#642|

## Description
This PR aims to take the deferred delete events on Windows (4659) into account. 

When deleting a file directly by using the `shift+del` shortcut or a `del` command the deferred delete event is triggered, followed by events 4656 and 4658. Since no 4660 (delete) event is triggered, FIM was not detecting the deletion of the file.

The 4659 event marks a file for deletion and no further actions on the file should be allowed other than it being deleted. Since there is no `handle_id` associated with the event, the easiest way to trigger the delete event is to generate it directly when receiving it and removing the file from the fim db.

## Configuration options
The default `localfile` eventchannel query on windows configuration was changed in order to exclude 4659 events which are now being handled by syscheck.
```
  <localfile>
    <location>Security</location>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and
      EventID != 5152 and EventID != 5157 and EventID != 4659]</query>
  </localfile>
```

## Logs/Alerts example
Creating a file in a monitored directory and deleting it permanently now triggers the expected alert:
```
** Alert 1585727850.596894: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Apr 01 07:57:30 (windows-agent) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File 'c:\testdir\nuevo documento de texto.txt' added
Mode: whodata

Attributes:
 - Size: 0
 - Permissions: Administradores (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, SYSTEM (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, Usuarios (allowed): read_control|synchronize|read_data|read_ea|execute|read_attributes, Usuarios autentificados (allowed): delete|read_control|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes
 - Date: Wed Apr  1 07:57:29 2020
 - User: moltr (S-1-5-21-1420650776-740624069-4218096664-1001)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - File attributes: ARCHIVE
 - (Audit) User name: moltr
 - (Audit) Process id: 13464
 - (Audit) Process name: C:\Windows\explorer.exe

** Alert 1585727854.598222: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Apr 01 07:57:34 (windows-agent) any->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File 'c:\testdir\nuevo documento de texto.txt' deleted
Mode: whodata

Attributes:
 - Size: 0
 - Permissions: Administradores (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, SYSTEM (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, Usuarios (allowed): read_control|synchronize|read_data|read_ea|execute|read_attributes, Usuarios autentificados (allowed): delete|read_control|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes
 - Date: Wed Apr  1 07:57:29 2020
 - User: moltr (S-1-5-21-1420650776-740624069-4218096664-1001)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - File attributes: ARCHIVE
 - (Audit) User name: moltr
 - (Audit) Process id: 13464
```

## Tests

- Compilation without warnings in every supported platform
  - [x] Windows
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory

### CODE REVIEW

**Comment by wazuhci** [comment]
The stress test has been launched. The charts will be posted when they are ready.
I will use the following configuration:
### General
- Commit: a4f1ecc
- Packages: 
  - [manager 3.12.1 0.commita4f1ecc rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-manager-3.12.1-0.commita4f1ecc.x86_64.rpm)
  - [agent 3.12.1 0.commita4f1ecc rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-agent-3.12.1-0.commita4f1ecc.x86_64.rpm)
  - [manager 3.12.1 0.commita4f1ecc deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-manager_3.12.1-0.commita4f1ecc_amd64.deb)
  - [agent 3.12.1 0.commita4f1ecc deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-agent_3.12.1-0.commita4f1ecc_amd64.deb)
  - [agent 3.12.1 0.commita4f1ecc msi](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/windows/wazuh-agent-3.12.1-0.commita4f1ecc.msi)

### Stress test parameters:
- Manager system: `centos`
- Launch CentOS agent: `true`
- Launch Ubuntu agent: `true`
- Launch Windows agent: `true`
- Test duration: `60`
- Scan frequency: `10`
- Modules to test: 
  - logcollector: `true`
  - syscheck: `true`
  - rootcheck: `true`
  - sca: `true`
  - osquery: `true`
  - syscollector: `true`
  - active-response: `true`
  - azure-logs: `true`
  - cis-cat: `true`
  - docker-listener: `true`
  - open-scap: `true`
  - vulnerability-detector: `false`
- FIM special test: `None`
- FIM sleep: `300`
- FIM max files: `25000`
- SCA sleep: `30`
- SCA max registers: `5000`
- Docker image name: `hello-world`
- Docker sleep: `5`
- Docker jobs: `10`
- Logcollector special test: `None`
- Logcollector max files: `50000`
- Logcollector creation sleep: `300`
- Logcollector write files: `1000`
- Logcollector write sleep: `10`
- Vuln sleep: `60`
- Authd port: `1515`
- Syscollector package: `imagemagick.app`
- Syscollector package version: `7.0.8.48`

Regards!.

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** a4f1ecc491a99f6737ff74a278b9ad5cd32ce4ee
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.1/B1053/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.1/B1053/ossec.log)
**Coverage:** 

```json
Lines executed:31.40% of 1860

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.1/B1053/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.1-B1053.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.1/B1053/Analysis_dynamic_valgrind-v3.12.1-B1053.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** a4f1ecc491a99f6737ff74a278b9ad5cd32ce4ee
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.1/B1054/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.1/B1054/ossec.log)
**Coverage:** 

```json
Lines executed:26.50% of 2996

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.1/B1054/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.1-B1054.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.1/B1054/Analysis_dynamic_valgrind-v3.12.1-B1054.log)

**Comment by wazuhci** [comment]
## Stress/Leaks test results
### Windows Agent ID0
- #### CPU
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.1/B567/monitor-winagent-ID0_B567_Test_stress_windows_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.1/B567/monitor-winagent-ID0_B567_Test_stress_windows_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.1/B567/monitor-winagent-ID0_B567_Test_stress_windows_Agent-warehouse-pullrequests_RSS(KB).svg)
### CentOS Manager ID0
- #### CPU
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.1/B567/monitor-manager-ID0_B567_Test_stress_Manager-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.1/B567/monitor-manager-ID0_B567_Test_stress_Manager-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.1/B567/monitor-manager-ID0_B567_Test_stress_Manager-warehouse-pullrequests_RSS(KB).svg)
### CentOS Agent ID1
- #### CPU
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.1/B567/monitor-agent-ID1_B567_Test_stress_centos_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.1/B567/monitor-agent-ID1_B567_Test_stress_centos_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.1/B567/monitor-agent-ID1_B567_Test_stress_centos_Agent-warehouse-pullrequests_RSS(KB).svg)
### Ubuntu Agent ID0
- #### CPU
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.1/B567/monitor-agent-ID0_B567_Test_stress_ubuntu_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.1/B567/monitor-agent-ID0_B567_Test_stress_ubuntu_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.1/B567/monitor-agent-ID0_B567_Test_stress_ubuntu_Agent-warehouse-pullrequests_RSS(KB).svg)

**Comment by wazuhci** [comment]
The stress test has been launched. The charts will be posted when they are ready.
I will use the following configuration:
### General
- Commit: 9aecdd5
- Packages: 
  - [manager 3.12.1 0.commit9aecdd5 rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-manager-3.12.1-0.commit9aecdd5.x86_64.rpm)
  - [agent 3.12.1 0.commit9aecdd5 rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-agent-3.12.1-0.commit9aecdd5.x86_64.rpm)
  - [manager 3.12.1 0.commit9aecdd5 deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-manager_3.12.1-0.commit9aecdd5_amd64.deb)
  - [agent 3.12.1 0.commit9aecdd5 deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-agent_3.12.1-0.commit9aecdd5_amd64.deb)
  - [agent 3.12.1 0.commit9aecdd5 msi](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/windows/wazuh-agent-3.12.1-0.commit9aecdd5.msi)

### Stress test parameters:
- Manager system: `centos`
- Launch CentOS agent: `true`
- Launch Ubuntu agent: `true`
- Launch Windows agent: `true`
- Test duration: `60`
- Scan frequency: `10`
- Modules to test: 
  - logcollector: `true`
  - syscheck: `true`
  - rootcheck: `true`
  - sca: `true`
  - osquery: `true`
  - syscollector: `true`
  - active-response: `true`
  - azure-logs: `true`
  - cis-cat: `true`
  - docker-listener: `true`
  - open-scap: `true`
  - vulnerability-detector: `false`
- FIM special test: `None`
- FIM sleep: `300`
- FIM max files: `25000`
- SCA sleep: `30`
- SCA max registers: `5000`
- Docker image name: `hello-world`
- Docker sleep: `5`
- Docker jobs: `10`
- Logcollector special test: `None`
- Logcollector max files: `50000`
- Logcollector creation sleep: `300`
- Logcollector write files: `1000`
- Logcollector write sleep: `10`
- Vuln sleep: `60`
- Authd port: `1515`
- Syscollector package: `imagemagick.app`
- Syscollector package version: `7.0.8.48`

Regards!.

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 9aecdd54a96326172920d96e8c8a2a09e98a3e62
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.1/B1059/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.1/B1059/ossec.log)
**Coverage:** 

```json
Lines executed:31.40% of 1860

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.1/B1059/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.1-B1059.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.1/B1059/Analysis_dynamic_valgrind-v3.12.1-B1059.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 9aecdd54a96326172920d96e8c8a2a09e98a3e62
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.1/B1060/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.1/B1060/ossec.log)
**Coverage:** 

```json
Lines executed:26.50% of 2996

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.1/B1060/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.1-B1060.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.1/B1060/Analysis_dynamic_valgrind-v3.12.1-B1060.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** fe83506f603802925465310e292232ad19da8979
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1610/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1610/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1610/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1610.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1610/Analysis_dynamic_valgrind-v3.13.0-B1610.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** fe83506f603802925465310e292232ad19da8979
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1611/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1611/ossec.log)
**Coverage:** 

```json
Lines executed:26.47% of 3056

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1611/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1611.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1611/Analysis_dynamic_valgrind-v3.13.0-B1611.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** d5399af8529e285591aea5ad7ca9273f356d1a3a
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1626/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1626/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1626/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1626.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1626/Analysis_dynamic_valgrind-v3.13.0-B1626.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** d5399af8529e285591aea5ad7ca9273f356d1a3a
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1627/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1627/ossec.log)
**Coverage:** 

```json
Lines executed:26.51% of 3056

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1627/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1627.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1627/Analysis_dynamic_valgrind-v3.13.0-B1627.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 1251b65f35b185c25a616a38c3f9f3eddd48f570
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1805/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1805/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1805/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1805.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1805/Analysis_dynamic_valgrind-v3.13.0-B1805.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 1251b65f35b185c25a616a38c3f9f3eddd48f570
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1806/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1806/ossec.log)
**Coverage:** 

```json
Lines executed:27.00% of 3159

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1806/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1806.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1806/Analysis_dynamic_valgrind-v3.13.0-B1806.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 1251b65f35b185c25a616a38c3f9f3eddd48f570
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1811/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1811/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1811/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1811.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1811/Analysis_dynamic_valgrind-v3.13.0-B1811.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 1251b65f35b185c25a616a38c3f9f3eddd48f570
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1812/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1812/ossec.log)
**Coverage:** 

```json
Lines executed:26.97% of 3159

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1812/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1812.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1812/Analysis_dynamic_valgrind-v3.13.0-B1812.log)

**Comment by jesusjimsa** [comment]
Here is the integration test report: [report.zip](https://github.com/wazuh/wazuh/files/4634215/agent_windows_html_report_test_integration_B143_20200514161758.zip)

**Comment by Molter73** [comment]
We are currently working on a refactor of whodata_callback which also takes 4659 events into account. Closing this PR since it will be fixed by #5144

**Pull request closed without merging**
