### PR TITLE
Fix a memory leak in Analysisd when overwriting a rule multiple times

### LINKED ISSUE #13505: Memory leak when overwriting a rule more than once
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.3.1 | Analysisd | Manager | All | All |

### Description

As reported in https://github.com/wazuh/wazuh/pull/13439#issuecomment-1126002863, we found a memory leak when a rule is overwritten twice or more times.

Here an example of rules than trigger the memory leak:
```xml
<!--
  Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
  -->
  <rule id="100001" level="5">
    <if_sid>5716</if_sid>
    <srcip>1.1.1.1</srcip>
    <description>sshd: authentication failed from IP 1.1.1.1.</description>
    <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
  </rule>

  <rule id="100001" level="12" overwrite="yes">
    <if_sid>5715</if_sid>
    <srcip>1.1.1.1</srcip>
    <description>Test overwrite</description>
    <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
  </rule>

  <rule id="100001" level="15" overwrite="yes">
    <if_sid>122000</if_sid>
    <srcip>1.1.1.1</srcip>
    <description>Test overwrite two</description>
    <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
  </rule>
```

And the valgrind report:

```bash
==12932== HEAP SUMMARY:
==12932==     in use at exit: 25,509,631 bytes in 124,334 blocks
==12932==   total heap usage: 820,306 allocs, 695,972 frees, 2,528,420,808 bytes allocated
==12932== 
==12932== 5 bytes in 1 blocks are indirectly lost in loss record 9 of 558
==12932==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12932==    by 0x12C550: loadmemory (rules.c:2004)
==12932==    by 0x1272C3: Rules_OP_ReadRules (rules.c:955)
==12932==    by 0x145B3C: main (analysisd.c:693)
==12932== 
==12932== 549 (544 direct, 5 indirect) bytes in 1 blocks are definitely lost in loss record 326 of 558
==12932==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12932==    by 0x12C860: zerorulemember (rules.c:2065)
==12932==    by 0x1238D6: Rules_OP_ReadRules (rules.c:385)
==12932==    by 0x145B3C: main (analysisd.c:693)
==12932== 
==12932== LEAK SUMMARY:
==12932==    definitely lost: 544 bytes in 1 blocks
==12932==    indirectly lost: 5 bytes in 1 blocks
==12932==      possibly lost: 32,912 bytes in 121 blocks
==12932==    still reachable: 25,476,170 bytes in 124,211 blocks
==12932==         suppressed: 0 bytes in 0 blocks
==12932== Reachable blocks (those to which a pointer was found) are not shown.
==12932== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==12932== 
==12932== For counts of detected and suppressed errors, rerun with: -v
==12932== ERROR SUMMARY: 23 errors from 23 contexts (suppressed: 0 from 0)
==12932== could not unlink /tmp/vgdb-pipe-from-vgdb-to-12932-by-root-on-???
==12932== could not unlink /tmp/vgdb-pipe-to-vgdb-from-12932-by-root-on-???
==12932== could not unlink /tmp/vgdb-pipe-shared-mem-vgdb-12932-by-root-on-???
```

### DoD

- [x] Fix the memory leak
- [x] Create automated tests to replicate the use case

### PR DESCRIPTION
**Pull request by vikman90**
|Related issue|
|---|
|Fixes #13505|

This PR aims to fix this memory leak, that appears when overwriting a rule more than once:

```
==20785==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 544 byte(s) in 1 object(s) allocated from:
    #0 0x7efca38b0a37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x55bc4b1cc394 in zerorulemember analysisd/rules.c:2065
    #2 0x55bc4b1b56b8 in Rules_OP_ReadRules analysisd/rules.c:385
    #3 0x55bc4b1e6b45 in main analysisd/analysisd.c:687
    #4 0x7efca2cc7fcf in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Indirect leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0x7efca38b0a37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x55bc4b1cbdb2 in loadmemory analysisd/rules.c:2004
    #2 0x55bc4b1bf2c1 in Rules_OP_ReadRules analysisd/rules.c:955
    #3 0x55bc4b1e6b45 in main analysisd/analysisd.c:687
    #4 0x7efca2cc7fcf in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: 549 byte(s) leaked in 2 allocation(s).
```

## Rationale

Rules with the `overwrite` flag replace the previous rule at `OS_AddRuleInfo()`. That function saves a pointer to the new rule structure into member `rule_overwrite`. But, if we redefine the same rule again, this pointer is overwritten, and we leak the second rule's structure.

## Proposed fix

Replace the pointer to a rule with a list of pointers. Thus, each rule will support many overwrites (the limit is undefined).

## Tests

- [x] Defining a rule 5 times (using `overwrite`) does not produce a memory leak (using AddressSanitizer).
- [x] The rule test included in this PR reveals three memory leaks in 4.3.1 but not in this branch.

### CODE REVIEW

**Review by chemamartinez — APPROVED** [review]
LGTM!

**Comment by vikman90** [comment]
Fixing the following extra memory leaks when having a single (or multiple) rule overwrite:

### `<if_sid>`
```
==2021==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0x7f5ba8292a37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x55ae29f2fdb2 in loadmemory analysisd/rules.c:2004
    #2 0x55ae29f232c1 in Rules_OP_ReadRules analysisd/rules.c:955
    #3 0x55ae29f0fc06 in w_logtest_initialize_session analysisd/logtest.c:462
    #4 0x55ae29f14364 in w_logtest_process_request_log_processing analysisd/logtest.c:1085
    #5 0x55ae29f13d12 in w_logtest_process_request analysisd/logtest.c:1024
    #6 0x55ae29f0dd2c in w_logtest_clients_handler analysisd/logtest.c:145
    #7 0x55ae29f0d490 in w_logtest_init analysisd/logtest.c:66
    #8 0x7f5ba770db42 in start_thread nptl/pthread_create.c:442

SUMMARY: AddressSanitizer: 5 byte(s) leaked in 1 allocation(s).
```

### `<if_level>`

```
==7305==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4 byte(s) in 2 object(s) allocated from:
    #0 0x7f81997cba37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x5576b53c3db2 in loadmemory analysisd/rules.c:2004
    #2 0x5576b53b75ee in Rules_OP_ReadRules analysisd/rules.c:970
    #3 0x5576b53a3c06 in w_logtest_initialize_session analysisd/logtest.c:462
    #4 0x5576b53a8364 in w_logtest_process_request_log_processing analysisd/logtest.c:1085
    #5 0x5576b53a7d12 in w_logtest_process_request analysisd/logtest.c:1024
    #6 0x5576b53a1d2c in w_logtest_clients_handler analysisd/logtest.c:145
    #7 0x5576b53a1490 in w_logtest_init analysisd/logtest.c:66
    #8 0x7f8198c46b42 in start_thread nptl/pthread_create.c:442

SUMMARY: AddressSanitizer: 4 byte(s) leaked in 2 allocation(s).
```

**Review by JcabreraC — APPROVED** [review]
LGTM !

**Comment by JcabreraC** [comment]
## Valgrind
```bash
# pkill -f analysisd; valgrind --track-origins=yes --leak-check=full --keep-stacktraces=alloc-and-free --num-callers=20 --show-leak-kinds=definite,indirect --log-file=/home/user/ValgrindPRs.log /var/ossec/bin/wazuh-analysisd -f
```
output:
```
==16543== Memcheck, a memory error detector
==16543== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==16543== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==16543== Command: /var/ossec/bin/wazuh-analysisd -f
==16543== Parent PID: 12523
==16543== 
==16543== 
==16543== HEAP SUMMARY:
==16543==     in use at exit: 22,143,343 bytes in 118,929 blocks
==16543==   total heap usage: 1,559,066 allocs, 1,440,137 frees, 4,980,211,293 bytes allocated
==16543== 
==16543== LEAK SUMMARY:
==16543==    definitely lost: 0 bytes in 0 blocks
==16543==    indirectly lost: 0 bytes in 0 blocks
==16543==      possibly lost: 32,640 bytes in 120 blocks
==16543==    still reachable: 22,110,703 bytes in 118,809 blocks
==16543==         suppressed: 0 bytes in 0 blocks
==16543== Reachable blocks (those to which a pointer was found) are not shown.
==16543== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==16543== 
==16543== For counts of detected and suppressed errors, rerun with: -v
==16543== ERROR SUMMARY: 22 errors from 22 contexts (suppressed: 0 from 0)
==16543== could not unlink /tmp/vgdb-pipe-from-vgdb-to-16543-by-root-on-???
==16543== could not unlink /tmp/vgdb-pipe-to-vgdb-from-16543-by-root-on-???
==16543== could not unlink /tmp/vgdb-pipe-shared-mem-vgdb-16543-by-root-on-???
```

**Comment by jmv74211** [comment]
## QA review

- **Type**: Manual testing
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/2998
- **Comments**: Nothing to highlight. Everything seems to work properly

**Pull request merged**
