### PR TITLE
Rework SCA Policy Ubuntu Linux 20.04

### PR DESCRIPTION
**Pull request by IsExec**
|Wazuh version| Component | 
|---| --- |
| 4.4.x | SCA | 

Rework SCA Policy for Ubuntu Linux 20.04

- [x] Solve typos.
- [x] Increase check coverage. 
- [x] Improve rules implementation.
- [x] Improve texts.
- [x] Solve reported issues:

### CODE REVIEW

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh/issues/17919 - Solved with this PR

@Selutario

**Comment by jk-olaoluwa** [comment]
LGTM

**Comment by IsExec** [comment]
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19192; Result: 'passed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19193; Result: 'passed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19194; Result: 'passed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19195; Result: 'passed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19196; Result: 'passed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19197; Result: 'passed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19198; Result: 'passed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19199; Result: 'passed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19200; Result: 'passed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19201; Result: 'passed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19202; Result: 'passed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19203; Result: 'passed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19204; Result: 'failed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19205; Result: 'failed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19206; Result: 'passed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19207; Result: 'passed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19208; Result: 'passed'
2023/07/14 08:05:07 sca[11031] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 19209; Result: 'passed'
2023/07/14 08:05:10 sca[11031] wm_sca.c:2450 at wm_sca_send_summary(): DEBUG: Sending summary event for file: 'cis_ubuntu20-04.yml'
2023/07/14 08:05:10 sca[11031] wm_sca.c:270 at wm_sca_send_alert(): DEBUG: Sending event: {"type":"summary","scan_id":551005352,"name":"CIS Ubuntu Linux 20.04 LTS Benchmark v2.0.0","policy_id":"cis_ubuntu20-04","file":"cis_ubuntu20-04.yml","description":"This document provides prescriptive guidance for establishing a secure configuration posture for Ubuntu Linux 20.04 LTS.","references":"https://www.cisecurity.org/cis-benchmarks/","passed":90,"failed":117,"invalid":3,"total_checks":210,"score":43.4782600402832,"start_time":1689347094,"end_time":1689347107,"hash":"ea03c0c804d5785f27da8022b5a5ded8e7f10da12cbdf4879faaac283194f1da","hash_file":"652b280a86e4af8c1ba8341ac8c9e8cb16634f6d1b5908a6ef80d0f83fe7bc0c","first_scan":1}

**Review by jk-olaoluwa — APPROVED** [review]
LGTM

**Review by 72nomada — APPROVED** [review]
LGTM

**Pull request merged**
