### PR TITLE
Revert for Sophos UTM firewall rules

### PR DESCRIPTION
**Pull request by jcruzlp**
|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/10972|

## Description

This PR adds the revert for the rules and ini testing of Sophos UTM Firewall added in: https://github.com/wazuh/wazuh/pull/10496

This will be reverted because the provided logs were not enough to develop new rules based on them:
```log
<139>2021:05:19-09:39:29 fw-int-name httpd[25917]: [proxy_http:error] [pid 25917:tid 3878202224] (70007)The timeout specified has expired: [client x.x.x.x:60914] AH01102: error reading status line from remote server x.x.x.x:443
```

These kinds of logs are not enough to develop rules and decoders for Sophos, and in consequence, the created rules couldn't ensure quality. So in this PR, the changes will be reverted.

### Syntax

- ~~1.a Rule tags order must be compliant.~~
-  ~~1.b Decoder tags order must be compliant.~~
-   ~~1.c XML blocks must as compact as possible.~~
-  ~~1.d Only one empty line between rule/decoder and the next rule/decoder.~~
-   ~~1.e Decoder extracted fields names must use '_' whether a space is needed.~~
-  ~~1.f Decoder name must use '-' whether a space is needed.~~
-  ~~2.d XML and ini files must use correct indentation~~
 
### Grammar

- ~~2.a Grammar quality.~~
- ~~2.b Similar phrases must keep tenses and expressions.~~
- ~~2.c Grammar basic rules like capitalization, punctuation marks, sentence construction, and others.~~

### Semantic

-   ~~3.a New decoder, rule, or test are written in the correct file and grouped correctly inside the file.~~
-   ~~3.b Group similar rules under same ID's group.~~
-  ~~3.c:~~
     - ~~3.c1 Find and reuse group name before creating a new one.~~
     - ~~3.c2 Include a new group definition in a PR comment.~~
     - ~~3.c3 Any group name must use '_' whether it does need a space char.~~
     - ~~3.c4 The groups inside a tag must be sorted in alphabetical order.~~
-  ~~3.d Rule level should be compliant with the [documentation](https://documentation.wazuh.com/current/user-manual/ruleset/rules-classification.html).~~

### Unit testing

-   ~~4.a A metadata block at the beginning of the .ini file describing software, version, and logs source.~~
-  ~~4.b Each new rule must have at least one test entry in the correct .ini file.~~
- [x] 4.c Runtest.py must pass and must include the results in raw format here.
<details><summary>Tests results</summary>
<p>

## python runtests.py -t tests/sophos.ini 

```
- [ File = ./tests/sophos.ini ] ---------
..............

- [ File = ./tests/doas.ini ] ---------
....

- [ File = ./tests/office365.ini ] ---------
................................................................................................................................

- [ File = ./tests/iptables.ini ] ---------
........

- [ File = ./tests/exim.ini ] ---------
.......

- [ File = ./tests/api.ini ] ---------
............................

- [ File = ./tests/trendmicro-cloud-one.ini ] ---------
.................

- [ File = ./tests/web_appsec.ini ] ---------
...............................

- [ File = ./tests/cisco_asa.ini ] ---------
........................................................................................

- [ File = ./tests/firewalld.ini ] ---------
..

- [ File = ./tests/mailscanner.ini ] ---------
.

- [ File = ./tests/nextcloud.ini ] ---------
.......

- [ File = ./tests/icinga.ini ] ---------
....

- [ File = ./tests/ossec.ini ] ---------
.....

- [ File = ./tests/paloalto.ini ] ---------
................

- [ File = ./tests/named.ini ] ---------
.....

- [ File = ./tests/vsftpd.ini ] ---------
....

- [ File = ./tests/gcp.ini ] ---------
...........

- [ File = ./tests/web_rules.ini ] ---------
..........

- [ File = ./tests/sysmon.ini ] ---------
...

- [ File = ./tests/fireeye.ini ] ---------
...

- [ File = ./tests/arbor.ini ] ---------
..

- [ File = ./tests/cisco_ios.ini ] ---------
.................

- [ File = ./tests/sudo.ini ] ---------
........

- [ File = ./tests/modsecurity.ini ] ---------
......

- [ File = ./tests/postfix.ini ] ---------
..

- [ File = ./tests/freepbx.ini ] ---------
......

- [ File = ./tests/SonicWall.ini ] ---------
........

- [ File = ./tests/audit_scp.ini ] ---------
.

- [ File = ./tests/cimserver.ini ] ---------
..

- [ File = ./tests/nginx.ini ] ---------
............

- [ File = ./tests/junos.ini ] ---------
...

- [ File = ./tests/glpi.ini ] ---------
...

- [ File = ./tests/proftpd.ini ] ---------
.......

- [ File = ./tests/syslog.ini ] ---------
......

- [ File = ./tests/fortigate.ini ] ---------
........................................

- [ File = ./tests/f5_big_ip.ini ] ---------
...........................................

- [ File = ./tests/opensmtpd.ini ] ---------
.......

- [ File = ./tests/sophos.ini ] ---------
..............

- [ File = ./tests/netscreen.ini ] ---------
....

- [ File = ./tests/apparmor.ini ] ---------
.....

- [ File = ./tests/squid_rules.ini ] ---------
..

- [ File = ./tests/gitlab.ini ] ---------
.........................

- [ File = ./tests/checkpoint_smart1.ini ] ---------
..................

- [ File = ./tests/apache.ini ] ---------
..................

- [ File = ./tests/dovecot.ini ] ---------
...............

- [ File = ./tests/systemd.ini ] ---------
..

- [ File = ./tests/pam.ini ] ---------
.....

- [ File = ./tests/github.ini ] ---------
....................................................................................................................................................................................................................................................................................................................................

- [ File = ./tests/oscap.ini ] ---------
................................

- [ File = ./tests/huawei_usg.ini ] ---------
...

- [ File = ./tests/cpanel.ini ] ---------
.......

- [ File = ./tests/samba.ini ] ---------
....

- [ File = ./tests/audit_lateral.ini ] ---------
......

- [ File = ./tests/vuln_detector.ini ] ---------
..

- [ File = ./tests/owlh.ini ] ---------
....

- [ File = ./tests/exchange.ini ] ---------
..

- [ File = ./tests/cisco_ftd.ini ] ---------
..........................................

- [ File = ./tests/openvpn_ldap.ini ] ---------
..

- [ File = ./tests/panda_paps.ini ] ---------
........

- [ File = ./tests/fortiauth.ini ] ---------
....

- [ File = ./tests/dropbear.ini ] ---------
...

- [ File = ./tests/mcafee_epo.ini ] ---------
.

- [ File = ./tests/openldap.ini ] ---------
.........

- [ File = ./tests/sshd.ini ] ---------
...........................................

- [ File = ./tests/kernel_usb.ini ] ---------
......

- [ File = ./tests/pix.ini ] ---------
......................

- [ File = ./tests/unbound.ini ] ---------


- [ File = ./tests/rsh.ini ] ---------
..

- [ File = ./tests/cylance.ini ] ---------
.......

- [ File = ./tests/cloudlfare-waf.ini ] ---------
.............

- [ File = ./tests/eset.ini ] ---------
........

- [ File = ./tests/auditd.ini ] ---------
...

- [ File = ./tests/pfsense.ini ] ---------
..

- [ File = ./tests/su.ini ] ---------
.....

- [ File = ./tests/audit_recon.ini ] ---------
..

- [ File = ./tests/aws_s3_access.ini ] ---------
.......
```

</p>
</details>

-  ~~4.d New CDB lists must include the proper test entry in the correct .ini file.~~

### E2E testing

- ~~5.a Logs for new or modified decoder/rules sent to a manager running with this PR ruleset appear in Kibana.~~ 
- ~~5.b There are not affected or broken visualizations on Kibana.~~
- ~~5.c New or modified items can be seen correctly using APP ruleset navigation.~~

### Elasticsearch Template

-  ~~6.a Known fields with output format managed and usually used for searching are included in template array index.query.default_field.~~
- ~~6.b The new field with the correct date format is stored as a "date" type field in the template.~~
-   ~~6.c The new extracted IP fields are in the pipeline as "geo" field and "geo_point" type in the template.~~
-  ~~6.d Known fields with output format managed and usually used for searching are included in the template.~~

### Stoppers

- [x] 7.a No previous rule ID changes without triple check.
- [x] 7.b No previous decoder name changes without triple check.
- [x] 7.c No previous file name changes without triple check.
- [x] 7.d No previous test changes its 'rule' field value without triple check.

### Others

-  ~~8.a Each file has the correct copyright block.~~
- ~~8.b The copyright block doesn't have "Author" only "Created by Wazuh". To include an "Author" request triple check.~~
- ~~8.c The copyright block doesn't use "-".~~
- ~~8.d The rule files don't have any sample log.~~
-  ~~8.e The decoder file has sample logs next to the decoder that matches that log.~~
-  ~~8.f The decoder and rule files have information about software, version, and any helpful information.~~
-  ~~8.g The PR has a single commit with CHANGELOG changes in the correct format.~~
- ~~8.h The new rule ID is not in use.~~
-  ~~8.i The new rule ID must be in the defined IDs range.~~
- ~~8.j New rules ID range must be verified with a triple check and noted in the rules ID document.~~
- ~~8.k The new extracted IP fields are in the pipeline as "geo" field and "geo_point" type in the template.~~

### CODE REVIEW

**Review by xrisbarney — APPROVED** [review]
LGTM.

**Comment by Spades0** [comment]
LGTM.

**Review by Spades0 — APPROVED** [review]
LGTM.

**Review by 72nomada — APPROVED** [review]
LGTM

**Review by nmkoremblum — APPROVED** [review]
LGTM

**Comment by juliancnn** [comment]
LGTM!

**Review by juliancnn — APPROVED** [review]

**Comment by reknayr** [comment]
In 2019 we had someone on our team do pull request for OSSEC to parse the Sophos UTM logs, and created the rules and decoders.  They worked great, but now that we wan to use Wazuh, we can't.  Can a similar change be done for Wazuh?

https://github.com/ossec/ossec-hids/pull/1794

I've attached the Sophos Rules and Decoder xml files for reference.  They also contain example logs that were tested

[local_decoders.txt](https://github.com/wazuh/wazuh/files/8516447/local_decoders.txt)
[local_rules.txt](https://github.com/wazuh/wazuh/files/8516448/local_rules.txt)
.

**Comment by juliancnn** [comment]
Hi @reknayr,

Thanks for using Wazuh and sharing your question with the community!

This PR is merge and closed, I encourage you to open a feature request issue proposing this improvement. This way we can analyse your proposal, estimate it and add it to our roadmap to be able to address it in the future.

On the other hand, if you need this change urgently, you have 2 options:
- You could recompile the Manager by following our documentation ([here](https://documentation.wazuh.com/current/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-server/index.html)).
- Use the [out_format](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html#out-format
) option when you collect the log from the file (localfile). This option will allow to adds a header in front of the log, which will make decoding easier.

If you have questions, feel free to create new issues in our repository. You could also participate in our [slack community](https://wazuh.com/community/join-us-on-slack/) or in our [mailing list](https://groups.google.com/g/wazuh).


Regards,
Julian

**Pull request merged**
