### PR TITLE
Add integration for the Microsoft Graph API

### LINKED ISSUE #16312: Add support for Microsoft Graph security API
## Description
The [Microsoft Graph security API](https://learn.microsoft.com/en-us/graph/api/resources/security-api-overview) provides a unified interface and schema to integrate with security solutions from Microsoft and ecosystem partners. This empowers customers to streamline security operations and better defend against increasing cyber threats. As part of Wazuh's continuous effort to integrate with principal security solutions, we propose designing and developing a new module to integrate logs from the Microsoft Graph Security API.

## Design requirements
To meet the necessary requirements of this module, we propose the following design:

- The solution will be written in C, similar to the current Office 365 module.
- The solution will provide the necessary code structure and layout to develop future integrations and logs with any other Microsoft Graph API endpoints, beyond security.
 image
- The solution will incorporate the same standard options and settings as the other [Wazuh Cloud security modules](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#options), including [AWS](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#options), [Azure](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-azure-logs.html), or [GCP](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/gcp-pubsub.html#options).
- The solution will incorporate full coverage and support to ingest logs from current security endpoints, as illustrated in the diagram below: 
image
- The solution will provide a full set of decoders and rules for Microsoft Graph security API logs.
- The solution will have unit tests with full coverage.
- The solution will incorporate a suite of integration tests, similar to [AWS](https://github.com/wazuh/wazuh-qa/issues/3333).
- The solution will include appropriate [documentation](https://documentation.wazuh.com/current/index.html) to help users understand how to configure and use the module.

## Impact
By adding support for Microsoft Graph Security API logs to the Wazuh platform, users will be able to easily monitor and analyze their security data in a more centralized and streamlined manner. This will help organizations detect and respond to threats faster, leading to a more secure environment for everyone involved.

## Additional Context
We believe that adding support for Microsoft Graph Security API logs to the Wazuh platform is a crucial step in improving the security posture of our users. With this module, Wazuh will be able to provide even more comprehensive coverage of security data across multiple endpoints, helping users better understand their security risks and take appropriate action.

## EPIC details
Epic branch: [feature/16312-microsoft-graph-security-API](https://github.com/wazuh/wazuh/tree/feature/16312-microsoft-graph-security-API)
Last rebase with master: March 2nd 2023 10:03 UTC

### PR DESCRIPTION
**Pull request by S-Bryce**
|Related issue|
|---|
|Resolves #16312|

## Description

A wide variety of logs and statistics concerning Microsoft 365 tenants (and their respective endpoints) are accessible via the Microsoft Graph REST API, which Wazuh does not have a native integration for. This PR addresses this by adding a module ('`ms-graph`) that is capable of communicating with Microsoft Graph & parsing its various logging sources, with an emphasis on the `security` resource.

This includes a full set of rules for categorizing these logs, alongside a standardized suite of configuration options that mirror other modules, such as Azure, GCP, and Office365. In relation to the resolved issue, the following design goals are met:
- [X] The solution will be written in C, similar to the current Office 365 module.
- [X] The solution will provide the necessary code structure and layout to develop future integrations and logs with any other Microsoft Graph API endpoints, beyond security.
- [X] The solution will incorporate the same standard options and settings as the other [Wazuh Cloud security modules](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#options), including [AWS](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#options), [Azure](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-azure-logs.html), or [GCP](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/gcp-pubsub.html#options).
- [X] The solution will incorporate full coverage and support to ingest logs from current security endpoints, including:
  - alerts
  - alerts_v2
  - incidents
  - secureScores
  - And all other security endpoints that support the GET method with date filtering
- [X] The solution will provide a full set of decoders and rules for Microsoft Graph security API logs.
- [X] The solution will have unit tests with full coverage.
- [ ] The solution will incorporate a suite of integration tests, similar to https://github.com/wazuh/wazuh-qa/issues/3333.
- [X] The solution will include appropriate [documentation](https://documentation.wazuh.com/current/index.html) to help users understand how to configure and use the module.
  - Contained within a seperate repo, ready to be made into a PR: https://github.com/S-Bryce/wazuh-documentation/tree/dev-16312-microsoft-graph-security-API

## Configuration options

|Parameter|Allowed Values|
|---|---|
|enabled|yes, no|
|only_future_events|yes, no|
|interval|A positive number + suffix|
|curl_max_size|A positive number + suffix|
|run_on_start|yes, no|
|version|beta, v1.0|
|api_auth|N/A|
|api_auth\tenant_id|Any string|
|api_auth\client_id|Any string|
|api_auth\secret_value|Any string|
|resource|N/A|
|resource\name|Any string|
|resource\relationship|Any string|

### Logging example
image

### Alerts example
```
{
            "integration":"ms-graph",
            "ms-graph":{
                "id":"xxxx-xxxx-xxxx-xxxx-xxxx",
                "providerAlertId":"xxxx-xxxx-xxxx-xxxx-xxxx",
                "incidentId":"91",
                "status":"resolved",
                "severity":"informational",
                "classification":"truePositive",
                "determination":null,
                "serviceSource":"microsoftDefenderForOffice365",
                "detectionSource":"microsoftDefenderForOffice365",
                "detectorId":"xxxx-xxxx-xxxx-xxxx-xxxx",
                "tenantId":"xxxx-xxxx-xxxx-xxxx-xxxx",
                "title":"Email messages containing malicious file removed after delivery.",
                "description":"Emails with malicious file that were delivered and later removed -V1.0.0.3",
                "recommendedActions":"",
                "category":"InitialAccess",
                "assignedTo":"Automation",
                "alertWebUrl":"https://security.microsoft.com/alerts/xxxx-xxxx-xxxx-xxxx-xxxx?tid=xxxx-xxxx-xxxx-xxxx-xxxx",
                "incidentWebUrl":"https://security.microsoft.com/incidents/91?tid=xxxx-xxxx-xxxx-xxxx-xxxx",
                "actorDisplayName":null,
                "threatDisplayName":null,
                "threatFamilyName":null,
                "resource":"security",
                "relationship":"alerts_v2",
                "mitreTechniques":[
                    "T1566.001"
                ],
                "createdDateTime":"2022-11-13T23:48:21.9847068Z",
                "lastUpdateDateTime":"2022-11-14T00:08:37.5366667Z",
                "resolvedDateTime":"2022-11-14T00:07:25.7033333Z",
                "firstActivityDateTime":"2022-11-13T23:45:41.0593397Z",
                "lastActivityDateTime":"2022-11-13T23:47:41.0593397Z",
                "comments":[

                ],
                "evidence":[
                    {
                        "_comment":"Snipped"
                    }
                ]
            }
}
```

### Scan-build
image

### Coverity
image

### Valgrind
image

### Dr. Memory
image

- Compilation without warnings in every supported platform
  - [X] Linux
- [X] Source installation
- [X] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [X] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [X] Scan-build report
  - [X] Coverity
  - [X] Valgrind (memcheck and descriptor leaks check)
  - [X] Dr. Memory
  - [X] AddressSanitizer

- [ ] Working on cluster environments
- [X] Configuration on demand reports new parameters
- [X] The data flow works as expected (agent-manager-api-app)
- [X] Added unit tests (for new features)
- [X] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

### CODE REVIEW

**Comment by Nicogp** [comment]
Hi @S-Bryce,

I have noticed that the `<api_type>` configuration option is not documented, if we see the configuration options in the [documentation branch](https://github.com/S-Bryce/wazuh-documentation/blob/dev-16312-microsoft-graph-security-API/source/user-manual/reference/ossec-conf/ms-graph-module.rst) `<api_type>` is not present :

> Screenshots of the documentation:
> image
> image

and when trying to start the module without that configuration it fails:
```
wazuh-modulesd[65920] wmodules-ms-graph.c:220 at wm_ms_graph_read(): ERROR: (1228): Element 'api_type' without any option.
wazuh-modulesd[65920] config.c:337 at ReadConfig(): ERROR: (1202): Configuration error at 'etc/ossec.conf'.
wazuh-modulesd: Configuration error. Exiting
```

**Comment by S-Bryce** [comment]
> Hi @S-Bryce,
> 
> I have noticed that the `<api_type>` configuration option is not documented, if we see the configuration options in the [documentation branch](https://github.com/S-Bryce/wazuh-documentation/blob/dev-16312-microsoft-graph-security-API/source/user-manual/reference/ossec-conf/ms-graph-module.rst) `<api_type>` is not present :
> ...
> and when trying to start the module without that configuration it fails:
> ...

Thanks for pointing this out, I'll get the documentation updated with `<api_type>` and its options.

**Comment by Nicogp** [comment]
Hi @S-Bryce ,
We are in the process of testing the integration with MS-Graph and are having problems getting logs from resource `security `(relationship `alerts_v2 `or `incidents`).
We follow all the steps in the documentation 
https://github.com/S-Bryce/wazuh-documentation/blob/dev-16312-microsoft-graph-security-API/source/ms-graph/monitoring-ms-graph-activity.rst#microsoft-graph-api-setup
image

but we always get the following error: `Unauthorized request - Account is not provisioned`
`{"error":{"code":"Unauthorized","message":"Unauthorized request - Account is not provisioned.","innerError":{"date":"2023-09-07T20:27:31","request-id":"6f2a18ec-7961-42eb-8a0b-66c12a1cd638","client-request-id":"6f2a18ec-7961-42eb-8a0b-66c12a1cd638"}}}`
Do we need to have a special account to be able to obtain these records? Could you guide us with the correct Azure/Ms-graph configuration so that we can receive the alerts correctly?

`Note: the Auditlogs logs are being obtained correctly.`

**Comment by S-Bryce** [comment]
Hi @Nicogp,

Sorry to hear that you've run into a snag while testing things. Having looked at our own tenants we've tested on and the logs you've included, I had a feeling this is down to a licensing issue. So far I've tested the integration on both a G5 GCC tenant and an E5 GCC High tenant: is the tenant shown in your screenshot a commercial tenant? And if so, is it perhaps an E3 or F3 license? 

My thought is that you might not have a [security provider](https://learn.microsoft.com/en-us/graph/api/resources/securityvendorinformation?view=graph-rest-1.0) included with your current tenant, especially since other resources are being obtained correctly.

**Pull request merged**
