### PR TITLE
Fix overreaching sibling decoders

### PR DESCRIPTION
**Pull request by jctello**
|Related issue|
|---|
|#8675 |

## Description

As mentioned in #8675  in 4.2 some sibling decoders were wrongly configured which would lead to the full event being assigned to several decoded fields.

This PR re-created these decoders with the correct logic and each decoder was tested on the latest RC of 4.2.

### CODE REVIEW

**Comment by juanrricci** [comment]
## Update
Corrected Sophos FW rule file: `<field>` option was replaced by `<status>` option on all the rules.

**Review by jnasselle — COMMENTED** [review]
Hi @juanrricci and @jctello,

One thing to keep in mind is that changing field `sophos_fw_status_msg` (dynamic) to `status`(static) changes the default type of regex used in rules from `osmatch` (status default regex type) to `osregex`(dynamic field default regex).

Despite several rules (70021 to 70030) try to match every available field value, this might affect custom rules that expect no only a specific field name but also to match a osmatch regular expression.

Regards,
Nico

**Comment by jctello** [comment]
Good catch @jnasselle , this PR should not change a previously dynamic field for a static one.
I made sure not to make this change in other places but omitted the one pointed out. 
So the solution here I believe is to modify the decoder and maintain the original rule.

**Comment by juanrricci** [comment]
## Update
- Rolled back Sophos FW rule file: `<status>` option was replaced by `<field>` option on all the rules.
- Rolled back `status` static field to `sophos_fw_status_msg` dynamic field on Sophos FW decoder file.

**Comment by jctello** [comment]
Awesome! 
I approve of the changes made to this branch.
@72nomada please review again for merging consideration.

**Review by jnasselle — APPROVED** [review]
LGTM!

**Review by 72nomada — APPROVED** [review]
LGTM! Merging

**Pull request merged**
