### PR TITLE
Fixed manager controller related tests.

### PR DESCRIPTION
**Pull request by RamosFe**
|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/24506|

## Description

Fixes manager controller related tests.

### CODE REVIEW

**Review by javiersanchz — CHANGES_REQUESTED** [review]
## Review

The changes look good.

The provided tests pass correctly.

Regarding the checks, the Integration API endpoints test failed, specifically the `test_rbac_black_manager_endpoints`.

This test needs to be reviewed as it is part of the changes made in the issue

**Comment by RamosFe** [comment]
## Update

After running it locally, no errors where present in the IT. I created the following issue to investigate these flaky results https://github.com/wazuh/wazuh/issues/24530.

**Review by javiersanchz — APPROVED** [review]
## Review

- The test was run locally and passed successfully. Additionally, https://github.com/wazuh/wazuh/issues/24530 was opened to work on fixing that test.

- From my side, LGTM!

**Review by fdalmaup — APPROVED** [review]
LGTM

> The error in the `test_cluster_endpoints` check is not related to the introduced changes.

**Pull request merged**
