### PR TITLE
Fix package installation script from generating malformed wazuh.json file content

### PR DESCRIPTION
**Pull request by mhamra**
|Related issue|
|---|
|#18785|

## Description
The package installation script creates a malformed wazuh.json file, making failures during the wazuh installation.

The configuration options were removed to fix this failure, changing the wazuh version by a variable and hardcoding the install_type to the 'server' value in the wazuh.json file.

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

### CODE REVIEW

**Comment by mhamra** [comment]
### INSTALL FROM SOURCES CHECK
I've followed the installation from the sources script, but cloning the branch `fix/18785-malformed-wazuh-json-on-install` instead of using the curl command to download the package. This is the result of the installation.

```console
root@844424be6707:/wazuh# more /wazuh/framework/wazuh/core/wazuh.json
{"install_type": "server", "wazuh_version": "v4.8.0", "installation_date": "Fri Sep 29 16:09:39 UTC 2023"}

root@844424be6707:/wazuh# /var/ossec/framework/python/bin/python3 -m pip show wazuh
Name: wazuh
Version: 4.8.0
Summary: Wazuh control with Python
Home-page: https://github.com/wazuh
Author: Wazuh
Author-email: hello@wazuh.com
License: GPLv2
Location: /var/ossec/framework/python/lib/python3.9/site-packages
Requires:
Required-by:
```

After stopping the server, removing the installation with `/var/ossec/bin/wazuh-control stop && rm -rf /var/ossec`, and launching the `/wazuh/install.sh` again, the installation works, and these are the result:

```console
root@844424be6707:/wazuh# /var/ossec/bin/wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...

root@844424be6707:/wazuh# more /wazuh/framework/wazuh/core/wazuh.json
{"install_type": "server", "wazuh_version": "v4.8.0", "installation_date": "Fri Sep 29 16:15:12 UTC 2023"}

root@844424be6707:/wazuh# more /var/ossec/framework/python/lib/python3.9/site-packages/wazuh/core/wazuh.json
{"install_type": "server", "wazuh_version": "v4.8.0", "installation_date": "Fri Sep 29 16:09:39 UTC 2023"}

root@844424be6707:/wazuh# /var/ossec/framework/python/bin/python3 -m pip show wazuh
Name: wazuh
Version: 4.8.0
Summary: Wazuh control with Python
Home-page: https://github.com/wazuh
Author: Wazuh
Author-email: hello@wazuh.com
License: GPLv2
Location: /var/ossec/framework/python/lib/python3.9/site-packages
Requires:
Required-by:
```

### NOTE:
The /wazuh/framework/wazuh/core/ and /var/ossec/framework/python/lib/python3.9/site-packages/wazuh/core/ differ in the installation date value. The package installer uses the file found in the `/wazuh/framework/wazuh/core/` folder, and after that, it generates it again. Repeating the uninstall (entirely removing the /var/ossec folder) and install:

#### Before installation
```console
root@844424be6707:/wazuh# more /wazuh/framework/wazuh/core/wazuh.json
{"install_type": "server", "wazuh_version": "v4.8.0", "installation_date": "Fri Sep 29 16:15:12 UTC 2023"}
```

#### After installation
```console
root@844424be6707:/wazuh# more /wazuh/framework/wazuh/core/wazuh.json
{"install_type": "server", "wazuh_version": "v4.8.0", "installation_date": "Fri Sep 29 16:27:37 UTC 2023"}
root@844424be6707:/wazuh# more /var/ossec/framework/python/lib/python3.9/site-packages/wazuh/core/wazuh.json
{"install_type": "server", "wazuh_version": "v4.8.0", "installation_date": "Fri Sep 29 16:15:12 UTC 2023"}
```

**Comment by mhamra** [comment]
### BUILD ERRORS
image

The above errors are not related to the changes applied to this PR.

**Review by GGP1 — APPROVED** [review]
LGTM

**Review by Selutario — APPROVED** [review]

**Comment by Selutario** [comment]
The reason behind the failing checks is the same as here:
- https://github.com/wazuh/wazuh/pull/19306#issuecomment-1740520176

**Pull request merged**
