### PR TITLE
Keystore refactor

### PR DESCRIPTION
**Pull request by zbalkan**
|Related issue|
|---|
| https://github.com/wazuh/wazuh/issues/24544 |

## Description

After upgrading to Wazuh 4.8.0, I had issues with keystore. Unfortunately all I got was `wazuh-modulesd:vulnerability-scanner: ERROR: VulnerabilityScannerFacade::start: RSA decryption failed`, and it is not helpful in troubleshooting.

In order to improve internal visibility, I only added some `logDebug2` options. Also did some refactoring around keystore application.

## Logs/Alerts example

Before:
```
wazuh-modulesd:vulnerability-scanner: ERROR: VulnerabilityScannerFacade::start: RSA decryption failed
```
After:

```
[DEBUG] keystore: Encryption successful for key: myKey
[DEBUG] keystore: Inserted encrypted value for key: myKey into column family: myFamily
```

```
[DEBUG] keystore: Decryption successful for key: myKey
```

```
[ERROR] keystore: Exception during encryption for key: myKey, Error: RSA encryption failed
```

```
[DEBUG] keystore: Encryption successful for key: myKey
[ERROR] keystore: Exception during database insertion for key: myKey, Error: Failed to put key-value pair into RocksDB
```

```
[DEBUG] keystore: Encryption successful for key: myKey
[DEBUG] keystore: Inserted encrypted value for key: myKey into column family: myFamily
[ERROR] keystore: Exception during decryption for key: myKey, Error: RSA decryption failed
```

```
[ERROR] keystore: Exception during database retrieval for key: myKey, Error: Failed to get value from RocksDB
```

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

### CODE REVIEW

**Comment by zbalkan** [comment]
Feel free to send any kind of feedback as I am not that fluent in C and C++, and I may not be able to provide the cleanest, bug-free code.

**Comment by zbalkan** [comment]
The tests fail for some reason. However, the failures do not come from the code I have changed. I am not sure what to do at this point.

**Comment by sebasfalcone** [comment]
@zbalkan Thanks for taking the time to improve Wazuh!

We are making some improvements around the keystore module here:
- https://github.com/wazuh/wazuh/pull/24529

We already improved the expectation message, and we could add some of the debug logs you propose

**Comment by MiguelazoDS** [comment]
Hi @zbalkan @sebasfalcone, the PR I'm working on is for 4.10. In 4.8.1 there's already an implementation to improve the logging for this tool among other changes, I'll take your contribution and merge it with what is already implemented here https://github.com/wazuh/wazuh/pull/24539. 

Regards!

**Comment by zbalkan** [comment]
Since this has been implemented already in a separate PR, I am closing the ticket.

**Pull request closed without merging**
