### PR TITLE
Updates requirements.txt 

### PR DESCRIPTION
**Pull request by RamosFe**
|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/20795|

## Description

Updates the `requirements.txt` adding new dependencies and deleting old ones. Also added an upgrade https://github.com/wazuh/wazuh/issues/20602.

### CODE REVIEW

**Review by nico-stefani — CHANGES_REQUESTED** [review]
As we already discussed, Is needed to add the dependecies mentioned [here](https://github.com/wazuh/wazuh/issues/20795#issuecomment-1865042094) into the `requeriments.txt`.

**Comment by RamosFe** [comment]
Added in 658962db453e994b7235f54936f921a4b55189ed.

**Review by nico-stefani — APPROVED** [review]
LGMT. The test errors were already addressed in the corresponding issues.

**Review by Selutario — APPROVED** [review]
LGTM

**Pull request merged**
