### PR TITLE
Delete cluster files when the connection is lost

### PR DESCRIPTION
**Pull request by javiersanchz**
|Related issue|
|---|
|#15075|

## Description

The solution has been implemented in the **connection_lost()** method of both **framework/wazuh/core/cluster/master.py** and **framework/wazuh/core/cluster/worker.py.** The **cluster.clean_up()** method has been added so that if the connection is lost between the master and worker or the wazuh-clusterd process is started, those temporary files will be deleted.

### Logs **/var/ossec/bin/wazuh-clusterd**

2023/07/12 11:33:22 DEBUG: [Worker worker] [Main] Disconnected worker.
2023/07/12 11:33:22 INFO: [Worker worker] [Main] Cancelling pending tasks.
2023/07/12 11:33:22 DEBUG: [Worker worker] [Main] Removing '/var/ossec/queue/cluster/worker'.
2023/07/12 11:33:22 DEBUG: [Worker worker] [Main] Removed '/var/ossec/queue/cluster/worker'.

### Test framework/wazuh/core/cluster/tests/test_master.py -v
```
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-0.13.1 -- /home/wazuh/venv/unittest-env/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.10.6', 'Platform': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.3.1', 'pluggy': '0.13.1'}, 'Plugins': {'aiohttp': '0.3.0', 'metadata': '2.0.4', 'html': '2.1.1', 'trio': '0.7.0', 'asyncio': '0.15.1'}}
rootdir: /home/wazuh/Git/wazuh/framework
plugins: aiohttp-0.3.0, metadata-2.0.4, html-2.1.1, trio-0.7.0, asyncio-0.15.1
collected 47 items                                                                                                                                                                                        

framework/wazuh/core/cluster/tests/test_master.py::test_rit_init PASSED                                                                                                                             [  2%]
framework/wazuh/core/cluster/tests/test_master.py::test_rit_set_up_coro PASSED                                                                                                                      [  4%]
framework/wazuh/core/cluster/tests/test_master.py::test_rit_done_callback PASSED                                                                                                                    [  6%]
framework/wazuh/core/cluster/tests/test_master.py::test_revt_init PASSED                                                                                                                            [  8%]
framework/wazuh/core/cluster/tests/test_master.py::test_revt_set_up_coro PASSED                                                                                                                     [ 10%]
framework/wazuh/core/cluster/tests/test_master.py::test_revt_done_callback PASSED                                                                                                                   [ 12%]
framework/wazuh/core/cluster/tests/test_master.py::test_rait_init PASSED                                                                                                                            [ 14%]
framework/wazuh/core/cluster/tests/test_master.py::test_seagt_init PASSED                                                                                                                           [ 17%]
framework/wazuh/core/cluster/tests/test_master.py::test_rait_set_up_coro PASSED                                                                                                                     [ 19%]
framework/wazuh/core/cluster/tests/test_master.py::test_rait_done_callback PASSED                                                                                                                   [ 21%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_init PASSED                                                                                                                  [ 23%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_to_dict PASSED                                                                                                               [ 25%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_process_request PASSED                                                                                                       [ 27%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_execute_ok PASSED                                                                                                            [ 29%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_execute_ko PASSED                                                                                                            [ 31%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_hello_ok PASSED                                                                                                              [ 34%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_hello_ko PASSED                                                                                                              [ 36%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_get_manager PASSED                                                                                                           [ 38%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_process_dapi_res_ok PASSED                                                                                                   [ 40%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_process_dapi_res_ko PASSED                                                                                                   [ 42%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_get_nodes PASSED                                                                                                             [ 44%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_get_health PASSED                                                                                                            [ 46%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_get_permission PASSED                                                                                                        [ 48%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_setup_sync_integrity PASSED                                                                                                  [ 51%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_setup_send_info PASSED                                                                                                       [ 53%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_process_sync_error_from_worker PASSED                                                                                        [ 55%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_end_receiving_integrity_checksums PASSED                                                                                     [ 57%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_sync_wazuh_db_info PASSED                                                                                                    [ 59%]
framework/wazuh/core/cluster/tests/test_master.py::test_manager_handler_send_entire_agent_groups_information PASSED                                                                                 [ 61%]
framework/wazuh/core/cluster/tests/test_master.py::test_manager_handler_send_agent_groups_information PASSED                                                                                        [ 63%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_sync_worker_files_ok PASSED                                                                                                  [ 65%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_sync_worker_files_ko PASSED                                                                                                  [ 68%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_sync_extra_valid PASSED                                                                                                      [ 70%]
framework/wazuh/core/cluster/tests/test_master.py::test_set_date_end_master PASSED                                                                                                                  [ 72%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_integrity_check[compare_result0] PASSED                                                                                      [ 74%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_integrity_check[compare_result1] PASSED                                                                                      [ 76%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_integrity_check_ko PASSED                                                                                                    [ 78%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_integrity_sync PASSED                                                                                                        [ 80%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_process_files_from_worker_ok PASSED                                                                                          [ 82%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_get_logger PASSED                                                                                                            [ 85%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_handler_connection_lost PASSED                                                                                                       [ 87%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_init PASSED                                                                                                                          [ 89%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_to_dict PASSED                                                                                                                       [ 91%]
framework/wazuh/core/cluster/tests/test_master.py::test_agent_groups_update PASSED                                                                                                                  [ 93%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_file_status_update_ok PASSED                                                                                                         [ 95%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_get_health PASSED                                                                                                                    [ 97%]
framework/wazuh/core/cluster/tests/test_master.py::test_master_get_node PASSED                                                                                                                      [100%]
```

### Test framework/wazuh/core/cluster/tests/test_worker.py -v 
```
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-0.13.1 -- /home/wazuh/venv/unittest-env/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.10.6', 'Platform': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.3.1', 'pluggy': '0.13.1'}, 'Plugins': {'aiohttp': '0.3.0', 'metadata': '2.0.4', 'html': '2.1.1', 'trio': '0.7.0', 'asyncio': '0.15.1'}}
rootdir: /home/wazuh/Git/wazuh/framework
plugins: aiohttp-0.3.0, metadata-2.0.4, html-2.1.1, trio-0.7.0, asyncio-0.15.1
collected 35 items                                                                                                                                                                                        

framework/wazuh/core/cluster/tests/test_worker.py::test_rgit_init PASSED                                                                                                                            [  2%]
framework/wazuh/core/cluster/tests/test_worker.py::test_rgit_set_up_coro PASSED                                                                                                                     [  5%]
framework/wazuh/core/cluster/tests/test_worker.py::test_rgcit_set_up_coro PASSED                                                                                                                    [  8%]
framework/wazuh/core/cluster/tests/test_worker.py::test_rgit_done_callback PASSED                                                                                                                   [ 11%]
framework/wazuh/core/cluster/tests/test_worker.py::test_rgcit_done_callback PASSED                                                                                                                  [ 14%]
framework/wazuh/core/cluster/tests/test_worker.py::test_rit_set_up_coro PASSED                                                                                                                      [ 17%]
framework/wazuh/core/cluster/tests/test_worker.py::test_rit_done_callback PASSED                                                                                                                    [ 20%]
framework/wazuh/core/cluster/tests/test_worker.py::test_sync_wazuh_db_init PASSED                                                                                                                   [ 22%]
framework/wazuh/core/cluster/tests/test_worker.py::test_sync_wazuh_db_sync_ok PASSED                                                                                                                [ 25%]
framework/wazuh/core/cluster/tests/test_worker.py::test_sync_wazuh_db_sync_ko PASSED                                                                                                                [ 28%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_init PASSED                                                                                                                  [ 31%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_connection_result PASSED                                                                                                     [ 34%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_process_request_ok PASSED                                                                                                    [ 37%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_connection_lost PASSED                                                                                                       [ 40%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_process_request_ko PASSED                                                                                                    [ 42%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_get_manager PASSED                                                                                                           [ 45%]
framework/wazuh/core/cluster/tests/test_worker.py::test_master_handler_setup_sync_integrity PASSED                                                                                                  [ 48%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_setup_receive_files_from_master PASSED                                                                                       [ 51%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_end_receiving_integrity PASSED                                                                                               [ 54%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_error_receiving_integrity PASSED                                                                                             [ 57%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_sync_integrity_ok_from_master PASSED                                                                                         [ 60%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_compare_agent_groups_checksums PASSED                                                                                                [ 62%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_check_agent_groups_checksums PASSED                                                                                                  [ 65%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_recv_agent_groups_information PASSED                                                                                         [ 68%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_sync_integrity PASSED                                                                                                        [ 71%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_sync_agent_info PASSED                                                                                                       [ 74%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_sync_agent_info_ko PASSED                                                                                                    [ 77%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_sync_extra_valid PASSED                                                                                                      [ 80%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_process_files_from_master_ok PASSED                                                                                          [ 82%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_process_files_from_master_ko PASSED                                                                                          [ 85%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_update_master_files_in_worker_ok PASSED                                                                                      [ 88%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_handler_get_logger PASSED                                                                                                            [ 91%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_init PASSED                                                                                                                          [ 94%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_add_tasks PASSED                                                                                                                     [ 97%]
framework/wazuh/core/cluster/tests/test_worker.py::test_worker_get_node PASSED                                                                                                                      [100%]
```

### CODE REVIEW

**Review by mhamra — CHANGES_REQUESTED** [review]
Missing endpoint in comment

https://github.com/wazuh/wazuh/blob/bba9fd91d8b8ca78bd1ef8346f6d8221a95b7eea/framework/wazuh/core/cluster/master.py#L985-L986

**Review by mhamra — CHANGES_REQUESTED** [review]
Missing endpoint in comment

https://github.com/wazuh/wazuh/blob/bba9fd91d8b8ca78bd1ef8346f6d8221a95b7eea/framework/wazuh/core/cluster/worker.py#L192-L193

**Review by mhamra — CHANGES_REQUESTED** [review]
Extra line separing tests

https://github.com/wazuh/wazuh/blob/bba9fd91d8b8ca78bd1ef8346f6d8221a95b7eea/framework/wazuh/core/cluster/tests/test_worker.py#L456-L467

**Review by mhamra — COMMENTED** [review]
The modified unit tests test_master_handler_connection_lost validate only that the clean_up function is called when the connection_lost function is called.

Shouldn't they validate also that the super().connection_lost function is called and that the task.cancel function is called for the pending_task elements?

**Review by mhamra — COMMENTED** [review]
The modified unit tests test_worker_handler_connection_lost validate that the clean_up function is called when the connection_lost function is called.

It shouldn't also validate that the super().connection_lost function is called?

**Review by mhamra — APPROVED** [review]
LGTM!

Thanks @javiersanchz !

**Review by Selutario — CHANGES_REQUESTED** [review]
Only a minor change. Also, rebase to `4.8.0` (`master`).

**Review by Selutario — APPROVED** [review]

**Pull request merged**
