### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**

### CODE REVIEW

**Comment by vikman90** [comment]
@jsoref,

thank you very much for this contribution!

Best regards.

**Comment by vikman90** [comment]
I've moved the corrections related to the Wazuh Framework to https://github.com/wazuh/wazuh-api/commit/62067869260db589cbf99ba543e4ddacbc527401, and those related to the ruleset to https://github.com/wazuh/wazuh-ruleset/commit/cccc8d0f69b1745688d997e9ec2544951f060cfc.

For future contributions, we would be very grateful if the changes related to the Wazuh API or the ruleset were sent to their respective projects.

Thank you again!

**Comment by jsoref** [comment]
To the extent that it's easy for me to recognize distinct project boundaries, I'm able to exclude things. I was planning to get to those other repos eventually.

(I'm considering deploying this tool shortly, hence the investigation of the project's health.)

**Comment by jsoref** [comment]
(In case people are curious, I've actually deployed wazuh and we're using it...)

**Pull request merged**
