### PR TITLE
Engine - Change the logger output to the stdout

### PR DESCRIPTION
**Pull request by NahuFigueroa97**
|Related issue|
|---|
|#25334|

## Description

This PR aims to change the logging output to the stdout.

Basically wazuh in 5.0.0 we will log into the stdout because when the engine runs into systems all stdout logs are written into the journals.

For docker executions, we maintain this and expect the users to have a custom driver.

### CODE REVIEW

**Review by JavierBejMen — APPROVED** [review]
LGTM

**Review by juliancnn — DISMISSED** [review]
LGTM!

**Review by Dwordcito — DISMISSED** [review]
This issue aims to ensure that the ENGINE daemon always logs through stdout and errors through stderr, not to eliminate the functionality of the logging helper. Note that with this change the vulnerability detector efficacy tests are broken (https://github.com/wazuh/wazuh/actions/runs/10566663253).

**Comment by NahuFigueroa97** [comment]
> This issue aims to ensure that the ENGINE daemon always logs through stdout and errors through stderr, not to eliminate the functionality of the logging helper. Note that with this change the vulnerability detector efficacy tests are broken (https://github.com/wazuh/wazuh/actions/runs/10566663253).

A custom sink was created, since following this approach
```
auto stdout_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
stdout_sink->set_level(spdlog::level::info); // minimum level for this sink
auto stderr_sink = std::make_shared<spdlog::sinks::stderr_color_sink_mt>();
stderr_sink->set_level(spdlog::level::warn); // minimum level for this sink
```
repeated logs are created for warning onwards. Instead of two sinks, there is one that internally manages the log destination according to the message level

**Review by JavierBejMen — APPROVED** [review]
LGTM

**Review by JcabreraC — APPROVED** [review]
LGTM !

**Pull request merged**
