### PR TITLE
Delete rules endpoints

### PR DESCRIPTION
**Pull request by GGP1**
|Related issue|
|---|
| Closes https://github.com/wazuh/wazuh/issues/17069 |

## Description
The `/rules` endpoints will be replaced by the new Wazuh Engine features, this pull request deletes them from the source code.

### Tests

<details><summary>test_decoder_endpoints.tavern.yaml</summary>

```console
(venv) gasti@pop-os:~/work/wazuh/api/test/integration$ pytest -vv test_decoder_endpoints.tavern.yaml
============================================================ test session starts =============================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.2.0 -- /home/gasti/work/wazuh/venv/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.9.16', 'Platform': 'Linux-6.2.0-76060200-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.3.1', 'pluggy': '1.2.0'}, 'Plugins': {'asyncio': '0.18.1', 'tavern': '1.23.5', 'trio': '0.7.0', 'html': '2.1.1', 'aiohttp': '1.0.4', 'metadata': '3.0.0'}}
rootdir: /home/gasti/work/wazuh/api/test/integration
configfile: pytest.ini
plugins: asyncio-0.18.1, tavern-1.23.5, trio-0.7.0, html-2.1.1, aiohttp-1.0.4, metadata-3.0.0
asyncio: mode=auto
collected 25 items                                                                                                                      	 

test_decoder_endpoints.tavern.yaml::GET /decoders PASSED                                                                           	[  4%]
test_decoder_endpoints.tavern.yaml::GET /decoders[filename] PASSED                                                                 	[  8%]
test_decoder_endpoints.tavern.yaml::GET /decoders[relative_dirname] PASSED                                                         	[ 12%]
test_decoder_endpoints.tavern.yaml::GET /decoders[name] PASSED                                                                     	[ 16%]
test_decoder_endpoints.tavern.yaml::GET /decoders[position] PASSED                                                                 	[ 20%]
test_decoder_endpoints.tavern.yaml::GET /decoders[status] PASSED                                                                   	[ 24%]
test_decoder_endpoints.tavern.yaml::GET /decoders/{decoder_name} PASSED                                                            	[ 28%]
test_decoder_endpoints.tavern.yaml::GET /decoders/{decoder_name}[filename] PASSED                                                  	[ 32%]
test_decoder_endpoints.tavern.yaml::GET /decoders/{decoder_name}[relative_dirname] PASSED                                          	[ 36%]
test_decoder_endpoints.tavern.yaml::GET /decoders/{decoder_name}[name] PASSED                                                      	[ 40%]
test_decoder_endpoints.tavern.yaml::GET /decoders/{decoder_name}[position] PASSED                                                  	[ 44%]
test_decoder_endpoints.tavern.yaml::GET /decoders/{decoder_name}[status] PASSED                                                    	[ 48%]
test_decoder_endpoints.tavern.yaml::GET /decoders/files PASSED                                                                     	[ 52%]
test_decoder_endpoints.tavern.yaml::GET /decoders/files[filename] PASSED                                                           	[ 56%]
test_decoder_endpoints.tavern.yaml::GET /decoders/files[relative_dirname] PASSED                                                   	[ 60%]
test_decoder_endpoints.tavern.yaml::GET /decoders/files[status] PASSED                                                             	[ 64%]
test_decoder_endpoints.tavern.yaml::GET /decoders/parents PASSED                                                                   	[ 68%]
test_decoder_endpoints.tavern.yaml::GET /decoders/parents[filename] PASSED                                                         	[ 72%]
test_decoder_endpoints.tavern.yaml::GET /decoders/parents[name] PASSED                                                             	[ 76%]
test_decoder_endpoints.tavern.yaml::GET /decoders/parents[relative_dirname] PASSED                                                 	[ 80%]
test_decoder_endpoints.tavern.yaml::GET /decoders/parents[position] PASSED                                                         	[ 84%]
test_decoder_endpoints.tavern.yaml::GET /decoders/parents[status] PASSED                                                           	[ 88%]
test_decoder_endpoints.tavern.yaml::GET /decoders/files/{file} PASSED                                                              	[ 92%]
test_decoder_endpoints.tavern.yaml::PUT /rule/decoders/{filename} PASSED                                                           	[ 96%]
test_decoder_endpoints.tavern.yaml::DELETE /decoders/files/{filename} PASSED                                                       	[100%]

================================================= 25 passed, 2 warnings in 416.45s (0:06:56) =================================================
```

> I added this test result because some modification were done to code that was used for both `/rules` and `/decoders` endpoints.

</details>

> Some checks are failing because of the epic branch [11334-dev-new-wazuh-engine](https://github.com/wazuh/wazuh/tree/11334-dev-new-wazuh-engine)

### CODE REVIEW

**Review by mhamra — CHANGES_REQUESTED** [review]
Check if these lines need to be removed.

https://github.com/wazuh/wazuh/blob/21997f2f11933e16c9edad7f51bfeb8de27a054b/api/api/spec/spec.yaml#L80-L81

**Review by mhamra — CHANGES_REQUESTED** [review]
Check if these lines need to be removed.

https://github.com/wazuh/wazuh/blob/21997f2f11933e16c9edad7f51bfeb8de27a054b/api/api/spec/spec.yaml#L374-L397

**Review by mhamra — CHANGES_REQUESTED** [review]
Fix the reference to rule in this DocString.

https://github.com/wazuh/wazuh/blob/21997f2f11933e16c9edad7f51bfeb8de27a054b/api/api/controllers/manager_controller.py#L100-L101

**Review by mhamra — CHANGES_REQUESTED** [review]
Fix description reference to rule in ruleset.

https://github.com/wazuh/wazuh/blob/21997f2f11933e16c9edad7f51bfeb8de27a054b/api/api/spec/spec.yaml#L3827-L3830

**Review by mhamra — COMMENTED** [review]
Do you know if WazuhStats object in spec.yaml will remain the same?

The line 3730 has a reference to Rule Id that probably needs to be changed unless Wazuh Core will maintain the concept of Rules.

https://github.com/wazuh/wazuh/blob/21997f2f11933e16c9edad7f51bfeb8de27a054b/api/api/spec/spec.yaml#L3727-L3730

**Review by mhamra — CHANGES_REQUESTED** [review]
This line needs to be removed.

https://github.com/wazuh/wazuh/blob/21997f2f11933e16c9edad7f51bfeb8de27a054b/api/api/spec/spec.yaml#L5299

**Review by mhamra — CHANGES_REQUESTED** [review]
These lines need to be removed.

https://github.com/wazuh/wazuh/blob/21997f2f11933e16c9edad7f51bfeb8de27a054b/api/api/spec/spec.yaml#L5901-L5910

**Review by mhamra — CHANGES_REQUESTED** [review]
Remove rule references in xml_filename and xml_filename_path descriptions. 

https://github.com/wazuh/wazuh/blob/21997f2f11933e16c9edad7f51bfeb8de27a054b/api/api/spec/spec.yaml#L6882-L6895

**Review by mhamra — COMMENTED** [review]
Review if "rules" should be removed from this line:

https://github.com/wazuh/wazuh/blob/21997f2f11933e16c9edad7f51bfeb8de27a054b/api/api/validator.py#L202

**Comment by mhamra** [comment]
Could you look at what will happen with wazuh_logtest.py because it is a tool used to test decoders and rules? Do you think it should be removed?

**Comment by GGP1** [comment]
@mhamra 

`wazuh_logtest.py` has the description `Tool for developing, tuning, and debugging rules`. I guess it will be removed and replaced with a different tool if necessary.

Regarding the question of `WazuhStats`, it's not possible to tell what is Core going to do with it, I think they may replace the rule ID with another one, so I will leave the field but remove the rule reference.

**Review by mhamra — CHANGES_REQUESTED** [review]
Fix this DocString.

https://github.com/wazuh/wazuh/blob/ffd3215417b5568492ea287f4a71b14c3c8c48a2/framework/wazuh/manager.py#L279

**Review by mhamra — CHANGES_REQUESTED** [review]
Remove these global variables.

https://github.com/wazuh/wazuh/blob/ffd3215417b5568492ea287f4a71b14c3c8c48a2/framework/wazuh/core/common.py#L168

https://github.com/wazuh/wazuh/blob/ffd3215417b5568492ea287f4a71b14c3c8c48a2/framework/wazuh/core/common.py#L252

https://github.com/wazuh/wazuh/blob/ffd3215417b5568492ea287f4a71b14c3c8c48a2/framework/wazuh/core/common.py#L256

**Review by mhamra — CHANGES_REQUESTED** [review]
Fix this DocString.

https://github.com/wazuh/wazuh/blob/ffd3215417b5568492ea287f4a71b14c3c8c48a2/framework/wazuh/core/configuration.py#L593

**Review by mhamra — CHANGES_REQUESTED** [review]
Remove this function.

https://github.com/wazuh/wazuh/blob/ffd3215417b5568492ea287f4a71b14c3c8c48a2/framework/wazuh/core/utils.py#L1788-L1804

**Review by mhamra — CHANGES_REQUESTED** [review]
Fix this DocString.

https://github.com/wazuh/wazuh/blob/ffd3215417b5568492ea287f4a71b14c3c8c48a2/framework/wazuh/core/utils.py#L1920

**Review by mhamra — CHANGES_REQUESTED** [review]
Remove common.USER_RULES_PATH global variable.

https://github.com/wazuh/wazuh/blob/ffd3215417b5568492ea287f4a71b14c3c8c48a2/framework/wazuh/core/cluster/cluster.py#L248-L250

**Review by mhamra — CHANGES_REQUESTED** [review]
Remove these lines.

https://github.com/wazuh/wazuh/blob/ffd3215417b5568492ea287f4a71b14c3c8c48a2/framework/wazuh/core/tests/test_manager.py#L27-L29

**Review by mhamra — CHANGES_REQUESTED** [review]
Remove expand_rules import.

https://github.com/wazuh/wazuh/blob/ffd3215417b5568492ea287f4a71b14c3c8c48a2/framework/wazuh/rbac/decorators.py#L14

**Review by mhamra — CHANGES_REQUESTED** [review]
Remove rules references in `framework/wazuh/rbac/default/relationships.yaml file`.

https://github.com/wazuh/wazuh/blob/ffd3215417b5568492ea287f4a71b14c3c8c48a2/framework/wazuh/rbac/default/relationships.yaml#L24

https://github.com/wazuh/wazuh/blob/ffd3215417b5568492ea287f4a71b14c3c8c48a2/framework/wazuh/rbac/default/relationships.yaml#L45

**Review by mhamra — CHANGES_REQUESTED** [review]
Remove rules references from `framework/wazuh/tests/test_manager.py` file

https://github.com/wazuh/wazuh/blob/ffd3215417b5568492ea287f4a71b14c3c8c48a2/framework/wazuh/tests/test_manager.py#L42-L44

**Review by mhamra — APPROVED** [review]
I reviewed all rules reference throughout the code and verified that all the requested changes were applied.

LGTM!

Thanks @GGP1 !

**Pull request closed without merging**
