### PR TITLE
Configuration endpoint adjustments with new vulnerability detection section

### PR DESCRIPTION
**Pull request by nico-stefani**
|Related issue|
|---|
| #18284 |

## Description

This PR adds compatibility with the new vulnerability detection module configurations:

* `vulnerability-detection`
* `indexer` 

## Logs/Alerts example

<details><summary>PUT /manager/configuration request</summary>
<p>

```bash
curl --location --request PUT -k 'https://0.0.0.0:55050/manager/configuration?pretty=false&wait_for_complete=false' \
--header 'Content-Type: application/octet-stream' \
--header 'Accept: application/json' \
--header "Authorization: Bearer $TOKEN" \
--data-raw '<ossec_config>
    <global>
        <jsonout_output>yes</jsonout_output>
        <alerts_log>yes</alerts_log>
        <logall>no</logall>
        <logall_json>no</logall_json>
        <email_notification>no</email_notification>
        <smtp_server>smtp.example.wazuh.com</smtp_server>
        <email_from>wazuh@example.wazuh.com</email_from>
        <email_to>recipient@example.wazuh.com</email_to>
        <email_maxperhour>12</email_maxperhour>
        <email_log_source>alerts.log</email_log_source>
        <agents_disconnection_time>10m</agents_disconnection_time>
        <agents_disconnection_alert_time>0</agents_disconnection_alert_time>
    </global>
    <alerts>
        <log_alert_level>3</log_alert_level>
        <email_alert_level>12</email_alert_level>
    </alerts>
    <logging>
        <log_format>plain</log_format>
    </logging>
    <remote>
        <connection>secure</connection>
        <port>1514</port>
        <protocol>tcp</protocol>
        <queue_size>131072</queue_size>
    </remote>
    <rootcheck>
        <disabled>no</disabled>
        <check_files>yes</check_files>
        <check_trojans>yes</check_trojans>
        <check_dev>yes</check_dev>
        <check_sys>yes</check_sys>
        <check_pids>yes</check_pids>
        <check_ports>yes</check_ports>
        <check_if>yes</check_if>
        <frequency>43200</frequency>
        <rootkit_files>etc/rootcheck/rootkit_files.txt</rootkit_files>
        <rootkit_trojans>etc/rootcheck/rootkit_trojans.txt</rootkit_trojans>
        <skip_nfs>yes</skip_nfs>
    </rootcheck>
    <wodle name="cis-cat">
        <disabled>yes</disabled>
        <timeout>1800</timeout>
        <interval>1d</interval>
        <scan-on-start>yes</scan-on-start>
        <java_path>wodles/java</java_path>
        <ciscat_path>wodles/ciscat</ciscat_path>
    </wodle>
    <wodle name="osquery">
        <disabled>yes</disabled>
        <run_daemon>yes</run_daemon>
        <log_path>/var/log/osquery/osqueryd.results.log</log_path>
        <config_path>/etc/osquery/osquery.conf</config_path>
        <add_labels>yes</add_labels>
    </wodle>
    <wodle name="syscollector">
        <disabled>no</disabled>
        <interval>1h</interval>
        <scan_on_start>yes</scan_on_start>
        <hardware>yes</hardware>
        <os>yes</os>
        <network>yes</network>
        <packages>yes</packages>
        <ports all="no">yes</ports>
        <processes>yes</processes>
        <synchronization>
            <max_eps>10</max_eps>
        </synchronization>
    </wodle>
    <sca>
        <enabled>yes</enabled>
        <scan_on_start>yes</scan_on_start>
        <interval>12h</interval>
        <skip_nfs>yes</skip_nfs>
    </sca>
    <vulnerability-detection>
        <enabled>yes</enabled>
        <index-status>yes</index-status>
        <feed-update-interval>60m</feed-update-interval>
    </vulnerability-detection>
    <indexer>
        <enabled>yes</enabled>
        <hosts>
            <host>http://127.0.0.1:9200</host>
        </hosts>
        <username>admin</username>
        <password>admin</password>
    </indexer>
    <syscheck>
        <disabled>no</disabled>
        <frequency>43200</frequency>
        <scan_on_start>yes</scan_on_start>
        <alert_new_files>yes</alert_new_files>
        <auto_ignore frequency="10" timeframe="3600">no</auto_ignore>
        <directories>/etc,/usr/bin,/usr/sbin</directories>
        <directories>/bin,/sbin,/boot</directories>
        <ignore>/etc/mtab</ignore>
        <ignore>/etc/hosts.deny</ignore>
        <ignore>/etc/mail/statistics</ignore>
        <ignore>/etc/random-seed</ignore>
        <ignore>/etc/random.seed</ignore>
        <ignore>/etc/adjtime</ignore>
        <ignore>/etc/httpd/logs</ignore>
        <ignore>/etc/utmpx</ignore>
        <ignore>/etc/wtmpx</ignore>
        <ignore>/etc/cups/certs</ignore>
        <ignore>/etc/dumpdates</ignore>
        <ignore>/etc/svc/volatile</ignore>
        <ignore type="sregex">.log$|.swp$</ignore>
        <nodiff>/etc/ssl/private.key</nodiff>
        <skip_nfs>yes</skip_nfs>
        <skip_dev>yes</skip_dev>
        <skip_proc>yes</skip_proc>
        <skip_sys>yes</skip_sys>
        <process_priority>10</process_priority>
        <max_eps>50</max_eps>
        <synchronization>
            <enabled>yes</enabled>
            <interval>5m</interval>
            <max_eps>10</max_eps>
        </synchronization>
    </syscheck>
    <global>
        <white_list>127.0.0.1</white_list>
        <white_list>^localhost.localdomain$</white_list>
        <white_list>181.30.140.134</white_list>
        <white_list>181.30.140.199</white_list>
    </global>
    <command>
        <name>disable-account</name>
        <executable>disable-account</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <command>
        <name>restart-wazuh</name>
        <executable>restart-wazuh</executable>
    </command>
    <command>
        <name>firewall-drop</name>
        <executable>firewall-drop</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <command>
        <name>host-deny</name>
        <executable>host-deny</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <command>
        <name>route-null</name>
        <executable>route-null</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <command>
        <name>win_route-null</name>
        <executable>route-null.exe</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <command>
        <name>netsh</name>
        <executable>netsh.exe</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <localfile>
        <log_format>syslog</log_format>
        <location>/var/ossec/logs/active-responses.log</location>
    </localfile>
    <localfile>
        <log_format>syslog</log_format>
        <location>/var/log/dpkg.log</location>
    </localfile>
    <localfile>
        <log_format>command</log_format>
        <command>df -P</command>
        <frequency>360</frequency>
    </localfile>
    <localfile>
        <log_format>full_command</log_format>
        <command>netstat -tulpn | sed '\''s/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/'\'' | sort -k 4 -g | sed '\''s/ == \(.*\) ==/:\1/'\'' | sed 1,2d</command>
        <alias>netstat listening ports</alias>
        <frequency>360</frequency>
    </localfile>
    <localfile>
        <log_format>full_command</log_format>
        <command>last -n 20</command>
        <frequency>360</frequency>
    </localfile>
    <ruleset>
        <decoder_dir>ruleset/decoders</decoder_dir>
        <rule_dir>ruleset/rules</rule_dir>
        <rule_exclude>0215-policy_rules.xml</rule_exclude>
        <list>etc/lists/audit-keys</list>
        <list>etc/lists/amazon/aws-eventnames</list>
        <list>etc/lists/security-eventchannel</list>
        <decoder_dir>etc/decoders</decoder_dir>
        <rule_dir>etc/rules</rule_dir>
    </ruleset>
    <rule_test>
        <enabled>yes</enabled>
        <threads>1</threads>
        <max_sessions>64</max_sessions>
        <session_timeout>15m</session_timeout>
    </rule_test>
    <auth>
        <disabled>no</disabled>
        <port>1515</port>
        <use_source_ip>no</use_source_ip>
        <purge>yes</purge>
        <use_password>no</use_password>
        <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
        <ssl_verify_host>no</ssl_verify_host>
        <ssl_manager_cert>etc/sslmanager.cert</ssl_manager_cert>
        <ssl_manager_key>etc/sslmanager.key</ssl_manager_key>
        <ssl_auto_negotiate>no</ssl_auto_negotiate>
    </auth>
    <cluster>
        <name>wazuh</name>
        <node_name>worker</node_name>
        <node_type>worker</node_type>
        <key>9d273b53510fef702b54a92e9cffc82e</key>
        <port>1516</port>
        <bind_addr>0.0.0.0</bind_addr>
        <nodes>
            <node>wazuh-master</node>
        </nodes>
        <hidden>no</hidden>
        <disabled>no</disabled>
    </cluster>
</ossec_config>' | jq

{
  "data": {
    "affected_items": [
      "master-node"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Configuration was successfully updated in specified node",
  "error": 0
}
```

</p>
</details> 

<details><summary>PUT /cluster/:node_id/configuration request</summary>
<p>

```bash
curl --location --request PUT -k 'https://0.0.0.0:55050/cluster/worker/configuration?pretty=false&wait_for_complete=false' \
--header 'Content-Type: application/octet-stream' \
--header 'Accept: application/json' \
--header "Authorization: Bearer $TOKEN" \
--data-raw '<ossec_config>
    <global>
        <jsonout_output>yes</jsonout_output>
        <alerts_log>yes</alerts_log>
        <logall>no</logall>
        <logall_json>no</logall_json>
        <email_notification>no</email_notification>
        <smtp_server>smtp.example.wazuh.com</smtp_server>
        <email_from>wazuh@example.wazuh.com</email_from>
        <email_to>recipient@example.wazuh.com</email_to>
        <email_maxperhour>12</email_maxperhour>
        <email_log_source>alerts.log</email_log_source>
        <agents_disconnection_time>10m</agents_disconnection_time>
        <agents_disconnection_alert_time>0</agents_disconnection_alert_time>
    </global>
    <alerts>
        <log_alert_level>3</log_alert_level>
        <email_alert_level>12</email_alert_level>
    </alerts>
    <logging>
        <log_format>plain</log_format>
    </logging>
    <remote>
        <connection>secure</connection>
        <port>1514</port>
        <protocol>tcp</protocol>
        <queue_size>131072</queue_size>
    </remote>
    <rootcheck>
        <disabled>no</disabled>
        <check_files>yes</check_files>
        <check_trojans>yes</check_trojans>
        <check_dev>yes</check_dev>
        <check_sys>yes</check_sys>
        <check_pids>yes</check_pids>
        <check_ports>yes</check_ports>
        <check_if>yes</check_if>
        <frequency>43200</frequency>
        <rootkit_files>etc/rootcheck/rootkit_files.txt</rootkit_files>
        <rootkit_trojans>etc/rootcheck/rootkit_trojans.txt</rootkit_trojans>
        <skip_nfs>yes</skip_nfs>
    </rootcheck>
    <wodle name="cis-cat">
        <disabled>yes</disabled>
        <timeout>1800</timeout>
        <interval>1d</interval>
        <scan-on-start>yes</scan-on-start>
        <java_path>wodles/java</java_path>
        <ciscat_path>wodles/ciscat</ciscat_path>
    </wodle>
    <wodle name="osquery">
        <disabled>yes</disabled>
        <run_daemon>yes</run_daemon>
        <log_path>/var/log/osquery/osqueryd.results.log</log_path>
        <config_path>/etc/osquery/osquery.conf</config_path>
        <add_labels>yes</add_labels>
    </wodle>
    <wodle name="syscollector">
        <disabled>no</disabled>
        <interval>1h</interval>
        <scan_on_start>yes</scan_on_start>
        <hardware>yes</hardware>
        <os>yes</os>
        <network>yes</network>
        <packages>yes</packages>
        <ports all="no">yes</ports>
        <processes>yes</processes>
        <synchronization>
            <max_eps>10</max_eps>
        </synchronization>
    </wodle>
    <sca>
        <enabled>yes</enabled>
        <scan_on_start>yes</scan_on_start>
        <interval>12h</interval>
        <skip_nfs>yes</skip_nfs>
    </sca>
    <vulnerability-detection>
        <enabled>yes</enabled>
        <index-status>yes</index-status>
        <feed-update-interval>60m</feed-update-interval>
    </vulnerability-detection>
    <indexer>
        <enabled>yes</enabled>
        <hosts>
            <host>http://127.0.0.1:9200</host>
        </hosts>
        <username>admin</username>
        <password>admin</password>
    </indexer>
    <syscheck>
        <disabled>no</disabled>
        <frequency>43200</frequency>
        <scan_on_start>yes</scan_on_start>
        <alert_new_files>yes</alert_new_files>
        <auto_ignore frequency="10" timeframe="3600">no</auto_ignore>
        <directories>/etc,/usr/bin,/usr/sbin</directories>
        <directories>/bin,/sbin,/boot</directories>
        <ignore>/etc/mtab</ignore>
        <ignore>/etc/hosts.deny</ignore>
        <ignore>/etc/mail/statistics</ignore>
        <ignore>/etc/random-seed</ignore>
        <ignore>/etc/random.seed</ignore>
        <ignore>/etc/adjtime</ignore>
        <ignore>/etc/httpd/logs</ignore>
        <ignore>/etc/utmpx</ignore>
        <ignore>/etc/wtmpx</ignore>
        <ignore>/etc/cups/certs</ignore>
        <ignore>/etc/dumpdates</ignore>
        <ignore>/etc/svc/volatile</ignore>
        <ignore type="sregex">.log$|.swp$</ignore>
        <nodiff>/etc/ssl/private.key</nodiff>
        <skip_nfs>yes</skip_nfs>
        <skip_dev>yes</skip_dev>
        <skip_proc>yes</skip_proc>
        <skip_sys>yes</skip_sys>
        <process_priority>10</process_priority>
        <max_eps>50</max_eps>
        <synchronization>
            <enabled>yes</enabled>
            <interval>5m</interval>
            <max_eps>10</max_eps>
        </synchronization>
    </syscheck>
    <global>
        <white_list>127.0.0.1</white_list>
        <white_list>^localhost.localdomain$</white_list>
        <white_list>181.30.140.134</white_list>
        <white_list>181.30.140.199</white_list>
    </global>
    <command>
        <name>disable-account</name>
        <executable>disable-account</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <command>
        <name>restart-wazuh</name>
        <executable>restart-wazuh</executable>
    </command>
    <command>
        <name>firewall-drop</name>
        <executable>firewall-drop</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <command>
        <name>host-deny</name>
        <executable>host-deny</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <command>
        <name>route-null</name>
        <executable>route-null</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <command>
        <name>win_route-null</name>
        <executable>route-null.exe</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <command>
        <name>netsh</name>
        <executable>netsh.exe</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <localfile>
        <log_format>syslog</log_format>
        <location>/var/ossec/logs/active-responses.log</location>
    </localfile>
    <localfile>
        <log_format>syslog</log_format>
        <location>/var/log/dpkg.log</location>
    </localfile>
    <localfile>
        <log_format>command</log_format>
        <command>df -P</command>
        <frequency>360</frequency>
    </localfile>
    <localfile>
        <log_format>full_command</log_format>
        <command>netstat -tulpn | sed '\''s/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/'\'' | sort -k 4 -g | sed '\''s/ == \(.*\) ==/:\1/'\'' | sed 1,2d</command>
        <alias>netstat listening ports</alias>
        <frequency>360</frequency>
    </localfile>
    <localfile>
        <log_format>full_command</log_format>
        <command>last -n 20</command>
        <frequency>360</frequency>
    </localfile>
    <ruleset>
        <decoder_dir>ruleset/decoders</decoder_dir>
        <rule_dir>ruleset/rules</rule_dir>
        <rule_exclude>0215-policy_rules.xml</rule_exclude>
        <list>etc/lists/audit-keys</list>
        <list>etc/lists/amazon/aws-eventnames</list>
        <list>etc/lists/security-eventchannel</list>
        <decoder_dir>etc/decoders</decoder_dir>
        <rule_dir>etc/rules</rule_dir>
    </ruleset>
    <rule_test>
        <enabled>yes</enabled>
        <threads>1</threads>
        <max_sessions>64</max_sessions>
        <session_timeout>15m</session_timeout>
    </rule_test>
    <auth>
        <disabled>no</disabled>
        <port>1515</port>
        <use_source_ip>no</use_source_ip>
        <purge>yes</purge>
        <use_password>no</use_password>
        <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
        <ssl_verify_host>no</ssl_verify_host>
        <ssl_manager_cert>etc/sslmanager.cert</ssl_manager_cert>
        <ssl_manager_key>etc/sslmanager.key</ssl_manager_key>
        <ssl_auto_negotiate>no</ssl_auto_negotiate>
    </auth>
    <cluster>
        <name>wazuh</name>
        <node_name>worker</node_name>
        <node_type>worker</node_type>
        <key>9d273b53510fef702b54a92e9cffc82e</key>
        <port>1516</port>
        <bind_addr>0.0.0.0</bind_addr>
        <nodes>
            <node>wazuh-master</node>
        </nodes>
        <hidden>no</hidden>
        <disabled>no</disabled>
    </cluster>
</ossec_config>' | jq
{
  "data": {
    "affected_items": [
      "worker"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Configuration was successfully updated in specified node",
  "error": 0
}
```

</p>
</details>

### CODE REVIEW

**Comment by nico-stefani** [comment]
The AIT fails are related to #20002 and #20143

**Review by fdalmaup — CHANGES_REQUESTED** [review]
- The `framework/wazuh/core/tests/test_configuration.py` test passes but uses an outdated `framework/wazuh/core/tests/data/configuration/default/vulnerability_detector.conf` file that should have the new VD configuration.
- In the `configuration.py` file there is still logic related to the old configuration (line 258).
- Lastly, we should check if the command found in `framework/wazuh/vulnerability.py` is still valid or if it suffered any changes due to the refactor which would require modification on our code and tests.

**Comment by nico-stefani** [comment]
> * Lastly, we should check if the command found in `framework/wazuh/vulnerability.py` is still valid or if it suffered any changes due to the refactor which would require modification on our code and tests.

These functions will be removed in #20116.

**Review by Selutario — APPROVED** [review]
LGTM. API and Framework unit tests are failing in Jenkins because the Python 3.10 changes are still not included in this branch, but they were also run in Github actions and passed successfully.

**Pull request merged**
