### PR TITLE
Removed static libstd link in FIMDB branch

### PR DESCRIPTION
**Pull request by jotacarma90**
|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/14403|

## Description
Hello team,
this PR is to adapt some changes made in the PR: [#14190](https://github.com/wazuh/wazuh/pull/14190), to stop linking the libstd library in the development branch of FIMDB.
I have also removed the linking of the library in the syscheck cmakelist.

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
- [x] Source installation

### CODE REVIEW

**Review by antoniomanuelfr — CHANGES_REQUESTED** [review]
Rsync is not compiled by the time syscheckd is compiling. Add the dependency between the shared modules and syscheckd target in the main makefile

**Comment by chemamartinez** [comment]
To approve this pull request we have to update it with the latest changes of https://github.com/wazuh/wazuh/pull/14190. In addition, separate the additions into two commits. The imported one from the other PR and one commit with the required changes to adapt the changes to the FIM development.

**Review by chemamartinez — COMMENTED** [review]
To approve this pull request we have to update it with the latest changes of https://github.com/wazuh/wazuh/pull/14190. In addition, separate the additions into two commits. The imported one from the other PR and one commit with the required changes to adapt the changes to the FIM development.

**Review by antoniomanuelfr — APPROVED** [review]

**Review by chemamartinez — APPROVED** [review]

**Comment by jotacarma90** [comment]
We proceed to close this PR because these changes have been included and adapted after merge the master branch (with the necessary changes that affected us) into our main development branch 9103-replace-fim-db-dbsync.

**Pull request closed without merging**
