### PR TITLE
Add clusterd async messaging service

### LINKED ISSUE #4918: Develop clusterd messaging service
## Description

This issue aims to develop and integrate a messaging service in `wazuh-clusterd` to allow communication between any wazuh daemon in a cluster node with any other wazuh daemon in a different cluster node.

Based on recent needs such as [agent-key polling from a worker](https://github.com/wazuh/wazuh/issues/4392) and [auth registration from a worker](https://github.com/wazuh/wazuh/issues/4905) we deem necessary to develop a generic clusterd messaging service that provides the tools to accomplish such needs and any other similar developments that may arise in the future.

By doing so, we try to ensure we keep `wazuh-clusterd` as agnostic to the communication between the daemons as possible as well as to provide an scalable tool able to communicate any two wazuh daemons with independence to the specifics of the messages.

## Design

Each cluster node is running a `LocalServer` inside the `wazuh-clusterd` process. This server is intended to answer internal cluster requests. It listens to a unix socket placed in `/var/ossec/queue/cluster/c-internal.sock`. The binary structure of messages sent to this socket is the following one:
  - A header with three fields:
    - Counter: big endian unsigned int (4 bytes)
    - Size of the payload: big endian unsigned int (4 bytes)
    - Command: 12 bytes. It is made up of a command name, a blank space and as much '-' character as needed to complete the 12 bytes in total. Example: 'control_res ', 'short ------'
  - Payload

Any intend to communicate with the cluster internal socket requires a new TCP connection that must be dealt with and closed when the communication is finished.

According to this communication protocol, we shall enable a new message type with command `send_sync` to send a message/petition to another daemon in another node. The payload must include the following:
- `node_id`: Destination node for the message. Optional, default value is master if request is sent from a worker or all the workers if request is sent from master.
- `function`: Function to execute in the framework destination, for messaging it is send_sync.
- `daemon_name`: Name of the daemon to send the message to in the destination node.
- `message`: Message to send to the destination daemon.

An example of this message could be: `\x00\x00\x00\x03\x00\x00\x00\x15send_sync --node_id  {"function": "send_sync", "arguments": {"daemon_name": "authd", "message": {"function": "add", "arguments": {"ip": "any", "name": "FromTheWorker1"}}}}`. 

In order to accomplish communication between wazuh daemons using any kind of protocol, we shall define a structure with the necessary information to complete a communication with those daemons using `wazuh-clusterd`, such as:
```python
daemons = {"authd":{"protocol":"TCP", "path":"/var/ossec/queue/ossec/auth", "header_format":"<I", "size":True},
"key_polling":{"protocol":"UDP","path":"/var/ossec/queue/ossec/krequest","header_format":None, "size":False}}
```

Also, we have to use a system similar to that already used by [`dapi`](https://github.com/wazuh/wazuh-documentation/blob/master/source/development/wazuh-cluster.rst#distributed-api-requests) to ensure the correct transmission of large data messages that may require chunking the response.

Lastly, it is imperative to maintain cluster efficiency when using the new service. The cluster is in charge of many other tasks and we cannot allow this communication between nodes to affect its behaviour significantly. For that reason, we shall develop a new asynchronous class to communicate with wazuh sockets, using already existing class [`OssecSocket`](https://github.com/wazuh/wazuh/blob/3.12/framework/wazuh/ossec_socket.py#L13-L49) and developing a new class `WazuhAsyncSocket` with `asyncio` transports and protocols to be used with the new command `send_sync`.

## Testing

This implementation should be tested at unit and integration level to ensure error and response handling.
For the integration tests we can use the tools for [cluster tests](https://github.com/wazuh/wazuh-qa/blob/master/deps/wazuh_testing/wazuh_testing/cluster.py) already developed.

## Tasks
- [x] Implement `WazuhAsyncSocket` and unit tests for it
- [ ] Accept message from any daemon in any node with command `send_sync`
- [ ] Send request from the origin node to `node_id`
- [ ] Communicate in `node_id` with `daemon_name` using defined protocol for that specific daemon.
- [ ] Write new cluster documentation for developers including `send_sync` and a complete flow chart.
- [ ] Write unit tests
- [ ] Write integration tests 
- [ ] Test in a real environment with at least one master and two workers.
- [ ] Write a small script to stress the cluster socket and run the send_sync intensively. Check that cluster and distributed API does not collapse.

### PR DESCRIPTION
**Pull request by CarlosRS9**
# Description

This PR closes #4918 . It adds a messaging service in `wazuh-clusterd` to allow communication between wazuh daemons by adding a new message type with command `send_sync` to send a message/petition to another daemon in another node. The payload must include the following:

* `node_id`: Destination node for the message. Optional, default value is master if request is sent from a worker or all the workers if request is sent from master.

* `function`: Function to execute in the framework destination, for messaging it is send_sync.

* `daemon_name`: Name of the daemon to send the message to in the destination node.

* `message`: Message to send to the destination daemon.

An example of this message could be: 
```
\x00\x00\x00\x03\x00\x00\x00\x15send_sync --node_id {"function": "send_sync", "arguments": {"daemon_name": "authd", "message": {"function": "add", "arguments": {"ip": "any", "name": "FromTheWorker1"}}}}.
```

A new asynchronous implementation of socket has been added with `Wazuh_socket.py` which replaces the old `ossec_socket.py` module. Works in the  same way but asynchronously.

# Test results

A new unit test module name `test_wazuh_socket.py` has been added. Unit test for `ossec_socket` have been moved to that module too. Here are the results of the old and new tests:

```
================================= test session starts ================================
platform linux -- Python 3.7.4, pytest-4.5.0, py-1.8.0, pluggy-0.13.0
rootdir: /home/carlos/GIT/wazuh/framework
plugins: pudb-0.7.0, cov-2.8.1
collected 30 items

wazuh/tests/test_wazuh_socket.py ..............................  [100%]

----------- coverage: platform linux, python 3.7.4-final-0 -----------
Name                                                    Stmts   Miss  Cover   Missing
-------------------------------------------------------------------------------------

wazuh/tests/test_wazuh_socket.py                          186      0   100%
wazuh/wazuh_socket.py                                     120      0   100%
```

### CODE REVIEW

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 9b9a10b1ad52d2ec4e72804c23ba0945b7ef6b6e
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2168/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2168/ossec.log)
**Coverage:** 

```json
Lines executed:3.93% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2168/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2168.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2168/Analysis_dynamic_valgrind-v3.13.0-B2168.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 76aeb8435215de7c4005848ac86c84f753a751c5
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2178/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2178/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2178/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2178.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2178/Analysis_dynamic_valgrind-v3.13.0-B2178.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 76aeb8435215de7c4005848ac86c84f753a751c5
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2179/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2179/ossec.log)
**Coverage:** 

```json
Lines executed:26.90% of 3190

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2179/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2179.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2179/Analysis_dynamic_valgrind-v3.13.0-B2179.log)

**Comment by CarlosRS9** [comment]
# Status update

Send_sync function now use the old `ossec_socket` instead of `wazuh_socket` because making this call asynchronous could cause timeout problems

Several manual tests have been performed using a cluster to ensure enrollment is working as expected with those changes.

**Pull request merged**
