### PR TITLE
Add base configuration module

### LINKED ISSUE #25812: Engine - Remove CLI11 and implement alternative configuration method
### Description:
As part of the ongoing development of Wazuh-Engine, we are phasing out the use of CLI11 for handling configuration inputs. This change requires a new approach to configuring the engine at startup. In the interim, before a permanent configuration API is established, we will implement a method that utilizes environment variables to manage configurations.

### Tasks:
- **Develop an Environment Variable Handler**: Create a component that reads environment variables at startup and uses them to set configuration parameters such as thread counts and socket addresses.
- **Set Default Configurations**: Ensure that default values are in place for all parameters, allowing the engine to run with minimal setup.
- **Prepare for Future API Configuration**: Design the temporary solution with consideration for the upcoming shift to API-based configuration fetching, ensuring easy transition.

### Expected Outcome:
This implementation will provide a flexible, albeit temporary, way to configure the Wazuh-Engine using environment variables. It will ensure that as we transition away from CLI11, the engine remains functional and configurable until the new configuration API is ready for integration.

### Definition of Done:
- [x] Environment variable handler is implemented and tested.
- [x] Default configurations are defined and used when not overridden by environment variables.
- [x] The system is ready for a smooth transition to API-based configuration management once available.

### PR DESCRIPTION
**Pull request by juliancnn**
Closes #25812 

This PR remove CLI11 library and add a new method for configuration based on environment variables and API configuration.

### CODE REVIEW

**Review by JcabreraC — CHANGES_REQUESTED** [review]
Some tests fail:
- Engine Coverage check / Engine Coverage check (pull_request) 
- Engine Helper Functions Test / Engine Helper Functions Test
- Engine Integration Test / Engine Integration Test
- Engine Unit Test / Engine Unit Test
- Engine VD Scanner Efficacy / Engine VD Efficacy Test

**Comment by juliancnn** [comment]
It is expected that the tests will fail as the CLI has been removed and will be fixed in the next EPICA issues:
- Engine Helper Functions Test / Engine Helper Functions Test
- Engine Integration Test / Engine Integration Test
- Engine VD Scanner Efficacy / Engine VD Efficacy Test 
- Engine OPENAPI

**Review by JavierBejMen — APPROVED** [review]
LGTM

**Review by NahuFigueroa97 — APPROVED** [review]
LGTM!

**Review by JcabreraC — APPROVED** [review]
LGTM !

**Pull request merged**
