### PR TITLE
Engine refinement

### PR DESCRIPTION
**Pull request by juliancnn**
|Related issue|
|---|
| #14840 |

### Ignore parser:

- [x] Change default behavior, the parser ignore will be a new parser, and will not be the default parser in the '_' field.
- [x]  Create ignore custom parser and fix parser The pointer points one character back when the first match fails.
- [x]  Create test 
- [x]  Adapat Actual assets
    
Parser ignore, now changed. It will be a parser like any other and not a specific parser for the field '_'.
The parser can receive 0 or 1 argument. If it receives no arguments, it will ignore everything up to the endtoken, that is, up to the first character of the next parser.
When it receives an argument, it will ignore that string, consecutively, for example: <_/ignore/wazuh>123, it will match the following log: `wazuhwazuhwa123`.

### CSV parser:

- [x]  Create a CSV parser
- [x]  Create test a CSV parser
- [x]  Apply in postgrest decoders.

The CSV parser receives a variable number of arguments (minimum 1), each argument is the destination key of the extracted field. If the log has less fields than the specified number of arguments, the parser will fail. If it has the same amount or more, the parser will succeed, and will be positioned on the last extracted field, i.e. the next parser will succeed with the next log:

```
logql: <_custom/csv/field_1/field_2>,<_dummy>
log: h1,hi2,hi3,hi4 bye
```
Event result:

```json
{
    "_custom": {
        "field_1": "hi1",
        "field_2": "hi2"
    },
    "_dummy": "hi3,hi4 bye"
}
```

### Other fixes:

- [x] Fixed memory problems related to the protocol handler, which solved the problem of cut logs in the output.
- [X] Add ASAN to cmake
- [X] Fix memori issues related to ASAN (HLP + TEST)
- [X] Create script to run ASAN after compiling
- [X] Create script to run Valgrind (meme check) after compiling

### CODE REVIEW

**Review by LucioDonda — APPROVED** [review]
LGTM!

**Review by nmkoremblum — APPROVED** [review]
LGTM :)

**Review by JcabreraC — APPROVED** [review]
LGTM !

**Review by JavierBejMen — APPROVED** [review]
LGTM!!

**Pull request merged**
