### PR TITLE
Create SCA Policy for Amazon Linux 2023

### PR DESCRIPTION
**Pull request by jk-olaoluwa**
### Description

This pull request adds an SCA policy for Amazon Linux 2023 operating system, following the CIS benchmark for such OS.

While developing this SCA, Amazon launched Amazon Linux 2023. Amazon Linux 2022 won't exist anymore. 

This PR will close #15681 PR and #15462 issue

### CODE REVIEW

**Review by 72nomada — APPROVED** [review]
LGTM

**Review by DFolchA — CHANGES_REQUESTED** [review]
Please add this file to the list in `sca.manager.files`

**Comment by ooniagbi** [comment]
> Please add this file to the list in `sca.manager.files`

Done.

**Review by DFolchA — APPROVED** [review]

**Review by ooniagbi — APPROVED** [review]
LGTM!

**Review by ooniagbi — APPROVED** [review]
LGTM!

**Pull request merged**
