### PR TITLE
Updated mitre JSON to latest update

### LINKED ISSUE #8740: Update the MITRE JSON up to latest version
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.3.0-1| MITRE | Add new version's JSON |

## Description

The last April there was a MITRE update, which requires updating our JSON file with the newest one.
### Reason

The main reason is to get the latest MITRE version whose changes can be seen here: https://github.com/mitre/cti/blob/master/CHANGELOG.md
### Current results

The `ruleset/mitre/enterprise-attack.json` file is outdated
### Expected results

Update the `ruleset/mitre/enterprise-attack.json` file with the lastest version, that can be found here: https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json

### PR DESCRIPTION
**Pull request by jcruzlp**
|Related issue|
|---|
| #8740  |

## Description
Closes #8740 

The mitre JSON which is located here: `ruleset/mitre/enterprise-attack.json` has a new update on April: https://attack.mitre.org/resources/updates/updates-april-2021.

Updated the `ruleset/mitre/enterprise-attack.json` with the new [version's JSON](https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json) and run analysisd test in a local environment with a Wazuh manager in 4.3 version.
## Logs/Alerts example
After running the tests, the `/var/ossec/logs/ossec.log` file was clean from both, warnings and errors:
```
root@ubuntu20LTS:/home/vagrant/wazuh/ruleset/testing# cat /var/ossec/logs/ossec.log | grep warning
root@ubuntu20LTS:/home/vagrant/wazuh/ruleset/testing# cat /var/ossec/logs/ossec.log | grep error
root@ubuntu20LTS:/home/vagrant/wazuh/ruleset/testing# 
```

## Tests
after running the analysisd test this was the result:
```
tests/integration/test_analysisd/test_error_messages/test_error_messages.py::test_error_messages[Event message errors] PASSED                                                                       [ 99%]
tests/integration/test_analysisd/test_error_messages/test_error_messages.py::test_error_messages[dbsync errors] PASSED                                                                              [ 99%]
tests/integration/test_analysisd/test_event_messages/test_event_messages.py::test_event_messages[Add] PASSED                                                                                        [ 99%]
tests/integration/test_analysisd/test_event_messages/test_event_messages.py::test_event_messages[Modify] PASSED                                                                                     [ 99%]
tests/integration/test_analysisd/test_event_messages/test_event_messages.py::test_event_messages[Delete] PASSED                                                                                     [ 99%]
tests/integration/test_analysisd/test_event_messages/test_event_messages.py::test_event_messages[Modify - Large inodes] PASSED                                                                      [ 99%]
tests/integration/test_analysisd/test_integrity_messages/test_integrity_messages.py::test_integrity_messages[Integrity_check_global] PASSED                                                         [ 99%]
tests/integration/test_analysisd/test_integrity_messages/test_integrity_messages.py::test_integrity_messages[Integrity_check_left] PASSED                                                           [ 99%]
tests/integration/test_analysisd/test_integrity_messages/test_integrity_messages.py::test_integrity_messages[Integrity_check_right] PASSED                                                          [ 99%]
tests/integration/test_analysisd/test_integrity_messages/test_integrity_messages.py::test_integrity_messages[Integrity_clear] PASSED                                                                [ 99%]
tests/integration/test_analysisd/test_mitre/test_mitre_check_alert.py::test_mitre_check_alert[/home/vagrant/wazuh-qa/tests/integration/test_analysisd/test_mitre/data/test1.xml] PASSED             [ 99%]
tests/integration/test_analysisd/test_mitre/test_mitre_check_alert.py::test_mitre_check_alert[/home/vagrant/wazuh-qa/tests/integration/test_analysisd/test_mitre/data/test2.xml] PASSED             [ 99%]
tests/integration/test_analysisd/test_mitre/test_mitre_check_alert.py::test_mitre_check_alert[/home/vagrant/wazuh-qa/tests/integration/test_analysisd/test_mitre/data/test3.xml] PASSED             [ 99%]
tests/integration/test_analysisd/test_mitre/test_mitre_check_alert.py::test_mitre_check_alert[/home/vagrant/wazuh-qa/tests/integration/test_analysisd/test_mitre/data/test4.xml] PASSED             [ 99%]
tests/integration/test_analysisd/test_mitre/test_mitre_check_alert.py::test_mitre_check_alert[/home/vagrant/wazuh-qa/tests/integration/test_analysisd/test_mitre/data/test5.xml] PASSED             [ 99%]
tests/integration/test_analysisd/test_mitre/test_mitre_check_alert.py::test_mitre_check_alert[/home/vagrant/wazuh-qa/tests/integration/test_analysisd/test_mitre/data/test6.xml] PASSED             [ 99%]
tests/integration/test_analysisd/test_mitre/test_mitre_check_alert.py::test_mitre_check_alert[/home/vagrant/wazuh-qa/tests/integration/test_analysisd/test_mitre/data/test7.xml] PASSED             [ 99%]
tests/integration/test_analysisd/test_mitre/test_mitre_check_alert.py::test_mitre_check_alert[/home/vagrant/wazuh-qa/tests/integration/test_analysisd/test_mitre/data/test8.xml] PASSED             [ 99%]
tests/integration/test_analysisd/test_mitre/test_mitre_check_alert.py::test_mitre_check_alert[/home/vagrant/wazuh-qa/tests/integration/test_analysisd/test_mitre/data/test9.xml] PASSED             [ 99%]
tests/integration/test_analysisd/test_mitre/test_mitre_check_alert.py::test_mitre_check_alert[/home/vagrant/wazuh-qa/tests/integration/test_analysisd/test_mitre/data/test10.xml] PASSED            [ 99%]
tests/integration/test_analysisd/test_mitre/test_mitre_check_alert.py::test_mitre_check_alert[/home/vagrant/wazuh-qa/tests/integration/test_analysisd/test_mitre/data/test11.xml] PASSED            [ 99%]
tests/integration/test_analysisd/test_mitre/test_mitre_check_alert.py::test_mitre_check_alert[/home/vagrant/wazuh-qa/tests/integration/test_analysisd/test_mitre/data/test12.xml] PASSED            [ 99%]
tests/integration/test_analysisd/test_mitre/test_mitre_check_alert.py::test_mitre_check_alert[/home/vagrant/wazuh-qa/tests/integration/test_analysisd/test_mitre/data/test13.xml] PASSED            [ 99%]
tests/integration/test_analysisd/test_mitre/test_mitre_check_alert.py::test_mitre_check_alert[/home/vagrant/wazuh-qa/tests/integration/test_analysisd/test_mitre/data/test14.xml] PASSED            [ 99%]
tests/integration/test_analysisd/test_scan_messages/test_scan_messages.py::test_scan_messages[Scan start] PASSED                                                                                    [ 99%]
tests/integration/test_analysisd/test_scan_messages/test_scan_messages.py::test_scan_messages[Scan end] PASSED                                                                                      [100%]

=================================================================================== 57148 passed in 4580.06s (1:16:20) ====================================================================================

```
after running the `runtest.py` located in `ruleset/testing` this was the result:

```
- [ File = ./tests/doas.ini ] ---------
....

- [ File = ./tests/iptables.ini ] ---------
........

- [ File = ./tests/exim.ini ] ---------
.....

- [ File = ./tests/api.ini ] ---------
.........

- [ File = ./tests/web_appsec.ini ] ---------
...............................

- [ File = ./tests/cisco_asa.ini ] ---------
........................................................................................

- [ File = ./tests/firewalld.ini ] ---------
..

- [ File = ./tests/mailscanner.ini ] ---------
.

- [ File = ./tests/nextcloud.ini ] ---------
.......

- [ File = ./tests/ossec.ini ] ---------
.....

- [ File = ./tests/paloalto.ini ] ---------
....

- [ File = ./tests/named.ini ] ---------
.....

- [ File = ./tests/vsftpd.ini ] ---------
....

- [ File = ./tests/web_rules.ini ] ---------
.....

- [ File = ./tests/sysmon.ini ] ---------
...

- [ File = ./tests/macos-sshd.ini ] ---------
.....................

- [ File = ./tests/cisco_ios.ini ] ---------
...............

- [ File = ./tests/sudo.ini ] ---------
........

- [ File = ./tests/modsecurity.ini ] ---------
......

- [ File = ./tests/postfix.ini ] ---------
..

- [ File = ./tests/SonicWall.ini ] ---------
........

- [ File = ./tests/cimserver.ini ] ---------
..

- [ File = ./tests/nginx.ini ] ---------
............

- [ File = ./tests/junos.ini ] ---------
...

- [ File = ./tests/proftpd.ini ] ---------
.......

- [ File = ./tests/syslog.ini ] ---------
......

- [ File = ./tests/sophos_fw.ini ] ---------
..........

- [ File = ./tests/opensmtpd.ini ] ---------
.......

- [ File = ./tests/sophos.ini ] ---------
........

- [ File = ./tests/netscreen.ini ] ---------
....

- [ File = ./tests/apparmor.ini ] ---------
.....

- [ File = ./tests/squid_rules.ini ] ---------
..

- [ File = ./tests/checkpoint_smart1.ini ] ---------
..................

- [ File = ./tests/apache.ini ] ---------
............

- [ File = ./tests/dovecot.ini ] ---------
...............

- [ File = ./tests/systemd.ini ] ---------
..

- [ File = ./tests/pam.ini ] ---------
.....

- [ File = ./tests/github.ini ] ---------
....................................................................................................................................................................................................................................................................................................................................

- [ File = ./tests/oscap.ini ] ---------
................................

- [ File = ./tests/cpanel.ini ] ---------
.......

- [ File = ./tests/samba.ini ] ---------
....

- [ File = ./tests/owlh.ini ] ---------
....

- [ File = ./tests/exchange.ini ] ---------
..

- [ File = ./tests/cisco_ftd.ini ] ---------
..........................................

- [ File = ./tests/openvpn_ldap.ini ] ---------
..

- [ File = ./tests/panda_paps.ini ] ---------
........

- [ File = ./tests/dropbear.ini ] ---------
...

- [ File = ./tests/mcafee_epo.ini ] ---------
.

- [ File = ./tests/openldap.ini ] ---------
.........

- [ File = ./tests/sshd.ini ] ---------
...........................

- [ File = ./tests/kernel_usb.ini ] ---------
......

- [ File = ./tests/pix.ini ] ---------
......................

- [ File = ./tests/unbound.ini ] ---------


- [ File = ./tests/rsh.ini ] ---------
..

- [ File = ./tests/auditd.ini ] ---------
.

- [ File = ./tests/pfsense.ini ] ---------
..

- [ File = ./tests/su.ini ] ---------
.....


```

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

### CODE REVIEW

**Comment by fabamatic** [comment]
File is huge and adds many new techniques, but it does not modify the Technique IDs of existing ones so it shouldn't cause any conflict with our content.

**Review by fabamatic — APPROVED** [review]
No changes were done to existing technique IDs nor any significant change was done to the structure of this document.

**Review by TomasTurina — APPROVED** [review]
LGTM!

**Review by 72nomada — APPROVED** [review]
LGTM! thanks @jcruzlp

**Pull request merged**
