### PR TITLE
Clean up agents labels during deletion

### PR DESCRIPTION
**Pull request by cborla**
|Related issue|
|---|
|#22925|

## Description
This PR clean the labels table: delete labels for non-existing agents on upgrade, also declare the relationship between labels.id and agent.id as a foreign key with DELETE CASCADE rule.

## Configuration options
Default configuration.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [x] Package upgrade
- [x] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [x] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)

### CODE REVIEW

**Comment by cborla** [comment]
## Deleting agents
### Branch: v4.8.0
#### /var/ossec/bin/agent_control -lc
```
Wazuh agent_control. List of available agents:
   ID: 000, Name: VBox (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: DESKTOP, IP: any, Active

```
#### wazuh-tools/utils/wdb-query2.py global "sql SELECT * from labels"
```
[
    {
        "id": 1,
        "key": "#\"_manager_hostname\"",
        "value": "VBox"
    },
    {
        "id": 1,
        "key": "#\"_agent_ip\"",
        "value": "192.168.56.108"
    },
    {
        "id": 1,
        "key": "#\"_node_name\"",
        "value": "node01"
    },
    {
        "id": 1,
        "key": "#\"_wazuh_version\"",
        "value": "Wazuh v4.6.0"
    }
]
```

#### /var/ossec/bin/manage_agents -r 001

```
****************************************
* Wazuh v4.8.0 Agent manager.          *
* The following options are available: *
****************************************
   (A)dd an agent (A).
   (E)xtract key for an agent (E).
   (L)ist already added agents (L).
   (R)emove an agent (R).
   (Q)uit.
Choose your action: A,E,L,R or Q: 
Available agents: 
   ID: 001, Name: DESKTOP-U8OHD3A, IP: any
Provide the ID of the agent to be removed (or '\q' to quit): 001
Confirm deleting it?(y/n): y
Agent '001' removed.
manage_agents: Exiting.
```

#### wazuh-tools/utils/wdb-query2.py global "sql SELECT * from labels"
```
[
    {
        "id": 1,
        "key": "#\"_manager_hostname\"",
        "value": "VBox"
    },
    {
        "id": 1,
        "key": "#\"_agent_ip\"",
        "value": "192.168.56.108"
    },
    {
        "id": 1,
        "key": "#\"_node_name\"",
        "value": "node01"
    },
    {
        "id": 1,
        "key": "#\"_wazuh_version\"",
        "value": "Wazuh v4.6.0"
    }
]
```

### Branch: `22925-clean-up-agents-labels-during-deletion`
#### /var/ossec/bin/agent_control -lc
```
Wazuh agent_control. List of available agents:
   ID: 000, Name: VBox (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: DESKTOP, IP: any, Active

```
#### wazuh-tools/utils/wdb-query2.py global "sql SELECT * from labels"
```
[
    {
        "id": 1,
        "key": "#\"_manager_hostname\"",
        "value": "VBox"
    },
    {
        "id": 1,
        "key": "#\"_agent_ip\"",
        "value": "192.168.56.108"
    },
    {
        "id": 1,
        "key": "#\"_node_name\"",
        "value": "node01"
    },
    {
        "id": 1,
        "key": "#\"_wazuh_version\"",
        "value": "Wazuh v4.6.0"
    }
]
```

#### /var/ossec/bin/manage_agents -r 001

```
****************************************
* Wazuh v4.8.0 Agent manager.          *
* The following options are available: *
****************************************
   (A)dd an agent (A).
   (E)xtract key for an agent (E).
   (L)ist already added agents (L).
   (R)emove an agent (R).
   (Q)uit.
Choose your action: A,E,L,R or Q: 
Available agents: 
   ID: 001, Name: DESKTOP-U8OHD3A, IP: any
Provide the ID of the agent to be removed (or '\q' to quit): 001
Confirm deleting it?(y/n): y
Agent '001' removed.
manage_agents: Exiting.
```

#### wazuh-tools/utils/wdb-query2.py global "sql SELECT * from labels"
```
[]
```

**Comment by cborla** [comment]
## Invalid agent id label cleaning test 

### From Agent 4.7.3

``` console
# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.7.3"
WAZUH_REVISION="40714"
WAZUH_TYPE="server"
```

Deleting Agent 001
``` console
# /var/ossec/bin/agent_control -lc
Wazuh agent_control. List of available agents:
   ID: 000, Name: vbox (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: DESKTOP, IP: any, Active

# /var/ossec/bin/manage_agents -r 001
```

Deleting Agent 002
``` console
# /var/ossec/bin/agent_control -lc
Wazuh agent_control. List of available agents:
   ID: 000, Name: vbox (server), IP: 127.0.0.1, Active/Local
   ID: 002, Name: DESKTOP, IP: any, Active

# /var/ossec/bin/manage_agents -r 002
```

Keeping Agent 003 connected
``` console
# /var/ossec/bin/agent_control -lc
Wazuh agent_control. List of available agents:
   ID: 000, Name: vbox (server), IP: 127.0.0.1, Active/Local
   ID: 003, Name: DESKTOP, IP: any, Active
```

`Labels table`, before the upgrade.

``` console
# ./wdb-query.py global "sql SELECT * from labels"
[
    {
        "id": 1,
        "key": "#\"_manager_hostname\"",
        "value": "vbox"
    },
    {
        "id": 1,
        "key": "#\"_agent_ip\"",
        "value": "192.168.56.108"
    },
    {
        "id": 1,
        "key": "#\"_node_name\"",
        "value": "node01"
    },
    {
        "id": 1,
        "key": "#\"_wazuh_version\"",
        "value": "Wazuh v4.6.0"
    },
    {
        "id": 2,
        "key": "#\"_manager_hostname\"",
        "value": "vbox"
    },
    {
        "id": 2,
        "key": "#\"_agent_ip\"",
        "value": "192.168.56.108"
    },
    {
        "id": 2,
        "key": "#\"_node_name\"",
        "value": "node01"
    },
    {
        "id": 2,
        "key": "#\"_wazuh_version\"",
        "value": "Wazuh v4.6.0"
    },
    {
        "id": 3,
        "key": "#\"_manager_hostname\"",
        "value": "vbox"
    },
    {
        "id": 3,
        "key": "#\"_agent_ip\"",
        "value": "192.168.56.108"
    },
    {
        "id": 3,
        "key": "#\"_node_name\"",
        "value": "node01"
    },
    {
        "id": 3,
        "key": "#\"_wazuh_version\"",
        "value": "Wazuh v4.6.0"
    }
]
```

### Upgrading to branch `22925-clean-up-agents-labels-during-deletion`

``` console
# /var/ossec/bin/wazuh-control info

WAZUH_VERSION="v4.8.0"
WAZUH_REVISION="40807"
WAZUH_TYPE="server"
```

Agent status
``` console
# /var/ossec/bin/agent_control -lc

Wazuh agent_control. List of available agents:
   ID: 000, Name: vbox (server), IP: 127.0.0.1, Active/Local
   ID: 003, Name: DESKTOP, IP: any, Active
```

`Labels table` after the upgrade
``` console
# ../../wazuh-tools/utils/wdb-query2.py global "sql SELECT * from labels"

[
    {
        "id": 3,
        "key": "#\"_manager_hostname\"",
        "value": "vbox"
    },
    {
        "id": 3,
        "key": "#\"_agent_ip\"",
        "value": "192.168.56.108"
    },
    {
        "id": 3,
        "key": "#\"_node_name\"",
        "value": "node01"
    },
    {
        "id": 3,
        "key": "#\"_wazuh_version\"",
        "value": "Wazuh v4.6.0"
    }
]
```
### Conclusion
As can be seen in the test, after applying an upgrede of the wazuh manager version, the agent ids labels tables that are not in the agents table are correctly deleted.

**Review by LucioDonda — APPROVED** [review]
LGTM!

**Comment by vikman90** [comment]
## Failing tests

- macOS compilation test / build-ventura
- macOS unit tests / build-ventura

They are completely unrelated to this PR as we are not changing agent's code.

**Review by vikman90 — APPROVED** [review]

**Review by vikman90 — APPROVED** [review]
### Upgrade test

- Add agent 001.
- Insert random labels for agents 000, 001 and 002.
- Upgrade global DB.

Result:

```sql
SELECT * FROM labels;
```

```
0|label0|zzz
1|label1|sss
```

**Pull request merged**
