### PR TITLE
Add a software limit to limit the amount of EPS that a manager can process

### PR DESCRIPTION
**Pull request by TomasTurina**
|Related issue|Documentation|Manual Testing|
|---|---|---|
|https://github.com/wazuh/wazuh/issues/12512|https://github.com/wazuh/wazuh-documentation/pull/5346|https://github.com/wazuh/wazuh-qa/issues/2995| 

## Description

As part of https://github.com/wazuh/wazuh/issues/12512, a new mechanism has been created to limit the amount of EPS a manager can process.

This mechanism is implemented within the `wazuh-analysisd` daemon and works by using a circular buffer that tracks the total number of events over a defined period of time.

Whenever the circular buffer fills up, the events are held within the related queues until some space is freed. This works like a moving average, this is to support event spikes.

## Configuration options

```
<global>
  <limits>
    <eps>
      <maximum>500</maximum>
      <timeframe>30</timeframe>
    </eps>
  </limits>
</global>
```

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [x] MAC OS X
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [x] Package upgrade
- [x] Review logs syntax and correct language

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)

- [x] Working on cluster environments
- [x] Configuration on demand reports new parameters
- [x] Added unit tests (for new features)

### CODE REVIEW

**Review by cborla — APPROVED** [review]
LGTM

**Review by cborla — APPROVED** [review]
LGTM

**Review by cborla — DISMISSED** [review]
LGTM!

**Comment by jmv74211** [comment]
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/2995
- **Comments**: 🟢 Everything seems to be working properly. Several suggestions have been proposed in https://github.com/wazuh/wazuh/issues/14665 https://github.com/wazuh/wazuh/issues/14666 and will be reviewed in future PRs.

**Review by vikman90 — APPROVED** [review]

**Review by cborla — APPROVED** [review]
LGTM!

**Review by cborla — APPROVED** [review]
LGTM!

**Review by jmv74211 — APPROVED** [review]
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/2995
- **Comments**:  https://github.com/wazuh/wazuh-qa/issues/2995#issuecomment-1282625035

**Review by vikman90 — APPROVED** [review]

**Pull request merged**
