### PR TITLE
Engine - Automatic documentation generation

### PR DESCRIPTION
**Pull request by NahuFigueroa97**
|Related issue|
|---|
|#24500|

## Description
The final stage in our development of a testing framework for Wazuh-Engine's helper functions focuses on automatically generating detailed and accurate documentation. This documentation will be derived from the enhanced YAML configurations used in previous stages and will include metadata and test results to provide comprehensive function descriptions.

## Objective
Comprehensive Documentation: Automatically generate detailed, up-to-date documentation for each helper function, incorporating metadata, test configurations, inputs, expected outputs, and actual test results.

### CODE REVIEW

**Review by JavierBejMen — CHANGES_REQUESTED** [review]
We need to generate the documentation

**Review by JavierBejMen — CHANGES_REQUESTED** [review]
I think the index should contain a brief introduction about helpers and types and it should list all available helpers (second indexes for each type are not friendly). Also, I would consider unifying everything under one readme as it is not that long.

**Review by juliancnn — APPROVED** [review]
LGTM

**Review by JavierBejMen — APPROVED** [review]
LGTM

**Pull request merged**
