### PR TITLE
3319 fim rework sqlite unit tests

### PR DESCRIPTION
**Pull request by nicolaspapp**
|Related issue|
|---|
| #4501 |

|Working branch|
|---|
|[3319-fim-rework-sqlite-unit-tests](https://github.com/wazuh/wazuh/tree/3319-fim-rework-sqlite-unit-tests)|

Progress and feedback from fim sqlite unit tests

### CODE REVIEW

**Comment by nicolaspapp** [comment]
## **fim_db_init**
Coverage: 100%

Comments:
- Memory leaks detected on failed initialization. `fdb_t` structure should be realeased before returning

**Comment by nicolaspapp** [comment]
## **fim_db_clean**
Coverage: 100%

**Comment by nicolaspapp** [comment]
## **fim_db_insert_data**
Coverage: -

Test method  | Status | Comments
-- |  -- | --
test_fim_db_insert_data_clean_error | Failure | Method continues even when statement cleaning fails.  
test_fim_db_insert_data_insert_error | Passed | --

General Comments:
- [fim_db_clean_stmt(fim_sql, FIMDB_STMT_UPDATE_DATA)](https://github.com/wazuh/wazuh/blob/3319-fim-rework-sqlite/src/syscheckd/fim_db.c#L587) is not necesarry if insert is successfull and could be moved to [SQLITE_CONSTRAIN](https://github.com/wazuh/wazuh/blob/3319-fim-rework-sqlite/src/syscheckd/fim_db.c#L596) case

**Comment by nicolaspapp** [comment]
## **fim_db_remove_path**
Coverage: -

Test method  | Status | Comments
-- |  -- | --
test_fim_db_remove_path_no_entry | Passed | -- 
test_fim_db_remove_path_one_entry| Passed | --
test_fim_db_remove_path_multiple_entry| Passed | --
test_fim_db_remove_path_failed_path | Passed | --

General Comments:
- No catching of failure of cleanup before executing
- There is no message on failure to remove a path. Only a message for failure to complete transaction

**Comment by nicolaspapp** [comment]
## **fim_db_get_inode**
Coverage: -

Test method  | Status | Comments
-- |  -- | --
test_fim_db_get_inode_non_existent| Passed | -- 
test_fim_db_get_inode_existent| Failed| Expected value when a inode exists is 1, but `fim_db_get_inode` is returning `FIMDB_ERROR (-1)`

**Comment by nicolaspapp** [comment]
## **fim_db_get_path**
Coverage: -

Test method  | Status | Comments
-- |  -- | --
test_fim_db_get_path_inexistent| Passed | -- 
test_fim_db_get_path_existent| Failed| *

*:  In the `function fim_db_decode_full_row` called inside the function, the following line:

`w_strdup((char *)sqlite3_column_text(stmt, 0), entry->path);`

Produces two sucesive calls to `sqlite3_column_text`. This is because in:

`#define w_strdup(x,y) ({ int retstr = 0; if (x) { os_strdup(x, y);} else retstr = 1; retstr;})`

 `sqlite3_column_text` is getting called both to evaluate the if function and to enter the os_strdup method. This tampers with the mock corresponding to the test. Also output of the function is being cast from a read only variable to read/write `(const unsigned char *) -> (char *) -> (const char *)` that could lead to warnings in some compilers. Replacing the calls for something like:

`os_strdup((const char *)sqlite3_column_text(stmt, 0), entry->path);`

Will fix the double call to `sqlite3_column_text` method

**Comment by nicolaspapp** [comment]
## **fim_db_set_all_unscanned**
Coverage: -

Test method  | Status | Comments
-- |  -- | --
test_fim_db_set_all_unscanned_failed| Passed | -- 
test_fim_db_set_all_unscanned_success| Passed| --

**Comment by nicolaspapp** [comment]
## **fim_db_get_data_checksum**
Coverage: -

Test method  | Status | Comments
-- |  -- | --
test_fim_db_get_data_checksum_failed| Passed | -- 
test_fim_db_get_data_checksum_success | Failed | Same problem as [fim_db_get_path](https://github.com/wazuh/wazuh/pull/4520#issuecomment-580286774)

**Comment by nicolaspapp** [comment]
## **fim_db_check_transaction**
Coverage: -

Test method  | Status | Comments
-- |  -- | --
test_fim_db_check_transaction_last_commit_is_0 | Failed| if previous last_commit is 0, commit time is updated even when commit fails
test_fim_db_check_transaction_failed | Passed | --
test_fim_db_check_transaction_success | Passed | --

General comments: 
Some retry method should be added to avoid the possibility of an inifinte loop in the following line:

   `while (fim_db_exec_simple_wquery(fim_sql, "BEGIN;") == FIMDB_ERR);`

**Comment by nicolaspapp** [comment]
## **fim_db_cache**
Coverage: -

Test method  | Status | Comments
-- |  -- | --
test_fim_db_cache_failed | Passed | -- 
test_fim_db_cache_success | Passed | --

**Comment by nicolaspapp** [comment]
## **fim_db_close**
Coverage: -

Test method  | Status | Comments
-- |  -- | --
test_fim_db_close_failed | Failed |  Expected error message when db fails to close
test_fim_db_close_success | Passed | --

**Comment by nicolaspapp** [comment]
## **fim_db_clean**
Coverage: -

Test method  | Status | Comments
-- |  -- | --
test_fim_db_clean_no_db_file| Passed| --
test_fim_db_clean_file_not_removed| Passed | --
test_fim_db_clean_succes | Passed | --

**Comment by nicolaspapp** [comment]
## **fim_db_finalize_stmt**
Coverage: -

Test method  | Status | Comments
-- |  -- | --
test_fim_db_finalize_stmt_failed | Passed | --
test_fim_db_finalize_stmt_success| Passed | --

**Comment by nicolaspapp** [comment]
## **fim_db_force_commit**
Coverage: -

Test method  | Status | Comments
-- |  -- | --
test_fim_db_force_commit_failed | Passed | --
test_fim_db_force_commit_success| Passed | --

## **fim_db_clean_stmt**
Coverage: -

Test method  | Status | Comments
-- |  -- | --
test_fim_db_clean_stmt_reset_failed | Passed | --
test_fim_db_clean_stmt_reset_and_prepare_failed | Passed | --
test_fim_db_clean_stmt_success | Passed | --

**Comment by nicolaspapp** [comment]
## **fim_db_get_paths_from_inode**
Coverage: -

Test method  | Status | Comments
-- |  -- | --
test_fim_db_get_paths_from_inode_none_path | Passed | --
test_fim_db_get_paths_from_inode_single_path | Passed | --
test_fim_db_get_paths_from_inode_multiple_path | Passed | --
test_fim_db_get_paths_from_inode_multiple_unamatched_rows | Failed | Should be an error message instead of `printf`, we probably should deallocate existing structure and return` null` for `paths` as well

**Comment by Molter73** [comment]
## fim_db_get_row_path
|Test method | Status | Comments|
|--|--|--|
|test_fim_db_get_row_path_error|Passed|--|
|test_fim_db_get_row_path_sqlite_row|Passed|Same issue as fim_db_get_path with w_strdup and sqlite3_column_text|
|test_fim_db_get_row_path_sqlite_done|Passed|--|

**Comment by nicolaspapp** [comment]
## fim_db_data_checksum_range
|Test method | Status | Comments|
|--|--|--|
|test_fim_db_data_checksum_range_first_half_failed|Passed| * |
|test_fim_db_data_checksum_range_second_half_failed|Passed| * |
|test_fim_db_data_checksum_range_success|Passed| * |
 
They all have the same issue with repeated calls to w_strdup and sqlite3_column_text

**Comment by Molter73** [comment]
## fim_db_get_count_range
|Test method | Status | Comments|
|-- | -- | --|
|test_fim_db_get_count_range_error_stepping| Passed | --|
|test_fim_db_get_count_range_success| Passed | --|

**Pull request closed without merging**
