### PR TITLE
SOC/TSC from AICPA compliance support

### PR DESCRIPTION
**Pull request by snaow**
## Description

Adding support to TSC criteria which will help all the users with the SOC compliance.
The same way Wazuh is doing for the other compliance standards (PCI DSS, HIPAA, NIST..) this PR aims to support the TSC controls at:

- Rule groups parsing and extracting the TSC numeric control. Including the control in the alert JSON output
- Framework support for API requests regarding TSC: `:/rules/tsc`

Source:

- [2017 Trust Services Criteria for Security, Availability, Processing Integrity, Confidentiality, and Privacy](https://www.aicpa.org/content/dam/aicpa/interestareas/frc/assuranceadvisoryservices/downloadabledocuments/trust-services-criteria.pdf)

## Related PRs
- API Commit: https://github.com/wazuh/wazuh-api/commit/719563a6e18581a2c062ba0f6a950730ac74222d
- Ruleset PR: https://github.com/wazuh/wazuh-ruleset/pull/613
- Frontend Commits: https://github.com/wazuh/wazuh-kibana-app/commit/bf2d31d043307e66e4a3209b60410d800828c16b https://github.com/wazuh/wazuh-kibana-app/commit/f47e606755a8ec9446203a8e4aba09d2cca4f52c

## Logs/Alerts example

```
{
  "timestamp": "2020-04-08T18:31:07.769+0000",
  "rule": {
    "level": 3,
    "description": "sshd: authentication success.",
    "id": "5715",
    "firedtimes": 1,
    "mail": false,
    "groups": [
      "syslog",
      "sshd",
      "authentication_success"
    ],
    "pci_dss": [
      "10.2.5"
    ],
    "gpg13": [
      "7.1",
      "7.2"
    ],
    "gdpr": [
      "IV_32.2"
    ],
    "hipaa": [
      "164.312.b"
    ],
    "nist_800_53": [
      "AU.14",
      "AC.7"
    ],
    "tsc": [
      "CC6.1",
      "CC6.8",
      "CC7.2",
      "CC7.3",
      "CC7.4"
    ]
  },
.
.
.
}
```

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [x] Package upgrade
- [x] Review logs syntax and correct language
- [x] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer

- [x] Retrocompatibility with older Wazuh versions
- [x] Working on cluster environments

### CODE REVIEW

**Comment by davidjiglesias** [comment]
### **Updated API Mocha test results:**
```node
  Rules
    GET/rules
(node:2605) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
      ✓ Request (400ms)
      ✓ Pagination (370ms)
      ✓ Retrieve all elements with limit=0 (373ms)
      ✓ Sort (385ms)
      ✓ Search (496ms)
      ✓ Filters: Invalid filter (78ms)
      ✓ Filters: Invalid filter - Extra field (80ms)
      ✓ Filters: status (377ms)
      ✓ Filters: group (412ms)
      ✓ Filters: level (1) (387ms)
      ✓ Filters: level (2) (513ms)
      ✓ Filters: path (378ms)
      ✓ Filters: file (380ms)
      ✓ Filters: pci (470ms)
      ✓ Filters: gdpr (376ms)
      ✓ Filters: hipaa (599ms)
      ✓ Filters: nist-800-53 (540ms)
      ✓ Filters: tsc (631ms)
      ✓ Filters: gpg13 (384ms)
      ✓ Filters: query 1 (377ms)
      ✓ Filters: query 2 (391ms)
    GET/rules/groups
      ✓ Request (371ms)
      ✓ Pagination (372ms)
      ✓ Retrieve all elements with limit=0 (370ms)
      ✓ Sort (375ms)
      ✓ Search (370ms)
      ✓ Filters: Invalid filter (78ms)
    GET/rules/pci
      ✓ Request (375ms)
      ✓ Pagination (385ms)
      ✓ Retrieve all elements with limit=0 (378ms)
      ✓ Sort (373ms)
      ✓ Search (387ms)
      ✓ Filters: Invalid filter (77ms)
    GET/rules/gdpr
      ✓ Request (388ms)
      ✓ Pagination (388ms)
      ✓ Retrieve all elements with limit=0 (382ms)
      ✓ Sort (382ms)
      ✓ Search (381ms)
      ✓ Filters: Invalid filter (78ms)
    GET/rules/gpg13
      ✓ Request (389ms)
      ✓ Pagination (411ms)
      ✓ Retrieve all elements with limit=0 (394ms)
      ✓ Sort (395ms)
      ✓ Search (402ms)
      ✓ Filters: Invalid filter (76ms)
    GET/rules/hipaa
      ✓ Request (394ms)
      ✓ Pagination (394ms)
      ✓ Retrieve all elements with limit=0 (400ms)
      ✓ Sort (410ms)
      ✓ Search (397ms)
      ✓ Filters: Invalid filter (78ms)
    GET/rules/nist-800-53
      ✓ Request (386ms)
      ✓ Pagination (387ms)
      ✓ Retrieve all elements with limit=0 (422ms)
      ✓ Sort (435ms)
      ✓ Search (421ms)
      ✓ Filters: Invalid filter (95ms)
    GET/rules/tsc
      ✓ Request (453ms)
      ✓ Pagination (415ms)
      ✓ Retrieve all elements with limit=0 (417ms)
      ✓ Sort (409ms)
      ✓ Search (398ms)
      ✓ Filters: Invalid filter (80ms)
    GET/rules/files
      ✓ Request (269ms)
      ✓ Pagination (244ms)
      ✓ Retrieve all elements with limit=0 (241ms)
      ✓ Sort (253ms)
      ✓ Search (250ms)
      ✓ Filters: Invalid filter (76ms)
      ✓ Filters: Invalid filter - Extra field (77ms)
      ✓ Filters: status (276ms)
      ✓ Filters: download (248ms)
    GET/rules/:rule_id
      ✓ Request (371ms)
      ✓ Pagination (382ms)
      ✓ Retrieve all elements with limit=0 (373ms)
      ✓ Sort (382ms)
      ✓ Search (373ms)
      ✓ Filters: Invalid filter (75ms)
      ✓ Params: Bad rule id (76ms)
      ✓ Params: No rule (368ms)


  80 passing (27s)
```

**Comment by davidjiglesias** [comment]
### **Framework Rules Unit Test Results:**
```python
============================= test session starts ==============================
platform linux -- Python 3.7.4, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- /usr/local/bin/python3.7
cachedir: .pytest_cache
rootdir: /home/davidjiglesias/git/wazuh/framework
plugins: tavern-1.0.0
collecting ... collected 107 items

test_rules.py::test_rule__init__ PASSED                                  [  0%]
test_rules.py::test_rule__str__ PASSED                                   [  1%]
test_rules.py::test_rule__compare__ PASSED                               [  2%]
test_rules.py::test_failed_rule__compare__ PASSED                        [  3%]
test_rules.py::test_rule_to_dict PASSED                                  [  4%]
test_rules.py::test_set_group PASSED                                     [  5%]
test_rules.py::test_set_pci PASSED                                       [  6%]
test_rules.py::test_set_gpg13 PASSED                                     [  7%]
test_rules.py::test_set_gdpr PASSED                                      [  8%]
test_rules.py::test_set_hippa PASSED                                     [  9%]
test_rules.py::test_nist_800_53 PASSED                                   [ 10%]
test_rules.py::test_tsc PASSED                                           [ 11%]
test_rules.py::test_add_details[if_sid-400-details0] PASSED              [ 12%]
test_rules.py::test_add_details[if_sid-400-details1] PASSED              [ 13%]
test_rules.py::test_get_rules_file_status_include[None-get_rules_files] PASSED [ 14%]
test_rules.py::test_get_rules_file_status_include[None-get_rules] PASSED [ 14%]
test_rules.py::test_get_rules_file_status_include[all-get_rules_files] PASSED [ 15%]
test_rules.py::test_get_rules_file_status_include[all-get_rules] PASSED  [ 16%]
test_rules.py::test_get_rules_file_status_include[enabled-get_rules_files] PASSED [ 17%]
test_rules.py::test_get_rules_file_status_include[enabled-get_rules] PASSED [ 18%]
test_rules.py::test_get_rules_file_status_include[disabled-get_rules_files] PASSED [ 19%]
test_rules.py::test_get_rules_file_status_include[disabled-get_rules] PASSED [ 20%]
test_rules.py::test_get_rules_file_status_include[random-get_rules_files] PASSED [ 21%]
test_rules.py::test_get_rules_file_status_include[random-get_rules] PASSED [ 22%]
test_rules.py::test_get_rules_file_path[None-get_rules_files] PASSED     [ 23%]
test_rules.py::test_get_rules_file_path[None-get_rules] PASSED           [ 24%]
test_rules.py::test_get_rules_file_path[ruleset/rules-get_rules_files] PASSED [ 25%]
test_rules.py::test_get_rules_file_path[ruleset/rules-get_rules] PASSED  [ 26%]
test_rules.py::test_get_rules_file_path[random-get_rules_files] PASSED   [ 27%]
test_rules.py::test_get_rules_file_path[random-get_rules] PASSED         [ 28%]
test_rules.py::test_get_rules_file_file_param[rules0.xml-get_rules_files] PASSED [ 28%]
test_rules.py::test_get_rules_file_file_param[rules0.xml-get_rules] PASSED [ 29%]
test_rules.py::test_get_rules_file_file_param[rules1.xml-get_rules_files] PASSED [ 30%]
test_rules.py::test_get_rules_file_file_param[rules1.xml-get_rules] PASSED [ 31%]
test_rules.py::test_get_rules_file_file_param[rules2.xml-get_rules_files] PASSED [ 32%]
test_rules.py::test_get_rules_file_file_param[rules2.xml-get_rules] PASSED [ 33%]
test_rules.py::test_get_rules_file_pagination[0-0-get_rules_files] PASSED [ 34%]
test_rules.py::test_get_rules_file_pagination[0-0-get_rules] PASSED      [ 35%]
test_rules.py::test_get_rules_file_pagination[0-1-get_rules_files] PASSED [ 36%]
test_rules.py::test_get_rules_file_pagination[0-1-get_rules] PASSED      [ 37%]
test_rules.py::test_get_rules_file_pagination[0-500-get_rules_files] PASSED [ 38%]
test_rules.py::test_get_rules_file_pagination[0-500-get_rules] PASSED    [ 39%]
test_rules.py::test_get_rules_file_pagination[1-500-get_rules_files] PASSED [ 40%]
test_rules.py::test_get_rules_file_pagination[1-500-get_rules] PASSED    [ 41%]
test_rules.py::test_get_rules_file_pagination[2-500-get_rules_files] PASSED [ 42%]
test_rules.py::test_get_rules_file_pagination[2-500-get_rules] PASSED    [ 42%]
test_rules.py::test_get_rules_file_pagination[3-500-get_rules_files] PASSED [ 43%]
test_rules.py::test_get_rules_file_pagination[3-500-get_rules] PASSED    [ 44%]
test_rules.py::test_get_rules_file_sort[None-get_rules_files] PASSED     [ 45%]
test_rules.py::test_get_rules_file_sort[None-get_rules] PASSED           [ 46%]
test_rules.py::test_get_rules_file_sort[sort1-get_rules_files] PASSED    [ 47%]
test_rules.py::test_get_rules_file_sort[sort1-get_rules] PASSED          [ 48%]
test_rules.py::test_get_rules_file_sort[sort2-get_rules_files] PASSED    [ 49%]
test_rules.py::test_get_rules_file_sort[sort2-get_rules] PASSED          [ 50%]
test_rules.py::test_get_rules_file_search[None-get_rules_files] PASSED   [ 51%]
test_rules.py::test_get_rules_file_search[None-get_rules] PASSED         [ 52%]
test_rules.py::test_get_rules_file_search[search1-get_rules_files] PASSED [ 53%]
test_rules.py::test_get_rules_file_search[search1-get_rules] PASSED      [ 54%]
test_rules.py::test_get_rules_file_search[search2-get_rules_files] PASSED [ 55%]
test_rules.py::test_get_rules_file_search[search2-get_rules] PASSED      [ 56%]
test_rules.py::test_failed_get_rules_file PASSED                         [ 57%]
test_rules.py::test_get_rules[arg0] PASSED                               [ 57%]
test_rules.py::test_get_rules[arg1] PASSED                               [ 58%]
test_rules.py::test_get_rules[arg2] PASSED                               [ 59%]
test_rules.py::test_get_rules[arg3] PASSED                               [ 60%]
test_rules.py::test_get_rules[arg4] PASSED                               [ 61%]
test_rules.py::test_get_rules[arg5] PASSED                               [ 62%]
test_rules.py::test_get_rules[arg6] PASSED                               [ 63%]
test_rules.py::test_get_rules[arg7] PASSED                               [ 64%]
test_rules.py::test_get_rules[arg8] PASSED                               [ 65%]
test_rules.py::test_get_rules[arg9] PASSED                               [ 66%]
test_rules.py::test_failed_get_rules PASSED                              [ 67%]
test_rules.py::test_get_groups[arg0] PASSED                              [ 68%]
test_rules.py::test_get_groups[arg1] PASSED                              [ 69%]
test_rules.py::test_get_groups[arg2] PASSED                              [ 70%]
test_rules.py::test_get_groups[arg3] PASSED                              [ 71%]
test_rules.py::test_get_pci PASSED                                       [ 71%]
test_rules.py::test_get_gpg13 PASSED                                     [ 72%]
test_rules.py::test_get_gdpr PASSED                                      [ 73%]
test_rules.py::test_get_hipaa PASSED                                     [ 74%]
test_rules.py::test_get_nist_800_53 PASSED                               [ 75%]
test_rules.py::test_get_tsc PASSED                                       [ 76%]
test_rules.py::test_protected_get_requirement[pci-None-None] PASSED      [ 77%]
test_rules.py::test_protected_get_requirement[pci-None-sort1] PASSED     [ 78%]
test_rules.py::test_protected_get_requirement[pci-search1-None] PASSED   [ 79%]
test_rules.py::test_protected_get_requirement[pci-search1-sort1] PASSED  [ 80%]
test_rules.py::test_protected_get_requirement[gdpr-None-None] PASSED     [ 81%]
test_rules.py::test_protected_get_requirement[gdpr-None-sort1] PASSED    [ 82%]
test_rules.py::test_protected_get_requirement[gdpr-search1-None] PASSED  [ 83%]
test_rules.py::test_protected_get_requirement[gdpr-search1-sort1] PASSED [ 84%]
test_rules.py::test_protected_get_requirement[gpg13-None-None] PASSED    [ 85%]
test_rules.py::test_protected_get_requirement[gpg13-None-sort1] PASSED   [ 85%]
test_rules.py::test_protected_get_requirement[gpg13-search1-None] PASSED [ 86%]
test_rules.py::test_protected_get_requirement[gpg13-search1-sort1] PASSED [ 87%]
test_rules.py::test_protected_get_requirement[wrong-None-None] PASSED    [ 88%]
test_rules.py::test_protected_get_requirement[wrong-None-sort1] PASSED   [ 89%]
test_rules.py::test_protected_get_requirement[wrong-search1-None] PASSED [ 90%]
test_rules.py::test_protected_get_requirement[wrong-search1-sort1] PASSED [ 91%]
test_rules.py::test_protected_get_requirement[hipaa-None-None] PASSED    [ 92%]
test_rules.py::test_protected_get_requirement[hipaa-None-sort1] PASSED   [ 93%]
test_rules.py::test_protected_get_requirement[hipaa-search1-None] PASSED [ 94%]
test_rules.py::test_protected_get_requirement[hipaa-search1-sort1] PASSED [ 95%]
test_rules.py::test_protected_get_requirement[nist-800-53-None-None] PASSED [ 96%]
test_rules.py::test_protected_get_requirement[nist-800-53-None-sort1] PASSED [ 97%]
test_rules.py::test_protected_get_requirement[nist-800-53-search1-None] PASSED [ 98%]
test_rules.py::test_protected_get_requirement[nist-800-53-search1-sort1] PASSED [ 99%]
test_rules.py::test_failed_load_rules_from_file PASSED                   [100%]

============================= 107 passed in 0.78s ==============================
```

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** b1e8181097fc94be2efcd7f787fd6649d21aea20
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1590/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1590/ossec.log)
**Coverage:** 

```json
Lines executed:31.40% of 1860

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1590/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1590.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1590/Analysis_dynamic_valgrind-v3.13.0-B1590.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** b1e8181097fc94be2efcd7f787fd6649d21aea20
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1591/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1591/ossec.log)
**Coverage:** 

```json
Lines executed:26.50% of 2996

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1591/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1591.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1591/Analysis_dynamic_valgrind-v3.13.0-B1591.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 545dc28f8805f5051875aa1e08194e02d5e0d908
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2008/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2008/ossec.log)
**Coverage:** 

```json
Lines executed:3.92% of 1860

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2008/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2008.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2008/Analysis_dynamic_valgrind-v3.13.0-B2008.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** a93464d66c3d9aed8b4447bd0d93b75389ba5442
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2010/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2010/ossec.log)
**Coverage:** 

```json
Lines executed:3.93% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2010/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2010.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2010/Analysis_dynamic_valgrind-v3.13.0-B2010.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 92c4c9ce1168827f37b7d0779314ec5e2d3bc1ac
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2066/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2066/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2066/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2066.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2066/Analysis_dynamic_valgrind-v3.13.0-B2066.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 92c4c9ce1168827f37b7d0779314ec5e2d3bc1ac
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2067/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2067/ossec.log)
**Coverage:** 

```json
Lines executed:26.80% of 3186

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2067/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2067.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2067/Analysis_dynamic_valgrind-v3.13.0-B2067.log)

**Pull request merged**
