### PR TITLE
Fix cmocka unit tests for FIM

### LINKED ISSUE #10806: Fix cmocka unit tests after FIM DB rework
After the development of #9103, we moved the DB code to C++ alongside the unit tests.

The purpose of this issue is to look at all the problems in the C unit tests that have been broken with this change.
## Steps to complete the issue.
Using the current design, we will need to:
- [x] Delete all the deprecated UT.
- [x] Remove all the deprecated wrappers. 
- [x] Add/adapt the wrappers for the C interface of the new FIM DB library. -> in progress
- [x] Add/adapt the syscheck UT to use the interface wrappers.
- [x] #12242

### LINKED ISSUE #12333: Fix coverage to cmocka unit tests
|EPIC|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/9103 | FIM |

### Description

The goal of this issue is review coverage report for cmocka unit tests this has a problem after change compile way from Makefile to Cmake

To do:
- [x] Fix coverage report for agent
- [x] Fix coverage report for server
- [ ] Fix coverage report for winagent

More information:
There is a work around this is: add the file to be tested inside executable test this will give coverage to this file

### PR DESCRIPTION
**Pull request by FrancoRivero**
|EPIC|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/9103 | FIM |

### Description

Fix cmocka unit tests for FIM

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [x] MAC OS X
- [x] Unit tests passed
- [x] Review logs syntax and correct language

- Memory tests for Linux
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [x] cppcheck (static code analysis)
  - [x] Coverage (unit tests coverage code)
  - [x] Sformat (code style)
  - [x] Scan build
 

Closes #10806
Closes #12333

### CODE REVIEW

**Review by antoniomanuelfr — CHANGES_REQUESTED** [review]
Running coverage I have seen that there are some missing reports:
- `src/syscheckd/src/registry`
- `src/syscheckd/src/whodata`
- `src/syscheckd/create_db.c`
image

**Review by chemamartinez — APPROVED** [review]

**Comment by FrancoRivero** [comment]
Hi @antoniomanuelfr we are working in this problem in [this issue](https://github.com/wazuh/wazuh/issues/12333)

**Comment by FrancoRivero** [comment]
Hi @antoniomanuelfr we are working in this problem in [this issue](https://github.com/wazuh/wazuh/issues/12333)

**Review by antoniomanuelfr — APPROVED** [review]
LGTM

**Pull request merged**
