### PR TITLE
Reduce Framework Python file permissions

### PR DESCRIPTION
**Pull request by grg121**
Hello team, this PR aims to fix some Python permissions that are too open.

## Description
There is a '*'' wildcard that applies some permissions to all the files inside the framework Python directory. We've removed it to avoid that such chmod affect those files. Also, we want to have the same permissions in both Debian and RPM systems. 

### Rpm from sources
- [x] Tested
```
[root@55494868681e wazuh-fix-python-permissions]# ls /var/ossec/framework/ -l
total 12
drwxr-x--- 6 root ossec 4096 May 28 11:18 python
drwxr-x--- 2 root ossec 4096 May 28 11:18 scripts
drwxr-x--- 3 root ossec 4096 May 28 11:18 wazuh

[root@55494868681e wazuh-fix-python-permissions]# ls /var/ossec/framework/python/ -l
total 16
drwxr-x--- 3 root ossec 4096 May 28 11:18 bin
drwxr-x--- 3 root ossec 4096 May 28 11:18 include
drwxr-x--- 4 root ossec 4096 May 28 11:18 lib
drwxr-x--- 3 root ossec 4096 May 28 11:18 share
```

### Debian from sources
- [x] Tested
```
root@db182f57170b:/wazuh-fix-python-permissions# ls /var/ossec/framework/ -l
total 12
drwxr-x--- 6 root ossec 4096 May 28 11:24 python
drwxr-x--- 2 root ossec 4096 May 28 11:24 scripts
drwxr-x--- 3 root ossec 4096 May 28 11:24 wazuh

root@db182f57170b:/wazuh-fix-python-permissions# ls /var/ossec/framework/python/ -l
total 16
drwxr-x--- 3 root ossec 4096 May 28 11:24 bin
drwxr-x--- 3 root ossec 4096 May 28 11:24 include
drwxr-x--- 4 root ossec 4096 May 28 11:24 lib
drwxr-x--- 3 root ossec 4096 May 28 11:24 share
```

## Current permissions (packages)
Notice that Debian package generation procedure doesn't modify the permissions generated during compilation. Rpm does based on his SPECs. 
### Debian
```
root@1069998f13b8:/# ls -l /var/ossec/framework/      
total 12
drwxr-xr-x 6 root ossec 4096 May 28 09:58 python
drwxr-x--- 2 root ossec 4096 May 28 09:58 scripts
drwxr-x--- 3 root ossec 4096 May 28 09:58 wazuh
root@1069998f13b8:/# 
```
### Centos
```
[root@434ea545435e /]# ls -l /var/ossec/framework/      
total 16
drwxr-x--- 2 root ossec 4096 May 28 09:58 lib
drwxr-x--- 6 root ossec 4096 May 28 09:58 python
drwxr-x--- 2 root ossec 4096 May 28 09:58 scripts
drwxr-x--- 3 root ossec 4096 May 28 09:58 wazu
```

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows [not affected] [test on jenkins]
  - [x] MAC OS X [not affected] [test on jenkins]
- [x] Source installation [on centos and debian]
- [x] Package installation [test on jenkins]
- [x] Source upgrade [on centos and debian]
- [x] Package upgrade [test on jenkins]
- [x] Review logs syntax and correct language
- [x] QA templates contemplate the added capabilities

### CODE REVIEW

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 17156f3721fe95011fd23914af48fb2831147825
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2283/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2283/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2283/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2283.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2283/Analysis_dynamic_valgrind-v3.13.0-B2283.log)

**Comment by grg121** [comment]
Hello team, 

We've added another commit to this PR to enhance the check of OpenScap on `wazuh.sh` script by redirecting the error output to `/dev/null` as well as the stdout. 

Best regards.

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 122c472d4e3fa94fce885d4a9df32330ed1bc536
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2293/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2293/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2293/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2293.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2293/Analysis_dynamic_valgrind-v3.13.0-B2293.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 122c472d4e3fa94fce885d4a9df32330ed1bc536
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2294/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2294/ossec.log)
**Coverage:** 

```json
Lines executed:26.87% of 3190

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2294/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2294.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2294/Analysis_dynamic_valgrind-v3.13.0-B2294.log)

**Pull request merged**
