### PR TITLE
Remove OpenSCAP functions from sources installer

### PR DESCRIPTION
**Pull request by BraulioV**
|Related issue|
|---|
|#5061|

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [x] Package upgrade
- [x] Review logs syntax and correct language

### CODE REVIEW

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 50587532469219e102fb5be3119f43ee821e180b
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2504/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2504/ossec.log)
**Coverage:** 

```json
Lines executed:26.92% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2504/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2504.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2504/Analysis_dynamic_valgrind-v3.13.0-B2504.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 50587532469219e102fb5be3119f43ee821e180b
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2503/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2503/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2503/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2503.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2503/Analysis_dynamic_valgrind-v3.13.0-B2503.log)

**Comment by wazuhci-staging** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 50587532469219e102fb5be3119f43ee821e180b
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B596/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B596/ossec.log)
**Coverage:** 

```json
Lines executed:26.92% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B596/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B596.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B596/Analysis_dynamic_valgrind-v3.13.0-B596.log)

**Comment by wazuhci-staging** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 50587532469219e102fb5be3119f43ee821e180b
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B595/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B595/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B595/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B595.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B595/Analysis_dynamic_valgrind-v3.13.0-B595.log)

**Comment by wazuhci-staging** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 50587532469219e102fb5be3119f43ee821e180b
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B598/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B598/ossec.log)
**Coverage:** 

```json
Lines executed:26.89% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B598/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B598.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B598/Analysis_dynamic_valgrind-v3.13.0-B598.log)

**Comment by wazuhci-staging** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 50587532469219e102fb5be3119f43ee821e180b
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B597/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B597/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B597/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B597.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B597/Analysis_dynamic_valgrind-v3.13.0-B597.log)

**Comment by wazuhci-staging** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 50587532469219e102fb5be3119f43ee821e180b
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B600/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B600/ossec.log)
**Coverage:** 

```json
Lines executed:26.92% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B600/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B600.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B600/Analysis_dynamic_valgrind-v3.13.0-B600.log)

**Comment by wazuhci-staging** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 50587532469219e102fb5be3119f43ee821e180b
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B599/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B599/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B599/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B599.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B599/Analysis_dynamic_valgrind-v3.13.0-B599.log)

**Comment by wazuhci-staging** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 50587532469219e102fb5be3119f43ee821e180b
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B602/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B602/ossec.log)
**Coverage:** 

```json
Lines executed:26.92% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B602/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B602.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B602/Analysis_dynamic_valgrind-v3.13.0-B602.log)

**Comment by wazuhci-staging** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 50587532469219e102fb5be3119f43ee821e180b
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B601/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B601/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B601/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B601.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B601/Analysis_dynamic_valgrind-v3.13.0-B601.log)

**Pull request merged**
