### PR TITLE
Update groups queries and scripts

### PR DESCRIPTION
**Pull request by GGP1**
|Related issue|
|---|
| Closes https://github.com/wazuh/wazuh/issues/26847 |

## Description

Updates agent groups queries and scripts to manipulate a string array instead of a string with values separated by commas.

### Tests

<details><summary>Create group</summary>

```console
root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -ks -X POST https://localhost:55000/groups -d '{
  "group_id": "group1"
}' | jq
{
  "message": "Group 'group1' created.",
  "error": 0
}
root@wazuh-master:/# ls -la /etc/wazuh-server/shared/
total 16
drwxr-x--- 1 root  wazuh 4096 Nov 15 15:13 .
drwxr-x--- 1 root  wazuh 4096 Nov 15 14:58 ..
-rw-rw---- 1 wazuh wazuh   21 Nov 15 15:13 group1.conf
```

</details>

<details><summary>Get groups</summary>

```console
root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -ks https://localhost:55000/groups | jq
{
  "data": {
    "affected_items": [
      {
        "name": "group1",
        "configSum": "65e363d76ef3e3b76f87b8eaa24cbff9"
      },
      {
        "name": "group2",
        "configSum": "65e363d76ef3e3b76f87b8eaa24cbff9"
      },
      {
        "name": "group3",
        "configSum": "65e363d76ef3e3b76f87b8eaa24cbff9"
      }
    ],
    "total_affected_items": 3,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected groups information was returned",
  "error": 0
}
```

</details>

<details><summary>Register an agent</summary>

```console
root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -X POST -k https://localhost:55000/agents -d '
{
  "id": "0a96a0ab-5bef-415c-bb3c-ea3e294215a0",
  "name": "test",
  "key": "7b8276c3bf96aff5709346d368f04fed",
  "type": "endpoint",
  "version": "5.0.0",
  "groups": ["group1", "group2"]
}
'
```

</details>

<details><summary>Get agents</summary>

```console
root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -ks https://localhost:55000/agents | jq
{
  "data": {
    "affected_items": [
      {
        "id": "0a96a0ab-5bef-415c-bb3c-ea3e294215a0",
        "name": "test",
        "key": "k/uAXddaPrK2I/3MSNC6q1TAUaS4juj3oX2v2KO299Gpy8bBrYPjxCnERLSeyrJ4",
        "type": "endpoint",
        "version": "5.0.0",
        "groups": [
          "default",
          "group1",
          "group2"
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}
```

</details>

<details><summary>Assign agent to group</summary>

```console
root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -ks -X PUT "https://localhost:55000/agents/group?agents_list=0a96a0ab-5bef-415c-bb3c-ea3e294215a0&group_id=group3" | jq
{
  "data": {
    "affected_items": [
      "0a96a0ab-5bef-415c-bb3c-ea3e294215a0"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents were assigned to group3",
  "error": 0
}
```

</details>

<details><summary>Get agents in group</summary>

```console
root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -ks https://localhost:55000/groups/group3/agents | jq
{
  "data": {
    "affected_items": [
      {
        "id": "0a96a0ab-5bef-415c-bb3c-ea3e294215a0",
        "name": "test",
        "key": "k/uAXddaPrK2I/3MSNC6q1TAUaS4juj3oX2v2KO299Gpy8bBrYPjxCnERLSeyrJ4",
        "type": "endpoint",
        "version": "5.0.0",
        "groups": [
          "default",
          "group1",
          "group2",
          "group3"
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected groups information was returned",
  "error": 0
}
```

</details>

<details><summary>Remove agent from group</summary>

```console
root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -ks -X DELETE "https://localhost:55000/agents/group?agents_list=0a96a0ab-5bef-415c-bb3c-ea3e294215a0&group_id=group3" | jq
{
  "data": {
    "affected_items": [
      "0a96a0ab-5bef-415c-bb3c-ea3e294215a0"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents were removed from group group3",
  "error": 0
}
```

</details>

<details><summary>Get agents</summary>

```console
root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -ks https://localhost:55000/agents | jq
{
  "data": {
    "affected_items": [
      {
        "id": "0a96a0ab-5bef-415c-bb3c-ea3e294215a0",
        "name": "test",
        "key": "k/uAXddaPrK2I/3MSNC6q1TAUaS4juj3oX2v2KO299Gpy8bBrYPjxCnERLSeyrJ4",
        "type": "endpoint",
        "version": "5.0.0",
        "groups": [
          "default",
          "group1",
          "group2"
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}
```

</details>

<details><summary>Delete a group</summary>

```console
root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -ks -X DELETE "https://localhost:55000/groups?groups_list=group2" | jq
{
  "data": {
    "affected_items": [
      "group2"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected groups were deleted",
  "error": 0
}
```

</details>

<details><summary>Get agents</summary>

```console
root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -ks https://localhost:55000/agents | jq
{
  "data": {
    "affected_items": [
      {
        "id": "0a96a0ab-5bef-415c-bb3c-ea3e294215a0",
        "name": "test",
        "key": "k/uAXddaPrK2I/3MSNC6q1TAUaS4juj3oX2v2KO299Gpy8bBrYPjxCnERLSeyrJ4",
        "type": "endpoint",
        "version": "5.0.0",
        "groups": [
          "default",
          "group1"
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}
```

</details>

<details><summary>Get groups</summary>

```console
root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -ks https://localhost:55000/groups | jq
{
  "data": {
    "affected_items": [
      {
        "name": "group1",
        "configSum": "65e363d76ef3e3b76f87b8eaa24cbff9"
      },
      {
        "name": "group3",
        "configSum": "65e363d76ef3e3b76f87b8eaa24cbff9"
      }
    ],
    "total_affected_items": 2,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected groups information was returned",
  "error": 0
}
```

</details>

<details><summary>Get agent group commands</summary>

> The `agent.groups=groups000` is added by the commands manager. The reason is unknown to me.

```console
gasti@gasti:~/work/wazuh-tools/framework/environments/dev$ curl -X POST -H "Content-Type: application/json" -ku admin:SecretPassword1% http://localhost:9200/.commands/_search?pretty -d'
{
   "query": {
      "match_all": {}
   }
}'
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 4,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : ".commands",
        "_id" : "U4VXMJMB3yN8yd0jCi4u",
        "_score" : 1.0,
        "_source" : {
          "agent" : {
            "groups" : [
              "groups000"
            ]
          },
          "command" : {
            "source" : "Users/Services",
            "user" : "Management API",
            "target" : {
              "type" : "agent",
              "id" : "0a96a0ab-5bef-415c-bb3c-ea3e294215a0"
            },
            "action" : {
              "name" : "update-group",
              "args" : [ ],
              "version" : "5.0.0"
            },
            "timeout" : 100,
            "status" : "PENDING",
            "order_id" : "UoVXMJMB3yN8yd0jCi4t",
            "request_id" : "UYVXMJMB3yN8yd0jCi4t"
          }
        }
      },
      {
        "_index" : ".commands",
        "_id" : "VoVmMJMB3yN8yd0jGy4E",
        "_score" : 1.0,
        "_source" : {
          "agent" : {
            "groups" : [
              "groups000"
            ]
          },
          "command" : {
            "source" : "Users/Services",
            "user" : "Management API",
            "target" : {
              "type" : "agent",
              "id" : "0a96a0ab-5bef-415c-bb3c-ea3e294215a0"
            },
            "action" : {
              "name" : "set-group",
              "args" : [
                "group3"
              ],
              "version" : "5.0.0"
            },
            "timeout" : 100,
            "status" : "PENDING",
            "order_id" : "VYVmMJMB3yN8yd0jGy4E",
            "request_id" : "VIVmMJMB3yN8yd0jGy4E"
          }
        }
      },
      {
        "_index" : ".commands",
        "_id" : "XIVvMJMB3yN8yd0j7S6I",
        "_score" : 1.0,
        "_source" : {
          "agent" : {
            "groups" : [
              "groups000"
            ]
          },
          "command" : {
            "source" : "Users/Services",
            "user" : "Management API",
            "target" : {
              "type" : "agent",
              "id" : "0a96a0ab-5bef-415c-bb3c-ea3e294215a0"
            },
            "action" : {
              "name" : "update-group",
              "args" : [ ],
              "version" : "5.0.0"
            },
            "timeout" : 100,
            "status" : "PENDING",
            "order_id" : "W4VvMJMB3yN8yd0j7S6I",
            "request_id" : "WoVvMJMB3yN8yd0j7S6I"
          }
        }
      },
      {
        "_index" : ".commands",
        "_id" : "ZYWAMJMB3yN8yd0j0S6G",
        "_score" : 1.0,
        "_source" : {
          "agent" : {
            "groups" : [
              "groups000"
            ]
          },
          "command" : {
            "source" : "Users/Services",
            "user" : "Management API",
            "target" : {
              "type" : "agent",
              "id" : "0a96a0ab-5bef-415c-bb3c-ea3e294215a0"
            },
            "action" : {
              "name" : "update-group",
              "args" : [ ],
              "version" : "5.0.0"
            },
            "timeout" : 100,
            "status" : "PENDING",
            "order_id" : "ZIWAMJMB3yN8yd0j0S6G",
            "request_id" : "Y4WAMJMB3yN8yd0j0S6G"
          }
        }
      }
    ]
  }
}
```

</details>

<details><summary>Assing agent to group forcing single group</summary>

```console
root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -ks -X PUT "https://localhost:55000/agents/group?agents_list=0a96a0ab-5bef-415c-bb3c-ea3e294215a0&group_id=group3&force_single_group=true" | jq
{
  "data": {
    "affected_items": [
      "0a96a0ab-5bef-415c-bb3c-ea3e294215a0"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents were assigned to group3 and removed from the other groups",
  "error": 0
}
```

</details>

<details><summary>Get agents</summary>

```console
root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -ks https://localhost:55000/agents | jq
{
  "data": {
    "affected_items": [
      {
        "id": "0a96a0ab-5bef-415c-bb3c-ea3e294215a0",
        "name": "test",
        "key": "k/uAXddaPrK2I/3MSNC6q1TAUaS4juj3oX2v2KO299Gpy8bBrYPjxCnERLSeyrJ4",
        "type": "endpoint",
        "version": "5.0.0",
        "groups": [
          "group3"
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}
```

</details>

<details><summary>Try to create an agent with a group that doesn't exist</summary>

```console
root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -X POST -ks https://localhost:55000/agents -d '
{
  "id": "1e80ccba-dfe0-44ea-bbfb-b2e59181960b",
  "name": "test2",
  "key": "7b8276c3bf96aff5709346d368f04fed",
  "type": "endpoint",
  "version": "5.0.0",
  "groups": ["group1", "group2"]
}
' | jq
{
  "title": "Bad Request",
  "detail": "The group does not exist: group2",
  "remediation": "Please, use `GET /agents/groups` to find all available groups",
  "dapi_errors": {
    "master": {
      "error": "The group does not exist: group2"
    }
  },
  "error": 1710
}
```

</details>

<details><summary>Try to assign an agent to a group that it already belongs to</summary>

```console
root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -ks -X PUT "https://localhost:55000/agents/group?agents_list=0a96a0ab-5bef-415c-bb3c-ea3e294215a0&group_id=group3" | jq
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 1,
    "failed_items": [
      {
        "error": {
          "code": 1766,
          "message": "The agent already belongs to the group"
        },
        "id": [
          "0a96a0ab-5bef-415c-bb3c-ea3e294215a0"
        ]
      }
    ]
  },
  "message": "No agents were assigned to group3",
  "error": 1
}
```

</details>

> [!Note]
> Unit tests are expected to fail and will be fixed in https://github.com/wazuh/wazuh/issues/26725.

### CODE REVIEW

**Review by nico-stefani — APPROVED** [review]
LGTM. I leave a nonblocking comment, Can we mark the tests as xfail?

**Comment by GGP1** [comment]
> LGTM. I leave a nonblocking comment, Could you mark the tests as xfail?

The tests failures were introduced in https://github.com/wazuh/wazuh/pull/26645 and are not related to these changes. Furthermore, the tests fail at the file level, so marking them as xfail is not possible.

Considering this has a high impact because it affects all master developents, I think the issue where this will be fixed (https://github.com/wazuh/wazuh/issues/26725) should be prioritized and therefore it doesn't make much sense to comment them just for a few days.

**Comment by GGP1** [comment]
> LGTM. I leave a nonblocking comment, Could you mark the tests as xfail?

The tests failures were introduced in https://github.com/wazuh/wazuh/pull/26645 and are not related to these changes. Furthermore, the tests fail at the file level, so marking them as xfail doesn't fix the issue.

Considering this has a high impact because it affects all master developents, I think the issue where this will be fixed (https://github.com/wazuh/wazuh/issues/26725) should be prioritized and therefore it doesn't make much sense to comment them just for a few days.

**Review by fdalmaup — APPROVED** [review]
LGTM

**Pull request merged**
