### PR TITLE
Add except to adapt path in System32 and SysWOW64.

### PR DESCRIPTION
**Pull request by FernandoCP**
|Related issue|
|---|
|#3739|

## Description

The bug is caused by the fact that the %windir%\System32 directory is reserved for 64-bit applications on 64-bit Windows and sysWOW64 hides this difference by using a file system redirector. But there are some exceptions that are not affected by this redirection system.

The list of exceptions of directories that don't follow the rule and it's this:

- %windir%\system32\catroot
- %windir%\system32\catroot2
- %windir%\system32\driverstore
- %windir%\system32\drivers\etc
- %windir%\system32\logfiles
- %windir%\system32\spool
- %windir%\system32\driverstore (Only in Windows Server 2008, Windows Vista, Windows Server 2003 and Windows XP)

This has been fixed by adding the exceptions and the necessary to make it work.

## Logs/Alerts example

**Example alert in System32 exception**
```
** Alert 1585909378.90640: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Apr 03 10:22:58 (WIN-BKBL07SR68H) 192.168.33.1->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File 'c:\windows\system32\driverstore\new text document.txt' added
Mode: whodata

Attributes:
 - Size: 0
 - Permissions: Everyone (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, ALL APPLICATION PACKAGES (allowed): read_control|synchronize|read_data|read_ea|execute|read_attributes, SYSTEM (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes
 - Date: Fri Apr  3 10:22:56 2020
 - User: Administrators (S-1-5-32-544)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - File attributes: ARCHIVE
 - (Audit) User name: Adminis trator
 - (Audit) Process id: 1644
 - (Audit) Process name: C:\Windows\explorer.exe
```

**Example alert in sysWOW64**
```
** Alert 1585909577.97274: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Apr 03 10:26:17 (WIN-BKBL07SR68H) 192.168.33.1->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File 'c:\windows\system32\en\new rich text document.rtf' added
Mode: whodata

Attributes:
 - Size: 7
 - Permissions: SYSTEM (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, Administrators (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, Users (allowed): read_control|synchronize|read_data|read_ea|execute|read_attributes, ALL APPLICATION PACKAGES (allowed): read_control|synchronize|read_data|read_ea|execute|read_attributes
 - Date: Fri Apr  3 10:26:16 2020
 - User: Administrators (S-1-5-32-544)
 - MD5: 8274425de767b30b2fff1124ab54abb5
 - SHA1: 2201589aa3ed709b3665e4ff979e10c6ad5137fc
 - SHA256: 0d6afb7e939f0936f40afdc759b5a354ea5427ec250a47e7b904ab1ea800a01d
 - File attributes: ARCHIVE
 - (Audit) User name: Adminis trator
 - (Audit) Process id: 1644
 - (Audit) Process name: C:\Windows\explorer.exe
```

**Example alert in System32**
```
** Alert 1585909681.100465: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Apr 03 10:28:01 (WIN-BKBL07SR68H) 192.168.33.1->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File 'c:\windows\sysnative\en\new rich text document.rtf' added
Mode: whodata

Attributes:
 - Size: 7
 - Permissions: SYSTEM (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, Administrators (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, Users (allowed): read_control|synchronize|read_data|read_ea|execute|read_attributes, ALL APPLICATION PACKAGES (allowed): read_control|synchronize|read_data|read_ea|execute|read_attributes
 - Date: Fri Apr  3 10:28:00 2020
 - User: Administrators (S-1-5-32-544)
 - MD5: 8274425de767b30b2fff1124ab54abb5
 - SHA1: 2201589aa3ed709b3665e4ff979e10c6ad5137fc
 - SHA256: 0d6afb7e939f0936f40afdc759b5a354ea5427ec250a47e7b904ab1ea800a01d
 - File attributes: ARCHIVE
 - (Audit) User name: Adminis trator
 - (Audit) Process id: 1644
 - (Audit) Process name: C:\Windows\explorer.exe
```

## Tests

- Compilation without warnings in every supported platform
  - [X] Windows
- [X] Source installation
- [X] Source upgrade

- Memory tests for Windows
  - [x] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory

- [X] Added unit tests (for new features)

### CODE REVIEW

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 21bf898b7e1d8fa4a51f01f38f0a2df175796174
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2060/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2060/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2060/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2060.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2060/Analysis_dynamic_valgrind-v3.13.0-B2060.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 21bf898b7e1d8fa4a51f01f38f0a2df175796174
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2061/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2061/ossec.log)
**Coverage:** 

```json
Lines executed:26.77% of 3186

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2061/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2061.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2061/Analysis_dynamic_valgrind-v3.13.0-B2061.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 2f130e5a1b7b2b9741cca1cc0886c666c49abdf0
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2383/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2383/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2383/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2383.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2383/Analysis_dynamic_valgrind-v3.13.0-B2383.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 2f130e5a1b7b2b9741cca1cc0886c666c49abdf0
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2384/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2384/ossec.log)
**Coverage:** 

```json
Lines executed:26.92% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2384/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2384.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2384/Analysis_dynamic_valgrind-v3.13.0-B2384.log)

**Comment by okynos** [comment]
@wazuhci run integration fim fim-non-scheduled ubuntu,centos agent_test 0

**Comment by okynos** [comment]
@wazuhci run integration fim fim-non-scheduled ubuntu,centos agent_test 0

**Comment by wazuhci-staging** [comment]
Check out integration results at [Jenkins-B106](https://jenkins-staging.wazuh.info/job/Test_integration/106/)

**Comment by wazuhci-staging** [comment]
Check out integration results at [Jenkins-B107](https://jenkins-staging.wazuh.info/job/Test_integration/107/)

**Comment by okynos** [comment]
@wazuhci run integration fim fim-non-scheduled ubuntu,centos agent_test 0

**Comment by wazuhci** [comment]
Check out integration results at [Jenkins-B212](https://jenkins-production.wazuh.info/job/test_integration/212/)

**Comment by chemamartinez** [comment]
This pull request is outdated. The fix will be addressed at https://github.com/wazuh/wazuh/issues/14796.

**Pull request closed without merging**
