### PR TITLE
Add configuration on demand for file_limit

### LINKED ISSUE #5111: Add file_limit option to configuration on demand
| Wazuh version | Component | Install type | Install method | Platform |
|---|---|---|---|---|
| 3.13 | ossec-syscheckd | Manager/Agent | Packages/Sources | n/a |

## Description

The `file_limit` option needs to be added to the configuration on demand. It was added here:
https://github.com/wazuh/wazuh/blob/f97e6eb4a99ebbbb3d6c70a9f90047832298b15b/src/syscheckd/config.c#L173
But after changing the format of the configuration, the change wasn't added to the on demand configuration.
This is the format of the configuration:
```xml
<!-- Maximum number of files to be monitored -->
<file_limit>
  <enabled>yes</enabled>
  <entries>100000</entries>
</file_limit>
```

### PR DESCRIPTION
**Pull request by jesusjimsa**
| Related issue  |
|---------------|
| #5111               |

## Description

This pull request adds the changes in the file_limit configuration to the configuration on demand.

Closes #5111.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [x] MAC OS X
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [x] Package upgrade
- [x] Review logs syntax and correct language
- [x] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Valgrind (memcheck and descriptor leaks check)

- [x] Configuration on demand reports new parameters
- [x] The data flow works as expected (agent-manager-api-app)
- [x] Added unit tests (for new features)

### CODE REVIEW

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 511c6eb9173bc1c20e880179c735db78ebd03cba
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2275/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2275/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2275/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2275.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2275/Analysis_dynamic_valgrind-v3.13.0-B2275.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 511c6eb9173bc1c20e880179c735db78ebd03cba
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2276/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2276/ossec.log)
**Coverage:** 

```json
Lines executed:26.92% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2276/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2276.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2276/Analysis_dynamic_valgrind-v3.13.0-B2276.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 43ec7f4927b25de7ae6fac0a6f9b101e2a87806c
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2277/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2277/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2277/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2277.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2277/Analysis_dynamic_valgrind-v3.13.0-B2277.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 43ec7f4927b25de7ae6fac0a6f9b101e2a87806c
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2278/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2278/ossec.log)
**Coverage:** 

```json
Lines executed:26.92% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2278/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2278.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2278/Analysis_dynamic_valgrind-v3.13.0-B2278.log)

**Comment by jesusjimsa** [comment]
Integration tests for tier 0 passed:
```
169 passed, 3749 skipped, 5 xfailed in 883.75s (0:14:43)
```

Integration tests for test_file_limit passed:
```
24 passed in 195.39s (0:03:15)
```

**Comment by jesusjimsa** [comment]
On demand configuration working:
```json
"file_limit": {
    "enabled": "yes",
    "entries": 10
},
```

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 6ec61dc656107bcf8a7fcdf9c9b57f969fac6270
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2285/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2285/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2285/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2285.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2285/Analysis_dynamic_valgrind-v3.13.0-B2285.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 6ec61dc656107bcf8a7fcdf9c9b57f969fac6270
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2286/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2286/ossec.log)
**Coverage:** 

```json
Lines executed:26.92% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2286/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2286.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2286/Analysis_dynamic_valgrind-v3.13.0-B2286.log)

**Comment by jesusjimsa** [comment]
## Unit tests (cmocka) results
### Agent
```
Test project /home/vagrant/wazuh/src/unit_tests/build
      Start  1: test_syscom
 1/18 Test  #1: test_syscom ......................   Passed    0.00 sec
      Start  2: test_create_db
 2/18 Test  #2: test_create_db ...................   Passed    0.01 sec
      Start  3: test_syscheck_audit
 3/18 Test  #3: test_syscheck_audit ..............   Passed    0.01 sec
      Start  4: test_seechanges
 4/18 Test  #4: test_seechanges ..................   Passed    0.01 sec
      Start  5: test_run_realtime
 5/18 Test  #5: test_run_realtime ................   Passed    0.01 sec
      Start  6: test_syscheck_config
 6/18 Test  #6: test_syscheck_config .............   Passed    0.01 sec
      Start  7: test_syscheck
 7/18 Test  #7: test_syscheck ....................   Passed    0.00 sec
      Start  8: test_fim_sync
 8/18 Test  #8: test_fim_sync ....................   Passed    0.01 sec
      Start  9: test_run_check
 9/18 Test  #9: test_run_check ...................   Passed    0.01 sec
      Start 10: test_fim_db
10/18 Test #10: test_fim_db ......................   Passed    0.01 sec
      Start 11: test_file_op
11/18 Test #11: test_file_op .....................   Passed    0.00 sec
      Start 12: test_integrity_op
12/18 Test #12: test_integrity_op ................   Passed    0.00 sec
      Start 13: test_rbtree_op
13/18 Test #13: test_rbtree_op ...................   Passed    0.01 sec
      Start 14: test_string_op
14/18 Test #14: test_string_op ...................   Passed    0.00 sec
      Start 15: test_version_op
15/18 Test #15: test_version_op ..................   Passed    0.00 sec
      Start 16: test_syscheck_op
16/18 Test #16: test_syscheck_op .................   Passed    0.00 sec
      Start 17: test_audit_op
17/18 Test #17: test_audit_op ....................   Passed    0.00 sec
      Start 18: test_privsep_op
18/18 Test #18: test_privsep_op ..................   Passed    0.00 sec

100% tests passed, 0 tests failed out of 18
```

### Server
```
Test project /home/vagrant/wazuh/src/unit_tests/build
      Start  1: test_analysisd_syscheck
 1/41 Test  #1: test_analysisd_syscheck ..........   Passed    0.03 sec
      Start  2: test_dbsync
 2/41 Test  #2: test_dbsync ......................   Passed    0.02 sec
      Start  3: test_mitre
 3/41 Test  #3: test_mitre .......................   Passed    0.01 sec
      Start  4: test_same_different_loop
 4/41 Test  #4: test_same_different_loop .........   Passed    0.01 sec
      Start  5: test_file_op
 5/41 Test  #5: test_file_op .....................   Passed    0.01 sec
      Start  6: test_integrity_op
 6/41 Test  #6: test_integrity_op ................   Passed    0.01 sec
      Start  7: test_rbtree_op
 7/41 Test  #7: test_rbtree_op ...................   Passed    0.01 sec
      Start  8: test_string_op
 8/41 Test  #8: test_string_op ...................   Passed    0.01 sec
      Start  9: test_version_op
 9/41 Test  #9: test_version_op ..................   Passed    0.01 sec
      Start 10: test_bzip2_op
10/41 Test #10: test_bzip2_op ....................   Passed    0.00 sec
      Start 11: test_syscheck_op
11/41 Test #11: test_syscheck_op .................   Passed    0.01 sec
      Start 12: test_audit_op
12/41 Test #12: test_audit_op ....................   Passed    0.01 sec
      Start 13: test_privsep_op
13/41 Test #13: test_privsep_op ..................   Passed    0.01 sec
      Start 14: test_syscom
14/41 Test #14: test_syscom ......................   Passed    0.00 sec
      Start 15: test_create_db
15/41 Test #15: test_create_db ...................   Passed    0.01 sec
      Start 16: test_syscheck_audit
16/41 Test #16: test_syscheck_audit ..............   Passed    0.01 sec
      Start 17: test_seechanges
17/41 Test #17: test_seechanges ..................   Passed    0.01 sec
      Start 18: test_run_realtime
18/41 Test #18: test_run_realtime ................   Passed    0.01 sec
      Start 19: test_syscheck_config
19/41 Test #19: test_syscheck_config .............   Passed    0.01 sec
      Start 20: test_syscheck
20/41 Test #20: test_syscheck ....................   Passed    0.00 sec
      Start 21: test_fim_sync
21/41 Test #21: test_fim_sync ....................   Passed    0.01 sec
      Start 22: test_run_check
22/41 Test #22: test_run_check ...................   Passed    0.01 sec
      Start 23: test_fim_db
23/41 Test #23: test_fim_db ......................   Passed    0.01 sec
      Start 24: test_wdb_integrity
24/41 Test #24: test_wdb_integrity ...............   Passed    0.00 sec
      Start 25: test_wdb_fim
25/41 Test #25: test_wdb_fim .....................   Passed    0.01 sec
      Start 26: test_wdb_parser
26/41 Test #26: test_wdb_parser ..................   Passed    0.01 sec
      Start 27: test_wm_gcp
27/41 Test #27: test_wm_gcp ......................   Passed    0.00 sec
      Start 28: test_wmodules_gcp
28/41 Test #28: test_wmodules_gcp ................   Passed    0.01 sec
      Start 29: test_wmodules_scheduling
29/41 Test #29: test_wmodules_scheduling .........   Passed    0.01 sec
      Start 30: test_aws_scheduling
30/41 Test #30: test_aws_scheduling ..............   Passed    0.01 sec
      Start 31: test_azure_scheduling
31/41 Test #31: test_azure_scheduling ............   Passed    0.01 sec
      Start 32: test_ciscat_scheduling
32/41 Test #32: test_ciscat_scheduling ...........   Passed    0.01 sec
      Start 33: test_command_scheduling
33/41 Test #33: test_command_scheduling ..........   Passed    0.03 sec
      Start 34: test_docker_scheduling
34/41 Test #34: test_docker_scheduling ...........   Passed    0.01 sec
      Start 35: test_gcp_scheduling
35/41 Test #35: test_gcp_scheduling ..............   Passed    0.01 sec
      Start 36: test_oscap_scheduling
36/41 Test #36: test_oscap_scheduling ............   Passed    0.01 sec
      Start 37: test_sca_scheduling
37/41 Test #37: test_sca_scheduling ..............   Passed    0.01 sec
      Start 38: test_schedule_scan
38/41 Test #38: test_schedule_scan ...............   Passed    0.01 sec
      Start 39: test_wm_vuln_detector
39/41 Test #39: test_wm_vuln_detector ............   Passed    0.01 sec
      Start 40: test_wm_vuln_detector_evr
40/41 Test #40: test_wm_vuln_detector_evr ........   Passed    0.00 sec
      Start 41: test_wm_vuln_detector_nvd
41/41 Test #41: test_wm_vuln_detector_nvd ........   Passed    0.01 sec

100% tests passed, 0 tests failed out of 41

Total Test time (real) =   0.39 sec
```

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 6ec61dc656107bcf8a7fcdf9c9b57f969fac6270
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2287/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2287/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2287/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2287.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2287/Analysis_dynamic_valgrind-v3.13.0-B2287.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 6ec61dc656107bcf8a7fcdf9c9b57f969fac6270
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2288/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2288/ossec.log)
**Coverage:** 

```json
Lines executed:26.89% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2288/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2288.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2288/Analysis_dynamic_valgrind-v3.13.0-B2288.log)

**Comment by jesusjimsa** [comment]
## Integration tests results
* [macOS](https://github.com/wazuh/wazuh/files/4695943/agent_macos_html_report_test_integration_B196_20200528133549.zip)
* [Solaris](https://github.com/wazuh/wazuh/files/4695946/agent_solaris_html_report_test_integration_B196_20200528133549.zip)
* [CentOS](https://github.com/wazuh/wazuh/files/4696388/agent_centos_html_report_test_integration_B194_20200528132646.zip)
* [Ubuntu](https://github.com/wazuh/wazuh/files/4696411/agent_ubuntu_html_report_test_integration_B194_20200528132646.zip)
* [Windows](https://github.com/wazuh/wazuh/files/4696413/agent_windows_html_report_test_integration_B194_20200528132646.zip) (There are two failed tests, `multiple_entries` and `synchronize_integrity_scan`, that need to be investigated).

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 65cfdd491a8f7e777295c149e4cb246a4eb64555
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2353/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2353/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2353/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2353.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2353/Analysis_dynamic_valgrind-v3.13.0-B2353.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 65cfdd491a8f7e777295c149e4cb246a4eb64555
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2354/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2354/ossec.log)
**Coverage:** 

```json
Lines executed:26.92% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2354/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2354.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2354/Analysis_dynamic_valgrind-v3.13.0-B2354.log)

**Pull request merged**
