### PR TITLE
FIM v2.0: Update inode_id when inode changes

### LINKED ISSUE #4629: FIM v2.0: inode_id is not updated when inode changes
| Wazuh version | Component         | Install type         | Install method        | Platform  |
|----------------|-----------------|-----------------|--------------------|----------|
| 3.12                   | ossec-syscheck | Manager/Agent  | Packages/Sources | Unix         |

## Bug description

When the inode of a file is modified, the `inode_id` of the `entry_path` table is not updated, while the inode of the `entry_data` table does get updated, causing the tables to unbalance and send `added` alerts instead of `modify` alerts.

## Remediation

Update the `inode_id` of the `entry_path` table when the inode of a file gets changed.

### PR DESCRIPTION
**Pull request by jesusjimsa**
| Related issue  |
|---------------|
| #4629             |

## Description

When the inode of a file is modified, the `inode_id` of the `entry_path` table is not updated, while the inode of the `entry_data` table does get updated, causing the tables to unbalance and send `added` alerts instead of `modify` alerts.  

To solve this, this Pull Request updates the `inode_id` of the `entry_path` table when the inode of a file gets changed.

Also, I have updated the `fim_db_insert` function to delete and re-insert the `entry_data` info only when the inode changes.

Closes #4629. 

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [x] MAC OS X
- [x] Source installation
- [ ] Package installation
- [x] Source upgrade
- [ ] Package upgrade
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [x] Scan-build report
  - [ ] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

### CODE REVIEW

**Comment by wazuhci** [comment]
The stress test has been launched. The charts will be posted when they are ready.
I will use the following configuration:
### General
- Commit: e56ca16
- Packages: 
  - [manager 3.12.0 0.branch4629updateinodeidinentrypath.commite56ca16 rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-manager-3.12.0-0.branch4629updateinodeidinentrypath.commite56ca16.x86_64.rpm)
  - [agent 3.12.0 0.branch4629updateinodeidinentrypath.commite56ca16 rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-agent-3.12.0-0.branch4629updateinodeidinentrypath.commite56ca16.x86_64.rpm)
  - [manager 3.12.0 0.branch4629updateinodeidinentrypath.commite56ca16 deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-manager_3.12.0-0.branch4629updateinodeidinentrypath.commite56ca16_amd64.deb)
  - [agent 3.12.0 0.branch4629updateinodeidinentrypath.commite56ca16 deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-agent_3.12.0-0.branch4629updateinodeidinentrypath.commite56ca16_amd64.deb)
  - [agent 3.12.0 0.branch4629updateinodeidinentrypath.commite56ca16 msi](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/windows/wazuh-agent-3.12.0-0.branch4629updateinodeidinentrypath.commite56ca16.msi)

### Stress test parameters:
- Manager system: `centos`
- Launch CentOS agent: `true`
- Launch Ubuntu agent: `true`
- Launch Windows agent: `true`
- Test duration: `60`
- Scan frequency: `10`
- Modules to test: 
  - logcollector: `true`
  - syscheck: `true`
  - rootcheck: `true`
  - sca: `true`
  - osquery: `true`
  - syscollector: `true`
  - active-response: `true`
  - azure-logs: `true`
  - cis-cat: `true`
  - docker-listener: `true`
  - open-scap: `true`
  - vulnerability-detector: `false`
- FIM special test: `None`
- FIM sleep: `300`
- FIM max files: `25000`
- SCA sleep: `30`
- SCA max registers: `5000`
- Docker image name: `hello-world`
- Docker sleep: `5`
- Docker jobs: `10`
- Logcollector special test: `None`
- Logcollector max files: `50000`
- Logcollector creation sleep: `300`
- Logcollector write files: `1000`
- Logcollector write sleep: `10`
- Vuln sleep: `60`
- Authd port: `1515`
- Syscollector package: `imagemagick.app`
- Syscollector package version: `7.0.8.48`

Regards!.

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** e56ca16aba55e51b9cf0d18f07efdc87cbc096cc
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Coverage:** 

```json
Lines executed:30.68% of 1832

```
**Coverage report detail:** [here](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B255/coverage-report-detail)
## Valgrind result:
```
==15394== Memcheck, a memory error detector
==15394== Copyright (C) 2002-2017, and GNU GPLd, by Julian Seward et al.
==15394== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==15394== Command: /var/ossec/bin/ossec-logcollector -f
==15394== Parent PID: 1
==15394== 
==15394== 
==15394== FILE DESCRIPTORS: 17 open at exit.
==15394== Open file descriptor 15: /var/log/duplicated_file.log
==15394==    at 0x621FD19: open (open64.c:47)
==15394==    by 0x619C589: _IO_file_open (fileops.c:189)
==15394==    by 0x619C589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15394==    by 0x618EEA9: __fopen_internal (iofopen.c:78)
==15394==    by 0x618EEA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15394==    by 0x176807: reload_file (logcollector.c:903)
==15394==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15394==    by 0x17248A: main (main.c:187)
==15394== 
==15394== Open file descriptor 14: /var/log/target_file.log
==15394==    at 0x621FD19: open (open64.c:47)
==15394==    by 0x619C589: _IO_file_open (fileops.c:189)
==15394==    by 0x619C589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15394==    by 0x618EEA9: __fopen_internal (iofopen.c:78)
==15394==    by 0x618EEA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15394==    by 0x176807: reload_file (logcollector.c:903)
==15394==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15394==    by 0x17248A: main (main.c:187)
==15394== 
==15394== Open file descriptor 13: /var/log/label_file.log
==15394==    at 0x621FD19: open (open64.c:47)
==15394==    by 0x619C589: _IO_file_open (fileops.c:189)
==15394==    by 0x619C589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15394==    by 0x618EEA9: __fopen_internal (iofopen.c:78)
==15394==    by 0x618EEA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15394==    by 0x176807: reload_file (logcollector.c:903)
==15394==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15394==    by 0x17248A: main (main.c:187)
==15394== 
==15394== Open file descriptor 12: /var/log/json_file.log
==15394==    at 0x621FD19: open (open64.c:47)
==15394==    by 0x619C589: _IO_file_open (fileops.c:189)
==15394==    by 0x619C589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15394==    by 0x618EEA9: __fopen_internal (iofopen.c:78)
==15394==    by 0x618EEA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15394==    by 0x176807: reload_file (logcollector.c:903)
==15394==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15394==    by 0x17248A: main (main.c:187)
==15394== 
==15394== Open file descriptor 11: /var/log/alias_file.log
==15394==    at 0x621FD19: open (open64.c:47)
==15394==    by 0x619C589: _IO_file_open (fileops.c:189)
==15394==    by 0x619C589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15394==    by 0x618EEA9: __fopen_internal (iofopen.c:78)
==15394==    by 0x618EEA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15394==    by 0x176807: reload_file (logcollector.c:903)
==15394==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15394==    by 0x17248A: main (main.c:187)
==15394== 
==15394== Open file descriptor 10: /var/log/database_file.log-20-02-20.log
==15394==    at 0x621FD19: open (open64.c:47)
==15394==    by 0x619C589: _IO_file_open (fileops.c:189)
==15394==    by 0x619C589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15394==    by 0x618EEA9: __fopen_internal (iofopen.c:78)
==15394==    by 0x618EEA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15394==    by 0x176807: reload_file (logcollector.c:903)
==15394==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15394==    by 0x17248A: main (main.c:187)
==15394== 
==15394== Open file descriptor 9: /var/log/remove_file.log
==15394==    at 0x621FD19: open (open64.c:47)
==15394==    by 0x619C589: _IO_file_open (fileops.c:189)
==15394==    by 0x619C589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15394==    by 0x618EEA9: __fopen_internal (iofopen.c:78)
==15394==    by 0x618EEA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15394==    by 0x176807: reload_file (logcollector.c:903)
==15394==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15394==    by 0x17248A: main (main.c:187)
==15394== 
==15394== Open file descriptor 8: /var/log/single_file.log
==15394==    at 0x621FD19: open (open64.c:47)
==15394==    by 0x619C589: _IO_file_open (fileops.c:189)
==15394==    by 0x619C589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15394==    by 0x618EEA9: __fopen_internal (iofopen.c:78)
==15394==    by 0x618EEA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15394==    by 0x176807: reload_file (logcollector.c:903)
==15394==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15394==    by 0x17248A: main (main.c:187)
==15394== 
==15394== Open file descriptor 7: /var/log/dpkg.log
==15394==    at 0x621FD19: open (open64.c:47)
==15394==    by 0x619C589: _IO_file_open (fileops.c:189)
==15394==    by 0x619C589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15394==    by 0x618EEA9: __fopen_internal (iofopen.c:78)
==15394==    by 0x618EEA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15394==    by 0x176807: reload_file (logcollector.c:903)
==15394==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15394==    by 0x17248A: main (main.c:187)
==15394== 
==15394== Open file descriptor 6: /var/ossec/logs/active-responses.log
==15394==    at 0x621FD19: open (open64.c:47)
==15394==    by 0x619C589: _IO_file_open (fileops.c:189)
==15394==    by 0x619C589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15394==    by 0x618EEA9: __fopen_internal (iofopen.c:78)
==15394==    by 0x618EEA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15394==    by 0x176807: reload_file (logcollector.c:903)
==15394==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15394==    by 0x17248A: main (main.c:187)
==15394== 
==15394== Open AF_UNIX socket 16: /var/ossec/queue/ossec/logcollector
==15394==    at 0x6232EC7: socket (syscall-template.S:78)
==15394==    by 0x25735C: OS_BindUnixDomain (os_net.c:153)
==15394==    by 0x16F5A4: lccom_main (lccom.c:102)
==15394==    by 0x5EF86DA: start_thread (pthread_create.c:463)
==15394==    by 0x623188E: clone (clone.S:95)
==15394== 
==15394== Open AF_UNIX socket 5: <unknown>
==15394==    at 0x6232EC7: socket (syscall-template.S:78)
==15394==    by 0x257623: OS_ConnectUnixDomain (os_net.c:203)
==15394==    by 0x248F78: StartMQ (mq_op.c:36)
==15394==    by 0x172438: main (main.c:182)
==15394== 
==15394== Open file descriptor 4: /dev/urandom
==15394==    at 0x5F02D2B: open (open64.c:47)
==15394==    by 0x253788: randombytes (randombytes.c:62)
==15394==    by 0x2538BA: srandom_init (randombytes.c:82)
==15394==    by 0x171DC6: main (main.c:60)
==15394== 
==15394== Open file descriptor 3: /tmp/dest/Analysis_dynamic_valgrind-v3.12.0-4635.log
==15394==    <inherited from parent>
==15394== 
==15394== Open file descriptor 2:
==15394==    <inherited from parent>
==15394== 
==15394== Open file descriptor 1:
==15394==    <inherited from parent>
==15394== 
==15394== Open file descriptor 0: /dev/null
==15394==    <inherited from parent>
==15394== 
==15394== 
==15394== HEAP SUMMARY:
==15394==     in use at exit: 32,463 bytes in 132 blocks
==15394==   total heap usage: 7,825 allocs, 7,693 frees, 4,603,437 bytes allocated
==15394== 
==15394== LEAK SUMMARY:
==15394==    definitely lost: 0 bytes in 0 blocks
==15394==    indirectly lost: 0 bytes in 0 blocks
==15394==      possibly lost: 1,904 bytes in 7 blocks
==15394==    still reachable: 30,559 bytes in 125 blocks
==15394==         suppressed: 0 bytes in 0 blocks
==15394== Reachable blocks (those to which a pointer was found) are not shown.
==15394== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==15394== 
==15394== For counts of detected and suppressed errors, rerun with: -v
==15394== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)

```

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** e56ca16aba55e51b9cf0d18f07efdc87cbc096cc
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Coverage:** 

```json
Lines executed:26.48% of 2949

```
**Coverage report detail:** [here](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B254/coverage-report-detail)
## Valgrind result:
```
==2321== Memcheck, a memory error detector
==2321== Copyright (C) 2002-2017, and GNU GPLd, by Julian Seward et al.
==2321== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==2321== Command: /var/ossec/bin/ossec-syscheckd -f
==2321== Parent PID: 16024
==2321== 
==2321== 
==2321== FILE DESCRIPTORS: 11 open at exit.
==2321== Open file descriptor 12: /bin/loadkeys
==2321==    at 0x5F07DAE: open (open64.c:47)
==2321==    by 0x1A0088: read_sys_file (check_rc_sys.c:75)
==2321==    by 0x1A09FC: read_sys_dir (check_rc_sys.c:284)
==2321==    by 0x1A0EFC: check_rc_sys (check_rc_sys.c:392)
==2321==    by 0x197725: run_rk_check (run_rk_check.c:239)
==2321==    by 0x197B50: w_rootcheck_thread (run_rk_check.c:317)
==2321==    by 0x5EFD6DA: start_thread (pthread_create.c:463)
==2321==    by 0x623688E: clone (clone.S:95)
==2321== 
==2321== Open file descriptor 9: /bin
==2321==    at 0x6224DB1: __open_nocancel (open64.c:69)
==2321==    by 0x61F4952: opendir (opendir.c:190)
==2321==    by 0x1A0674: read_sys_dir (check_rc_sys.c:211)
==2321==    by 0x1A0EFC: check_rc_sys (check_rc_sys.c:392)
==2321==    by 0x197725: run_rk_check (run_rk_check.c:239)
==2321==    by 0x197B50: w_rootcheck_thread (run_rk_check.c:317)
==2321==    by 0x5EFD6DA: start_thread (pthread_create.c:463)
==2321==    by 0x623688E: clone (clone.S:95)
==2321== 
==2321== Open file descriptor 10: /dev/urandom
==2321==    at 0x5F07DAE: open (open64.c:47)
==2321==    by 0x27B1E6: randombytes (randombytes.c:62)
==2321==    by 0x27B37C: os_random (randombytes.c:88)
==2321==    by 0x2730EF: OSHash_Create (hash_op.c:54)
==2321==    by 0x17871B: realtime_start (run_realtime.c:35)
==2321==    by 0x1789BB: realtime_adddir (run_realtime.c:67)
==2321==    by 0x179845: fim_scan (create_db.c:59)
==2321==    by 0x17E279: start_daemon (run_check.c:165)
==2321==    by 0x185B22: main (main.c:269)
==2321== 
==2321== Open file descriptor 7: /var/ossec/queue/fim/db/fim.db
==2321==    at 0x5F07DAE: open (open64.c:47)
==2321==    by 0x53943A6: posixOpen (sqlite3.c:30223)
==2321==    by 0x5394819: robust_open (sqlite3.c:30516)
==2321==    by 0x5399B83: unixOpen (sqlite3.c:35680)
==2321==    by 0x53892C1: sqlite3OsOpen (sqlite3.c:20291)
==2321==    by 0x53A4FDE: sqlite3PagerOpen (sqlite3.c:51704)
==2321==    by 0x53B2A98: sqlite3BtreeOpen (sqlite3.c:61370)
==2321==    by 0x545F147: openDatabase (sqlite3.c:143418)
==2321==    by 0x545F50B: sqlite3_open_v2 (sqlite3.c:143595)
==2321==    by 0x18EC5D: fim_db_init (fim_db.c:253)
==2321==    by 0x18046A: fim_initialize (syscheck.c:84)
==2321==    by 0x1859B1: main (main.c:245)
==2321== 
==2321== Open AF_UNIX socket 6: <unknown>
==2321==    at 0x6237EC7: socket (syscall-template.S:78)
==2321==    by 0x27FB4B: OS_ConnectUnixDomain (os_net.c:203)
==2321==    by 0x272017: StartMQ (mq_op.c:36)
==2321==    by 0x1852C2: main (main.c:177)
==2321== 
==2321== Open AF_UNIX socket 5: /var/ossec/queue/ossec/syscheck
==2321==    at 0x6237EC7: socket (syscall-template.S:78)
==2321==    by 0x27F884: OS_BindUnixDomain (os_net.c:153)
==2321==    by 0x184131: syscom_main (syscom.c:125)
==2321==    by 0x5EFD6DA: start_thread (pthread_create.c:463)
==2321==    by 0x623688E: clone (clone.S:95)
==2321== 
==2321== Open AF_UNIX socket 4: <unknown>
==2321==    at 0x6237EC7: socket (syscall-template.S:78)
==2321==    by 0x27FB4B: OS_ConnectUnixDomain (os_net.c:203)
==2321==    by 0x272017: StartMQ (mq_op.c:36)
==2321==    by 0x196977: rootcheck_connect (rootcheck.c:249)
==2321==    by 0x1852A8: main (main.c:173)
==2321== 
==2321== Open file descriptor 3: /tmp/dest/Analysis_dynamic_valgrind-v3.12.0-4635.log
==2321==    <inherited from parent>
==2321== 
==2321== Open file descriptor 2:
==2321==    <inherited from parent>
==2321== 
==2321== Open file descriptor 1:
==2321==    <inherited from parent>
==2321== 
==2321== Open file descriptor 0: /dev/null
==2321==    <inherited from parent>
==2321== 
==2321== 
==2321== HEAP SUMMARY:
==2321==     in use at exit: 486,838 bytes in 695 blocks
==2321==   total heap usage: 6,276,824 allocs, 6,276,129 frees, 848,890,875 bytes allocated
==2321== 
==2321== LEAK SUMMARY:
==2321==    definitely lost: 0 bytes in 0 blocks
==2321==    indirectly lost: 0 bytes in 0 blocks
==2321==      possibly lost: 5,464 bytes in 6 blocks
==2321==    still reachable: 481,374 bytes in 689 blocks
==2321==                       of which reachable via heuristic:
==2321==                         length64           : 269,568 bytes in 329 blocks
==2321==         suppressed: 0 bytes in 0 blocks
==2321== Reachable blocks (those to which a pointer was found) are not shown.
==2321== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==2321== 
==2321== For counts of detected and suppressed errors, rerun with: -v
==2321== ERROR SUMMARY: 6 errors from 6 contexts (suppressed: 0 from 0)

```

**Comment by wazuhci** [comment]
## Stress/Leaks test results
### Windows Agent ID0
- #### CPU
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B165/monitor-winagent-ID0_B165_Test_stress_windows_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B165/monitor-winagent-ID0_B165_Test_stress_windows_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B165/monitor-winagent-ID0_B165_Test_stress_windows_Agent-warehouse-pullrequests_RSS(KB).svg)
### CentOS Manager ID0
- #### CPU
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B165/monitor-manager-ID0_B165_Test_stress_Manager-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B165/monitor-manager-ID0_B165_Test_stress_Manager-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B165/monitor-manager-ID0_B165_Test_stress_Manager-warehouse-pullrequests_RSS(KB).svg)
### CentOS Agent ID1
- #### CPU
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B165/monitor-agent-ID1_B165_Test_stress_centos_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B165/monitor-agent-ID1_B165_Test_stress_centos_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B165/monitor-agent-ID1_B165_Test_stress_centos_Agent-warehouse-pullrequests_RSS(KB).svg)
### Ubuntu Agent ID0
- #### CPU
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B165/monitor-agent-ID0_B165_Test_stress_ubuntu_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B165/monitor-agent-ID0_B165_Test_stress_ubuntu_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B165/monitor-agent-ID0_B165_Test_stress_ubuntu_Agent-warehouse-pullrequests_RSS(KB).svg)

**Comment by chemamartinez** [comment]
GJ @jesusjimsa!

**Pull request merged**
