### PR TITLE
Engine - Add Geo and ASN data enrichment rule

### PR DESCRIPTION
**Pull request by NahuFigueroa97**
|Related issue|
|---|
|#21835|

## Summary
This pull request addresses Issue #21835  by enhancing the Wazuh ruleset to integrate GeoIP and ASN data enrichment using newly developed helper functions from the MaxMind module. It also introduces conditional logic within the ruleset to selectively apply GeoIP and ASN data enrichment based on event types and specific criteria. Additionally, the structure of the `default_parents` object within the policy has been modified to allow for differentiation between rules and decoders, enabling the use of a single namespace for both. This PR also adds a base rule that optionally enriches data with GeoIP and ASN information.

## Changes
- Updated the Wazuh ruleset to integrate GeoIP and ASN data enrichment.
- Implemented conditional logic within the ruleset to selectively apply data enrichment.
- Modified the structure of the `default_parents` object within the policy to differentiate between rules and decoders.
- Added a base rule for optional enrichment with GeoIP and ASN data.

## Implementation Details
- Modified the `default_parents` object within the policy to allow both rules and decoders in a single namespace.
- Added the capability to set rule-type parents for rule configuration.

### CODE REVIEW

**Review by JavierBejMen — APPROVED** [review]
LGTM

**Review by juliancnn — CHANGES_REQUESTED** [review]
LGTM, just a few minor details

**Review by juliancnn — APPROVED** [review]
LGTM!

**Review by JcabreraC — APPROVED** [review]
LGTM !

**Pull request merged**
