### PR TITLE
Strip trailing whitespaces / newlines from sca.template

### PR DESCRIPTION
**Pull request by iasdeoupxe**
|Related issue|
|---|
||

## Description

I haven't filled out most of the template below because this PR should be straight forward.

Doing a ``diff -c /var/ossec/etc/ossec.conf /var/ossec/etc/ossec.conf.new`` after updating a Debian installation from Wazuh 4.9 to 4.10 shows the added trailing spaces which shouldn't be there:

```
--- 89,96 ----
      <scan_on_start>yes</scan_on_start>
      <interval>12h</interval>
      <skip_nfs>yes</skip_nfs>
    </sca>
+   
  
    <!-- File integrity monitoring -->
    <syscheck>
```

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

### CODE REVIEW

**Comment by iasdeoupxe** [comment]
Hello, is there anybody out there?

**Comment by iasdeoupxe** [comment]
6 months and counting, really?

**Comment by iasdeoupxe** [comment]
@bah07 @chemamartinez @crd1985 @CarlosRS9 Just pinging some random people having done some commits / MR accepting in the hope anyone gets active here...

**Comment by chemamartinez** [comment]
Hi @iasdeoupxe,

Sorry for the delay in the review. It will be merged right now.

Thank you for your contribution.

Regards.

**Pull request merged**
