### PR TITLE
Experimental endpoints (new API)

### LINKED ISSUE #2957: Experimental endpoints (new API)
Hi team,

It is necessary to implement `experimental` endpoints in the new API.

Best regards,

Demetrio.

### PR DESCRIPTION
**Pull request by druizz90**
Hi team,

This PR closes #2957.  Endpoints for `experimental` were implemented in new API. Issue #2957 contains examples of calls.

Best regards,

Demetrio.

### CODE REVIEW

**Comment by druizz90** [comment]
## PR update

I added new `tavern` test for checking that all filters of `experimental` API calls are working properly.

**Comment by wazuhci** [comment]
ERROR IN PACKAGE INSTALLATION TEST

**Comment by wazuhci** [comment]
ex_msg

**Comment by wazuhci** [comment]
${ex_msg}

**Comment by davidjiglesias** [comment]
Hi team,

I have updated tests and endpoints for experimental after changes to nested fields.

### **Updated test results:**
```

**Pull request merged**
