### PR TITLE
Add missing agent:group resource to RBAC's catalog

### LINKED ISSUE #6427: [RBAC] Missing agent:group resource
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.0 | API | Manager | Packages/Sources | Linux |

Hi team,

We have detected an error when creating policies from the Wazuh interface. All RBAC actions that operate with the agent:id resource can also operate with the agent:group resource. However, in the spec.yaml file this resource is not indicated.

This causes the APP to be unable to obtain the correct information from the RBAC catalog. Here is an example of this:
spec_error

To fix this error, we need to add this resource to all affected actions.

Best regards,
Adrián Peña

### PR DESCRIPTION
**Pull request by AdriiiPRodri**
|Related issue|
|---|
|#6427|

Hi team,

This PR closes #6427. In this PR we have added the missing agent:group parameter to all actions that operate with agent:id resource. The reason is that the resource agent:group is a quick way to include all the agent_ids of the agents belonging to the group.

```json
{
  "data": {
    "active-response:command": {
      "description": "Execute active response commands in the agents",
      "resources": [
        "agent:id",
        "agent:group"
      ],
      "example": {
        "actions": [
          "active-response:command"
        ],
        "resources": [
          "agent:id:001",
          "agent:group:atlantic"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "PUT /active-response"
      ]
    },
    "agent:delete": {
      "description": "Delete agents",
      "resources": [
        "agent:id",
        "agent:group"
      ],
      "example": {
        "actions": [
          "agent:delete"
        ],
        "resources": [
          "agent:id:010",
          "agent:group:pacific"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "DELETE /agents"
      ]
    },
    "agent:read": {
      "description": "Access agents information (id, name, group, last keep alive, etc)",
      "resources": [
        "agent:id",
        "agent:group"
      ],
      "example": {
        "actions": [
          "agent:read"
        ],
        "resources": [
          "agent:id:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "GET /agents",
        "GET /agents/{agent_id}/config/{component}/{configuration}",
        "GET /agents/{agent_id}/group/is_sync",
        "GET /agents/{agent_id}/key",
        "GET /groups/{group_id}/agents",
        "GET /agents/no_group",
        "GET /agents/outdated",
        "GET /agents/stats/distinct",
        "GET /agents/summary/os",
        "GET /agents/summary/status",
        "GET /overview/agents"
      ]
    },
    "agent:create": {
      "description": "Create new agents",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "agent:create"
        ],
        "resources": [
          "*:*:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "POST /agents",
        "POST /agents/insert",
        "POST /agents/insert/quick"
      ]
    },
    "agent:modify_group": {
      "description": "Change the group of agents",
      "resources": [
        "agent:id",
        "agent:group"
      ],
      "example": {
        "actions": [
          "agent:modify_group"
        ],
        "resources": [
          "agent:id:004",
          "agent:group:us-east"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "DELETE /agents/{agent_id}/group",
        "DELETE /agents/{agent_id}/group/{group_id}",
        "PUT /agents/{agent_id}/group/{group_id}",
        "DELETE /agents/group",
        "PUT /agents/group",
        "DELETE /groups"
      ]
    },
    "group:modify_assignments": {
      "description": "Change the agents assigned to the group",
      "resources": [
        "group:id"
      ],
      "example": {
        "actions": [
          "group:modify_assignments"
        ],
        "resources": [
          "group:id:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "DELETE /agents/{agent_id}/group",
        "DELETE /agents/{agent_id}/group/{group_id}",
        "PUT /agents/{agent_id}/group/{group_id}",
        "DELETE /agents/group",
        "PUT /agents/group",
        "DELETE /groups"
      ]
    },
    "agent:restart": {
      "description": "Restart agents",
      "resources": [
        "agent:id",
        "agent:group"
      ],
      "example": {
        "actions": [
          "agent:restart"
        ],
        "resources": [
          "agent:id:050",
          "agent:id:049"
        ],
        "effect": "deny"
      },
      "related_endpoints": [
        "PUT /agents/{agent_id}/restart",
        "PUT /agents/group/{group_id}/restart",
        "PUT /agents/node/{node_id}/restart",
        "PUT /agents/restart"
      ]
    },
    "agent:upgrade": {
      "description": "Upgrade the version of the agents",
      "resources": [
        "agent:id",
        "agent:group"
      ],
      "example": {
        "actions": [
          "agent:upgrade"
        ],
        "resources": [
          "agent:id:001",
          "agent:group:mediterranean"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "PUT /agents/{agent_id}/upgrade",
        "PUT /agents/{agent_id}/upgrade_custom",
        "GET /agents/{agent_id}/upgrade_result"
      ]
    },
    "group:delete": {
      "description": "Delete agent groups",
      "resources": [
        "group:id"
      ],
      "example": {
        "actions": [
          "group:delete"
        ],
        "resources": [
          "group:id:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "DELETE /groups"
      ]
    },
    "group:read": {
      "description": "Access agent groups information (id, name, agents, etc)",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "group:create"
        ],
        "resources": [
          "*:*:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "GET /groups",
        "GET /groups/{group_id}/agents",
        "GET /groups/{group_id}/configuration",
        "GET /groups/{group_id}/files",
        "GET /groups/{group_id}/files/{file_name}/json",
        "GET /groups/{group_id}/files/{file_name}/xml",
        "GET /overview/agents"
      ]
    },
    "group:create": {
      "description": "Create new agent groups",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "group:create"
        ],
        "resources": [
          "*:*:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "POST /groups"
      ]
    },
    "group:update_config": {
      "description": "Change the configuration of agent groups",
      "resources": [
        "group:id"
      ],
      "example": {
        "actions": [
          "group:update_config"
        ],
        "resources": [
          "group:id:*"
        ],
        "effect": "deny"
      },
      "related_endpoints": [
        "PUT /groups/{group_id}/configuration"
      ]
    },
    "cluster:read": {
      "description": "Read Wazuh's cluster nodes configuration",
      "resources": [
        "node:id"
      ],
      "example": {
        "actions": [
          "cluster:read"
        ],
        "resources": [
          "node:id:worker1",
          "node:id:worker3"
        ],
        "effect": "deny"
      },
      "related_endpoints": [
        "PUT /agents/node/{node_id}/restart",
        "GET /cluster/local/info",
        "GET /cluster/nodes",
        "GET /cluster/healthcheck",
        "GET /cluster/local/config",
        "GET /cluster/{node_id}/status",
        "GET /cluster/{node_id}/info",
        "GET /cluster/{node_id}/configuration",
        "GET /cluster/{node_id}/stats",
        "GET /cluster/{node_id}/stats/hourly",
        "GET /cluster/{node_id}/stats/weekly",
        "GET /cluster/{node_id}/stats/analysisd",
        "GET /cluster/{node_id}/stats/remoted",
        "GET /cluster/{node_id}/logs",
        "GET /cluster/{node_id}/logs/summary",
        "GET /cluster/{node_id}/files",
        "PUT /cluster/{node_id}/files",
        "DELETE /cluster/{node_id}/files",
        "PUT /cluster/restart",
        "GET /cluster/configuration/validation",
        "GET /cluster/{node_id}/configuration/{component}/{configuration}"
      ]
    },
    "ciscat:read": {
      "description": "Access CIS-CAT results for agents",
      "resources": [
        "agent:id",
        "agent:group"
      ],
      "example": {
        "actions": [
          "ciscat:read"
        ],
        "resources": [
          "agent:id:001",
          "agent:id:003",
          "agent:group:default"
        ],
        "effect": "deny"
      },
      "related_endpoints": [
        "GET /ciscat/{agent_id}/results",
        "GET /experimental/ciscat/results"
      ]
    },
    "cluster:status": {
      "description": "Check Wazuh's cluster general status",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "cluster:status"
        ],
        "resources": [
          "*:*:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "GET /cluster/status"
      ]
    },
    "cluster:read_api_config": {
      "description": "Check Wazuh's cluster nodes API configuration",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "cluster:read_api_config"
        ],
        "resources": [
          "node:id:worker1",
          "node:id:worker3"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "GET /cluster/api/config"
      ]
    },
    "cluster:update_api_config": {
      "description": "Modify Wazuh's cluster nodes API configuration",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "cluster:update_api_config"
        ],
        "resources": [
          "node:id:worker1",
          "node:id:worker3"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "PUT /cluster/api/config",
        "DELETE /cluster/api/config"
      ]
    },
    "cluster:read_file": {
      "description": "Read Wazuh's cluster nodes files",
      "resources": [
        "node:id",
        "file:path"
      ],
      "example": {
        "actions": [
          "cluster:read_file"
        ],
        "resources": [
          "node:id:worker1",
          "file:path:etc/rules/new-rules.xml"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "GET /cluster/{node_id}/files"
      ]
    },
    "cluster:delete_file": {
      "description": "Delete Wazuh's cluster nodes files",
      "resources": [
        "node:id",
        "file:path"
      ],
      "example": {
        "actions": [
          "cluster:delete_file"
        ],
        "resources": [
          "node:id:worker1",
          "file:path:etc/rules/new-rules.xml"
        ],
        "effect": "deny"
      },
      "related_endpoints": [
        "PUT /cluster/{node_id}/files",
        "DELETE /cluster/{node_id}/files"
      ]
    },
    "cluster:upload_file": {
      "description": "Upload files to Wazuh's cluster nodes",
      "resources": [
        "node:id"
      ],
      "example": {
        "actions": [
          "cluster:upload_file"
        ],
        "resources": [
          "node:id:worker1"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "PUT /cluster/{node_id}/files"
      ]
    },
    "cluster:restart": {
      "description": "Restart Wazuh's cluster nodes",
      "resources": [
        "node:id"
      ],
      "example": {
        "actions": [
          "cluster:restart"
        ],
        "resources": [
          "node:id:worker1"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "PUT /cluster/restart"
      ]
    },
    "lists:read": {
      "description": "Read cdb lists files",
      "resources": [
        "list:path"
      ],
      "example": {
        "actions": [
          "lists:read"
        ],
        "resources": [
          "list:path:etc/lists/audit-keys"
        ],
        "effect": "deny"
      },
      "related_endpoints": [
        "GET /lists",
        "GET /lists/files"
      ]
    },
    "manager:read": {
      "description": "Read Wazuh manager configuration",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "manager:read"
        ],
        "resources": [
          "*:*:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "GET /manager/status",
        "GET /manager/info",
        "GET /manager/configuration",
        "GET /manager/stats",
        "GET /manager/stats/hourly",
        "GET /manager/stats/weekly",
        "GET /manager/stats/analysisd",
        "GET /manager/stats/remoted",
        "GET /manager/logs",
        "GET /manager/logs/summary",
        "GET /manager/files",
        "PUT /manager/files",
        "DELETE /manager/files",
        "PUT /manager/restart",
        "GET /manager/configuration/validation",
        "GET /manager/configuration/{component}/{configuration}"
      ]
    },
    "manager:read_file": {
      "description": "Read Wazuh manager files",
      "resources": [
        "file:path"
      ],
      "example": {
        "actions": [
          "manager:read_file"
        ],
        "resources": [
          "file:path:etc/rules/new-rules.xml"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "GET /manager/files"
      ]
    },
    "manager:delete_file": {
      "description": "Delete Wazuh manager files",
      "resources": [
        "file:path"
      ],
      "example": {
        "actions": [
          "manager:delete_file"
        ],
        "resources": [
          "file:path:etc/rules/new-rules.xml"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "PUT /manager/files",
        "DELETE /manager/files"
      ]
    },
    "manager:upload_file": {
      "description": "Upload files to Wazuh manager",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "manager:upload_file"
        ],
        "resources": [
          "*:*:*"
        ],
        "effect": "deny"
      },
      "related_endpoints": [
        "PUT /manager/files"
      ]
    },
    "manager:read_api_config": {
      "description": "Read Wazuh manager API configuration",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "manager:read_api_config"
        ],
        "resources": [
          "*:*:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "GET /manager/api/config"
      ]
    },
    "manager:update_api_config": {
      "description": "Modify Wazuh manager API configuration",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "manager:update_api_config"
        ],
        "resources": [
          "*:*:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "PUT /manager/api/config",
        "DELETE /manager/api/config"
      ]
    },
    "manager:restart": {
      "description": "Restart Wazuh managers",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "manager:restart"
        ],
        "resources": [
          "*:*:*"
        ],
        "effect": "deny"
      },
      "related_endpoints": [
        "PUT /manager/restart"
      ]
    },
    "mitre:read": {
      "description": "Access attacks information from MITRE database",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "mitre:read"
        ],
        "resources": [
          "*:*:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "GET /mitre"
      ]
    },
    "rules:read": {
      "description": "Read rules files",
      "resources": [
        "rule:file"
      ],
      "example": {
        "actions": [
          "rules:read"
        ],
        "resources": [
          "rule:file:0610-win-ms_logs_rules.xml"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "GET /rules",
        "GET /rules/groups",
        "GET /rules/requirement/{requirement}",
        "GET /rules/files",
        "GET /rules/files/{filename}/download"
      ]
    },
    "sca:read": {
      "description": "Access agents security configuration assessment",
      "resources": [
        "agent:id",
        "agent:group"
      ],
      "example": {
        "actions": [
          "sca:read"
        ],
        "resources": [
          "agent:id:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "GET /sca/{agent_id}",
        "GET /sca/{agent_id}/checks/{policy_id}"
      ]
    },
    "syscheck:run": {
      "description": "Run agents syscheck scan",
      "resources": [
        "agent:id",
        "agent:group"
      ],
      "example": {
        "actions": [
          "syscheck:run"
        ],
        "resources": [
          "agent:id:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "PUT /syscheck"
      ]
    },
    "syscheck:read": {
      "description": "Access information from agents syscheck database",
      "resources": [
        "agent:id",
        "agent:group"
      ],
      "example": {
        "actions": [
          "syscheck:read"
        ],
        "resources": [
          "agent:id:011",
          "agent:group:us-west"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "GET /syscheck/{agent_id}",
        "GET /syscheck/{agent_id}/last_scan"
      ]
    },
    "syscheck:clear": {
      "description": "Clear the agents syscheck database",
      "resources": [
        "agent:id",
        "agent:group"
      ],
      "example": {
        "actions": [
          "syscheck:clear"
        ],
        "resources": [
          "agent:id:*"
        ],
        "effect": "deny"
      },
      "related_endpoints": [
        "DELETE /syscheck/{agent_id}",
        "DELETE /experimental/syscheck"
      ]
    },
    "decoders:read": {
      "description": "Read decoders files",
      "resources": [
        "decoder:file"
      ],
      "example": {
        "actions": [
          "decoders:read"
        ],
        "resources": [
          "decoder:file:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "GET /decoders",
        "GET /decoders/files",
        "GET /decoders/files/{filename}/download",
        "GET /decoders/parents"
      ]
    },
    "syscollector:read": {
      "description": "Access agents syscollector information",
      "resources": [
        "agent:id",
        "agent:group"
      ],
      "example": {
        "actions": [
          "syscollector:read"
        ],
        "resources": [
          "agent:id:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "GET /experimental/syscollector/hardware",
        "GET /experimental/syscollector/netaddr",
        "GET /experimental/syscollector/netiface",
        "GET /experimental/syscollector/netproto",
        "GET /experimental/syscollector/os",
        "GET /experimental/syscollector/packages",
        "GET /experimental/syscollector/ports",
        "GET /experimental/syscollector/processes",
        "GET /experimental/syscollector/hotfixes",
        "GET /syscollector/{agent_id}/hardware",
        "GET /syscollector/{agent_id}/hotfixes",
        "GET /syscollector/{agent_id}/netaddr",
        "GET /syscollector/{agent_id}/netiface",
        "GET /syscollector/{agent_id}/netproto",
        "GET /syscollector/{agent_id}/os",
        "GET /syscollector/{agent_id}/packages",
        "GET /syscollector/{agent_id}/ports",
        "GET /syscollector/{agent_id}/processes"
      ]
    },
    "security:read": {
      "description": "Access information about system security resources",
      "resources": [
        "policy:id",
        "role:id",
        "user:id",
        "rule:id"
      ],
      "example": {
        "actions": [
          "security:read"
        ],
        "resources": [
          "policy:id:*",
          "role:id:2",
          "user:id:5",
          "rule:id:3"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "GET /security/users",
        "GET /security/roles",
        "GET /security/rules",
        "GET /security/policies"
      ]
    },
    "security:create_user": {
      "description": "Create new system users",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "security:create_user"
        ],
        "resources": [
          "*:*:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "POST /security/users"
      ]
    },
    "security:delete": {
      "description": "Delete system security resources",
      "resources": [
        "policy:id",
        "role:id",
        "user:id",
        "rule:id"
      ],
      "example": {
        "actions": [
          "security:update"
        ],
        "resources": [
          "policy:id:*",
          "role:id:3",
          "user:id:4",
          "rule:id:2"
        ],
        "effect": "deny"
      },
      "related_endpoints": [
        "DELETE /security/users",
        "DELETE /security/roles",
        "DELETE /security/rules",
        "DELETE /security/policies",
        "DELETE /security/users/{user_id}/roles",
        "DELETE /security/roles/{role_id}/policies",
        "DELETE /security/roles/{role_id}/rules"
      ]
    },
    "security:update": {
      "description": "Update the information of system security resources",
      "resources": [
        "policy:id",
        "role:id",
        "user:id",
        "rule:id"
      ],
      "example": {
        "actions": [
          "security:update"
        ],
        "resources": [
          "policy:id:*",
          "role:id:4",
          "user:id:3",
          "rule:id:4"
        ],
        "effect": "deny"
      },
      "related_endpoints": [
        "PUT /security/users/{user_id}",
        "PUT /security/roles/{role_id}",
        "PUT /security/rules/{rule_id}",
        "PUT /security/policies/{policy_id}",
        "POST /security/users/{user_id}/roles",
        "POST /security/roles/{role_id}/policies",
        "POST /security/roles/{role_id}/rules"
      ]
    },
    "security:create": {
      "description": "Create new system security resources",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "security:create"
        ],
        "resources": [
          "*:*:*"
        ],
        "effect": "deny"
      },
      "related_endpoints": [
        "POST /security/roles",
        "POST /security/rules",
        "POST /security/policies"
      ]
    },
    "security:read_config": {
      "description": "Read current system security configuration",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "security:read_config"
        ],
        "resources": [
          "*:*:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "GET /security/config"
      ]
    },
    "security:update_config": {
      "description": "Update current system security configuration",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "security:update_config"
        ],
        "resources": [
          "*:*:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "PUT /security/config",
        "DELETE /security/config"
      ]
    }
  },
  "error": 0
}
```

### CODE REVIEW

**Review by davidjiglesias — CHANGES_REQUESTED** [review]
Add a documentation change to https://documentation.wazuh.com/4.0/user-manual/api/rbac/reference.html#actions, maybe a hint or something to explain the user that agent:id can be referenced as a resource directly using agent:id or using agent:group.

**Review by davidjiglesias — CHANGES_REQUESTED** [review]
Add fix to changelog

**Comment by AdriiiPRodri** [comment]
> Add fix to changelog

Added

> Add fix to changelog

Done

**Comment by AdriiiPRodri** [comment]
> Add a documentation change to https://documentation.wazuh.com/4.0/user-manual/api/rbac/reference.html#actions, maybe a hint or something to explain the user that agent:id can be referenced as a resource directly using agent:id or using agent:group.

Done: https://github.com/wazuh/wazuh-documentation/pull/3099

**Review by davidjiglesias — APPROVED** [review]

**Pull request merged**
