### PR TITLE
Attempt to Fix Incorrect Alert ID in Active Response

### PR DESCRIPTION
**Pull request by ssigwart**
|Related issue|Comment|
|---|---|
| #3267 ||
| #2829 | I'm not sure if this will actually fix this one, but this is based off the comment there. |

## Description

This is an attempt to fix the alert ID being wrong in active responses.

## Tests

Sorry, but I don't know how to really test this, but was trying to follow the notes in #2829.

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

### CODE REVIEW

**Comment by ssigwart** [comment]
@sergiospa or @vikman90, I see you both are mentioned on #3267.  Can either of you look at this or let me know if someone else can help with this?

**Comment by juliancnn** [comment]
hi @ssigwart 

Thank you very much for your contribution to the Wazuh community.
The problem of using the previous offset of the file as id causes duplicate ids to be generated.
Analysisd is a multi-threaded process, several threads process events (`w_process_event_thread`) and the `w_writer_log_thread` thread assign value to `lf->crt_ftell`.
If 2 events are processed before the writer thread writes the file then they will both have the same id.

To confirm this I applied your changes to our latest version of wazuh, then:

-  Create a custom rule in `/var/ossec/etc/rules/local_rules.xml`

```xml
  <rule id="100011" level="4">
    <url>test.com</url>
    <description>Force AR</description>
  </rule>
```

- Configure the AR (in `/var/ossec/etc/ossec.conf`)

```xml
  <command>
    <name>ls_ar</name>
    <executable>test_ar.sh</executable>
    <timeout_allowed>yes</timeout_allowed>
  </command>
  <active-response>
    <command>ls_ar</command>
    <location>server</location>
    <rules_id>100011</rules_id>
  </active-response>
```

- Create a  custom AR  (in `/var/ossec/etc/ossec.conf`)
```
touch /var/ossec/active-response/bin/test_ar.sh
chmod 750 /var/ossec/active-response/bin/test_ar.sh
vim  /var/ossec/active-response/bin/test_ar.sh
```

With the following content
```
#!/bin/sh
/bin/echo "`date` $0 $1 $2 $3 $4 $5 " >>  /root/ar.log
```

- Created a localfile to stimulate the AR
```xml
  <localfile>
    <log_format>syslog</log_format>
    <location>/root/log_test.log</location>
  </localfile>
```


- Finally I send 2 events to try to force the race condition
```
echo "{ \"url\" : \"test.com\", \"command\" : \"logged\" }\n{ \"url\" : \"test.com\", \"command\" : \"logged\" }">> /root/log_test.log
```

For example, my output of `/root/ar.log`

```
Mon 18 Jan 2021 05:07:31 PM UTC /var/ossec/active-response/bin/test_ar.sh add - - 1610989651.478711 100011
Mon 18 Jan 2021 05:07:31 PM UTC /var/ossec/active-response/bin/test_ar.sh add - - 1610989651.478711 100011
```

We appreciate the effort and help to the Wazuh community, feel free to tag me if you upload a PR/coomit again.

Issue [ Active Response Alert Lookup Race Condition #2829 ](https://github.com/wazuh/wazuh/issues/2829) will remain open and when it is included in the roadmap you could see its updates there.

Thank you very much for your contribution,
Julian

**Comment by ssigwart** [comment]
Hi @juliancnn.  Thank you for taking time to look at this.  I updated the code to keep track of `last_crt_ftell`, so now I don't think it should result in duplicate IDs.  Do you think that is a good idea?

I'm able to compile it in Docker on `amazonlinux:2`.  However, I can't figure out how to run it to test it.  Are there any guides on how to compile and test on Docker?

**Comment by juliancnn** [comment]
Hi @ssigwart ,

I have tested your PR, I keep getting the same results. I think this may not be the way the solution should take.
The problem is not only the RC ([duplicate IDs](https://github.com/wazuh/wazuh/issues/2829)), but also the ID of the AR alert must be the same both for the alert.json (and elasticsearch) and for the [argument of the AR scripts](https://github.com/wazuh/wazuh/issues/3267).
From Wazuh we will work on a solution that can solve both problems at the same time since they are closely related.

The compilation and installation guides can be found [here](https://documentation.wazuh.com/4.0/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-server/index.html). We do not have an exclusive guide to modifying the source code, compiling and testing on docker, but I think [this](https://documentation.wazuh.com/4.0/docker/wazuh-container.html) may be useful to you.

If you have any problem, doubts or just want to know more, feel free to create new issues in our repositories, this will help people with the same concerns to find solutions easily.

Thank you very much for your contribution, i hope this information is useful to you
Julian

**Comment by ssigwart** [comment]
Thanks @juliancnn for testing the new patch and for the information.  Since it sounds like this approach isn't going to work and the Wazuh team is going to work on a solution, I'll close this pull request.

**Pull request closed without merging**
