### PR TITLE
Report non-applicable checks for SCA

### PR DESCRIPTION
**Pull request by cristgl**
This is the PR for the issue https://github.com/wazuh/wazuh/issues/3029

Two new fields have been added. This occurs when a check cannot be run because the file or directory do not exist, an execution of command has returned timeout, cannot open a registry, etc.

For example, the next check could not be run because there is no field named inted.conf in my specific system:
```
 - id: 5030
   title: "Ensure telnet client is not installed"
   description: "The telnet package contains the telnet client, which allows users to start connections to other systems via the telnet protocol."
   rationale: "The telnet protocol is insecure and unencrypted. The use of an unencrypted transmission medium could allow an unauthorized user to steal credentials. The ssh package provides an encrypted session and stronger security and is included in most Linux distributions."
   remediation: "Run the following command to uninstall telnet: # apt-get remove telnet"
   compliance:
    - cis_csc: "2.6, 4.5"
    - cis: "2.3.4"
    - pci_dss: "2.2.3"
   condition: any
   rules:
     - 'f:/etc/inetd.conf -> !r:^# && r:telnet;'
```
This is its entry at the database:

```
1017679814|5030|cis_debian|Ensure telnet client is not installed|The telnet package contains the telnet client, which allows users to start connections to other systems via the telnet protocol.|The telnet protocol is insecure and unencrypted. The use of an unencrypted transmission medium could allow an unauthorized user to steal credentials. The ssh package provides an encrypted session and stronger security and is included in most Linux distributions.|Run the following command to uninstall telnet: # apt-get remove telnet||||||||Not applicable|File /etc/inetd.conf not found.
```

And the alert generated:

```
** Alert 1555491173.684284: - sca,gdpr_IV_35.7.d
2019 Apr 17 10:52:53 misi->sca
Rule: 19009 (level 3) -> 'CIS benchmark for Debian/Linux: Ensure telnet client is not installed. Not applicable. Reason: File /etc/inetd.conf not found.'
{"type":"check","id":249621373,"policy":"CIS benchmark for Debian/Linux","policy_id":"cis_debian","check":{"id":5030,"title":"Ensure telnet client is not installed","description":"The telnet package contains the telnet client, which allows users to start connections to other systems via the telnet protocol.","rationale":"The telnet protocol is insecure and unencrypted. The use of an unencrypted transmission medium could allow an unauthorized user to steal credentials. The ssh package provides an encrypted session and stronger security and is included in most Linux distributions.","remediation":"Run the following command to uninstall telnet: # apt-get remove telnet","compliance":{"cis_csc":"2.6, 4.5","cis":"2.3.4","pci_dss":"2.2.3"},"file":"","status":"Not applicable","reason":"File /etc/inetd.conf not found."}}
sca.type: check
sca.scan_id: 249621373
sca.policy: CIS benchmark for Debian/Linux
sca.check.id: 5030
sca.check.title: Ensure telnet client is not installed
sca.check.description: The telnet package contains the telnet client, which allows users to start connections to other systems via the telnet protocol.
sca.check.rationale: The telnet protocol is insecure and unencrypted. The use of an unencrypted transmission medium could allow an unauthorized user to steal credentials. The ssh package provides an encrypted session and stronger security and is included in most Linux distributions.
sca.check.remediation: Run the following command to uninstall telnet: # apt-get remove telnet
sca.check.compliance.cis_csc: 2.6, 4.5
sca.check.compliance.cis: 2.3.4
sca.check.compliance.pci_dss: 2.2.3
sca.check.status: Not applicable
sca.check.reason: File /etc/inetd.conf not found.
```

These checks will return a status field which states that the check is 'not applicable' and the reason why. If a check has two or more rules, in case that one of them can't be run, the whole check will be invalid returning the reason from that specific rule. In case there is more than one invalid rule, the check will return the reason of the last one.

Testing
---------
- Valgrind `analysisd`.
- Valgrind `modulesd`.
- Having a check that has a rule with the name of a file that doesn't exist returns a `passed` status.
- Having a check that has a rule with the name of a file that doesn't exist and has pattern returns a `not applicable` status with its specific reason.
- Having a check that has a rule with the name of a directory that doesn't exist returns a `passed` status.
- Having a check that has a rule with the name of a directory that doesn't exist and has file pattern returns a `not applicable` status with its specific reason.
- Running a command at the agent side with the option `remote_commands` disabled returns a `non applicable` check with its specific reason.
- The policy file summary has two new fields, `invalid` which states the number of invalid checks run and `total_checks`, which is the total number of checks passed.
- 
- Check that an alert is generated when a new invalid check appears.
- Check that alerts are generated when a previous check changes its status from `passed` or `failed` to `not applicable`.
- Check that the DB is filled when running a non-applicable check.
- Check that the DB is updated when a check changes its status to `not applicable`.

### CODE REVIEW

**Comment by cristgl** [comment]
Testing
---------

- Valgrind: Fixed some invalid reads when accessing the db hash array: [39b3e77](https://github.com/wazuh/wazuh/pull/3122/commits/39b3e77dcdfacd55f5e10fc7b62d09820c78377f)
- Integration checksum does not fail.
- Change the result field from an agent's database check file and see that the next time the scan is run the integration checksum fails.

**Comment by chemamartinez** [comment]
There are two cases we are not capturing the error status and reason:

- When `skip_nfs` is enabled and one directory is skipped: https://github.com/wazuh/wazuh/blob/5cba7ef364e1bcc798f48dc9cbef889f61c76229/src/wazuh_modules/wm_sca.c#L1045

-  For Windows registries, when it is missing or we don't have permissions to read it: https://github.com/wazuh/wazuh/blob/5cba7ef364e1bcc798f48dc9cbef889f61c76229/src/wazuh_modules/wm_sca.c#L999

In addition, check this please:

- Here we can overwrite the error status if `found == 2`: https://github.com/wazuh/wazuh/blob/5cba7ef364e1bcc798f48dc9cbef889f61c76229/src/wazuh_modules/wm_sca.c#L1098

**Comment by chemamartinez** [comment]
When testing the execution of SCA with Valgrind and analyzing directories we find there is a memory leak we have to catch:

```
==90341== 32,816 bytes in 1 blocks are possibly lost in loss record 135 of 145
==90341==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==90341==    by 0x5B659B5: __alloc_dir (opendir.c:216)
==90341==    by 0x5B659B5: opendir_tail (opendir.c:136)
==90341==    by 0x5B659B5: opendir (opendir.c:190)
==90341==    by 0x16BF9C: wm_sca_check_dir (wm_sca.c:1787)
==90341==    by 0x169DE0: wm_sca_do_scan (wm_sca.c:1062)
==90341==    by 0x168103: wm_sca_read_files (wm_sca.c:531)
==90341==    by 0x167615: wm_sca_start (wm_sca.c:341)
==90341==    by 0x166FBF: wm_sca_main (wm_sca.c:222)
==90341==    by 0x586E6DA: start_thread (pthread_create.c:463)
==90341==    by 0x5BA788E: clone (clone.S:95)
==90341==
==90341== 4,102,000 bytes in 125 blocks are definitely lost in loss record 145 of 145
==90341==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==90341==    by 0x5B659B5: __alloc_dir (opendir.c:216)
==90341==    by 0x5B659B5: opendir_tail (opendir.c:136)
==90341==    by 0x5B659B5: opendir (opendir.c:190)
==90341==    by 0x16BF9C: wm_sca_check_dir (wm_sca.c:1787)
==90341==    by 0x169DE0: wm_sca_do_scan (wm_sca.c:1062)
==90341==    by 0x168103: wm_sca_read_files (wm_sca.c:531)
==90341==    by 0x167615: wm_sca_start (wm_sca.c:341)
==90341==    by 0x166FBF: wm_sca_main (wm_sca.c:222)
==90341==    by 0x586E6DA: start_thread (pthread_create.c:463)
==90341==    by 0x5BA788E: clone (clone.S:95)
==90341==
==90341== LEAK SUMMARY:
==90341==    definitely lost: 4,102,000 bytes in 125 blocks
==90341==    indirectly lost: 0 bytes in 0 blocks
==90341==      possibly lost: 38,936 bytes in 9 blocks
==90341==    still reachable: 811,574 bytes in 7,662 blocks
==90341==                       of which reachable via heuristic:
==90341==                         length64           : 223,896 bytes in 124 blocks
==90341==         suppressed: 0 bytes in 0 blocks
==90341== Reachable blocks (those to which a pointer was found) are not shown.
==90341== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```

As well as a file descriptor leak:

```
==90341== FILE DESCRIPTORS: 137 open at exit.
==90341== Open file descriptor 139: /
==90341==    at 0x5B95DB1: __open_nocancel (open64.c:69)
==90341==    by 0x5B65952: opendir (opendir.c:190)
==90341==    by 0x16BF9C: wm_sca_check_dir (wm_sca.c:1787)
==90341==    by 0x169DE0: wm_sca_do_scan (wm_sca.c:1062)
==90341==    by 0x168103: wm_sca_read_files (wm_sca.c:531)
==90341==    by 0x167615: wm_sca_start (wm_sca.c:341)
==90341==    by 0x166FBF: wm_sca_main (wm_sca.c:222)
==90341==    by 0x586E6DA: start_thread (pthread_create.c:463)
==90341==    by 0x5BA788E: clone (clone.S:95)
==90341==
==90341== Open file descriptor 138: /home
==90341==    at 0x5B95DB1: __open_nocancel (open64.c:69)
==90341==    by 0x5B65952: opendir (opendir.c:190)
==90341==    by 0x16BF9C: wm_sca_check_dir (wm_sca.c:1787)
==90341==    by 0x169DE0: wm_sca_do_scan (wm_sca.c:1062)
==90341==    by 0x168103: wm_sca_read_files (wm_sca.c:531)
==90341==    by 0x167615: wm_sca_start (wm_sca.c:341)
==90341==    by 0x166FBF: wm_sca_main (wm_sca.c:222)
==90341==    by 0x586E6DA: start_thread (pthread_create.c:463)
==90341==    by 0x5BA788E: clone (clone.S:95)
```

It has been discovered when testing the policies `cis_debianlinux7-8_L1_rcl.yml` and `cis_debianlinux7-8_L2_rcl.yml` which analyze several directories in their rules.

In addition, please review this memory allocation:

**Comment by cristgl** [comment]
Valgrind and Dr. Memory reports
-----------------------------------------

```
==2916== Thread 2:
==2916== Invalid read of size 8
==2916==    at 0x16B12B: wm_sca_do_scan (wm_sca.c:1294)
==2916==    by 0x16855A: wm_sca_read_files (wm_sca.c:531)
==2916==    by 0x167A6C: wm_sca_start (wm_sca.c:341)
==2916==    by 0x167416: wm_sca_main (wm_sca.c:222)
==2916==    by 0x586F6DA: start_thread (pthread_create.c:463)
==2916==    by 0x5BA888E: clone (clone.S:95)
==2916==  Address 0xc284d68 is 8 bytes after a block of size 4,096 free'd
==2916==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2916==    by 0x5B152EA: _IO_setb (genops.c:349)
==2916==    by 0x5B1326B: _IO_file_close_it@@GLIBC_2.2.5 (fileops.c:154)
==2916==    by 0x5B05386: fclose@@GLIBC_2.2.5 (iofclose.c:53)
==2916==    by 0x13DE09: _log (debug_op.c:195)
==2916==    by 0x13EE11: _mtinfo (debug_op.c:400)
==2916==    by 0x1684D9: wm_sca_read_files (wm_sca.c:529)
==2916==    by 0x167A6C: wm_sca_start (wm_sca.c:341)
==2916==    by 0x167416: wm_sca_main (wm_sca.c:222)
==2916==    by 0x586F6DA: start_thread (pthread_create.c:463)
==2916==    by 0x5BA888E: clone (clone.S:95)
==2916==  Block was alloc'd at
==2916==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2916==    by 0x5B0518B: _IO_file_doallocate (filedoalloc.c:101)
==2916==    by 0x5B15378: _IO_doallocbuf (genops.c:365)
==2916==    by 0x5B14497: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:759)
==2916==    by 0x5B129EC: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1266)
==2916==    by 0x5AE3C01: vfprintf (vfprintf.c:1642)
==2916==    by 0x5AEBE53: fprintf (fprintf.c:32)
==2916==    by 0x13DD11: _log (debug_op.c:180)
==2916==    by 0x13EE11: _mtinfo (debug_op.c:400)
==2916==    by 0x1684D9: wm_sca_read_files (wm_sca.c:529)
==2916==    by 0x167A6C: wm_sca_start (wm_sca.c:341)
==2916==    by 0x167416: wm_sca_main (wm_sca.c:222)
==2916== 
==2916== Invalid read of size 8
==2916==    at 0x16B14F: wm_sca_do_scan (wm_sca.c:1294)
==2916==    by 0x16855A: wm_sca_read_files (wm_sca.c:531)
==2916==    by 0x167A6C: wm_sca_start (wm_sca.c:341)
==2916==    by 0x167416: wm_sca_main (wm_sca.c:222)
==2916==    by 0x586F6DA: start_thread (pthread_create.c:463)
==2916==    by 0x5BA888E: clone (clone.S:95)
==2916==  Address 0xc284d78 is 24 bytes after a block of size 4,096 in arena "client"
==2916== 
==2916== Invalid free() / delete / delete[] / realloc()
==2916==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2916==    by 0x16B159: wm_sca_do_scan (wm_sca.c:1294)
==2916==    by 0x16855A: wm_sca_read_files (wm_sca.c:531)
==2916==    by 0x167A6C: wm_sca_start (wm_sca.c:341)
==2916==    by 0x167416: wm_sca_main (wm_sca.c:222)
==2916==    by 0x586F6DA: start_thread (pthread_create.c:463)
==2916==    by 0x5BA888E: clone (clone.S:95)
==2916==  Address 0x1040 is not stack'd, malloc'd or (recently) free'd
==2916== 
==2916== Invalid write of size 8
==2916==    at 0x16B176: wm_sca_do_scan (wm_sca.c:1294)
==2916==    by 0x16855A: wm_sca_read_files (wm_sca.c:531)
==2916==    by 0x167A6C: wm_sca_start (wm_sca.c:341)
==2916==    by 0x167416: wm_sca_main (wm_sca.c:222)
==2916==    by 0x586F6DA: start_thread (pthread_create.c:463)
==2916==    by 0x5BA888E: clone (clone.S:95)
==2916==  Address 0xc284d78 is 24 bytes after a block of size 4,096 in arena "client"
==2916== 

valgrind: m_mallocfree.c:307 (get_bszB_as_is): Assertion 'bszB_lo == bszB_hi' failed.
valgrind: Heap block lo/hi size mismatch: lo = 4160, hi = 0.
This is probably caused by your program erroneously writing past the
end of a heap block and corrupting heap metadata.  If you fix any
invalid writes reported by Memcheck, this assertion failure will
probably go away.  Please try that before reporting this as a bug.


host stacktrace:
==2916==    at 0x580441BA: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==2916==    by 0x580442D4: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==2916==    by 0x58044459: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==2916==    by 0x58053C5A: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==2916==    by 0x5800B8CC: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==2916==    by 0x5800BFEA: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==2916==    by 0x5809F5DC: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==2916==    by 0x580AED50: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==2916==    by 0x580AF03A: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==2916==    by 0x580DA89D: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==2916==    by 0xDEADBEEFDEADBEEE: ???
==2916==    by 0xDEADBEEFDEADBEEE: ???
==2916==    by 0xDEADBEEFDEADBEEE: ???

sched status:
  running_tid=2

Thread 1: status = VgTs_WaitSys (lwpid 2916)
==2916==    at 0x5870D2D: __pthread_timedjoin_ex (pthread_join_common.c:89)
==2916==    by 0x111F5F: main (main.c:107)

Thread 2: status = VgTs_Runnable (lwpid 3361)
==2916==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2916==    by 0x169509: wm_sca_do_scan (wm_sca.c:830)
==2916==    by 0x16855A: wm_sca_read_files (wm_sca.c:531)
==2916==    by 0x167A6C: wm_sca_start (wm_sca.c:341)
==2916==    by 0x167416: wm_sca_main (wm_sca.c:222)
==2916==    by 0x586F6DA: start_thread (pthread_create.c:463)
==2916==    by 0x5BA888E: clone (clone.S:95)

Thread 3: status = VgTs_WaitSys (lwpid 3363)
==2916==    at 0x58759F3: futex_wait_cancelable (futex-internal.h:88)
==2916==    by 0x58759F3: __pthread_cond_wait_common (pthread_cond_wait.c:502)
==2916==    by 0x58759F3: pthread_cond_wait@@GLIBC_2.3.2 (pthread_cond_wait.c:655)
==2916==    by 0x11AA9C: wm_inotify_pop (wm_database.c:1532)
==2916==    by 0x1154DB: wm_database_main (wm_database.c:143)
==2916==    by 0x586F6DA: start_thread (pthread_create.c:463)
==2916==    by 0x5BA888E: clone (clone.S:95)

Thread 4: status = VgTs_WaitSys (lwpid 3364)
==2916==    at 0x58796D7: accept (accept.c:26)
==2916==    by 0x11ADF6: wm_download_main (wm_download.c:76)
==2916==    by 0x586F6DA: start_thread (pthread_create.c:463)
==2916==    by 0x5BA888E: clone (clone.S:95)

Thread 5: status = VgTs_WaitSys (lwpid 3365)
==2916==    at 0x5B9E03F: select (select.c:41)
==2916==    by 0x11500B: wmcom_main (wmcom.c:100)
==2916==    by 0x586F6DA: start_thread (pthread_create.c:463)
==2916==    by 0x5BA888E: clone (clone.S:95)

Thread 6: status = VgTs_WaitSys (lwpid 3432)
==2916==    at 0x58798F2: recvfrom (recvfrom.c:27)
==2916==    by 0x1452F5: OS_RecvUnix (os_net.c:472)
==2916==    by 0x16E890: wm_sca_request_thread (wm_sca.c:2780)
==2916==    by 0x586F6DA: start_thread (pthread_create.c:463)
==2916==    by 0x5BA888E: clone (clone.S:95)

Thread 7: status = VgTs_WaitSys (lwpid 3433)
==2916==    at 0x58759F3: futex_wait_cancelable (futex-internal.h:88)
==2916==    by 0x58759F3: __pthread_cond_wait_common (pthread_cond_wait.c:502)
==2916==    by 0x58759F3: pthread_cond_wait@@GLIBC_2.3.2 (pthread_cond_wait.c:655)
==2916==    by 0x141A90: queue_pop_ex (queue_op.c:106)
==2916==    by 0x16E2B7: wm_sca_dump_db_thread (wm_sca.c:2606)
==2916==    by 0x586F6DA: start_thread (pthread_create.c:463)
==2916==    by 0x5BA888E: clone (clone.S:95)

Thread 8: status = VgTs_WaitSys (lwpid 3440)
==2916==    at 0x5879384: read (read.c:27)
==2916==    by 0x11A30F: wm_inotify_start (wm_database.c:1426)
==2916==    by 0x586F6DA: start_thread (pthread_create.c:463)
==2916==    by 0x5BA888E: clone (clone.S:95)
```

```
==28885== HEAP SUMMARY:
==28885==     in use at exit: 4,905,958 bytes in 11,080 blocks
==28885==   total heap usage: 392,518 allocs, 381,438 frees, 99,939,159 bytes allocated
==28885== 
==28885== 288 bytes in 1 blocks are possibly lost in loss record 82 of 150
==28885==    at 0x4C31B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28885==    by 0x40134A6: allocate_dtv (dl-tls.c:286)
==28885==    by 0x40134A6: _dl_allocate_tls (dl-tls.c:530)
==28885==    by 0x5870227: allocate_stack (allocatestack.c:627)
==28885==    by 0x5870227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==28885==    by 0x13BB7F: CreateThreadJoinable (pthreads_op.c:47)
==28885==    by 0x13BC26: CreateThread (pthreads_op.c:62)
==28885==    by 0x111F30: main (main.c:102)
==28885== 
==28885== 2,016 bytes in 7 blocks are possibly lost in loss record 108 of 150
==28885==    at 0x4C31B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28885==    by 0x40134A6: allocate_dtv (dl-tls.c:286)
==28885==    by 0x40134A6: _dl_allocate_tls (dl-tls.c:530)
==28885==    by 0x5870227: allocate_stack (allocatestack.c:627)
==28885==    by 0x5870227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==28885==    by 0x13BB7F: CreateThreadJoinable (pthreads_op.c:47)
==28885==    by 0x111E8F: main (main.c:95)
==28885== 
==28885== 4,104 bytes in 1 blocks are possibly lost in loss record 121 of 150
==28885==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28885==    by 0x50FEDAA: sqlite3MemMalloc (sqlite3.c:20790)
==28885==    by 0x50FF7A2: mallocWithAlarm (sqlite3.c:24464)
==28885==    by 0x50FF84B: sqlite3Malloc (sqlite3.c:24494)
==28885==    by 0x510DC36: pcache1Alloc (sqlite3.c:45336)
==28885==    by 0x510DF24: sqlite3PageMalloc (sqlite3.c:45479)
==28885==    by 0x511E55F: allocateTempSpace (sqlite3.c:61560)
==28885==    by 0x51208CA: btreeCursor (sqlite3.c:63234)
==28885==    by 0x5120A3C: sqlite3BtreeCursor (sqlite3.c:63276)
==28885==    by 0x513C44F: sqlite3VdbeExec (sqlite3.c:81807)
==28885==    by 0x5135036: sqlite3Step (sqlite3.c:76693)
==28885==    by 0x51351E4: sqlite3_step (sqlite3.c:76754)
==28885== 
==28885== 3,937,920 bytes in 120 blocks are definitely lost in loss record 150 of 150
==28885==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28885==    by 0x5B669B5: __alloc_dir (opendir.c:216)
==28885==    by 0x5B669B5: opendir_tail (opendir.c:136)
==28885==    by 0x5B669B5: opendir (opendir.c:190)
==28885==    by 0x16C213: wm_sca_check_dir (wm_sca.c:1760)
==28885==    by 0x16A21C: wm_sca_do_scan (wm_sca.c:1059)
==28885==    by 0x16855A: wm_sca_read_files (wm_sca.c:531)
==28885==    by 0x167A6C: wm_sca_start (wm_sca.c:341)
==28885==    by 0x167416: wm_sca_main (wm_sca.c:222)
==28885==    by 0x586F6DA: start_thread (pthread_create.c:463)
==28885==    by 0x5BA888E: clone (clone.S:95)
```

```
==6035== 65,536 bytes in 1 blocks are definitely lost in loss record 176 of 181
==6035==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==6035==    by 0x16B0E3: wm_sca_check_file (wm_sca.c:1399)
==6035==    by 0x169A9C: wm_sca_do_scan (wm_sca.c:945)
==6035==    by 0x168366: wm_sca_read_files (wm_sca.c:511)
==6035==    by 0x167A6C: wm_sca_start (wm_sca.c:340)
==6035==    by 0x167416: wm_sca_main (wm_sca.c:221)
==6035==    by 0x586F6DA: start_thread (pthread_create.c:463)
==6035==    by 0x5BA888E: clone (clone.S:95)
```

```
==23763== 65,536 bytes in 1 blocks are definitely lost in loss record 119 of 123
==23763==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==23763==    by 0x16B0E9: wm_sca_check_file (wm_sca.c:1400)
==23763==    by 0x169A9C: wm_sca_do_scan (wm_sca.c:945)
==23763==    by 0x168366: wm_sca_read_files (wm_sca.c:511)
==23763==    by 0x167A6C: wm_sca_start (wm_sca.c:340)
==23763==    by 0x167416: wm_sca_main (wm_sca.c:221)
==23763==    by 0x586F6DA: start_thread (pthread_create.c:463)
==23763==    by 0x5BA888E: clone (clone.S:95)
```

```
NFO:~~8136~~
~~8136~~ Error #11: UNINITIALIZED READ: reading register eax
~~8136~~ # 0 wm_sca_read_command               [wazuh_modules/wm_sca.c:1505]
~~8136~~ # 1 wm_sca_do_scan                    [wazuh_modules/wm_sca.c:984]
~~8136~~ # 2 wm_sca_read_files                 [wazuh_modules/wm_sca.c:530]
~~8136~~ # 3 wm_sca_start                      [wazuh_modules/wm_sca.c:340]
~~8136~~ # 4 wm_sca_main                       [wazuh_modules/wm_sca.c:221]
~~8136~~ # 5 KERNEL32.dll!BaseThreadInitThunk +0x23     (0x751a8484 <KERNEL32.dll+0x18484>)
~~8136~~ Note: @0:00:14.124 in thread 8136
~~8136~~ Note: instruction: cmp    %eax $0x0000007f
 (6~~8136~~
~~8136~~ Error #12: UNINITIALIZED READ: reading register eax
~~8136~~ # 0 wm_sca_read_command               [wazuh_modules/wm_sca.c:1508]
~~8136~~ # 1 wm_sca_do_scan                    [wazuh_modules/wm_sca.c:984]
~~8136~~ # 2 wm_sca_read_files                 [wazuh_modules/wm_sca.c:530]
~~8136~~ # 3 wm_sca_start                      [wazuh_modules/wm_sca.c:340]
~~8136~~ # 4 wm_sca_main                       [wazuh_modules/wm_sca.c:221]
~~8136~~ # 5 KERNEL32.dll!BaseThreadInitThunk +0x23     (0x751a8484 <KERNEL32.dll+0x18484>)
~~8136~~ Note: @0:00:14.124 in thread 8136
~~8136~~ Note: instruction: cmp    %eax $0x00000001
```

Most of these reports have been fixed with the new changes made to the code, the invalid checks array has been removed as only the first reason why a check cannot be passed is needed.
The lasting reports were due to overwriting the `reason` variable without `free`ing it.

**Pull request merged**
