### PR TITLE
Add geoip for AWS ALB client IP addresses

### PR DESCRIPTION
**Pull request by rh0dy**
|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/13095|
|https://github.com/wazuh/wazuh/pull/14525|

Closes: #16198 

## Description

As part of release `4.4`, the AWS S3 Wodle will now extract IP addresses from AWS ALB logs, as per https://github.com/wazuh/wazuh/issues/13095 and https://github.com/wazuh/wazuh/pull/14525.  The IP addresses are extracted to the following fields: `data.aws.target_ip` and `data.aws.source_ip`.  This PR is to preprocess those fields so that they are geolocated by Filebeat (to add country, latitude, longitude, etc.) before being stored in Elasticsearch.

### CODE REVIEW

**Comment by jctello** [comment]
Hi @davidjiglesias , @nico-stefani , this PR appears to be a very straightforward improvement to the upcoming AWS ALB integration so users will then have geoIP enrichment. 

It would be great if you could briefly review it so it could be merged to an upcoming Wazuh version.

**Comment by davidjiglesias** [comment]
Yes @jctello, we will be reviewing, testing and incorporating this change in v4.6.0.

Thanks @rh0dy for the contribution!

**Review by nico-stefani — CHANGES_REQUESTED** [review]
What is the purpose of geolocating the `target_ip` field? The example that I took to test the changes, corresponds to a private IP from the AWS network. By example `10.0.0.125`.

I suggest that only geolocate the `client_ip`, which I understand, always must be a public IP.

**Review by nico-stefani — APPROVED** [review]
LGTM! Thanks @rh0dy for the contribution.

**Review by davidjiglesias — APPROVED** [review]

**Pull request merged**
