### PR TITLE
Fix descriptors leak when cleaning agents state

### PR DESCRIPTION
**Pull request by chemamartinez**
|Related issue|
|---|
| https://github.com/wazuh/wazuh/issues/15426 |

## Description

The goal of this issue is to fix the descriptor leaks reported at https://github.com/wazuh/wazuh/issues/15426 for 4.4, affecting Wazuh DB, Analysisd and Remoted.

Once reproduced, the following `valgrind` report shows where the leak is located for Analysisd:
```
==51123== Open AF_UNIX socket 36: <unknown>
==51123==    at 0x52C57DB: socket (syscall-template.S:78)
==51123==    by 0x27FF22: OS_ConnectUnixDomain (os_net.c:211)
==51123==    by 0x27F054: wdbc_connect (wazuhdb_op.c:29)
==51123==    by 0x27F28A: wdbc_query_ex (wazuhdb_op.c:120)
==51123==    by 0x24260C: wdb_get_agents_ids_of_current_node (wdb_global_helpers.c:1161)
==51123==    by 0x11E4EC: w_analysisd_clean_agents_state (state.c:556)
==51123==    by 0x11D32C: w_analysisd_state_main (state.c:253)
==51123==    by 0x518A608: start_thread (pthread_create.c:477)
==51123==    by 0x52C4162: clone (clone.S:95)
```

same as for Remoted:
```
==17214== Open AF_UNIX socket 17: <unknown>
==17214==    at 0x52C57DB: socket (syscall-template.S:78)
==17214==    by 0x2240BF: OS_ConnectUnixDomain (os_net.c:211)
==17214==    by 0x2231F1: wdbc_connect (wazuhdb_op.c:29)
==17214==    by 0x223427: wdbc_query_ex (wazuhdb_op.c:120)
==17214==    by 0x1E8B88: wdb_get_agents_ids_of_current_node (wdb_global_helpers.c:1161)
==17214==    by 0x12246E: w_remoted_clean_agents_state (state.c:242)
==17214==    by 0x121E85: rem_state_main (state.c:138)
==17214==    by 0x518A608: start_thread (pthread_create.c:477)
==17214==    by 0x52C4162: clone (clone.S:95)
```

This behavior makes Wazuh DB increase its opened socket descriptors as well for every opened connection from Analysisd and Remoted.

For every `state_interval` (which is 5 seconds by default), a request is made to Wazuh DB to get the agents status. For that request, a new socket descriptor was opened without closing it when the request was finished. 

To avoid this situation, now the socket is opened when starting the thread that handles the agents state, so it is reused every iteration.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Valgrind (memcheck and descriptor leaks check)

- [x] Added unit tests (for new features)
- [x] Stress test for affected components (Report [here](https://github.com/wazuh/wazuh/issues/15426#issuecomment-1324489006))
image

- Manual tests
- [x] Agents state is clean properly
- [x] Once applied the fix, no descriptor leak is found in affected components (Wazuh DB, Remoted and Analysisd)
- [x] Killing Wazuh DB doesn't produce any leaks. The connections are recovered when Wazuh DB is up again.

### CODE REVIEW

**Review by cborla — APPROVED** [review]
LGTM

**Review by sdvendramini — APPROVED** [review]
LGTM!

**Review by MarcelKemp — APPROVED** [review]
LGTM!

**Review by jmv74211 — APPROVED** [review]
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3632
- **Comments**:  https://github.com/wazuh/wazuh-qa/issues/3632#issuecomment-1333730744

**Pull request merged**
