### PR TITLE
Added validation for empty blobs in Azure wodle.

### PR DESCRIPTION
**Pull request by RamosFe**
|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/17510|

## Description
Backport Azure InvalidRange error fix from Issue https://github.com/wazuh/wazuh/issues/16866

### CODE REVIEW

**Review by GGP1 — CHANGES_REQUESTED** [review]
We should backport the modifications to the tests as well: https://github.com/wazuh/wazuh/pull/16805

**Comment by RamosFe** [comment]
> We should backport the modifications to the tests as well: #16805


After talking with the team, due to the test being part of another Issue https://github.com/wazuh/wazuh/issues/13390 that is not part of the release `4.4.5` we should not add the tests to this backport.

**Review by GGP1 — APPROVED** [review]
Considering we don't have to migrate tests and that the checks are failing due to the parent branch `4.4.5`, I approve these changes.

**Comment by RamosFe** [comment]
After rebasing with branch `4.4.5` all checks passed.

**Review by Selutario — CHANGES_REQUESTED** [review]
Tests that were modified as a result of the original change also have to be backported:
https://github.com/wazuh/wazuh/pull/16805/files#diff-7d48f81a012abae59c827d114e0f09f30d7588bb32e8b3096e2793257c6fad4f

**Review by Selutario — APPROVED** [review]

**Pull request merged**
