### PR TITLE
Dev 12481 Integrating new KVDB feature into engine

### PR DESCRIPTION
**Pull request by san1526**
|Related issue|
|---|
|#12481|

## Description
Integrating development branch of KVDB to the dev branch of the new Engine to close down the KVDB epic #12481

### CODE REVIEW

**Review by LucioDonda — APPROVED** [review]
LGTM

**Comment by LucioDonda** [comment]
Exploratory testing steps:

1. Create a file named "TEST_DB" (or as you choose to name the DB you need to use) with the next format:
```
key1:value1
key2:value2
key3:value3
```
Do not leave empty lines, _value<X>_ can be discarded (for only key DBs) but always use at least 1 ":" per line.
This file will be later used for the DB creation, the name you choose for it will be the DB name and each key-value pair it respective name value.

2. Move the file (or all of them) to `/var/ossec/queue/db/kvdb/legacy` this directory structure can be created, otherwise this directory can be defined on execution with the option _**--kvdbPath**_ and creating inside that path a directory called "legacy" where the files will be placed.

3. Inside _**decoder_test.yml**_ edit or add the helper functions needed ( **kvdb_extract** , **kvdb_match** or **kvdb_notmatch**) e.g:
```
name: decoder_test
check:
  - queue: +exists
  - location: +exists
  - message: +exists
  - fieldExtract: +kvdb_extract/TEST_DB_SHORT/key8
  - fieldMatch: +kvdb_match/TEST_DB_SHORT
  - fieldNotMatched: +kvdb_notmatch/TEST_ONLY_KEY_DB_SHORT
```

4. create the build directory, execute cmake and then build the engine with:
`make all `

5. Inside the build directory execute the engine as usual and leave it in the foreground on some specific terminal:
`$ sudo GLOG_logtostderr=1 ./main --file_storage ../test/assets/ --endpoint tcp:localhost:5054 --threads 1 -q 10000000
`
or with the directory option:
`$ sudo GLOG_logtostderr=1 ./main --file_storage ../test/assets/ --endpoint tcp:localhost:5054 --threads 1 --kvdbPath /home/lucho/Documents/TestsKVDB  -q 10000000
`  
If the process starts ok then it should print lines like the next:

```
09:05:33.194169 tcpEndpoint.cpp:138 INF[358966] TCP endpoint configured: [localhost:5054]
09:05:33.200317 kvdbManager.cpp:78 DBG[358968] adding DB with name [TEST_ONLY_KEY_DB_SHORT] to available Databases
09:05:33.380081 kvdb.cpp:278     DBG[358968] Successfull insert [key_1,] into DB [TEST_ONLY_KEY_DB_SHORT] CF [default]
09:05:33.380292 kvdbManager.cpp:78 DBG[358968] adding DB with name [TEST_DB_SHORT] to available Databases
09:05:33.554142 kvdb.cpp:278     DBG[358968] Successfull insert [key1,value1] into DB [TEST_DB_SHORT] CF [default]
```

6. Inside `/wazuh/src/engine/test/acceptance_test/utils` execute the benchmark_tool as usual:
`$ sudo go run benchmark_tool.go -o /tmp/filepath.txt -p tcp -s 127.0.0.1:5054 -t 5  -r 0 -b -i test_logs.txt
`
This will cause some debug lines to be printed on the engine terminal:
```
09:40:33.193743 kvdb.cpp:403     DBG[361792] Value obtained OK [key8,value8] from DB [TEST_DB_SHORT] CF [default]
09:40:33.193755 kvdb.cpp:403     DBG[361792] Value obtained OK [key8,value8] from DB [TEST_DB_SHORT] CF [default]
09:40:37.591241 tcpEndpoint.cpp:89 INF[361790] TCP EndEvent: Terminating connection.
09:40:37.591346 tcpEndpoint.cpp:96 INF[361790] TCP CloseEvent: Connection closed.

```
On the other terminal, where the benchmark tool is being executed it should show the benchmark report:
```
Benchmark report
----------------

Configuration:
Rate:         	    infinite events/sec
Time:         	           5 sec
Concurrent connections: 1
Dataset: test_logs.txt
Output:  /tmp/filepath.txt

Results:
Duration:           5.018689 seconds
Sent events:          434175
Processed events:     105140
Lost events:          329035

```
And in the file `/tmp/filepath.txt` the result of the execution, example line in pretty json format:
```

{
    "queue": 1,
    "location": ":
    [123] (hostname_test_bench) any->/var/some_location:",
    "message": "[Mon Jan 2 15:04:05 2006] host test_decoder_example[1234]: Test_example for acceptation test #27\r",
    "field2extract": "value8",
    "decoded":
    {
        "queue": "decoded_queue",
        "location": "decoded_location",
        "message": "decoded_message"
    },
    "index": "27\r",
    "locNum": "1234",
    "tloc": "test_decoder_example",
    "logLine": "Test_example for acceptation test ",
    "timestamp":
    {
        "seconds": "5",
        "hour": "15",
        "minutes": "4",
        "day": "2",
        "month": "1",
        "year": "2006"
    },
    "host": "host",
    "alerted":
    {
        "queue": "alerted_queue",
        "location": "alerted_location",
        "message": "alerted_message"
    }
}
```

**Review by juliancnn — APPROVED** [review]
LGTM! :rocket: :rocket:

**Review by JavierBejMen — APPROVED** [review]
LGTM!

**Comment by LucioDonda** [comment]
Benchmark Run without KVDB usage:
Screenshot from 2022-04-20 12-34-25


Run with KVDB usage:
Screenshot from 2022-04-20 12-30-03

**Pull request merged**
