### PR TITLE
Fix link count alerts for ignored directories

### PR DESCRIPTION
**Pull request by Hexta**
Fix alerts like "Files hidden inside directory '/a/b/c'. Link count does not match number of files" if there is ignored subdirectories in ossec.conf:
<ignore type="sregex">/b/c/d</ignore>.

|Related issue|
|---|
||

## Description

Do not skip counting of child directories if they are ignored.

## Configuration options

<rootcheck>
<ignore type="sregex">/b/c/d</ignore>
</rootcheck>

## Logs/Alerts example

** Alert 1581846806.102584252: - ossec,rootcheck,gdpr_IV_35.7.d,
2020 Feb 16 09:53:26 (XXX) 148.251.47.26->rootcheck
Rule: 510 (level 7) -> 'Host-based anomaly detection event (rootcheck).'
Files hidden inside directory '/a/b/c'. Link count does not match number of files (39,42).
title: Files hidden inside directory '/a/b/c'.

## Tests

Run and check alerts.

- Compilation without warnings in every supported platform
  - [X] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

### CODE REVIEW

**Comment by Hexta** [comment]
Could anybody please take a look at the PR?

**Comment by Lopuiz** [comment]
Hello Hexta,

Many thanks for your contribution!
We will put this PR in our task queue.
I hope it merges as soon as possible.

Best regards,
Eva

**Comment by Hexta** [comment]
Hello Eva @Lopuiz ,
Any updates?

**Comment by antoniomanuelfr** [comment]
Hi @Hexta! 

I have been  reviewing this PR and this what I have done:
## Tests 
- Compilation without warnings in every supported platform
  - [X] Linux
  - [X] Windows
  - [X] MAC OS X
  - [X] Source installation
  - [X] Source upgrade

- System resources
  - [X] CPU usage is normal.
  - [X] Memory usage is normal.
  - [X] I/O usage is normal.
  - [X] The fix doesn' t increase heavily the time of the rootcheck scan.

## Configuration used.

Default rootcheck configuration with an ignore tag:
`<ignore>/etc/dummy</ignore>`

## Previous alert
```
** Alert 1589886740.13269: - ossec,rootcheck,gdpr_IV_35.7.d,
2020 May 19 11:12:20 centosmanager->rootcheck
Rule: 510 (level 7) -> 'Host-based anomaly detection event (rootcheck).'
Files hidden inside directory '/etc'. Link count does not match number of files (78,79).
title: Files hidden inside directory '/etc'.
```
After the fix, this false negative isn' t generated. 

Thanks @Hexta for contributing to the wazuh project.
Regards

**Comment by vikman90** [comment]
@Hexta thank you very much for this fix! I've merged it into 3.13 for the next release 3.0.0.

Thanks to @antoniomanuelfr for his review.

**Pull request merged**
