### PR TITLE
Reduce modulesd CPU usage on systems with large routing tables

### LINKED ISSUE #7192: Wazuh-modulesd single CPU 100% utilisation
Hi,
I have upgraded my WAZUH installation to wazuh-agent 4.0.3-1 amd64 debian package managed by puppet.
Configuration is mostly default, just SCA and active responses are disabled.

I can see wazuh-modulesd process eating 100% of one CPU core on two of my servers.
Strace and lsof told me the wazuh-modulesd is busy reading /proc/PID/net/route files.
The problem is that those servers are actually BGP routers and each of the route files has over 800k lines.

Would it be possible just to skip them?

### PR DESCRIPTION
**Pull request by Molter73**
|Related issue|
|---|
|#7192|

## Description

This PR closes #7192. The high CPU usage of modulesd was due to logcollector and agentd querying the control module for the main IP of the agent quite often, in systems with large routing tables this could cause it to continuously read the routing table located at `/proc/net/route`. In order to solve this issue, logcollector now queries the main IP every `logcollector.vcheck_files` seconds (64 seconds by default) and agentd has a new configuration option (`ip_update_time`) which can be used to further tune how often it queries the control module (by default it will query every time a keep-alive message is sent).

## Configuration options

| Option name | Default value | Possible values|
|---|---|---|
| ip_update_interval | 0 | Positive integers |

Example configuration, update main ip every minute:
```xml
  <client>
    <server>
      <address>192.168.50.20</address>
      <port>1514</port>
      <protocol>udp</protocol>
    </server>
    <config-profile>ubuntu, ubuntu18</config-profile>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <ip_update_interval>60</ip_update_interval>
    <auto_restart>yes</auto_restart>
    <crypto_method>aes</crypto_method>
    <local_ip>10.0.2.15</local_ip>
  </client>
```

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation
- [x] Source upgrade
- [x] Review logs syntax and correct language
- [x] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Valgrind (memcheck and descriptor leaks check)

- [x] Configuration on demand reports new parameters
- [x] Added unit tests (for new features)

### CODE REVIEW

**Review by antoniomanuelfr — DISMISSED** [review]
LGTM!!

**Comment by Molter73** [comment]
I've run agentd integration tests and they passed correctly, here are the reports:

[agent_ubuntu_html_report_test_integration_B1293_20210216113248.zip](https://github.com/wazuh/wazuh/files/5988308/agent_ubuntu_html_report_test_integration_B1293_20210216113248.zip)
[agent_windows_html_report_test_integration_B1293_20210216113248.zip](https://github.com/wazuh/wazuh/files/5988309/agent_windows_html_report_test_integration_B1293_20210216113248.zip)
[agent_centos_html_report_test_integration_B1293_20210216113248.zip](https://github.com/wazuh/wazuh/files/5988310/agent_centos_html_report_test_integration_B1293_20210216113248.zip)

**Comment by Molter73** [comment]
I've run scan-build on agent and manager configurations and show 3 errors, but none is due to this PR. Scan-build on windows is currently failing due to a problem with the new C++ modules.

[scan-build-agent.zip](https://github.com/wazuh/wazuh/files/5989219/scan-build-agent.zip)
[scan-build-server.zip](https://github.com/wazuh/wazuh/files/5989220/scan-build-server.zip)

**Review by antoniomanuelfr — APPROVED** [review]
LGTM

**Review by vikman90 — APPROVED** [review]

**Pull request merged**
