### PR TITLE
Engine f5 apm afm new decoders

### LINKED ISSUE #15848: Create F5 decoder
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
It is necessary to extend the coverage of our ruleset, so a F5 decoder will be written for this purpose.

## DoD

- [x] Create decoder files.
- [x] Perform Validation and add to a testing environment.
- [x] Define testing policy. Manual testing.
- [x] Documentation.

### PR DESCRIPTION
**Pull request by JorgeMarinoDev**
## Description

With the aim of expanding the coverage of the decoders, this PR adds a decoder for F5 BigIp APM and AFM.

## Continue work from #16100

Huge rebase from 11334. Continue from scratch to a new branch.

## Configuration options

**Validate the new decoders**:

- main catalog validate decoder/f5-apm/0 < engine/ruleset/decoders/f5/f5-apm.yml
- main catalog validate decoder/f5-afm/0 < engine/ruleset/decoders/f5/f5-afm.yml

**Create decoders**:

- main catalog create decoder < engine/ruleset/decoders/f5/f5-apm.yml
- main catalog create decoder < engine/ruleset/decoders/f5/f5-afm.yml

**Update environment**:

- main catalog update environment/wazuh/0 < engine/ruleset/environments/wazuh-environment.yml

**Test new decoder**
- ./build/main test -q -1

## Tests

Event:
iusm modtempo olab6078.home olaboris tur itv [F5@odoco acl_policy_name=ria acl_policy_type=min acl_rule_name=ite action=Closed hostname=tatemac3541.api.corp bigip_mgmt_ip=10.228.193.207 context_name=liqua context_type=ciade date_time=Jan 29 2016 06:09:59 dest_ip=10.125.114.51 dst_geo=umq dest_port=2288 device_product=pexe device_vendor=nes device_version=1.2262 drop_reason=reveri errdefs_msgno=boNemoe errdefs_msg_name=equepor flow_id=eni ip_protocol=ipv6 severity=low partition_name=ehend route_domain=ritquiin sa_translation_pool=umqui sa_translation_type=reeufugi source_ip=10.208.121.85 src_geo=sperna source_port=884 source_user=billoi translated_dest_ip=10.165.201.71 translated_dest_port=6153 translated_ip_protocol=tatemU translated_route_domain=deF translated_source_ip=10.11.196.142 translated_source_port=5222 translated_vlan=iatnu vlan=3810

Output:
```
{
    "wazuh": {
        "queue": 49,
        "origin": "/dev/stdin"
    },
    "event": {
        "original": "iusm modtempo olab6078.home olaboris tur itv [F5@odoco acl_policy_name=ria acl_policy_type=min acl_rule_name=ite action=Closed hostname=tatemac3541.api.corp bigip_mgmt_ip=10.228.193.207 context_name=liqua context_type=ciade date_time=Jan 29 2016 06:09:59 dest_ip=10.125.114.51 dst_geo=umq dest_port=2288 device_product=pexe device_vendor=nes device_version=1.2262 drop_reason=reveri errdefs_msgno=boNemoe errdefs_msg_name=equepor flow_id=eni ip_protocol=ipv6 severity=low partition_name=ehend route_domain=ritquiin sa_translation_pool=umqui sa_translation_type=reeufugi source_ip=10.208.121.85 src_geo=sperna source_port=884 source_user=billoi translated_dest_ip=10.165.201.71 translated_dest_port=6153 translated_ip_protocol=tatemU translated_route_domain=deF translated_source_ip=10.11.196.142 translated_source_port=5222 translated_vlan=iatnu vlan=3810",
        "action": "Closed",
        "code": "boNemoe",
        "dataset": "f5.bigipafm",
        "module": "f5"
    },
    "@timestamp": "2016-01-29T06:09:59.000Z",
    "destination": {
        "geo": {
            "country_name": "umq"
        },
        "nat": {
            "ip": "10.165.201.71",
            "port": 6153
        },
        "port": 2288
    },
    "fileset": {
        "name": "bigipafm"
    },
    "host": {
        "ip": "10.228.193.207",
        "name": "tatemac3541.api.corp"
    },
    "input": {
        "type": "log"
    },
    "log": {
        "level": "low"
    },
    "network": {
        "protocol": "ipv6"
    },
    "observer": {
        "product": "pexe",
        "type": "Firewall",
        "vendor": "F5",
        "version": 1.2262
    },
    "related": {
        "hosts": [
            "tatemac3541.api.corp"
        ],
        "ip": [
            "10.228.193.207",
            "10.208.121.85",
            "10.165.201.71",
            "10.11.196.142"
        ],
        "user": [
            "billoi"
        ]
    },
    "rsa": {
        "internal": {
            "messageid": "BIGIP_AFM"
        },
        "investigations": {
            "ec_activity": "Disable",
            "ec_subject": "NetworkComm",
            "ec_theme": "Communication"
        },
        "misc": {
            "action": [
                "Closed"
            ],
            "context": "liqua",
            "event_type": "equepor",
            "obj_name": "odoco",
            "policy_name": "ria",
            "rule_name": "ite",
            "severity": "low",
            "version": 1.2262
        },
        "network": {
            "alias_host": [
                "tatemac3541.api.corp"
            ],
            "vlan": 3810
        },
        "time": {
            "event_time_str": "2016-01-29T06:09:59.000Z"
        }
    },
    "rule": {
        "name": "ite"
    },
    "service": {
        "type": "f5"
    },
    "source": {
        "geo": {
            "country_name": "sperna"
        },
        "ip": "10.208.121.85",
        "nat": {
            "ip": "10.11.196.142",
            "port": 5222
        },
        "port": 884
    },
    "tags": [
        "f5.bigipafm",
        "forwarded"
    ],
    "user": {
        "name": "billoi"
    }
}



```

### CODE REVIEW

**Comment by JorgeMarinoDev** [comment]
This PR replaces  https://github.com/wazuh/wazuh/pull/16100 
As we know 11334 original branch had many changes. Rebasing was done manually and a new branch was created to avoid merge issues.

image

**Comment by JorgeMarinoDev** [comment]
[Added](https://github.com/wazuh/wazuh/pull/16348/commits/828e2c1e8f57d93ef1c1f2a4a0454550067cff55) RSA fields to schema. RSA is a community and many networking hardware vendors adhere to standards using RSA algorithm. Might be used for sure for other vendors than F5.

**Review by cborla — APPROVED** [review]
LGTM

**Comment by cborla** [comment]
Moved to #16100,

**Pull request closed without merging**
