### PR TITLE
Fixed empty rule file checking

### PR DESCRIPTION
**Pull request by TJOSERAFAEL**
This PR solves the issue https://github.com/wazuh/wazuh/issues/883.

### CODE REVIEW

**Comment by vikman90** [comment]
Should this change apply to the rule parser for DBD?

Function `OS_ReadXMLRules()` at _src/shared/rule_op.c_.

**Comment by TJOSERAFAEL** [comment]
Hi @vikman90,

the latest commit has the functionality for `rule_op.c` added.

**Comment by chemamartinez** [comment]
Being a generic function to check if a file is empty, it makes sense that it is located at _shared/file_op.c_. This way we can use it whenever we want for the whole project.

**Comment by vikman90** [comment]
Awesome! 
GJ !!

**Pull request merged**
