### PR TITLE
Fix mapping template for AWS GuardDuty

### PR DESCRIPTION
**Pull request by UranusBytes**
Resolve issue of many GuardDuty findings failing to be indexed by Elasticsearch - wazuh/wazuh#1696

### CODE REVIEW

**Comment by UranusBytes** [comment]
Hi @druizz90 

So for the current 3.7 code without the fix, could you please try indexing the following raw GuardDuty event.  If this successfully parses and indexes for you, then I will do more research on my side.  

```
{"version":"0","id":"9d9e64ed-158b-c1af-05e7-b59c732ea762","detail-type":"GuardDuty Finding","source":"aws.guardduty","account":"123412341234","time":"2018-11-30T15:45:11Z","region":"us-east-1","resources":[],"detail":{"schemaVersion":"2.0","accountId":"123412341234","region":"us-east-1","partition":"aws","id":"fab3b2a4f4ee84b507a92fc5d3a39b81","arn":"arn:aws:guardduty:us-east-1:123412341234:detector/82b32f872d33980b486c57b7df0fdb13/finding/fab3b2a4f4ee84b507a92fc5d3a39b81","type":"UnauthorizedAccess:EC2/MaliciousIPCaller.Custom","resource":{"resourceType":"Instance","instanceDetails":{"imageId":"ami-123d30b6","instanceId":"i-12320eee","instanceType":"m3.2xlarge","launchTime":"2018-01-03T17:06:24Z","platform":null,"productCodes":[],"iamInstanceProfile":null,"networkInterfaces":[],"tags":[{"key":"Name","value":"myVM"}],"instanceState":"running","availabilityZone":"us-east-1b"}},"service":{"serviceName":"guardduty","detectorId":"82b32f872d33980b486c57b7df0fdb13","action":{"actionType":"NETWORK_CONNECTION","networkConnectionAction":{"connectionDirection":"INBOUND","remoteIpDetails":{"ipAddressV4":"196.52.43.120","organization":{"asn":"60781","asnOrg":"LeaseWeb Netherlands B.V.","isp":"LogicWeb Inc","org":"LogicWeb Inc"},"country":{"countryName":"United States"},"city":{"cityName":"Edison"},"geoLocation":{"lat":40.4981,"lon":-74.3194}},"remotePortDetails":{"port":52338,"portName":"Unknown"},"localPortDetails":{"port":443,"portName":"HTTPS"},"protocol":"TCP","blocked":false}},"resourceRole":"TARGET","additionalInfo":{"threatName":"Customer Threat Intel","threatListName":"OTX_Reputation"},"eventFirstSeen":"2018-11-30T15:41:16Z","eventLastSeen":"2018-11-30T15:42:15Z","archived":false,"count":1},"severity":5,"createdAt":"2018-11-30T15:43:22.077Z","updatedAt":"2018-11-30T15:43:22.077Z","title":"EC2 instance i-12320eee communicating with disallowed IP address.","description":"EC2 instance i-12320eee is communicating with a disallowed IP address 196.52.43.120 on the list OTX_Reputation."}}
```

Thanks,

Jeremy

**Comment by druizz90** [comment]
Hi @UranusBytes,

I had a problem changing templates, sorry. I have checked that we are losing events without your fix.

I found the files where this field appears (Kibana App repository):
```bash
# grep -ri "data.aws.service.action.networkConnectionAction.remoteIpDetails.geoLocation"
wazuh-kibana-app/server/integration-files/known-fields.js:      'data.aws.service.action.networkConnectionAction.remoteIpDetails.geoLocation.lat',
wazuh-kibana-app/server/integration-files/known-fields.js:      'data.aws.service.action.networkConnectionAction.remoteIpDetails.geoLocation.lon',```
```

By that, we should do changes. After upgrade the template, move the old index and create a new index, I obtain the next conflict with Kibana:



Nonetheless, I think we should accept your PR and open an issue for fix that in the future.

Thank you one more time @UranusBytes.

Best regards,

Demetrio.

**Comment by jesuslinares** [comment]
Hi team,

In summary:
- The current template is dropping **some** events due to the type.
- The proposed change looks right.
- If some events were indexed by Elastic, and we apply this new template, the events will be indexed but we will have **conflicts**.

The change is necessary but we need to analyze when we accept it ,since it is a "breaking change".

On the other hand, when we accept the change, we will open an issue for wazuh-kibana-app in order to change the following files:

> wazuh-kibana-app/server/integration-files/known-fields.js:      'data.aws.service.action.networkConnectionAction.remoteIpDetails.geoLocation.lat',
> wazuh-kibana-app/server/integration-files/known-fields.js:      'data.aws.service.action.networkConnectionAction.remoteIpDetails.geoLocation.lon',```

Thanks.

**Comment by jesuslinares** [comment]
This PR will be finally added in v3.8.

Thanks for your contribution and feedback.

**Pull request merged**
