### PR TITLE
get_date helper function added

### PR DESCRIPTION
**Pull request by NahuFigueroa97**
|Related issue|
|---|
|#27289|

## Description

A new helper function named get_date is required in Wazuh-Engine. This helper will not accept any arguments and should map the current date and time into a specified field in the format '%Y-%m-%dT%H:%M:%SZ'. This function aims to standardize date handling within the engine, ensuring consistent formatting for date/time values.

### CODE REVIEW

**Comment by NahuFigueroa97** [comment]
```
name: decoder/core-wazuh-message/0

metadata:
  module: wazuh
  title: Wazuh message decoder
  description: >
    Base decoder to process Wazuh message format, parses location part and enriches the events
    that comes from a Wazuh agent with the host information.
  compatibility: All wazuh events.
  versions:
    - Wazuh 5.*
  author:
    name: Wazuh, Inc.
    date: 22/11/2024
  references:
    - https://documentation.wazuh.com/

normalize:
  - map:
      - '@timestamp': get_date()
```

```
(venv) root@bad7a5170333:# engine-test run test-n system -dd 
Enter any events [ENTER to send event, CTRL+C to finish]:

some event


---
traces:
[🟢] decoder/core-wazuh-message/0 -> success
  ↳ @timestamp: get_date -> Success
[🟢] decoder/integrations/0 -> success
  ↳ event.original: exists -> Success
  ↳ tmp_json: parse_json($event.original) -> Parser parser failed at: some event
[🟢] output/file-output-integrations/0 -> success
  ↳ write.output(/var/log/wazuh-server/engine/alerts-ecs.json) -> Success

output:
  '@timestamp': '2024-12-16T15:10:14Z'
  agent:
    groups:
    - group1
    - group2
    host:
      architecture: x86_64
      hostname: wazuh-endpoint-linux
      ip:
      - 192.168.1.2
      os:
        name: Amazon Linux 2
        platform: Linux
    id: 2887e1cf-9bf2-431a-b066-a46860080f56
    name: wazuh-agent-name
    type: endpoint
    version: 5.0.0
  event:
    ingested: '2024-12-16T15:10:14Z'
    module: syslog
    original: some event
    provider: some
  tags:
  - production-server



Enter any events [ENTER to send event, CTRL+C to finish]:

other event


---
traces:
[🟢] decoder/core-wazuh-message/0 -> success
  ↳ @timestamp: get_date -> Success
[🟢] decoder/integrations/0 -> success
  ↳ event.original: exists -> Success
  ↳ tmp_json: parse_json($event.original) -> Parser parser failed at: other event
[🟢] output/file-output-integrations/0 -> success
  ↳ write.output(/var/log/wazuh-server/engine/alerts-ecs.json) -> Success

output:
  '@timestamp': '2024-12-16T15:11:05Z'
  agent:
    groups:
    - group1
    - group2
    host:
      architecture: x86_64
      hostname: wazuh-endpoint-linux
      ip:
      - 192.168.1.2
      os:
        name: Amazon Linux 2
        platform: Linux
    id: 2887e1cf-9bf2-431a-b066-a46860080f56
    name: wazuh-agent-name
    type: endpoint
    version: 5.0.0
  event:
    ingested: '2024-12-16T15:11:05Z'
    module: syslog
    original: other event
    provider: some
  tags:
  - production-server

```

**Review by juliancnn — APPROVED** [review]
LGTM!

Tested with pkg https://github.com/wazuh/wazuh/actions/runs/12355044639

## engine-test

```bash
╰─# engine-test -c engine-test-conf.json run apache-http-access -dd -n system

Enter any events [ENTER to send event, CTRL+C to finish]:

2a02:cf40:add:4002:91f2:a9b2:e09a:6fc6 - - [29/May/2021:19:02:48 +0200] "GET /A%20Beka%20G1%20Howe/029_AND_30/15%20reading%20elephants.mp4 HTTP/1.1" 200 612 "-" "Mozilla/5.0 (Windows NT 6.1; rv:15.0) Gecko/20120716 Firefox/15.0a2" X-Forwarded-For="10.225.192.17, 10.2.2.121"


---
traces:
[🟢] decoder/core-wazuh-message/0 -> success
  ↳ @timestamp: get_date -> Success
[🟢] decoder/integrations/0 -> success
  ↳ event.original: exists -> Success
  ↳ tmp_json: parse_json($event.original) -> Parser EOF failed at: a02:cf40:add:4002:91f2:a9b2:e09a:6fc6 - - [29/May/2021:19:02:48 +0200] "GET /A%20Beka%20G1%20Howe/029_AND_30/15%20reading%20elephants.mp4 HTTP/1.1" 200 612 "-" "Mozilla/5.0 (Windows NT 6.1; rv:15.0) Gecko/20120716 Firefox/15.0a2" X-Forwarded-For="10.225.192.17, 10.2.2.121"
[🟢] output/indexer/0 -> success
  ↳ write.output(wazuh-indexer/alerts) -> Success
[🟢] output/file-output-integrations/0 -> success
  ↳ write.output(/var/log/wazuh-server/engine/alerts-ecs.json) -> Success

output:
  '@timestamp': '2024-12-16T18:29:14Z'
  agent:
    groups:
    - group1
    - group2
    host:
      architecture: x86_64
      hostname: wazuh-endpoint-linux
      ip:
      - 192.168.1.2
      os:
        name: Amazon Linux 2
        platform: Linux
    id: 2887e1cf-9bf2-431a-b066-a46860080f56
    name: wazuh-agent-name
    type: endpoint
    version: 5.0.0
  client:
    ip: 10.225.192.17
  event:
    category:
    - web
    created: '2021-05-29T17:02:48.000Z'
    dataset: apache-access
    ingested: '2024-10-22T02:00:00Z'
    kind: event
    module: apache-http
    original: 2a02:cf40:add:4002:91f2:a9b2:e09a:6fc6 - - [29/May/2021:19:02:48 +0200]
      "GET /A%20Beka%20G1%20Howe/029_AND_30/15%20reading%20elephants.mp4 HTTP/1.1"
      200 612 "-" "Mozilla/5.0 (Windows NT 6.1; rv:15.0) Gecko/20120716 Firefox/15.0a2"
      X-Forwarded-For="10.225.192.17, 10.2.2.121"
    outcome: success
    provider: file
  http:
    request:
      method: GET
      referrer: '-'
    response:
      body:
        bytes: 612
      status_code: 200
    version: '1.1'
  log:
    file:
      path: /var/log/apache2/access.log
  network:
    forwarded_ip: 10.225.192.17
  service:
    type: apache
  source:
    address: 2a02:cf40:add:4002:91f2:a9b2:e09a:6fc6
    ip: 2a02:cf40:add:4002:91f2:a9b2:e09a:6fc6
  tags:
  - production-server
  url:
    extension: mp4
    original: /A%20Beka%20G1%20Howe/029_AND_30/15%20reading%20elephants.mp4
    path: /A%20Beka%20G1%20Howe/029_AND_30/15%20reading%20elephants.mp4
  user:
    name: '-'
  user_agent:
    original: Mozilla/5.0 (Windows NT 6.1; rv:15.0) Gecko/20120716 Firefox/15.0a2
  wazuh:
    decoders:
    - apache-access



Enter any events [ENTER to send event, CTRL+C to finish]:
```

## Opensearch

image

**Comment by JcabreraC** [comment]
## Test
Added new FH to enter the @timestamp field at the start of decoders:
```yml
name: decoder/core-wazuh-message/0 

metadata: 
  module: wazuh
  title: Wazuh message decoder
  description: >
    Base decoder to process Wazuh message format, parses location part and enriches the events
    that comes from a Wazuh agent with the host information.
  compatibility: All wazuh events.
  versions:
    - Wazuh 5.*
  author:
    name: Wazuh, Inc.
    date: 22/11/2024
  references:
    - https://documentation.wazuh.com/

normalize:
  - map:
      - '@timestamp': get_date()
```
Test run with `engine-test`:
```
# engine-test run test-n system -dd 
```
Output:
```json
Enter any events [ENTER to send event, CTRL+C to finish]:

Test event


---
traces:
[🟢] decoder/core-wazuh-message/0 -> success
  ↳ @timestamp: get_date -> Success
[🟢] decoder/integrations/0 -> success
  ↳ event.original: exists -> Success
  ↳ tmp_json: parse_json($event.original) -> Parser parser failed at: some event
[🟢] output/file-output-integrations/0 -> success
  ↳ write.output(/var/log/wazuh-server/engine/alerts-ecs.json) -> Success

output:
  '@timestamp': '2024-12-17T17:32:54Z'
  agent:
    groups:
    - group1
    - group2
    host:
      architecture: x86_64
      hostname: wazuh-engine
      ip:
      - 192.168.1.98
      os:
        name: Amazon Linux 2
        platform: Linux
    id: 2887e1cf-9bf2-431a-b066-a46860080f56
    name: wazuh-engine
    type: endpoint
    version: 5.0.0
  event:
    ingested: '2024-12-17T17:32:54Z'
    module: syslog
    original: Test event
    provider: test
  tags:
  - production-server
```

**Review by JcabreraC — APPROVED** [review]
LGTM !

**Pull request merged**
