### PR TITLE
Remove chroot from agent daemon

### PR DESCRIPTION
**Pull request by Molter73**
|Related issue|
|---|
|#2770|

## Description

Chroot jailing prevented agents from resolving host names after initialization, causing them to never connect to the manager if the DNS server was not available. This condition will be fixed by removing the chroot jailing from the agents.

## Tests

- Compilation without warnings in every supported platform
  - [X] Linux
  - [X] Windows
  - [x] MAC OS X
- [X] Source installation
- [X] Source upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [X] Scan-build report
https://github.com/wazuh/wazuh/pull/4241#issuecomment-557542952
  - [ ] Coverity
  - [X] Valgrind (memcheck and descriptor leaks check)
```
==30138== LEAK SUMMARY:
==30138==    definitely lost: 0 bytes in 0 blocks
==30138==    indirectly lost: 0 bytes in 0 blocks
==30138==      possibly lost: 1,088 bytes in 4 blocks
==30138==    still reachable: 91,921 bytes in 43 blocks
==30138==         suppressed: 0 bytes in 0 blocks
==30138== Reachable blocks (those to which a pointer was found) are not shown.
==30138== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==30138== 
==30138== For counts of detected and suppressed errors, rerun with: -v
==30138== ERROR SUMMARY: 4 errors from 4 contexts (suppressed: 0 from 0)
```
  - [X] AddressSanitizer
_No reports found_

- Memory tests for Windows
  - [X] Scan-build report
```
Done building winagent

make: Leaving directory '/mnt/c/Users/moltr/Documents/workspace/git/wazuh/src'
scan-build: Removing directory '/tmp/scan-build-2019-11-19-13-59-16-910199-8gmf4uar' because it contains no report.
```
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

### Tests run over tcp
- Reloading agent with no access to the DNS Server
```
2019/11/15 15:18:00 ossec-agentd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2019/11/15 15:18:09 ossec-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2019/11/15 15:18:09 ossec-agentd: INFO: Version detected -> Linux |centos-agent |4.18.0-80.11.2.el8_0.x86_64 |#1 SMP Tue Sep 24 11:32:19 UTC 2019 |x86_64 [CentOS Linux|centos: 8.0] - Wazuh v3.12.0
2019/11/15 15:18:09 ossec-agentd: INFO: (1410): Reading authentication keys file.
2019/11/15 15:18:09 ossec-agentd: INFO: Using AES as encryption method.
2019/11/15 15:18:09 ossec-agentd: INFO: Started (pid: 3792).
2019/11/15 15:18:09 ossec-agentd: INFO: Server IP Address: manager.wazuh.lan
2019/11/15 15:22:09 ossec-agentd: INFO: Trying to connect to server (manager.wazuh.lan/192.168.50.10:1514/tcp).
2019/11/15 15:22:09 ossec-agentd: INFO: (4102): Connected to the server (manager.wazuh.lan/192.168.50.10:1514/tcp).
```
- Stopping and starting the manager.
```
2019/11/18 18:35:45 ossec-agentd: INFO: (4102): Connected to the server (manager.wazuh.lan/192.168.50.10:1514/tcp).
2019/11/18 18:36:19 ossec-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
2019/11/18 18:36:28 ossec-agentd: INFO: Trying to connect to server (manager.wazuh.lan/192.168.50.10:1514/tcp).
2019/11/18 18:36:28 ossec-agentd: ERROR: (1216): Unable to connect to '192.168.50.10': 'Connection refused'.
2019/11/18 18:36:38 ossec-agentd: INFO: Trying to connect to server (manager.wazuh.lan/192.168.50.10:1514/tcp).
2019/11/18 18:36:38 ossec-agentd: ERROR: (1216): Unable to connect to '192.168.50.10': 'Connection refused'.
2019/11/18 18:36:48 ossec-agentd: INFO: Trying to connect to server (manager.wazuh.lan/192.168.50.10:1514/tcp).
2019/11/18 18:36:48 ossec-agentd: INFO: (4102): Connected to the server (manager.wazuh.lan/192.168.50.10:1514/tcp).
2019/11/18 18:36:48 ossec-agentd: INFO: Server responded. Releasing lock.
```
- Losing connection to the server and the DNS and later reconneting both.
```
2019/11/18 18:38:41 ossec-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
2019/11/18 18:39:23 ossec-agentd: INFO: Trying to connect to server (manager.wazuh.lan/192.168.50.10:1514/tcp).
2019/11/18 18:39:23 ossec-agentd: INFO: (4102): Connected to the server (manager.wazuh.lan/192.168.50.10:1514/tcp).
2019/11/18 18:39:23 ossec-agentd: INFO: Server responded. Releasing lock.
```
- Address specified as an IP, no DNS server running, manager stopped and then started.
```
2019/11/18 18:44:03 ossec-agentd: INFO: (4102): Connected to the server (192.168.50.10:1514/tcp).
2019/11/18 18:44:28 ossec-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
2019/11/18 18:44:37 ossec-agentd: INFO: Trying to connect to server (192.168.50.10:1514/tcp).
2019/11/18 18:44:37 ossec-agentd: ERROR: (1216): Unable to connect to '192.168.50.10': 'Connection refused'.
2019/11/18 18:44:47 ossec-agentd: INFO: Trying to connect to server (192.168.50.10:1514/tcp).
2019/11/18 18:44:47 ossec-agentd: ERROR: (1216): Unable to connect to '192.168.50.10': 'Connection refused'.
2019/11/18 18:44:57 ossec-agentd: INFO: Trying to connect to server (192.168.50.10:1514/tcp).
2019/11/18 18:44:57 ossec-agentd: INFO: (4102): Connected to the server (192.168.50.10:1514/tcp).
2019/11/18 18:44:57 ossec-agentd: INFO: Server responded. Releasing lock.
```
### Tests run over udp
- Reloading agent with no access to the DNS Server
```
2019/11/18 18:50:22 ossec-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2019/11/18 18:50:22 ossec-agentd: INFO: Version detected -> Linux |centos-agent |4.18.0-80.11.2.el8_0.x86_64 |#1 SMP Tue Sep 24 11:32:19 UTC 2019 |x86_64 [CentOS Linux|centos: 8.0] - Wazuh v3.12.0
2019/11/18 18:50:22 ossec-agentd: INFO: (1410): Reading authentication keys file.
2019/11/18 18:50:22 ossec-agentd: INFO: Using AES as encryption method.
2019/11/18 18:50:22 ossec-agentd: INFO: Started (pid: 11932).
2019/11/18 18:50:22 ossec-agentd: INFO: Server IP Address: manager.wazuh.lan
2019/11/18 18:54:12 ossec-agentd: INFO: Trying to connect to server (manager.wazuh.lan/192.168.50.10:1514/udp).
2019/11/18 18:54:13 ossec-agentd: INFO: (4102): Connected to the server (manager.wazuh.lan/192.168.50.10:1514/udp).
```
- Stop and starting the manager.
```
2019/11/18 18:54:13 ossec-agentd: INFO: (4102): Connected to the server (manager.wazuh.lan/192.168.50.10:1514/udp).
2019/11/18 18:56:04 ossec-agentd: WARNING: Server unavailable. Setting lock.
2019/11/18 18:56:04 ossec-agentd: WARNING: Process locked due to agent is offline. Waiting for connection...
2019/11/18 18:56:14 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 18:56:26 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 18:56:27 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: 'manager.wazuh.lan/192.168.50.10'.
2019/11/18 18:56:29 ossec-agentd: INFO: Trying to connect to server (manager.wazuh.lan/192.168.50.10:1514/udp).
2019/11/18 18:56:39 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 18:56:51 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 18:56:52 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: 'manager.wazuh.lan/192.168.50.10'.
2019/11/18 18:57:03 ossec-agentd: INFO: Trying to connect to server (manager.wazuh.lan/192.168.50.10:1514/udp).
2019/11/18 18:57:04 ossec-agentd: INFO: (4102): Connected to the server (manager.wazuh.lan/192.168.50.10:1514/udp).
2019/11/18 18:57:04 ossec-agentd: INFO: Server responded. Releasing lock.
2019/11/18 18:57:09 ossec-agentd: INFO: Agent is now online. Process unlocked, continuing...
```
- Losing connection to the server and the DNS and later reconnecting both.

Starting DNS first
```
2019/11/18 19:00:35 ossec-agentd: WARNING: Server unavailable. Setting lock.
2019/11/18 19:00:35 ossec-agentd: WARNING: Process locked due to agent is offline. Waiting for connection...
2019/11/18 19:00:45 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 19:00:57 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 19:00:58 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: 'manager.wazuh.lan/192.168.50.10'.
2019/11/18 19:02:24 ossec-agentd: INFO: Trying to connect to server (manager.wazuh.lan/192.168.50.10:1514/udp).
2019/11/18 19:02:34 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 19:02:46 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 19:02:47 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: 'manager.wazuh.lan/192.168.50.10'.
2019/11/18 19:02:58 ossec-agentd: INFO: Trying to connect to server (manager.wazuh.lan/192.168.50.10:1514/udp).
2019/11/18 19:03:08 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 19:03:20 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: 'manager.wazuh.lan/192.168.50.10'.
2019/11/18 19:03:31 ossec-agentd: INFO: Trying to connect to server (manager.wazuh.lan/192.168.50.10:1514/udp).
2019/11/18 19:03:32 ossec-agentd: INFO: (4102): Connected to the server (manager.wazuh.lan/192.168.50.10:1514/udp).
2019/11/18 19:03:32 ossec-agentd: INFO: Server responded. Releasing lock.
2019/11/18 19:03:35 ossec-agentd: INFO: Agent is now online. Process unlocked, continuing...
```
Restarting the manager first
```
2019/11/18 19:02:47 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: 'manager.wazuh.lan/192.168.50.10'.
2019/11/18 19:02:58 ossec-agentd: INFO: Trying to connect to server (manager.wazuh.lan/192.168.50.10:1514/udp).
2019/11/18 19:03:08 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 19:03:20 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: 'manager.wazuh.lan/192.168.50.10'.
2019/11/18 19:03:31 ossec-agentd: INFO: Trying to connect to server (manager.wazuh.lan/192.168.50.10:1514/udp).
2019/11/18 19:03:32 ossec-agentd: INFO: (4102): Connected to the server (manager.wazuh.lan/192.168.50.10:1514/udp).
2019/11/18 19:03:32 ossec-agentd: INFO: Server responded. Releasing lock.
2019/11/18 19:03:35 ossec-agentd: INFO: Agent is now online. Process unlocked, continuing...
2019/11/18 19:05:24 ossec-agentd: WARNING: Server unavailable. Setting lock.
2019/11/18 19:05:24 ossec-agentd: WARNING: Process locked due to agent is offline. Waiting for connection...
2019/11/18 19:05:34 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 19:05:46 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 19:05:47 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: 'manager.wazuh.lan/192.168.50.10'.
2019/11/18 19:11:41 ossec-agentd: INFO: Trying to connect to server (manager.wazuh.lan/192.168.50.10:1514/udp).
2019/11/18 19:11:42 ossec-agentd: INFO: (4102): Connected to the server (manager.wazuh.lan/192.168.50.10:1514/udp).
2019/11/18 19:11:42 ossec-agentd: INFO: Server responded. Releasing lock.
2019/11/18 19:11:44 ossec-agentd: INFO: Agent is now online. Process unlocked, continuing...
```
Address specified as an IP, no DNS server running, manager stopped and then started.
```
2019/11/18 19:13:02 ossec-agentd: INFO: (4102): Connected to the server (192.168.50.10:1514/udp).
2019/11/18 19:13:22 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 19:14:13 ossec-agentd: WARNING: Server unavailable. Setting lock.
2019/11/18 19:14:13 ossec-agentd: WARNING: Process locked due to agent is offline. Waiting for connection...
2019/11/18 19:14:23 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 19:14:35 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 19:14:36 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: '192.168.50.10'.
2019/11/18 19:14:38 ossec-agentd: INFO: Trying to connect to server (192.168.50.10:1514/udp).
2019/11/18 19:14:48 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 19:15:00 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2019/11/18 19:15:01 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: '192.168.50.10'.
2019/11/18 19:15:12 ossec-agentd: INFO: Trying to connect to server (192.168.50.10:1514/udp).
2019/11/18 19:15:13 ossec-agentd: INFO: (4102): Connected to the server (192.168.50.10:1514/udp).
2019/11/18 19:15:13 ossec-agentd: INFO: Server responded. Releasing lock.
2019/11/18 19:15:18 ossec-agentd: INFO: Agent is now online. Process unlocked, continuing...
```

### CODE REVIEW

**Comment by Molter73** [comment]
@wazuhci run scan-build -maxloop=10 custom-flag="--track-origins=yes --leak-check=full --keep-stacktraces=alloc-and-free --show-leak-kinds=definite,indirec" -source-target=agent

**Comment by wazuhci** [comment]
## scan-build analysis:
Commit: dd32a186048af5ac6eaaaaf8eb406f4cb8a294eb
Parameters: --track-origins=yes --leak-check=full --keep-stacktraces=alloc-and-free --show-leak-kinds=definite,indirec
Result: [here](https://ci.wazuh.com/data/Analysis_static_scanbuild/wazuh/v3.12.0/B2/scan-build-v3.12.0-4241.zip)

**Comment by Molter73** [comment]
@wazuhci run scan-build -maxloop=10 custom-flag="--track-origins=yes --leak-check=full --keep-stacktraces=alloc-and-free --show-leak-kinds=definite,indirec" -source-target=agent

**Comment by wazuhci** [comment]
## scan-build analysis:
Commit: 854f8914507b21926710a40b0c234da9a340eaaa
Parameters: --track-origins=yes --leak-check=full --keep-stacktraces=alloc-and-free --show-leak-kinds=definite,indirec
Result: [here](https://ci.wazuh.com/data/Analysis_static_scanbuild/wazuh/v3.12.0/B3/scan-build-v3.12.0-4241.zip)

**Pull request merged**
