### PR TITLE
Remove & Change doc_type for elasticsearch

### PR DESCRIPTION
**Pull request by Lunatictwo**
We need to remove "document_type" in logstash-elasticsearch-output because doc_type will be deprecated in elasticsearch 7.x, and in logstash-output-elasticsearch(v 9.0.0), the default doc_type send to es was set to 'doc'. 

referrer:
https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html
https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/v9.2.4/CHANGELOG.md#900

### CODE REVIEW

**Comment by jesusgn90** [comment]
Hi @Lunatictwo, 

Thanks for your contribution. We already know about this issue, and we are going to remove it for 7.0.0, we can't break the template or the existing installations until a major version of Elasticsearch.

Regards

**Comment by root360-AndreasUlm** [comment]
Hi @jesusgn90,

with ES 6.6.x Elasticsearch already implemented this breaking change.
Without applying this patch you cannot use the configuration as ES denies indexing the messages, see #3032.

Can you plan merging ealier?

Regards,
Andreas

**Comment by jesusgn90** [comment]
Hi @root360-AndreasUlm , we are currently working with types up to 6.7.1 with no issues, just the warning message. We are planning to modify all the integration for 7.0 (https://github.com/wazuh/wazuh-kibana-app/projects/15)

**Comment by jesusgn90** [comment]
Hello again @root360-AndreasUlm,

We are almost ready for Elastic 7, here you can see some details:

- https://github.com/wazuh/wazuh/tree/elastic-7/extensions these are the configuration files and the alerts template adapted, you can identify the new files because they include `-7` in the file name.
- Here https://github.com/wazuh/wazuh-kibana-app/issues/1382, we explained some changes about those configuration files.
- Here you can see all the tasks involved in this development https://github.com/wazuh/wazuh-kibana-app/projects/15

I think this PR is no longer needed and I'm going to close it, with the recently 3.9.0 version of Wazuh we are planning to release the Wazuh app for Elastic 7 as soon as possible, in any case, I can provide you a beta app or you can check out the branch https://github.com/wazuh/wazuh-kibana-app/tree/3.9-7.0 which will be the numbered branch for the `wazuhapp-3.9.0_7.0.0.zip` package. 

We are here to help, ask us anything you want about Wazuh or the Elastic stack. And as a reminder, we are on Slack too, just in case you are not on Slack yet here is the link https://wazuh.com/community/join-us-on-slack/, there we can discuss on chat.

Best regards,
Jesús

**Pull request closed without merging**
