### PR TITLE
Fixed wrong engine vs schema helper pattern and QoL changes

### PR DESCRIPTION
**Pull request by JavierBejMen**
|Related issue|
|---|
|#23952|

- This PR fixes the vs schema helper pattern to recognize latest format.
- Changed module to integration in asset metadata.
- QoL in engine-schema py script.

### CODE REVIEW

**Review by juliancnn — CHANGES_REQUESTED** [review]
I have noticed some details. Is it possible to fix them?

1.  `parse|field`: There are errors in the stage parse: 

image

2. End of string is not checked in the regex of the helpers functions

image

3. Only the 3er case should be valid:

image
4. Only 1 and 2 case should be valid:
image

5. Should Byte support floats if it is long?

image

**Comment by JavierBejMen** [comment]
## Update
Fixed end of string in helper and ref pattern
Fixed parse item definition in schema
Ip not included as it will be overkill to create a regex to match all possible IP formats
Float distinction not included as in json only number is available

**Review by juliancnn — APPROVED** [review]
LGTM!

**Review by NahuFigueroa97 — APPROVED** [review]
LGTM!

**Review by JcabreraC — APPROVED** [review]
LGTM !

**Pull request merged**
