### PR TITLE
analysisd: Fix Missing fields in rules description evaluation

### PR DESCRIPTION
**Pull request by juliancnn**
|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/7044|

Hi team!,

This PR fix the `description` output in rules evaluation.

## Description

When variables are used in the `description` option, the `dstgeoip` and `dstport` variables are never filled. This does not affect the evaluation of the rule but the output of the alert.

## Wazuh-Logtest Output

simple example for test

**decoders**
```xml
<decoder name="example">
  <program_name>^example</program_name>
</decoder>

<decoder name="example">
  <parent>example</parent>
  <regex>User '(\w+)' logged from '(\d+.\d+.\d+.\d+):(\d+)' to '(\d+.\d+.\d+.\d+):(\d+)'</regex>
  <order>user, srcip, srcport, dstip, dstport</order>
</decoder>
```

**rules**
```xml
  <rule id="100010" level="0">
  <program_name>example</program_name>
  <description>User logged from $(srcip):$(srcport) to $(dstip):$(dstport)[$(dstgeoip)] </description>
</rule>
```

**test log**
```console
Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '8.8.8.8:55000' to '200.16.19.1:22'
```
### Current output

missing `dstgeoip` and `dstport` in description (Phase 3)
```
Starting wazuh-logtest v4.2.0
Type one log per line
Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '8.8.8.8:55000' to '200.16.19.1:22'
**Phase 1: Completed pre-decoding.
        full event: 'Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '8.8.8.8:55000' to '200.16.19.1:22''
        timestamp: 'Dec 25 20:45:02'
        hostname: 'MyHost'
        program_name: 'example'
**Phase 2: Completed decoding.
        name: 'example'
        dstip: '200.16.19.1'
        dstport: '22'
        dstuser: 'admin'
        srcip: '8.8.8.8'
        srcport: '55000'
**Phase 3: Completed filtering (rules).
        id: '100010'
        level: '0'
        description: 'User logged from 8.8.8.8:55000 to 200.16.19.1:[] '
        groups: '['local', 'syslog', 'sshd']'
        firedtimes: '1'
        mail: 'False'
```

### PR output

```
Starting wazuh-logtest v4.2.0
Type one log per line

Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '8.8.8.8:55000' to '200.16.19.1:22'

**Phase 1: Completed pre-decoding.
        full event: 'Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '8.8.8.8:55000' to '200.16.19.1:22''
        timestamp: 'Dec 25 20:45:02'
        hostname: 'MyHost'
        program_name: 'example'

**Phase 2: Completed decoding.
        name: 'example'
        dstip: '200.16.19.1'
        dstport: '22'
        dstuser: 'admin'
        srcip: '8.8.8.8'
        srcport: '55000'

**Phase 3: Completed filtering (rules).
        id: '100010'
        level: '0'
        description: 'User logged from 8.8.8.8:55000 to 200.16.19.1:22[AR / Cordoba] '
        groups: '['local', 'syslog', 'sshd']'
        firedtimes: '1'
        mail: 'False'
```

## Tests

- [X] `runtest.py -c -g`
- Compilation without warnings in every supported platform
  - [X] Linux
  - [x] ~~Windows~~
  - [x] ~~MAC OS X~~
- [X] Source installation
- [X] Package installation

- Memory tests for Linux
  - [X] Scan-build report
  - [x] ~~Coverity~~
  - [X] Valgrind (memcheck and descriptor leaks check)
  - [x] ~~Dr. Memory~~
  - [x] ~~AddressSanitizer~~
 - ~~Memory tests for Windows~~
- ~~Memory tests for macOS~~

- [X] Retrocompatibility with older Wazuh versions
- [X] Working on cluster environments
- [x] ~~Configuration on demand reports new parameters~~
- [X] The data flow works as expected (agent-manager-api-app)

### CODE REVIEW

**Review by jnasselle — CHANGES_REQUESTED** [review]
Hi @juliancnn !

This changes still doesn't fix the use of static fields like `program_name`, `hostname` and `location`. Could you please add them in order to have full support?

Regards,
Nico

**Comment by juliancnn** [comment]
> Hi @juliancnn !
> 
> This changes still doesn't fix the use of static fields like `program_name`, `hostname` and `location`. Could you please add them in order to have full support?
> 
> Regards,
> Nico

Hi @jnasselle,

You're right, `hostname` and `program_name` was added in the last commit.
@chemamartinez suggested not adding the location field, since this is an internal Wazuh data that is not decoded from log

Regards,
Juli

**Comment by juliancnn** [comment]
## New test rule:

```xml
  <rule id="100010" level="0">
    <program_name>example</program_name>
    <description>User logged from $(srcip):$(srcport) to $(dstip):$(dstport)[$(dstgeoip)] - program_name: '$(program_name)' hostname '$(hostname)'</description>
  </rule>

```

## PR output
```console
Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '8.8.8.8:55000' to '200.16.19.1:22'

**Phase 1: Completed pre-decoding.
        full event: 'Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '8.8.8.8:55000' to '200.16.19.1:22''
        timestamp: 'Dec 25 20:45:02'
        hostname: 'MyHost'
        program_name: 'example'

**Phase 2: Completed decoding.
        name: 'example'
        dstip: '200.16.19.1'
        dstport: '22'
        dstuser: 'admin'
        srcip: '8.8.8.8'
        srcport: '55000'

**Phase 3: Completed filtering (rules).
        id: '100010'
        level: '0'
        description: 'User logged from 8.8.8.8:55000 to 200.16.19.1:22[] - program_name: 'example' hostname 'MyHost''
        groups: '['local', 'syslog', 'sshd']'
        firedtimes: '1'
        mail: 'False'

```

**Review by jnasselle — APPROVED** [review]
LGTM!

**Review by Lopuiz — APPROVED** [review]

**Review by JcabreraC — APPROVED** [review]

**Pull request merged**
