### PR TITLE
Fix error parsing ':' character in CDB lists

### PR DESCRIPTION
**Pull request by mcarmona99**
**Related issue**
#5690 

Hi team,

This PR closes https://github.com/wazuh/wazuh/issues/5690. In this PR i have solved the parsing error of character `:` in CDB lists.
Now you can write the keys and/or the values surrounded by quotes so keys and/or values with the character `:` will be possible, too.

**EXAMPLES:**

In order to replicate the error and solve it, I have monitored files with FIM using a cdb list.
Some examples of possible combinations:
- File in `/var/ossec/etc/lists/fim-file-classification`
```
"/t/example::1":"medium"
"/t/example:2":medium
/t/example3:"medium"
/t/example4:medium
```

- API response for `GET /lists`:

```
curl -k -X GET "https://localhost:55000/lists?limit=500&filename=fim-files-classification" -H "accept: application/json" -H "Authorization: Bearer $TOKEN"

{
  "data": {
    "affected_items": [
      {
        "items": [
          {
            "key": "/t/example::1",
            "value": "medium"
          },
          {
            "key": "/t/example:2",
            "value": "medium"
          },
          {
            "key": "/t/example3",
            "value": "medium"
          },
          {
            "key": "/t/example4",
            "value": "medium"
          }
        ],
        "relative_dirname": "etc/lists",
        "filename": "fim-files-classification"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All specified lists were shown"
}
```

As it can be seen, all the possible combinations work and the API request is correct.

-Things that will raise an exception:
```
a"/t/example::1":"medium"
"/t/example::1"b:"medium"
"/t/example::1":c"medium"
"/t/example:2"d:medium
/t/example3:"medium"e
   .   .   .   .   .   .
```

**TEST RESULTS**

New test cases added to core/.../test_cdb_list.py and to core/.../test_utils.py.

```
framework/wazuh/core/tests/test_cdb_list.py 
============================== 22 passed in 0.12s ==============================

framework/wazuh/core/tests/test_utils.py 
============================= 199 passed in 0.64s ==============================
```

### CODE REVIEW

**Review by davidjiglesias — CHANGES_REQUESTED** [review]
Move code inside to another function

**Comment by mcarmona99** [comment]
**CHANGES**
- New function `split_key_value_with_quotes` in order to make `get_list_from_file` shorter.
- New test case for the function `split_key_value_with_quotes`.
- Some if statements changed in order to remove redundant code.
- Third and fourth quotes indexes calculated only when necessary.
- New line format for CDB lists available: 
```
     "example:1":my:value
     Before: key = example:1, value = value
     Now: key = example:1, value = my:value
```

**TEST RESULTS**
- Unit tests:
```
framework/wazuh/core/tests/test_cdb_list.py 
============================== 26 passed in 0.13s ==============================

framework/wazuh/core/tests/test_utils.py 
============================= 199 passed in 0.75s ==============================
```
- API integration test for CDB lists:

```
python3 api/test/integration/run_tests.py -k lists

test_lists_endpoints.tavern.yaml 
	 2 passed, 4 warnings

test_rbac_black_lists_endpoints.tavern.yaml 
	 2 passed, 4 warnings

test_rbac_white_lists_endpoints.tavern.yaml 
	 2 passed, 4 warnings
```

**Review by davidjiglesias — CHANGES_REQUESTED** [review]
All good, I am only missing Unit Test Cases for the 1800 exception in the different cases

**Comment by mcarmona99** [comment]
**REVIEW** CHANGES:
 
Added unit test cases for the 1800 exception.

Examples added to `core/tests/test_cdb_list.py`:
```
Line: '"example:4":a"value:4"'
Line: '"example:5":"value:5"a'
Line: 'a"example:6":"value:6"'
Line: 'a"example:7":value7'
Line: '"example:8"a:value8'
Line: 'example9:a"value:9"'
Line: 'example10:"value:10"a'
```

All of them raises the expected WazuhError, with code 1800.

**Test results:**

```
framework/wazuh/core/tests/test_cdb_list.py
============================== 33 passed in 0.13s ==============================

framework/wazuh/tests/test_cdb_list.py 
============================== 47 passed in 0.32s ==============================

test_lists_endpoints.tavern.yaml 
	 2 passed, 4 warnings

test_rbac_black_lists_endpoints.tavern.yaml 
	 2 passed, 4 warnings

test_rbac_white_lists_endpoints.tavern.yaml 
	 2 passed, 4 warnings
```

**Review by davidjiglesias — APPROVED** [review]

**Pull request merged**
