### PR TITLE
Remove legacy code after engine vd integration

### LINKED ISSUE #25318: Project cleanup after VD integration into the engine project building
## Description
This issue aims to iterate over the project cleanup/removal after incorporating VD into the engine process building.

We expect the removal of some pending files and folders from the wazuh/src path.

ex:
- active response
- ci/fim (syscollector rtr)
- config
- data_provider
- headers
- dbsync
- rsync
- router
- c unittests

### PR DESCRIPTION
**Pull request by Dwordcito**
|Related issue|
|---|
|Closes #25318|

### Description
This pr aims to remove some unused and legacy components, after the vd integration into the engine build system.

### CODE REVIEW

**Review by juliancnn — CHANGES_REQUESTED** [review]
1. Shouldn't the `src/Makefile` file be deleted?
2. Inside `./ruleset` you should remove `decoders`, `list`, `mitre`, `rules` and `testing` and leave `sca` and `rootcheck` if you want to leave them. 
3. The ./src/init folder has the installation right? Shouldn't we delete it and start from scratch?

**Review by sebasfalcone — DISMISSED** [review]
Shoulnd't the wazuhDB files be removed?
```
wazuhDBQuery
├── argsParser.hpp
├── CMakeLists.txt
├── config.json
└── main.cpp
                
── wazuhDBQueryBuilder_test.cpp
── wazuhDBQueryBuilder_test.hpp  
── wazuhDBQueryBuilder.hpp              
```

**Comment by Dwordcito** [comment]
> Shoulnd't the wazuhDB files be removed?
> 
> ```
> wazuhDBQuery
> ├── argsParser.hpp
> ├── CMakeLists.txt
> ├── config.json
> └── main.cpp
>                 
> ── wazuhDBQueryBuilder_test.cpp
> ── wazuhDBQueryBuilder_test.hpp  
> ── wazuhDBQueryBuilder.hpp              
> ```

Good catch

**Review by juliancnn — APPROVED** [review]
LGTM!

**Review by sebasfalcone — CHANGES_REQUESTED** [review]
What about:
```
─ windowsHelper.h
─ windowsHelper_test.cpp
─ windowsHelper_test.h
─ encodingWindows_test.cpp
─ encodingWindows_test.h
─ encodingWindowsHelper.h
─ osPrimitivesImplMac.h
─ osPrimitivesInterfaceMac.h
─ registryHelper.h
─ sqliteWrapperTemp.h
─ sqliteWrapperTempMock.h
```

**Pull request merged**
