### PR TITLE
Fix issues reported by scan-build

### PR DESCRIPTION
**Pull request by JuantAldea**
|Related issue|
|---|
|#3774|

## Description
This PR fixes the issues reported by scan-build while building in MacOS

Bug Group | Bug Type | File | Function/Method | Line | Fixed in
-- | -- | -- | -- | -- | --
Logic error | Dereference of null pointer | os_xml/os_xml.c | _xml_sgetc | 52 | Won't fix. Also disappears when scanning with a newer llvm (in Linux)
Logic error | Dereference of null pointer | os_regex/os_regex_execute.c | OSRegex_Execute_ex | 118 | Won't fix. Also disappears when scanning with a newer llvm (in Linux)
Memory Error | Memory leak | syscheckd/create_db.c | read_dir | 760 | Already fixed in 3.9
Unix API | Allocator sizeof operand mismatch | wazuh_modules/syscollector/syscollector_bsd.c | getGatewayList | 1255 | #3773
Unix API | Undefined allocation of 0 bytes (CERT MEM04-C; CWE-131) | wazuh_modules/wm_control.c | getPrimaryIP | 51 | #3773
Memory Error | Memory leak | wazuh_modules/syscollector/syscollector_bsd.c | getGatewayList | 1307 | #3773
Dead store | Dead assignment | addagent/main.c | main | 175 | 2ddd149a196a60c6b18213ba1a3b7fc936a71fd8, #3795
Memory Error | Memory leak | wazuh_modules/syscollector/syscollector_bsd.c | sys_hw_bsd | 572 | 70b3def6e074f4fcb0f6177cec691463e1fc6a7a, #3795
Memory Error | Memory leak | wazuh_modules/syscollector/syscollector_bsd.c | sys_hw_bsd | 586 | 5744ae0f27e9e37c08c8426f8b3903285b538eeb, #3795
API | Argument with 'nonnull' attribute passed null | os_execd/config.c | getClusterConfig | 331 | 5f9a5116921812646e12ed6b07803a449b73e9ef
Memory error | Nullability | wazuh_modules/wm_osquery_monitor.c | wm_osquery_monitor_main | 619 | bacf62a37d746834f07bcfa83e08d586df781544
Logic error | Uninitialized argument value | wazuh_modules/wm_exec.c | wm_exec | 298 | 958d474d4d007ac7962e760c040a0f64e9bea50a
API | Argument with 'nonnull' attribute passed null | os_execd/execd.c | ExecdStart | 507 | be77f158c7c37c4af1147c7ff7b675f373d55b35

# Fix rationale

- Argument with 'nonnull' attribute passed null	os_execd/config.c	getClusterConfig	331
    * Missing early return on failure, leading to parsing an invalid pointer.
- Dead assignment addagent/main.c main 175
    * Unused variable when builiding the agent.
- Memory leak  wazuh_modules/syscollector/syscollector_bsd.c  sys_hw_bsd  572
    * String not released. String duplication is unnecesary as `OS_StrBreak`  does not modify the original string.
- Memory leak  wazuh_modules/syscollector/syscollector_bsd.c  sys_hw_bsd  586
    * String not released.
- Nullability  wazuh_modules/wm_osquery_monitor.c wm_osquery_monitor_main 619
    * False positive. "Fixed" after little refactoring.
- Uninitialized argument value	wazuh_modules/wm_exec.c	wm_exec	298	
    *  Because boolean expresions use Short-Circuit Evaluation, if output evaluates to false pipe() is not executed and w_descriptor_cloexec(pipe_fd[0]); is called with an undefined pipe_fd.
- Argument with 'nonnull' attribute passed null  os_execd/execd.c  ExecdStart  507
   * There's an invalid acess (leading to a SEGFAULT), that can be triggered by with incomplete timeout information, as commands are assumed to have 4 components (`timeout_args[0-3]`)

## Tests
With this set of changes, scan-build reports only those marked as "Won't fix"

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [x] MAC OS X
- Memory tests
  - [x] Valgrind report for affected components
  - [x] RAM usage impact
- [ ] Working on cluster environments
- [x] Review logs syntax and correct language

### CODE REVIEW

**Comment by chemamartinez** [comment]
Some of the fixes of this PR have been added to 3.9.4 at https://github.com/wazuh/wazuh/pull/3795. The others will be merged to 3.10.

**Comment by JuantAldea** [comment]
# Fuzzing of execd
Using variations of `echo -n '!script.sh 1234 1234 2134' | nc -Uu /var/ossec/queue/alerts/execq`
```
2019/08/06 13:26:36 ossec-execd[783] config.c:146 at ExecdConfig(): INFO: Adding offenders timeout: 30 (for #1)
2019/08/06 13:26:36 ossec-execd[783] config.c:146 at ExecdConfig(): INFO: Adding offenders timeout: 5 (for #2)
2019/08/06 13:26:36 ossec-execd[783] config.c:146 at ExecdConfig(): INFO: Adding offenders timeout: 10 (for #3)
2019/08/06 13:26:36 ossec-execd[783] pthreads_op.c:45 at CreateThreadJoinable(): DEBUG: Thread stack size set to: 8192 KiB
2019/08/06 13:26:36 ossec-execd[783] wcom.c:655 at wcom_main(): DEBUG: Local requests thread ready
2019/08/06 13:26:36 ossec-execd[783] execd.c:187 at main(): INFO: Started (pid: 783).
2019/08/06 13:26:45 ossec-execd[783] execd.c:365 at ExecdStart(): DEBUG: Received message: 'firewall-drop1000 500 1'
2019/08/06 13:26:45 ossec-execd[783] exec.c:102 at ReadExecConfig(): INFO: Active response command not present: '/var/ossec/active-response/bin/restart-ossec.cmd'. Not using it on this system.
2019/08/06 13:26:45 ossec-execd[783] execd.c:462 at ExecdStart(): ERROR: (1311): Invalid command name 'firewall-drop1000' provided.
2019/08/06 13:26:52 ossec-execd[783] execd.c:365 at ExecdStart(): DEBUG: Received message: 'firewall-drop1000 500 1 asdhfasjhfkja'
2019/08/06 13:26:52 ossec-execd[783] execd.c:462 at ExecdStart(): ERROR: (1311): Invalid command name 'firewall-drop1000' provided.
2019/08/06 13:26:58 ossec-execd[783] execd.c:365 at ExecdStart(): DEBUG: Received message: 'firewall-drop100 500 1 asdhfasjhfkja'
2019/08/06 13:26:58 ossec-execd[783] execd.c:588 at ExecdStart(): DEBUG: Executing command '/var/ossec/active-response/bin/firewall-drop.sh add'
2019/08/06 13:26:58 ossec-execd[783] execd.c:642 at ExecdStart(): DEBUG: Adding command '/var/ossec/active-response/bin/firewall-drop.sh' to the timeout list, with a timeout of '100s'.
2019/08/06 13:27:06 ossec-execd[783] execd.c:365 at ExecdStart(): DEBUG: Received message: 'firewall-drop100'
2019/08/06 13:27:06 ossec-execd[783] execd.c:378 at ExecdStart(): WARNING: (1310): Invalid active response (execd) message 'firewall-drop100'.
2019/08/06 13:27:17 ossec-execd[783] execd.c:365 at ExecdStart(): DEBUG: Received message: 'firewall-drop100'
2019/08/06 13:27:17 ossec-execd[783] execd.c:378 at ExecdStart(): WARNING: (1310): Invalid active response (execd) message 'firewall-drop100'.
2019/08/06 13:27:21 ossec-execd[783] execd.c:365 at ExecdStart(): DEBUG: Received message: 'firewall-drop100'
2019/08/06 13:27:21 ossec-execd[783] execd.c:378 at ExecdStart(): WARNING: (1310): Invalid active response (execd) message 'firewall-drop100'.
2019/08/06 13:27:27 ossec-execd[783] execd.c:365 at ExecdStart(): DEBUG: Received message: 'firewall-drop100 124'
2019/08/06 13:27:27 ossec-execd[783] execd.c:504 at ExecdStart(): ERROR: Invalid number of arguments (firewall-drop100).
2019/08/06 13:27:37 ossec-execd[783] execd.c:365 at ExecdStart(): DEBUG: Received message: 'firewall-drop100      124'
2019/08/06 13:27:37 ossec-execd[783] execd.c:588 at ExecdStart(): DEBUG: Executing command '/var/ossec/active-response/bin/firewall-drop.sh add'
2019/08/06 13:27:37 ossec-execd[783] execd.c:642 at ExecdStart(): DEBUG: Adding command '/var/ossec/active-response/bin/firewall-drop.sh' to the timeout list, with a timeout of '100s'.
/var/ossec/active-response/bin/firewall-drop.sh: <action> <username> <ip>
2019/08/06 13:27:45 ossec-execd[783] execd.c:365 at ExecdStart(): DEBUG: Received message: 'firewall-drop1000      124'
2019/08/06 13:27:45 ossec-execd[783] execd.c:462 at ExecdStart(): ERROR: (1311): Invalid command name 'firewall-drop1000' provided.
2019/08/06 13:27:51 ossec-execd[783] execd.c:365 at ExecdStart(): DEBUG: Received message: 'firewall-drop1000  jhdfkljhadfklj hafhjkas hdfkjahf lkjas fl124'
2019/08/06 13:27:51 ossec-execd[783] execd.c:462 at ExecdStart(): ERROR: (1311): Invalid command name 'firewall-drop1000' provided.
2019/08/06 13:27:53 ossec-execd[783] sig_op.c:49 at HandleSIG(): INFO: (1225): SIGNAL [(2)-(Interrupt)] Received. Exit Cleaning...
/var/ossec/active-response/bin/firewall-drop.sh: <action> <username> <ip>
2019/08/06 13:28:22 ossec-execd[855] execd.c:365 at ExecdStart(): DEBUG: Received message: 'firewall-drop100 1234 1234 2134'
2019/08/06 13:28:22 ossec-execd[855] exec.c:102 at ReadExecConfig(): INFO: Active response command not present: '/var/ossec/active-response/bin/restart-ossec.cmd'. Not using it on this system.
2019/08/06 13:28:22 ossec-execd[855] execd.c:588 at ExecdStart(): DEBUG: Executing command '/var/ossec/active-response/bin/firewall-drop.sh add'
2019/08/06 13:28:22 ossec-execd[855] execd.c:642 at ExecdStart(): DEBUG: Adding command '/var/ossec/active-response/bin/firewall-drop.sh' to the timeout list, with a timeout of '100s'.
2019/08/06 13:28:26 ossec-execd[855] execd.c:365 at ExecdStart(): DEBUG: Received message: 'firewall-drop100 1234 1234 2134'
2019/08/06 13:28:26 ossec-execd[855] execd.c:538 at ExecdStart(): DEBUG: Command already received, updating time of addition to now.
2019/08/06 13:28:26 ossec-execd[855] execd.c:570 at ExecdStart(): DEBUG: Repeated offender. Setting timeout to '1800s'
2019/08/06 13:28:28 ossec-execd[855] execd.c:365 at ExecdStart(): DEBUG: Received message: 'firewall-drop100 1234 1234 2134'
2019/08/06 13:28:28 ossec-execd[855] execd.c:538 at ExecdStart(): DEBUG: Command already received, updating time of addition to now.
2019/08/06 13:28:28 ossec-execd[855] execd.c:570 at ExecdStart(): DEBUG: Repeated offender. Setting timeout to '300s'
2019/08/06 13:28:30 ossec-execd[855] execd.c:365 at ExecdStart(): DEBUG: Received message: 'firewall-drop100 1234 1234 2134'
2019/08/06 13:28:30 ossec-execd[855] execd.c:538 at ExecdStart(): DEBUG: Command already received, updating time of addition to now.
2019/08/06 13:28:30 ossec-execd[855] execd.c:570 at ExecdStart(): DEBUG: Repeated offender. Setting timeout to '600s'
2019/08/06 13:28:31 ossec-execd[855] execd.c:365 at ExecdStart(): DEBUG: Received message: 'firewall-drop100 1234 1234 2134'
2019/08/06 13:28:31 ossec-execd[855] execd.c:538 at ExecdStart(): DEBUG: Command already received, updating time of addition to now.
2019/08/06 13:28:31 ossec-execd[855] execd.c:570 at ExecdStart(): DEBUG: Repeated offender. Setting timeout to '600s'
2019/08/06 13:28:32 ossec-execd[855] execd.c:365 at ExecdStart(): DEBUG: Received message: 'firewall-drop100 1234 1234 2134'
2019/08/06 13:28:32 ossec-execd[855] execd.c:538 at ExecdStart(): DEBUG: Command already received, updating time of addition to now.
2019/08/06 13:28:32 ossec-execd[855] execd.c:570 at ExecdStart(): DEBUG: Repeated offender. Setting timeout to '600s'
2019/08/06 13:30:00 ossec-execd[901] execd.c:365 at ExecdStart(): DEBUG: Received message: '!script.hs 1234 1234 2134'
2019/08/06 13:30:00 ossec-execd[901] execd.c:588 at ExecdStart(): DEBUG: Executing command '/var/ossec/active-response/bin/script.hs add'
2019/08/06 13:30:00 ossec-execd[901] exec.c:196 at ExecCmd(): ERROR: (1312): Error executing '/var/ossec/active-response/bin/script.hs': No such file or directory
==907== 
==907== HEAP SUMMARY:
==907==     in use at exit: 8,823 bytes in 9 blocks
==907==   total heap usage: 4,353 allocs, 4,344 frees, 2,152,889 bytes allocated
==907== 
==907== LEAK SUMMARY:
==907==    definitely lost: 0 bytes in 0 blocks
==907==    indirectly lost: 0 bytes in 0 blocks
==907==      possibly lost: 0 bytes in 0 blocks
==907==    still reachable: 8,823 bytes in 9 blocks
==907==         suppressed: 0 bytes in 0 blocks
==907== Rerun with --leak-check=full to see details of leaked memory
==907== 
==907== For counts of detected and suppressed errors, rerun with: -v
==907== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
2019/08/06 13:30:13 ossec-execd[901] execd.c:365 at ExecdStart(): DEBUG: Received message: '!script.sh 1234 1234 2134'
2019/08/06 13:30:13 ossec-execd[901] execd.c:588 at ExecdStart(): DEBUG: Executing command '/var/ossec/active-response/bin/script.sh add'
2019/08/06 13:31:00 ossec-execd[901] execd.c:58 at execd_shutdown(): INFO: (1314): Shutdown received. Deleting responses.
2019/08/06 13:31:00 ossec-execd[901] sig_op.c:49 at HandleSIG(): INFO: (1225): SIGNAL [(2)-(Interrupt)] Received. Exit Cleaning...
==855== 
==855== HEAP SUMMARY:
==855==     in use at exit: 9,226 bytes in 14 blocks
==855==   total heap usage: 4,434 allocs, 4,420 frees, 2,249,404 bytes allocated
==855== 
==855== LEAK SUMMARY:
==855==    definitely lost: 0 bytes in 0 blocks
==855==    indirectly lost: 0 bytes in 0 blocks
==855==      possibly lost: 272 bytes in 1 blocks
==855==    still reachable: 8,954 bytes in 13 blocks
==855==         suppressed: 0 bytes in 0 blocks
==855== Rerun with --leak-check=full to see details of leaked memory
==855== 
==855== For counts of detected and suppressed errors, rerun with: -v
==855== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

```

**Comment by JuantAldea** [comment]
Rebased on top of 3.10

**Comment by JuantAldea** [comment]
# Scan-build
Reports only those marked as **Won't fix**

**Comment by JuantAldea** [comment]
Neither Valgrind nor Address sanitizer report issues while flooding with os-query messages.

**Pull request merged**
