### PR TITLE
Avoid to get the creation date of Whodata monitored files

### PR DESCRIPTION
**Pull request by crolopez**
|Related issue|
|---|
|#3864|

The problem described in the issue is due to a race condition between the Whodata state checker and an external software that needs to access with remove permissions to a monitored file.

It is possible to reproduce easily the condition by setting the frequency of the checker to its minimum value. For do this, add the following line to the `syscheck` block.

``` XML
<windows_audit_interval>1</windows_audit_interval>
``` 

Once Wazuh is monitoring a folder in whodata mode with this option, the race condition can be forced with a Powershell script which renames a file indefinitely (removal + addition permissions).

``` ps1
$prefix=Get-Random
$i = 0
$i_next = $i + 1
echo "" > log.txt
echo "" > $prefix-$i.txt
while ($true) {
    Rename-Item -Path "$prefix-$i.txt" -NewName "$prefix-$i_next.txt" -erroraction 'silentlycontinue'
    if($?)
    {
        echo (Get-Date).datetime >> log.txt    
        echo "$prefix-$i.txt -> $prefix-$i_next.txt" >> log.txt
           $i = $i_next
        $i_next = $i + 1
    } else {
        echo (Get-Date).datetime >> log.txt    
        echo "ERROR" >> log.txt
    }
} 
```

Concretely, the race condition appears when the checker thread request de directory handler to evaluate its creation time. This is done by calling to the blocking function `CreateFile` at this point:

https://github.com/wazuh/wazuh/blob/6f47eb206f65ecef6053ff77921639161e1a8db6/src/shared/file_op.c#L1181

The solution proposed in this PR consists in to save the handler and reuse it each time the monitored directory is checked by the thread.

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [x] MAC OS X
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [x] Package upgrade
- [x] Review logs syntax and correct language
- [x] QA templates contemplate the added capabilities
- Memory tests for Windows
  - [x] Dr. Memory

### Update

Finally, the solution proposed at this Pull Request is not to reuse the handler for the Whodata monitored directories. That date was queried to know if a monitored file had been recreated between two successive scans, to log that case. 

That feature has been removed to avoid the blocking of the scanned files by Whodata. More information [here](https://github.com/wazuh/wazuh/pull/3872#issuecomment-536517558).

### CODE REVIEW

**Comment by sergiovp** [comment]
I reproduced the issue and in my case, I got the following error message:

image

As is specified on the issue, Wazuh Agent is locking files when whodata or realtime is enabled. It avoids deleting files or folders even by the Administrator user.

When we stop Wazuh Agent, we don't have any problem to delete files or folders.

I have checked that this PR fixes the error.
In consequence, Wazuh Agent doesn't lock files, permitting deleting files or folders without problems.

**Comment by chemamartinez** [comment]
Hi, @Lopuiz , @JcabreraC , @sergiovp ,

Has this PR passed the memory tests? What is the result of these tests? In addition, I am missing a checklist with the use cases tested over these changes.

Regards.

**Comment by JcabreraC** [comment]
I have not able to replicate the bug with the crolopez script, so I created one to replicate the error. The script used is as follows: 

```ps1
#Script to generate "nfiles" of "size" in the folder "folder"
#EJ: .\scriptfiles.ps1 -nfiles 20000 -size 50kb -folder 'C:\Temp\Files'

param(
$nfiles = $(throw "Error: select number of files to create")
, $size = $(throw "Error: select size of files")
, $folder = $(throw "Error: select an output folder")
)
CLS

if(Test-Path $folder)
{

$name = 'test'
$extension = 'txt'

for($i = 1; $i -le $nfiles; $i++)
{
$path = $folder + '\test' + '_' + $i + '.txt'
$file = [io.file]::Create($path)
$file.SetLength($size)
$file.Close()

sleep 0.5
}

Compress-Archive -Path $folder -DestinationPath Test.zip

}
else{
Write-Host "The folder $folder doesn't exist" -ForegroundColor Red
Exit(0)
}

echo "OK"
```

This script has been executed to create 20.000 50KB files that have been compressed and saved in a folder whose monitoring has been configured by adding the following line: `<directories check_all="yes" whodata="yes">PATH</directories>`

I have changed the value `<windows_audit_interval>300</windows_audit_interval>` to 1. I have replicated the error when unzipping and deleting the folder, because at some point it coincides that is trying to delete a file that is using Wazuh

Confirmed that the error only appears when decompressing and erasing quickly. If you wait a few seconds, the error does not occur.

Tested the solution of this PR. It works correctly the decompressed and erased when reusing the handler.

**Comment by chemamartinez** [comment]
Still missing memory / resources tests. We are playing with the creation and deletion of Windows handles, so the provided tests should be, at leasts, the following:

- Stress test: handling a large number of files by who-data, Logcollector, and any other module that works with opened files at the agent. Monitoring the limit of opened handles by Wazuh simultaneously.
- Monitor the memory usage of Wazuh while the test described below.

**Comment by wazuhci** [comment]
Stress/leaks test launched you will have the graphics in a few hours, please be patient.

**Comment by JcabreraC** [comment]
# Stress test

I changed the value `<windows_audit_interval>300</windows_audit_interval>` to 1 in `ossec.conf`. Also, the frequency has been lowered from `syscheck` to 60.

I have launched script to decompress and delete compressed files with 20.000 files inside. The PR has been working with more than 200ks of files.

Running `while (1) {Get-Process -Name ossec-agent | Select-Object Name,@{Name='WorkingSet';Expression={($_.WorkingSet)}}; sleep(2/3)}` on powershell, I watched as the memory grew until we deleted the files and passed the frequency interval, returning to normal values.

Everything worked correctly.

### Resume
|Name|WorkingSet|
|---|---|
|ossec-agent|8477568|
|ossec-agent|8478533|
|ossec-agent|8478617|
|ossec-agent|8479255|
|...|...|

Decompress and delete files

|Name|WorkingSet|
|---|---|
|ossec-agent|10637312|
|ossec-agent|11223040|
|ossec-agent|11632340|
|ossec-agent|12607488|
|...|...|
|ossec-agent|14245785|
|ossec-agent|14435996|
|ossec-agent|16127485|
|...|...|

Deletefiles and pass frequency

|Name|WorkingSet|
|---|---|
|ossec-agent|12876623|
|ossec-agent|12697541|
|ossec-agent|12632748|
|...|...|
|ossec-agent|8852963|

**Comment by wazuhci** [comment]
Stress/leaks test launched you will have the graphics in a few hours, please be patient.

**Comment by wazuhci** [comment]
Stress/leaks test launched you will have the graphics in a few hours, please be patient.

**Comment by wazuhci** [comment]
## Stress/Leaks test results
### CentOS Manager ID0
- #### CPU
    [CentOS Manager](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/13/monitor-manager-ID0_B13_memory_leak_Manager-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Manager](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/13/monitor-manager-ID0_B13_memory_leak_Manager-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Manager](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/13/monitor-manager-ID0_B13_memory_leak_Manager-warehouse-pullrequests_RSS(KB).svg)
### CentOS Agent ID0
- #### CPU
    [CentOS Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/13/monitor-agent-ID0_B13_memory_leak_centos_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/13/monitor-agent-ID0_B13_memory_leak_centos_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/13/monitor-agent-ID0_B13_memory_leak_centos_Agent-warehouse-pullrequests_RSS(KB).svg)
### Ubuntu Agent ID0
- #### CPU
    [Ubuntu Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/13/monitor-agent-ID0_B13_memory_leak_ubuntu_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Ubuntu Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/13/monitor-agent-ID0_B13_memory_leak_ubuntu_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Ubuntu Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/13/monitor-agent-ID0_B13_memory_leak_ubuntu_Agent-warehouse-pullrequests_RSS(KB).svg)
### Agent Windows ID0
- #### CPU
    [Windows Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/13/monitor-winagent-ID0_B13_memory_leak_windows_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Windows Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/13/monitor-winagent-ID0_B13_memory_leak_windows_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Windows Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/13/monitor-winagent-ID0_B13_memory_leak_windows_Agent-warehouse-pullrequests_RSS(KB).svg)

**Comment by crolopez** [comment]
The current state of the PR solves the problem related with the whodata checker thread, so the execution of the directory validation won't longer block any operation on the files of that directory.

The solution proposed in https://github.com/wazuh/wazuh/pull/3872#pullrequestreview-294240722, despite saving us from getting a handler, is still blocking. Instead, it has been decided to change the evaluation of the directory, so it's no longer necessary to obtain the creation date.

However, there are more calls to `GetFileAttributesEx` in the Syscheck code, so we can block more operations in realtime or whodata modes.

https://github.com/wazuh/wazuh/blob/f3fcc09f1a75f51f445d7d5e96faa95d486edd57/src/syscheckd/create_db.c#L255
https://github.com/wazuh/wazuh/blob/f3fcc09f1a75f51f445d7d5e96faa95d486edd57/src/shared/syscheck_op.c#L1152

In addition, exists other Windows API calls that can also block some file operations.

https://github.com/wazuh/wazuh/blob/f3fcc09f1a75f51f445d7d5e96faa95d486edd57/src/shared/syscheck_op.c#L900-L907

There is a significant difference with the blockage generated by existing blocking functions with respect to the generated by the whodata check thread. While the whodata thread blocks all files under the directory, the other blocking operations are granular and affect only independent files, so the race condition presented in https://github.com/wazuh/wazuh/pull/3872#issue-310255072 is unlikely.

**Comment by wazuhci** [comment]
Stress/leaks test launched you will have the graphics in a few hours, please be patient.

**Comment by wazuhci** [comment]
## Stress/Leaks test results
### CentOS Manager ID0
- #### CPU
    [CentOS Manager](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/16/monitor-manager-ID0_B16_memory_leak_Manager-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Manager](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/16/monitor-manager-ID0_B16_memory_leak_Manager-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Manager](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/16/monitor-manager-ID0_B16_memory_leak_Manager-warehouse-pullrequests_RSS(KB).svg)
### CentOS Agent ID0
- #### CPU
    [CentOS Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/16/monitor-agent-ID0_B16_memory_leak_centos_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/16/monitor-agent-ID0_B16_memory_leak_centos_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/16/monitor-agent-ID0_B16_memory_leak_centos_Agent-warehouse-pullrequests_RSS(KB).svg)
### Ubuntu Agent ID0
- #### CPU
    [Ubuntu Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/16/monitor-agent-ID0_B16_memory_leak_ubuntu_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Ubuntu Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/16/monitor-agent-ID0_B16_memory_leak_ubuntu_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Ubuntu Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/16/monitor-agent-ID0_B16_memory_leak_ubuntu_Agent-warehouse-pullrequests_RSS(KB).svg)
### Agent Windows ID0
- #### CPU
    [Windows Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/16/monitor-winagent-ID0_B16_memory_leak_windows_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Windows Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/16/monitor-winagent-ID0_B16_memory_leak_windows_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Windows Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/16/monitor-winagent-ID0_B16_memory_leak_windows_Agent-warehouse-pullrequests_RSS(KB).svg)

**Comment by wazuhci** [comment]
Stress/leaks test launched you will have the graphics in a few hours, please be patient.

**Comment by wazuhci** [comment]
## Stress/Leaks test results
### CentOS Manager ID0
- #### CPU
    [CentOS Manager](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/24/monitor-manager-ID0_B24_memory_leak_Manager-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Manager](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/24/monitor-manager-ID0_B24_memory_leak_Manager-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Manager](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/24/monitor-manager-ID0_B24_memory_leak_Manager-warehouse-pullrequests_RSS(KB).svg)
### CentOS Agent ID0
- #### CPU
    [CentOS Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/24/monitor-agent-ID0_B24_memory_leak_centos_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/24/monitor-agent-ID0_B24_memory_leak_centos_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/24/monitor-agent-ID0_B24_memory_leak_centos_Agent-warehouse-pullrequests_RSS(KB).svg)
### Ubuntu Agent ID0
- #### CPU
    [Ubuntu Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/24/monitor-agent-ID0_B24_memory_leak_ubuntu_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Ubuntu Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/24/monitor-agent-ID0_B24_memory_leak_ubuntu_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Ubuntu Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/24/monitor-agent-ID0_B24_memory_leak_ubuntu_Agent-warehouse-pullrequests_RSS(KB).svg)
### Agent Windows ID0
- #### CPU
    [Windows Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/24/monitor-winagent-ID0_B24_memory_leak_windows_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Windows Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/24/monitor-winagent-ID0_B24_memory_leak_windows_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Windows Agent](https://packages-dev.wazuh.com/utils/memory_leaks/3.11.0/warehouse-pullrequests/24/monitor-winagent-ID0_B24_memory_leak_windows_Agent-warehouse-pullrequests_RSS(KB).svg)

**Pull request merged**
