### PR TITLE
Create SCA Policy for Alma Linux OS 8

### PR DESCRIPTION
**Pull request by jk-olaoluwa**
| Component | Action type           | Main Issue 
| --- | --- | ---
| SCA       | Create |  #14358 

## Main tasks

- [x] Use the latest CIS benchmark PDF Draft version - CIS Alma Linux OS 8 Benchmark v2.0.0 - v3.0.0 now available, will be updated after 4.8.1
- [x] Verify IDs numbers.
- [x] Verify texts are correct: Title, Description, Rationale and Remediation.
- [x] Verify Compliance: CIS, CIS_CSC.
- [x] Verify condition and rules:
  - [x] To Pass.
  - [x] To Fail.

  
### Issue QA:
- TBD

### Syntax and semantic

- [x] a) ID of each policy must be contiguous.
- [x] b) The order and format set in [Documentation](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/creating-custom-policies.html) must be respected.
- [x] c) YML must be valid to avoid errors.

### Content

- [x] a) Compare each check with its analog from CIS Benchmark.
- [x] b) Try maintaining each rule as similar as possible to the `Audit` section from the CIS check.
- [x] c) Check that the commands provide the expected output.
- [x] d) When a failure is discovered, check similar policies to avoid repetition of the issue.

### Unit testing

- [x] a) Output from `ossec.log` after the SCA scan and a raw output of the result of the checks.
<details><summary>Tests results</summary>
<p>

#### Analysisd (server or local)
analysisd.debug=2

#### Auth daemon debug (server)
authd.debug=0

#### Exec daemon debug (server, local, or Unix agent)
execd.debug=0

#### Monitor daemon debug (server, local, or Unix agent)
monitord.debug=0

#### Log collector (server, local or Unix agent)
logcollector.debug=0

#### Integrator daemon debug (server, local, or Unix agent)
integrator.debug=0

#### Unix agentd
agent.debug=2

```
2024/01/03 13:09:54 sca[5652] wm_sca.c:2598 at wm_sca_send_summary(): DEBUG: Sending summary event for file: 'cis_alma_linux_8.yml'
2024/01/03 13:09:54 sca[5652] wm_sca.c:271 at wm_sca_send_alert(): DEBUG: Sending event: {"type":"summary","scan_id":887922632,"name":"CIS Alma Linux 8 Benchmark v2.0.0","policy_id":"cis_alma_linux_8","file":"cis_alma_linux_8.yml","description":"This document provides prescriptive guidance for establishing a secure configuration posture for Alma Linux 8 systems running on x86 and x64 platforms. This document was tested against Alma Linux 8.","references":"https://www.cisecurity.org/cis-benchmarks/","passed":82,"failed":119,"invalid":4,"total_checks":205,"score":40.7960205078125,"start_time":1704287380,"end_time":1704287391,"hash":"72947eb2c5ded89fc7c20e67595179bda0b9e3b4d1752aead59071fe0d72f7f0","hash_file":"9e614aa2fa952bd2df8267fa033883df6ee34f21eb366e95851245fcf387330e","first_scan":1}
```

</p>
</details>

### Deployment

- [x] a) If the policy it's new, it must be added to the `sca.files` templates.
- [x] b) If the OS has many supported SCA policies, a policy must be set as the default policy. ([as example](https://github.com/wazuh/wazuh/blob/master/etc/templates/config/centos/sca.files))

### Documentation

- [x] a) Ensure documentation SCA list includes the created or updated SCA.

# Checks
| Check Id and Name                                                                                                                | Status | Ready for QA    |
| -------------------------------------------------------------------------------------------------------------------------------- | ------ | --------------- |
|                                                                                                                                  |        |                 |
| 1 Initial setup                                                                      |        |                 |
| 1.1 Filesystem Configuration                                                                      |        |                 |
| 1.1.1 Disable unused filesystems                                                                      |        |                 |
||||
| 1.1.1.1 Ensure mounting of cramfs filesystems is disabled. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.1.2 Ensure mounting of squashfs filesystems is disabled. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.1.3 Ensure mounting of udf filesystems is disabled. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.2 Configure /tmp                                                                      |        |                 |
||||
| 1.1.2.1 Ensure /tmp is a separate partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.2.2 Ensure nodev option set on /tmp partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.2.3 Ensure noexec option set on /tmp partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.2.4 Ensure nosuid option set on /tmp partition. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 1.1.3 Configure /var                                                                      |        |                 |
||||
| 1.1.3.1 Ensure separate partition exists for /var. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.3.2 Ensure nodev option set on /var partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.3.3 Ensure noexec option set on /var partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.3.4 Ensure nosuid option set on /var partition. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 1.1.4 Configure /var/tmp                                                                      |        |                 |
||||
| 1.1.4.1 Ensure separate partition exists for /var/tmp. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.4.2 Ensure noexec option set on /var/tmp partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.4.3 Ensure nosuid option set on /var/tmp partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.4.4 Ensure nodev option set on /var/tmp partition. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 1.1.5 Configure /var/log                                                                      |        |                 |
||||
| 1.1.5.1 Ensure separate partition exists for /var/log. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.5.2 Ensure nodev option set on /var/log partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.5.3 Ensure noexec option set on /var/log partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.5.4 Ensure nosuid option set on /var/log partition. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 1.1.6 Configure /var/log/audit                                                                      |        |                 |
||||
| 1.1.6.1 Ensure separate partition exists for /var/log/audit. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.6.2 Ensure noexec option set on /var/log/audit partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.6.3 Ensure nodev option set on /var/log/audit partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.6.4 Ensure nosuid option set on /var/log/audit partition. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 1.1.7 Configure /home                                                                      |        |                 |
||||
| 1.1.7.1 Ensure separate partition exists for /home. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.7.2 Ensure nodev option set on /home partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.7.3 Ensure nosuid option set on /home partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.7.4 Ensure usrquota option set on /home partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.7.5 Ensure grpquota option set on /home partition. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 1.1.8 Configure /dev/shm                                                                      |        |                 |
||||
| 1.1.8.1 Ensure nodev option set on /dev/shm partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.8.2 Ensure noexec option set on /dev/shm partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.8.3 Ensure nosuid option set on /dev/shm partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.9 Disable Automounting. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.10 Disable USB Storage. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 1.2 Configure Software Updates                                                                      |        |                 |
||||
| 1.2.1 Ensure GPG keys are configured (Manual)                                                                                           | ⚫      | Not implemented |
| 1.2.2 Ensure gpgcheck is globally activated. (Automated)                                                                    | 🟢      | 🟢               |
| 1.2.3 Ensure package manager repositories are configured. (Manual)                                                                                           | ⚫      | Not implemented |
||||
| 1.3 Filesystem Integrity Checking                                                                      |        |                 |
||||
| 1.3.1 Ensure AIDE is installed. (Automated)                                                                    | 🟢      | 🟢               |
| 1.3.2 Ensure filesystem integrity is regularly checked. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 1.4 Secure Boot Settings                                                                      |        |                 |
||||
| 1.4.1 Ensure bootloader password is set. (Automated)                                                                                           | ⚫      | Not implemented |
| 1.4.2 Ensure permissions on bootloader config are configured. (Automated)                                                                                           | ⚫      | Not implemented |
| 1.4.3 Ensure authentication is required when booting into rescue mode. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 1.5 Additional Process Hardening                                                                      |        |                 |
||||
| 1.5.1 Ensure core dump storage is disabled. (Automated)                                                                    | 🟢      | 🟢               |
| 1.5.2 Ensure core dump backtraces are disabled. (Automated)                                                                    | 🟢      | 🟢               |
| 1.5.3 Ensure address space layout randomization (ASLR) is enabled. (Automated)                                                                                           | ⚫      | Not implemented |
||||
| 1.6 Mandatory Access Control                                                                      |        |                 |
| 1.6.1 Configure SELinux                                                                      |        |                 |
||||
| 1.6.1.1 Ensure SELinux is installed. (Automated)                                                                    | 🟢      | 🟢               |
| 1.6.1.2 Ensure SELinux is not disabled in bootloader configuration. (Automated)                                                                    | 🟢      | 🟢               |
| 1.6.1.3 Ensure SELinux policy is configured. (Automated)                                                                    | 🟢      | 🟢               |
| 1.6.1.4 Ensure the SELinux mode is not disabled. (Automated)                                                                    | 🟢      | 🟢               |
| 1.6.1.5 Ensure the SELinux mode is enforcing. (Automated)                                                                    | 🟢      | 🟢               |
| 1.6.1.6 Ensure no unconfined services exist. (Automated)                                                                    | 🟢      | 🟢               |
| 1.6.1.7 Ensure SETroubleshoot is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 1.6.1.8 Ensure the MCS Translation Service (mcstrans) is not installed. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 1.7 Command Line Warning Banners                                                                      |        |                 |
||||
| 1.7.1 Ensure message of the day is configured properly. (Automated)                                                                    | 🟢      | 🟢               |
| 1.7.2 Ensure local login warning banner is configured properly. (Automated)                                                                    | 🟢      | 🟢               |
| 1.7.3 Ensure remote login warning banner is configured properly. (Automated)                                                                    | 🟢      | 🟢               |
| 1.7.4 Ensure permissions on /etc/motd are configured. (Automated)                                                                    | 🟢      | 🟢               |
| 1.7.5 Ensure permissions on /etc/issue are configured. (Automated)                                                                    | 🟢      | 🟢               |
| 1.7.6 Ensure permissions on /etc/issue.net are configured. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 1.8 GNOME Display Manager                                                                      |        |                 |
||||
| 1.8.1 Ensure GNOME Display Manager is removed. (Manual)                                                                    | 🟢      | 🟢               |
| 1.8.2 Ensure GDM login banner is configured. (Automated)                                                                    | 🟢      | 🟢               |
| 1.8.3 Ensure last logged in user display is disabled. (Automated)                                                                    | 🟢      | 🟢               |
| 1.8.4 Ensure XDMCP is not enabled. (Automated)                                                                    | 🟢      | 🟢               |
| 1.8.5 Ensure automatic mounting of removable media is disabled. (Automated)                                                                    | 🟢      | 🟢               |
| 1.9 Ensure updates, patches, and additional security software are installed. (Manual)                                                                    | 🟢      | 🟢               |
| 1.10 Ensure system-wide crypto policy is not legacy. (Automated)                                                                    | 🟢      | 🟢               |
| 2.1.1 Ensure time synchronization is in use. (Automated)                                                                    | 🟢      | 🟢               |
| 2.1.2 Ensure chrony is configured. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 2.2 Attack Surface Reduction                                                                      |        |                 |
||||
| 2.2.1 Ensure xinetd is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.2 Ensure xorg-x11-server-common is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.3 Ensure Avahi Server is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.4 Ensure CUPS is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.5 Ensure DHCP Server is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.6 Ensure DNS Server is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.7 Ensure VSFTP Server is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.8 Ensure TFTP Server is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.9 Ensure a web server is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.10 Ensure IMAP and POP3 server is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.11 Ensure Samba is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.12 Ensure HTTP Proxy Server is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.13 Ensure net-snmp is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.14Ensure NIS server is not installed (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.15 Ensure telnet-server is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.16 Ensure mail transfer agent is configured for local-only mode. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.17 Ensure nfs-utils is not installed or the nfs-server service is masked. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.18 Ensure rpcbind is not installed or the rpcbind services are masked. (Automated)                                                                    | 🟢      | 🟢               |
| 2.2.19 Ensure rsync-daemon is not installed or the rsyncd service is masked. (Automated)                                                                    | 🟢      | 🟢               |
| 2.3.1 Ensure NIS client is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.3.2 Ensure rsh client is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.3.3 Ensure talk client is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.3.4 Ensure telnet client is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.3.5 Ensure LDAP client is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.3.6 Ensure TFTP client is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.3.7 Ensure FTP client is not installed. (Automated)                                                                    | 🟢      | 🟢               |
| 2.4 Ensure nonessential services listening on the system are removed or masked. (Manual)                                                                    | ⚫      | Not Implemented               |
||||
| 3.1 Networks & Communication                                                                      |        |                 |
||||
| 3.1.1 Ensure wireless interfaces are disabled. (Automated)                                                                    | ⚫      | Not Implemented               |
| 3.1.2 Verify IPv6 status is enabled or disabled on the system. (Manual)                                                                    | ⚫      | Not Implemented               |
| 3.1.3 Ensure TIPC is disabled. (Automated)                                                                    | 🟢      | 🟢               |
| 3.2.1 Ensure IP forwarding is disabled. (Automated)                                                                    | ⚫      | Not Implemented               |
| 3.2.2 Ensure packet redirect sending is disabled. (Automated)                                                                    | ⚫      | Not Implemented               |
||||
| 3.3 Network Parameters (Host and Router)                                                                      |        |                 |
||||
| 3.3.1 Ensure source routed packets are not accepted. (Automated)                                                                    | ⚫      | Not Implemented               |
| 3.3.2 Ensure ICMP redirects are not accepted. (Automated)                                                                    | ⚫      | Not Implemented               |
| 3.3.3 Ensure secure ICMP redirects are not accepted. (Automated)                                                                    | ⚫      | Not Implemented               |
| 3.3.4 Ensure suspicious packets are logged. (Automated)                                                                    | ⚫      | Not Implemented               |
| 3.3.5 Ensure broadcast ICMP requests are ignored. (Automated)                                                                    | ⚫      | Not Implemented               |
| 3.3.6 Ensure bogus ICMP responses are ignored. (Automated)                                                                    | ⚫      | Not Implemented               |
| 3.3.7 Ensure Reverse Path Filtering is enabled. (Automated)                                                                    | ⚫      | Not Implemented               |
| 3.3.8 Ensure TCP SYN Cookies is enabled. (Automated)                                                                    | ⚫      | Not Implemented               |
| 3.3.9 Ensure IPv6 router advertisements are not accepted. (Automated)                                                                    | ⚫      | Not Implemented               |
| 3.4.1.1 Ensure firewalld is installed (Automated)                                                                  | 🟢      | 🟢               |
| 3.4.1.2Ensure iptables-services not installed with firewalld (Automated)                                                                  | 🟢      | 🟢               |
|3.4.1.3 Ensure nftables either not installed or masked with firewalld (Automated)                                                                | 🟢      | 🟢               |
3.4.1.4 Ensure firewalld service enabled and running (Automated)                                                             | 🟢      | 🟢               |
|3.4.1.5 Ensure firewalld default zone is set (Automated)                                                                | 🟢      | 🟢               |
|3.4.1.6 Ensure network interfaces are assigned to appropriate zone (Manual)                                                               | 🟢      | 🟢               |
|3.4.1.7 Ensure firewalld drops unnecessary services and ports (Manual)                                                               | 🟢      | 🟢               |
| 3.4.2.1 Ensure nftables is installed (Automated)                                                                    | ⚫      | Not Implemented               |
| 3.4.2.2 Ensure firewalld is either not installed or masked with nftables (Automated)                                                                   | 🟢      | 🟢               |
| 3.4.2.3 Ensure iptables-services not installed with nftables (Automated)                                                                    | 🟢      | 🟢               |
| 3.4.2.4 Ensure iptables are flushed with nftables (Manual)                                                                   | ⚫      | Not Implemented               |
| 3.4.2.5 Ensure an nftables table exists (Automated)                                                                    | ⚫      | Not Implemented               |
| 3.4.2.6 Ensure nftables base chains exist (Automated)                                                                    | ⚫      | Not Implemented               |
| 3.4.2.7 Ensure nftables loopback traffic is configured (Automated)                                                                   | 🟢      | 🟢               |
| 3.4.2.8 Ensure nftables outbound and established connections are configured (Manual)                                                                   | 🟢      | 🟢               |
| 3.4.2.9 Ensure nftables default deny firewall policy (Automated)                                                                  | 🟢      | 🟢               |
| 3.4.2.10 Ensure nftables service is enabled (Automated)                                                                  | 🟢      | 🟢               |
| 3.4.2.11 Ensure nftables rules are permanent (Automated)                                                                 | 🟢      | 🟢               |
| 3.4.3.1.1 Ensure iptables packages are installed (Automated)                                                                 | 🟢      | 🟢               |
| 3.4.3.1.2 Ensure nftables is not installed with iptables (Automated)                                                                  | 🟢      | 🟢               |
||||

### CODE REVIEW

**Review by 72nomada — APPROVED** [review]
LGTM

**Review by DFolchA — CHANGES_REQUESTED** [review]
The directory names do not conform with the information retrieved by `dist-detect.sh`:
```
[root@almalinux8 vagrant]# bash dist-detect.sh 
DIST_NAME=almalinux
DIST_VER=8
DIST_SUBVER=8
```

**Review by DFolchA — CHANGES_REQUESTED** [review]
The new files must be added to `sca.manager.files`

**Review by ooniagbi — APPROVED** [review]
LGTM!

**Pull request merged**
