### PR TITLE
Merge 4.8.1 into 4.8.2

### PR DESCRIPTION
**Pull request by TomasTurina**
|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/22317|

### CODE REVIEW

**Review by cborla — DISMISSED** [review]
LGTM!

**Comment by MarcelKemp** [comment]
### Failed checks


- [Wazuh CI / Run wazuh-ruleset ini tests](https://github.com/wazuh/wazuh/pull/22358/checks?check_run_id=22287729084)
  - @wazuh/devel-threatintel is this expected?
```
|./tests/windows_baseline_intrusion_detection.ini|    28    |    1     |   ���    |
```
```
Failing tests summary:
----------------------------------------
Failed test: Special privileges (Admin-equivalent Access) assigned to new logon, excluding LocalSystem
Failed log: log 1 pass
Summary: Hit a different rule. Expected: 67028. Got: 60226
|           |        Expected         |         Result          |
|------     |         ------          |         ------          |
|Decoder    |          json           |          json           |
|Rule       |          67028          |          60226          |
|Level      |            3            |            8            |
```

- Integration tests executed in Jenkins.
  - This should be fixed with the IT migration, so it should not be a problem.
  - https://github.com/wazuh/wazuh/issues/17427

- [Wazuh CI / Analysis_dynamic_valgrind [logcollector]](https://github.com/wazuh/wazuh/pull/22358/checks?check_run_id=22285633359)
  - It seems that the Jenkins environment deploy fails.
```
Analysis_dynamic_valgrind#8645 FAILED:

Build: https://ci.wazuh.info/job/Analysis_dynamic_valgrind/8645/console
Exception: org.wazuh.JenkinsException: Error deploying task.
```

**Comment by ooniagbi** [comment]
> ### Failed checks
> * [Wazuh CI / Run wazuh-ruleset ini tests](https://github.com/wazuh/wazuh/pull/22358/checks?check_run_id=22287729084)
>   
>   * @wazuh/devel-threatintel is this expected?
> 
> ```
> |./tests/windows_baseline_intrusion_detection.ini|    28    |    1     |   ���    |
> ```
> 
> ```
> Failing tests summary:
> ----------------------------------------
> Failed test: Special privileges (Admin-equivalent Access) assigned to new logon, excluding LocalSystem
> Failed log: log 1 pass
> Summary: Hit a different rule. Expected: 67028. Got: 60226
> |           |        Expected         |         Result          |
> |------     |         ------          |         ------          |
> |Decoder    |          json           |          json           |
> |Rule       |          67028          |          60226          |
> |Level      |            3            |            8            |

The rules are duplicates. I'll create an issue to remove one of them.

**Review by MarcelKemp — APPROVED** [review]

**Comment by TomasTurina** [comment]
Failing tests are not related to this PR.

**Pull request merged**
