### PR TITLE
FIM rework improve unit tests for windows

### PR DESCRIPTION
**Pull request by aurelioremonda**
|Related issue|
|---|
|#4569|

## Description

The purpouse of this PR is to keep adding unit tests required for windows under the FIM rework context.

Unit tests for the functions listed on issue #4569 will be added using cmocka.

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

### CODE REVIEW

**Comment by wazuhci** [comment]
The stress test has been launched. The charts will be posted when they are ready.
I will use the following configuration:
### General
- Commit: aa9800f
- Packages: 
  - [manager 3.12.0 0.branch4569fimreworkimproveunittestsforwindows.commitaa9800f rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-manager-3.12.0-0.branch4569fimreworkimproveunittestsforwindows.commitaa9800f.x86_64.rpm)
  - [agent 3.12.0 0.branch4569fimreworkimproveunittestsforwindows.commitaa9800f rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-agent-3.12.0-0.branch4569fimreworkimproveunittestsforwindows.commitaa9800f.x86_64.rpm)
  - [manager 3.12.0 0.branch4569fimreworkimproveunittestsforwindows.commitaa9800f deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-manager_3.12.0-0.branch4569fimreworkimproveunittestsforwindows.commitaa9800f_amd64.deb)
  - [agent 3.12.0 0.branch4569fimreworkimproveunittestsforwindows.commitaa9800f deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-agent_3.12.0-0.branch4569fimreworkimproveunittestsforwindows.commitaa9800f_amd64.deb)
  - [agent 3.12.0 0.branch4569fimreworkimproveunittestsforwindows.commitaa9800f msi](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/windows/wazuh-agent-3.12.0-0.branch4569fimreworkimproveunittestsforwindows.commitaa9800f.msi)

### Stress test parameters:
- Manager system: `centos`
- Launch CentOS agent: `true`
- Launch Ubuntu agent: `true`
- Launch Windows agent: `true`
- Test duration: `60`
- Scan frequency: `10`
- Modules to test: 
  - logcollector: `true`
  - syscheck: `true`
  - rootcheck: `true`
  - sca: `true`
  - osquery: `true`
  - syscollector: `true`
  - active-response: `true`
  - azure-logs: `true`
  - cis-cat: `true`
  - docker-listener: `true`
  - open-scap: `true`
  - vulnerability-detector: `false`
- FIM special test: `None`
- FIM sleep: `300`
- FIM max files: `25000`
- SCA sleep: `30`
- SCA max registers: `5000`
- Docker image name: `hello-world`
- Docker sleep: `5`
- Docker jobs: `10`
- Logcollector special test: `None`
- Logcollector max files: `50000`
- Logcollector creation sleep: `300`
- Logcollector write files: `1000`
- Logcollector write sleep: `10`
- Vuln sleep: `60`
- Authd port: `1515`
- Syscollector package: `imagemagick.app`
- Syscollector package version: `7.0.8.48`

Regards!.

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** aa9800faa1213110f63c8b87d0512b837a92c215
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B582/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B582/ossec.log)
**Coverage:** 

```json
Lines executed:25.93% of 2997

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B582/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.0-B582.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B582/Analysis_dynamic_valgrind-v3.12.0-B582.log)

**Comment by wazuhci** [comment]
## Stress/Leaks test results
### Windows Agent ID0
- #### CPU
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B310/monitor-winagent-ID0_B310_Test_stress_windows_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B310/monitor-winagent-ID0_B310_Test_stress_windows_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B310/monitor-winagent-ID0_B310_Test_stress_windows_Agent-warehouse-pullrequests_RSS(KB).svg)
### CentOS Manager ID0
- #### CPU
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B310/monitor-manager-ID0_B310_Test_stress_Manager-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B310/monitor-manager-ID0_B310_Test_stress_Manager-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B310/monitor-manager-ID0_B310_Test_stress_Manager-warehouse-pullrequests_RSS(KB).svg)
### CentOS Agent ID1
- #### CPU
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B310/monitor-agent-ID1_B310_Test_stress_centos_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B310/monitor-agent-ID1_B310_Test_stress_centos_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B310/monitor-agent-ID1_B310_Test_stress_centos_Agent-warehouse-pullrequests_RSS(KB).svg)
### Ubuntu Agent ID0
- #### CPU
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B310/monitor-agent-ID0_B310_Test_stress_ubuntu_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B310/monitor-agent-ID0_B310_Test_stress_ubuntu_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B310/monitor-agent-ID0_B310_Test_stress_ubuntu_Agent-warehouse-pullrequests_RSS(KB).svg)

**Comment by wazuhci** [comment]
The stress test has been launched. The charts will be posted when they are ready.
I will use the following configuration:
### General
- Commit: 7711590
- Packages: 
  - [manager 3.12.0 0.branch4569fimreworkimproveunittestsforwindows.commit7711590 rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-manager-3.12.0-0.branch4569fimreworkimproveunittestsforwindows.commit7711590.x86_64.rpm)
  - [agent 3.12.0 0.branch4569fimreworkimproveunittestsforwindows.commit7711590 rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-agent-3.12.0-0.branch4569fimreworkimproveunittestsforwindows.commit7711590.x86_64.rpm)
  - [manager 3.12.0 0.branch4569fimreworkimproveunittestsforwindows.commit7711590 deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-manager_3.12.0-0.branch4569fimreworkimproveunittestsforwindows.commit7711590_amd64.deb)
  - [agent 3.12.0 0.branch4569fimreworkimproveunittestsforwindows.commit7711590 deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-agent_3.12.0-0.branch4569fimreworkimproveunittestsforwindows.commit7711590_amd64.deb)
  - [agent 3.12.0 0.branch4569fimreworkimproveunittestsforwindows.commit7711590 msi](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/windows/wazuh-agent-3.12.0-0.branch4569fimreworkimproveunittestsforwindows.commit7711590.msi)

### Stress test parameters:
- Manager system: `centos`
- Launch CentOS agent: `true`
- Launch Ubuntu agent: `true`
- Launch Windows agent: `true`
- Test duration: `60`
- Scan frequency: `10`
- Modules to test: 
  - logcollector: `true`
  - syscheck: `true`
  - rootcheck: `true`
  - sca: `true`
  - osquery: `true`
  - syscollector: `true`
  - active-response: `true`
  - azure-logs: `true`
  - cis-cat: `true`
  - docker-listener: `true`
  - open-scap: `true`
  - vulnerability-detector: `false`
- FIM special test: `None`
- FIM sleep: `300`
- FIM max files: `25000`
- SCA sleep: `30`
- SCA max registers: `5000`
- Docker image name: `hello-world`
- Docker sleep: `5`
- Docker jobs: `10`
- Logcollector special test: `None`
- Logcollector max files: `50000`
- Logcollector creation sleep: `300`
- Logcollector write files: `1000`
- Logcollector write sleep: `10`
- Vuln sleep: `60`
- Authd port: `1515`
- Syscollector package: `imagemagick.app`
- Syscollector package version: `7.0.8.48`

Regards!.

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 77115908077ab22d32b2733a55b765cd084fc1ff
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B590/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B590/ossec.log)
**Coverage:** 

```json
Lines executed:30.68% of 1832

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B590/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.0-B590.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B590/Analysis_dynamic_valgrind-v3.12.0-B590.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 77115908077ab22d32b2733a55b765cd084fc1ff
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B591/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B591/ossec.log)
**Coverage:** 

```json
Lines executed:26.46% of 2997

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B591/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.0-B591.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B591/Analysis_dynamic_valgrind-v3.12.0-B591.log)

**Comment by wazuhci** [comment]
## Stress/Leaks test results
### Windows Agent ID0
- #### CPU
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B314/monitor-winagent-ID0_B314_Test_stress_windows_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B314/monitor-winagent-ID0_B314_Test_stress_windows_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B314/monitor-winagent-ID0_B314_Test_stress_windows_Agent-warehouse-pullrequests_RSS(KB).svg)
### CentOS Manager ID0
- #### CPU
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B314/monitor-manager-ID0_B314_Test_stress_Manager-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B314/monitor-manager-ID0_B314_Test_stress_Manager-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B314/monitor-manager-ID0_B314_Test_stress_Manager-warehouse-pullrequests_RSS(KB).svg)
### CentOS Agent ID1
- #### CPU
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B314/monitor-agent-ID1_B314_Test_stress_centos_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B314/monitor-agent-ID1_B314_Test_stress_centos_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B314/monitor-agent-ID1_B314_Test_stress_centos_Agent-warehouse-pullrequests_RSS(KB).svg)
### Ubuntu Agent ID0
- #### CPU
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B314/monitor-agent-ID0_B314_Test_stress_ubuntu_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B314/monitor-agent-ID0_B314_Test_stress_ubuntu_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B314/monitor-agent-ID0_B314_Test_stress_ubuntu_Agent-warehouse-pullrequests_RSS(KB).svg)

**Comment by Molter73** [comment]
Closing this PR in order to reopen it as draft.

**Pull request closed without merging**
