### PR TITLE
Fix links to images (img->assets)

### PR DESCRIPTION
**Pull request by bufferoverflow**
## Description

The images within wazuh/wazuh-kibana-app repo have been moved from img to assets folder.

## Tests

not relevant, see preview of file.

### CODE REVIEW

**Comment by bufferoverflow** [comment]
@chemamartinez this is just a little fix for the README.md to show the images again.

**Review by max-wittig — APPROVED** [review]

**Comment by bufferoverflow** [comment]
@vikman90 could you maybe look at this mini doc fix, so images are displayed again within the `README.md` ?

**Review by vikman90 — APPROVED** [review]
LGTM!

**Comment by vikman90** [comment]
@bufferoverflow Merged. Thank you very much for taking the time to fix that!

Best regards.

**Pull request merged**
