### PR TITLE
Ruleset copyright update

### PR DESCRIPTION
**Pull request by 72nomada**
|Related issue|
|---|
||

Modify copyright details to:

- [X]  Update author reference
- [X]  Update copyright year to 2021

Configuration options

N/A

Logs/Alerts example

N/A

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

### CODE REVIEW

**Review by JavierBejMen — DISMISSED** [review]
LGTM

**Review by JavierBejMen — COMMENTED** [review]
LGTM

**Review by JavierBejMen — DISMISSED** [review]

**Comment by MiguelCasaresRobles** [comment]
Files that still have an author:
- ruleset/decoders/0485-nextcloud_decoders.xml  
-  ruleset/decoders/0480-perdition_decoders.xml 
-  ruleset/decoders/0535-haproxy_decoders.xml
-  ruleset/rules/0630-nextcloud_rules.xml

**Review by MiguelCasaresRobles — APPROVED** [review]

**Review by JavierBejMen — APPROVED** [review]
LGTM

**Pull request merged**
