### PR TITLE
Update Wazuh MITRE ATT&CK database to version 11.3

### PR DESCRIPTION
**Pull request by 72nomada**
|Related issue|
|---|
|#13555|

Add the new MITRE ATT&CK Enterprise version 11.3

## Tasks

- [x] Replace MITRE ATT&CK enterprise-attack.json file with the newest
- [x] Verify new created DB works with the Manager, API, and Dashboards
- [x] Verify a full packet from the branch that creates the DB.

### CODE REVIEW

**Comment by 72nomada** [comment]
Search details from Dashboard

image

**Comment by 72nomada** [comment]
Techniques list from Mitre - Intelligence

image

**Comment by 72nomada** [comment]
The Mitre items from the event list.

image

**Review by mcarmona99 — APPROVED** [review]

**Review by mcarmona99 — APPROVED** [review]

**Review by jmv74211 — APPROVED** [review]
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3395
- **Comments**:  Everything seems to be working properly

**Pull request merged**
