### PR TITLE
Engine - Fix cmake target all

### LINKED ISSUE #12331: Engine - Cmake target all is broken
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| engine-dev | engine | Manager | - | - |

Hi team!,

It is necessary to repair the target all of cmake, since many tests do not compile and make it difficult to measure the impact of a change because they cannot all be compiled at the same time.

We will also take advantage of this opportunity to implement the `split` function for strings in the development branch.

### PR DESCRIPTION
**Pull request by juliancnn**
|Related issue|
|---|
| Closes #12331 |

Hi Team, 

This PR fixes the target all in cmake of engine. For this, we should skkip some test.

The `split` function for strings is also added.

### CODE REVIEW

**Comment by JcabreraC** [comment]
## Split function test
```
[==========] Running 6 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 6 tests from split
[ RUN      ] split.notDelimiter
[       OK ] split.notDelimiter (0 ms)
[ RUN      ] split.middleDelimiter
[       OK ] split.middleDelimiter (0 ms)
[ RUN      ] split.firstDelimiter
[       OK ] split.firstDelimiter (0 ms)
[ RUN      ] split.finalDelimiter
[       OK ] split.finalDelimiter (0 ms)
[ RUN      ] split.dobleDelimiter
[       OK ] split.dobleDelimiter (0 ms)
[ RUN      ] split.okDelimiter
[       OK ] split.okDelimiter (0 ms)
[----------] 6 tests from split (0 ms total)
[----------] Global test environment tear-down
[==========] 6 tests from 1 test suite ran. (0 ms total)
[  PASSED  ] 6 tests.
```

**Review by JcabreraC — APPROVED** [review]
LGTM !

**Review by nmkoremblum — APPROVED** [review]
LGTM :)

**Review by JavierBejMen — APPROVED** [review]
LGTM

**Pull request merged**
