### PR TITLE
Deprecating get_agents_by_last_keepalive and get_agents_by_keepalive code

### PR DESCRIPTION
**Pull request by DProvinciani**
|Related issue|
|---|
| [Issue 6461](https://github.com/wazuh/wazuh/issues/6461) |

## Description

After implementing all the new agents' connection status management designed as part of the [Epic 5887](https://github.com/wazuh/wazuh/issues/5887), there is some code that is no longer required.

This PR removes the methods `get_agents_by_last_keepalive` and `get_agents_by_keepalive` as well as all the code related to them.

For more details, check the **requirements** section of the issue #6461.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [x] Package upgrade

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Valgrind

### CODE REVIEW

**Review by palaciosjeremias — COMMENTED** [review]
Shouldn't we remove WDB_STMT_GLOBAL_GET_AGENTS_BY_GREATER_KEEPALIVE and WDB_STMT_GLOBAL_GET_AGENTS_BY_LESS_KEEPALIVE queries from the array now they are not used anymore?

**Comment by DProvinciani** [comment]
@palaciosjeremias good catch! DONE!

**Review by palaciosjeremias — APPROVED** [review]
LGTM

**Review by pereyra-m — APPROVED** [review]
LGTM!

**Pull request merged**
