### PR TITLE
Update cis_rhel7_linux.yml

### PR DESCRIPTION
**Pull request by jdmedeiros**
Fixed bug in 4543: condition should be 'all' but it was 'none'
Fixed bug in 4556: it was looking for the wrong output

|Related issue|
|---|
||

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

### CODE REVIEW

**Comment by jdmedeiros** [comment]
Found another bug. All "stat" commands should have the "-L" flag so that it follows the symbolic link [if there is one] in order to get the right permissions. For example in 4547. Symbolic links, with the exception of BSD and MacOS, always have 777 permissions and will obviously fail the compliance check, but what really matters are the permissions on the file and not in the symbolic link.

**Comment by jdmedeiros** [comment]
Consider for example:
# 3.2.1 Ensure IP forwarding is disabled (Automated)
  - id: 4582 
If IPv6 is disabled in the kernel then the response from `sysctl net.ipv6.conf.all.accept_source_route` is not `net.ipv4.conf.default.accept_source_route = 0` It is in fact `sysctl: cannot stat /proc/sys/net/ipv6/conf/all/accept_source_route: No such file or directory` 

So the verification should be one of:
a) `net.ipv4.conf.default.accept_source_route = 0`
b) `sysctl: cannot stat`

This should be applied to all sysctl checks.

**Review by chemamartinez — CHANGES_REQUESTED** [review]

**Comment by chemamartinez** [comment]
> Found another bug. All "stat" commands should have the "-L" flag so that it follows the symbolic link [if there is one] in order to get the right permissions. For example in 4547. Symbolic links, with the exception of BSD and MacOS, always have 777 permissions and will obviously fail the compliance check, but what really matters are the permissions on the file and not in the symbolic link.

Opened issue https://github.com/wazuh/wazuh/issues/7624 to fix this case.

**Comment by chemamartinez** [comment]
> Consider for example:
> 
> # 3.2.1 Ensure IP forwarding is disabled (Automated)
> * id: 4582
>   If IPv6 is disabled in the kernel then the response from `sysctl net.ipv6.conf.all.accept_source_route` is not `net.ipv4.conf.default.accept_source_route = 0` It is in fact `sysctl: cannot stat /proc/sys/net/ipv6/conf/all/accept_source_route: No such file or directory`
> 
> So the verification should be one of:
> a) `net.ipv4.conf.default.accept_source_route = 0`
> b) `sysctl: cannot stat`
> 
> This should be applied to all sysctl checks.

In this case, we could discuss if there exists a bug in the policies when checking the `sysctl` output. We understand your point of view, however, SCA should be understood as a **configuration assessment**. 

That means you can have a feature disabled by several vias (kernel, configuration, etc.), but SCA is just checking if your configuration is correct. In the case of 4582, you can have IPv6 disabled but that fact is not reflected in the configuration since there no exists the file `/proc/sys/net/ipv6/conf/all/accept_source_route` with the value 0. In that situation, the **configuration** assessment should tell you that it is not properly configured.

**Comment by jdmedeiros** [comment]
> net.ipv4.conf.default.accept_source_route

...it is properly configure.

I understand your point, but it's still a programming problem. Maybe my approach to solve it is not the best, but if you look at page 199 of CIS_Red_Hat_Enterprise_Linux_7_Benchmark_v3.0.1.pdf it states clearly: 

> IF IPv6 is enabled:
> Run the following commands and verify output matches:

So, either we are able to conditionally do the verifications, and in the case of IPv6 one would need to verify if it's enabled before checking, or we deal with the results of doing those verifications conditionally. Probable the first option would be the elegant solution; the second may be easier to implement.

**Comment by chemamartinez** [comment]
> > net.ipv4.conf.default.accept_source_route
> 
> ...it is properly configure.
> 
> I understand your point, but it's still a programming problem. Maybe my approach to solve it is not the best, but if you look at page 199 of CIS_Red_Hat_Enterprise_Linux_7_Benchmark_v3.0.1.pdf it states clearly:
> 
> > IF IPv6 is enabled:
> > Run the following commands and verify output matches:
> 
> So, either we are able to conditionally do the verifications, and in the case of IPv6 one would need to verify if it's enabled before checking, or we deal with the results of doing those verifications unconditionally. Probable the first option would be the elegant solution; the second may be easier to implement.

I understand and will discuss it with the team because it is so interesting. We also have to analyze if the current SCA limitations (checks and rules cannot be nested) allow us to achieve a better solution for the cases in which this applies.

**Comment by chemamartinez** [comment]
Hi @jdmedeiros,

Hope you are doing well.

I've seen you have opened three more pull request to apply the changes I requested here:
https://github.com/wazuh/wazuh/pull/7627
https://github.com/wazuh/wazuh/pull/7628
https://github.com/wazuh/wazuh/pull/7629

Please remove them and apply the changes in this same pull request. If you are not used to working with Github we can help you with that.

Best regards.

**Comment by chemamartinez** [comment]
Closing this pull request since changes were already merged at https://github.com/wazuh/wazuh/pull/7645.

Best regards.

**Pull request closed without merging**
