### PR TITLE
Fix segfault for wazuh-logtest-legacy -a argument

### LINKED ISSUE #8890: wazuh-logtest-legacy segfault when -a option is used
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2-rc6 up to master (4.3) | `wazuh-logtest-legacy` (ex `ossec-logtest`) | Manager | Any | Any |

Hi team!

This issue aims to report a segfault when using `wazuh-logtest-legacy` with `-a` option. Expected behavior is `wazuh-logtest-legacy` showing `alert.log`-like information in case the log generates an alert.
### Expected output (v4.1.5)
```
╰─# /var/ossec/bin/ossec-logtest -V

Wazuh v4.1.5 - Wazuh Inc.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License (version 2) as 
published by the Free Software Foundation. For more details, go to 
https://www.gnu.org/licenses/gpl.html

╰─#  /var/ossec/bin/ossec-logtest -a
2021/06/02 20:04:43 ossec-testrule: INFO: Started (pid: 1859).
Since Wazuh v4.1.0 this binary is deprecated. Use wazuh-logtest instead

Oct 15 21:07:00 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928

** Alert 1622664283.1: - syslog,sshd,invalid_login,authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,pci_dss_10.6.1,gpg13_7.1,gdpr_IV_35.7.d,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,nist_800_53_AU.6,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2021 Jun 02 20:04:43 linux-agent->stdin
Rule: 5710 (level 5) -> '(null)'
Src IP: 18.18.18.18
Src Port: 48928
Oct 15 21:07:00 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928
[root@manager ~]# /var/ossec/bin/ossec-logtest -V
Wazuh v4.1.5 - Wazuh Inc.
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License (version 2) as 
published by the Free Software Foundation. For more details, go to 
https://www.gnu.org/licenses/gpl.html
```

### Current output on 4.2
```
╰─# /var/ossec/bin/wazuh-logtest-legacy -V                                                                                                                                                                             
 
Wazuh v4.2.0 - Wazuh Inc.
 
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License (version 2) as 
published by the Free Software Foundation. For more details, go to 
https://www.gnu.org/licenses/gpl.html

╰─# /var/ossec/bin/wazuh-logtest-legacy -a
2021/06/02 19:50:18 wazuh-testrule: INFO: Started (pid: 212628).

Since Wazuh v4.1.0 this binary is deprecated. Use wazuh-logtest instead

Oct 15 21:07:00 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928
[1]    212628 segmentation fault (core dumped)  /var/ossec/bin/wazuh-logtest-legacy -a
```
### Current output on master (4.3)
```
╰─# /var/ossec/bin/wazuh-logtest-legacy -V                                                                                                                                                                             
 
Wazuh v4.3.0 - Wazuh Inc.
 
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License (version 2) as 
published by the Free Software Foundation. For more details, go to 
https://www.gnu.org/licenses/gpl.html

╰─# /var/ossec/bin/wazuh-logtest-legacy -a
2021/06/02 19:59:47 wazuh-testrule: INFO: Started (pid: 212635).

Since Wazuh v4.1.0 this binary is deprecated. Use wazuh-logtest instead

Oct 15 21:07:00 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928
[1]    212635 segmentation fault (core dumped)  /var/ossec/bin/wazuh-logtest-legacy -a
```

Regards,
Nico

### PR DESCRIPTION
**Pull request by juliancnn**
|Related issue|
|---|
|Closes #8890|

Hi team!,

This PR solves the segfault when an alert is generated with the -a option.

PR Output:

```
╰─# /var/ossec/bin/wazuh-logtest-legacy -a      
2021/06/02 23:11:10 wazuh-testrule: INFO: Started (pid: 148714).
Since Wazuh v4.1.0 this binary is deprecated. Use wazuh-logtest instead
Oct 15 21:07:00 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928
** Alert 1622675471.1: - syslog,sshd,invalid_login,authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,pci_dss_10.6.1,gpg13_7.1,gdpr_IV_35.7.d,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,nist_800_53_AU.6,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2021 Jun 02 23:11:11 linux-agent->stdin
Rule: 5710 (level 5) -> '(null)'
Src IP: 18.18.18.18
Src Port: 48928
Oct 15 21:07:00 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928
^C#                                                                                                                                                     
╭─root@30-u20-manager ~/repos/wazuh ‹4.2*› 
╰─# /var/ossec/bin/wazuh-logtest-legacy -V 
Wazuh v4.2.0 - Wazuh Inc.
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License (version 2) as 
published by the Free Software Foundation. For more details, go to 
https://www.gnu.org/licenses/gpl.html
```

## Logs/Alerts example

input log:
```
Oct 15 21:07:00 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928
```

PR Output
```
** Alert 1622675471.1: - syslog,sshd,invalid_login,authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,pci_dss_10.6.1,gpg13_7.1,gdpr_IV_35.7.d,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,nist_800_53_AU.6,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2021 Jun 02 23:11:11 linux-agent->stdin
Rule: 5710 (level 5) -> '(null)'
Src IP: 18.18.18.18
Src Port: 48928
Oct 15 21:07:00 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928
```

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [X] ~Windows~
  - [X] ~MAC OS X~
- [x] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [x] Scan-build report
  - [ ] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [X] ~Dr. Memory~
  - [X] ~AddressSanitizer~
- Memory tests for Windows
  - [X] ~Scan-build report~
  - [X] ~Coverity~
  - [X] ~Dr. Memory~
- Memory tests for macOS
  - [X] ~Scan-build report~
  - [X] ~Leaks~
  - [X] ~AddressSanitizer~

- [x] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

### CODE REVIEW

**Comment by jnasselle** [comment]
## `scanbuild` report
[scan-build-2021-06-02-232741-263490-1.zip](https://github.com/wazuh/wazuh/files/6587939/scan-build-2021-06-02-232741-263490-1.zip)

**Comment by juliancnn** [comment]
Attached are 2 clean valgrind reports.
This report ([ValgrindPR_logtest_arg_a.log](https://github.com/wazuh/wazuh/files/6587950/ValgrindPR_logtest_arg_a.log)) is generating alerts with option `-a`,
and this report ([ValgrindPR_logtest_no_arg.log](https://github.com/wazuh/wazuh/files/6587952/ValgrindPR_logtest_no_arg.log))
 without any option
 
 
 ```
 ==259031== Memcheck, a memory error detector
==259031== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==259031== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==259031== Command: /var/ossec/bin/wazuh-logtest-legacy
==259031== Parent PID: 70275
==259031== 
==259031== 
==259031== HEAP SUMMARY:
==259031==     in use at exit: 16,038,109 bytes in 80,852 blocks
==259031==   total heap usage: 572,503 allocs, 491,651 frees, 1,811,662,551 bytes allocated
==259031== 
==259031== LEAK SUMMARY:
==259031==    definitely lost: 0 bytes in 0 blocks
==259031==    indirectly lost: 0 bytes in 0 blocks
==259031==      possibly lost: 0 bytes in 0 blocks
==259031==    still reachable: 16,038,109 bytes in 80,852 blocks
==259031==         suppressed: 0 bytes in 0 blocks
==259031== Reachable blocks (those to which a pointer was found) are not shown.
==259031== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==259031== 
 ```
 
 ```
 ==258856== Memcheck, a memory error detector
==258856== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==258856== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==258856== Command: /var/ossec/bin/wazuh-logtest-legacy -a
==258856== Parent PID: 70275
==258856== 
==258856== 
==258856== HEAP SUMMARY:
==258856==     in use at exit: 16,037,962 bytes in 80,849 blocks
==258856==   total heap usage: 572,501 allocs, 491,652 frees, 1,811,663,428 bytes allocated
==258856== 
==258856== LEAK SUMMARY:
==258856==    definitely lost: 0 bytes in 0 blocks
==258856==    indirectly lost: 0 bytes in 0 blocks
==258856==      possibly lost: 0 bytes in 0 blocks
==258856==    still reachable: 16,037,962 bytes in 80,849 blocks
==258856==         suppressed: 0 bytes in 0 blocks
==258856== Reachable blocks (those to which a pointer was found) are not shown.
==258856== To see them, rerun with: --leak-check=full --show-leak-kinds=all
 ```

**Review by jnasselle — APPROVED** [review]
:rocket:

**Review by nmkoremblum — APPROVED** [review]

**Review by vikman90 — CHANGES_REQUESTED** [review]
@juliancnn thank you for this quick fix.
I see that function `OS_LogOutput()` is very similar to `OS_Log()`. Do you think that we could merge them back into one?

For instance:
```c
void OS_Log(FILE *fp) { }
```
So, Analysisd would call `OS_Log(_aflog)` while Logtest would call `OS_Log(stdout)`.

Chiers!

**Comment by juliancnn** [comment]
Hi team!,

I update the reports after the changes requested by @vikman90 

Valgrind  report of `wazuh-analysisd ` with `<logall>yes</logall>`

```
==25305== Memcheck, a memory error detector
==25305== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==25305== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==25305== Command: /var/ossec/bin/wazuh-analysisd -fdd
==25305== Parent PID: 22734
==25305== 
==25305== 
==25305== HEAP SUMMARY:
==25305==     in use at exit: 16,333,000 bytes in 84,131 blocks
==25305==   total heap usage: 606,288 allocs, 522,157 frees, 1,868,106,684 bytes allocated
==25305== 
==25305== LEAK SUMMARY:
==25305==    definitely lost: 0 bytes in 0 blocks
==25305==    indirectly lost: 0 bytes in 0 blocks
==25305==      possibly lost: 42,704 bytes in 157 blocks
==25305==    still reachable: 16,290,296 bytes in 83,974 blocks
==25305==         suppressed: 0 bytes in 0 blocks
```


[Scanbuild report] (https://github.com/wazuh/wazuh/files/6592833/scan.zip)

**Review by jnasselle — APPROVED** [review]

**Comment by JcabreraC** [comment]
Valgrind report of `wazuh-logtest-legacy -a`:
```
==29598== Memcheck, a memory error detector
==29598== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==29598== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==29598== Command: /var/ossec/bin/wazuh-logtest-legacy -a
==29598== Parent PID: 10278
==29598== 
==29598== 
==29598== FILE DESCRIPTORS: 10 open at exit.
==29598== Open file descriptor 9: queue/fts/ig-queue
==29598==    at 0x5EBED5E: open (open64.c:47)
==29598==    by 0x5E3B659: _IO_file_open (fileops.c:189)
==29598==    by 0x5E3B659: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==29598==    by 0x5E2DF89: __fopen_internal (iofopen.c:78)
==29598==    by 0x5E2DF89: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==29598==    by 0x11F775: FTS_Init (fts.c:133)
==29598==    by 0x148B73: OS_ReadMSG (testrule.c:538)
==29598==    by 0x1489F4: main (testrule.c:490)
==29598== 
==29598== Open file descriptor 8: queue/fts/fts-queue
==29598==    at 0x5EBED5E: open (open64.c:47)
==29598==    by 0x5E3B659: _IO_file_open (fileops.c:189)
==29598==    by 0x5E3B659: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==29598==    by 0x5E2DF89: __fopen_internal (iofopen.c:78)
==29598==    by 0x5E2DF89: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==29598==    by 0x11F436: FTS_Init (fts.c:81)
==29598==    by 0x148B73: OS_ReadMSG (testrule.c:538)
==29598==    by 0x1489F4: main (testrule.c:490)
==29598== 
==29598== Open file descriptor 7: /dev/urandom
==29598==    at 0x5BA1E1B: open (open64.c:47)
==29598==    by 0x251F9B: randombytes (randombytes.c:62)
==29598==    by 0x252073: srandom_init (randombytes.c:82)
==29598==    by 0x147A4D: main (testrule.c:188)
==29598== 
==29598== Open file descriptor 6: /proc/stat
==29598==    at 0x5BA1E1B: open (open64.c:47)
==29598==    by 0x4F3DE8F: init_libproc (in /var/ossec/lib/libwazuhext.so)
==29598==    by 0x40108D2: call_init (dl-init.c:72)
==29598==    by 0x40108D2: _dl_init (dl-init.c:119)
==29598==    by 0x40010C9: ??? (in /lib/x86_64-linux-gnu/ld-2.27.so)
==29598==    by 0x1: ???
==29598==    by 0x1FFF00071E: ???
==29598==    by 0x1FFF000742: ???
==29598== 
==29598== Open file descriptor 5: /proc/uptime
==29598==    at 0x5BA1E1B: open (open64.c:47)
==29598==    by 0x4F3DE3B: init_libproc (in /var/ossec/lib/libwazuhext.so)
==29598==    by 0x40108D2: call_init (dl-init.c:72)
==29598==    by 0x40108D2: _dl_init (dl-init.c:119)
==29598==    by 0x40010C9: ??? (in /lib/x86_64-linux-gnu/ld-2.27.so)
==29598==    by 0x1: ???
==29598==    by 0x1FFF00071E: ???
==29598==    by 0x1FFF000742: ???
==29598== 
==29598== Open file descriptor 4: /home/cabrera/ValgrindPRs.log
==29598==    <inherited from parent>
==29598== 
==29598== Open file descriptor 3: /home/cabrera/test.txt
==29598==    <inherited from parent>
==29598== 
==29598== Open file descriptor 2: /dev/pts/1
==29598==    <inherited from parent>
==29598== 
==29598== Open file descriptor 1: /dev/pts/1
==29598==    <inherited from parent>
==29598== 
==29598== Open file descriptor 0: /dev/pts/1
==29598==    <inherited from parent>
==29598== 
==29598== 
==29598== HEAP SUMMARY:
==29598==     in use at exit: 16,028,198 bytes in 80,834 blocks
==29598==   total heap usage: 573,875 allocs, 493,041 frees, 1,818,527,905 bytes allocated
==29598== 
==29598== LEAK SUMMARY:
==29598==    definitely lost: 0 bytes in 0 blocks
==29598==    indirectly lost: 0 bytes in 0 blocks
==29598==      possibly lost: 0 bytes in 0 blocks
==29598==    still reachable: 16,028,198 bytes in 80,834 blocks
==29598==         suppressed: 0 bytes in 0 blocks
==29598== Reachable blocks (those to which a pointer was found) are not shown.
==29598== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==29598== 
==29598== For counts of detected and suppressed errors, rerun with: -v
==29598== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Review by JcabreraC — APPROVED** [review]
LGTM !

**Comment by juliancnn** [comment]
> @juliancnn thank you for this quick fix.
> I see that function `OS_LogOutput()` is very similar to `OS_Log()`. Do you think that we could merge them back into one?
> 
> For instance:
> 
> ```c
> void OS_Log(FILE *fp) { }
> ```
> 
> So, Analysisd would call `OS_Log(_aflog)` while Logtest would call `OS_Log(stdout)`.
> 
> Chiers!

Done!

**Review by nmkoremblum — APPROVED** [review]

**Review by vikman90 — APPROVED** [review]

**Pull request merged**
