### PR TITLE
CVEs alerts inventory for Vulnerability Detector - Implementation

### PR DESCRIPTION
**Pull request by DProvinciani**
|Related issue|
|---|
| https://github.com/wazuh/wazuh/issues/7749 |

## Description

This pull request includes all the changes of the epic [**CVEs alerts inventory for Vulnerability Detector**](https://github.com/wazuh/wazuh/issues/7749).

- For details on the desing, check the **description** section of the issue: 
  - https://github.com/wazuh/wazuh/issues/7749.
- For details on the testing done:
    - **Exploratory testing**: Check the **comments** of the issue: 
      - https://github.com/wazuh/wazuh/issues/7928.
    - **Unit testing**: We implemented unit test cases to cover all the new and modified functions. Check the issues:
      - https://github.com/wazuh/wazuh/issues/8112
      - https://github.com/wazuh/wazuh/issues/8092
      - https://github.com/wazuh/wazuh/issues/8027
      - https://github.com/wazuh/wazuh/issues/7926.

## Configuration options

- **ignore_time**: This setting was deprecated. Check the changes implemented in:
  - https://github.com/wazuh/wazuh/pull/7892
  - https://github.com/wazuh/wazuh/pull/8134
  - https://github.com/wazuh/wazuh-documentation/pull/3600.
- **min_full_scan_interval**: This new setting was added to define the minimum amount of time before which a full scan shouldn't be performed.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [x] MAC OS X
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [x] Package upgrade

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)

- [x] Retrocompatibility with older Wazuh versions
- [x] Working on cluster environments
- [x] Added unit tests (for new features)

### CODE REVIEW

**Comment by MiguelazoDS** [comment]
Scan-build execution
image

**Comment by DProvinciani** [comment]
### Coverity scan

image

The issue reported by Coverity was analyzed and was not introduced as part of this implementation. It will be resolved as a separate issue.

```
*** CID 236639:  Program hangs  (LOCK)
/syscheckd/create_db.c: 1723 in update_wildcards_config()
1717             os_free(paths);
1718         }
1719     
1720         removed_entries = OSList_Create();
1721         if (removed_entries == NULL) {
1722             merror(MEM_ERROR, errno, strerror(errno));
>>>     CID 236639:  Program hangs  (LOCK)
>>>     Returning without unlocking "syscheck.directories_lock".
1723             return;
1724         }
1725         OSList_SetFreeDataPointer(removed_entries, (void (*)(void *))free_directory);
1726     
1727         node_it = OSList_GetFirstNode(syscheck.directories);
1728         while (node_it != NULL) {
```

**Comment by palaciosjeremias** [comment]
UT Valgrind executions after fixing rebase problems:
image
image

**Review by vikman90 — APPROVED** [review]
LGTM!

**Pull request merged**
