### PR TITLE
Update stateful events models

### PR DESCRIPTION
**Pull request by GGP1**
|Related issue|
|---|
| Closes https://github.com/wazuh/wazuh/issues/26568 |

## Description

Updates the stateful events models and index names to conform with what is defined in https://github.com/wazuh/wazuh-indexer/tree/master/ecs and https://github.com/wazuh/wazuh-indexer/issues/270.

### Tests

<details><summary>Send FIM event</summary>

```console
(venv) gasti@gasti:~/work/wazuh$ curl -H "Authorization: Bearer $TOKEN" -H "User-Agent: test endpoint v5.0.0" -H "Agent-Groups: default,group1,group2" -H "Content-Type: application/json" -ks -X POST https://0.0.0.0:27000/api/v1/events/stateful -d '
{
  "events": [
    {
      "data": {
        "file": {
          "attributes": ["string"],
          "name": "string",
          "path": "string",
          "gid": 0,
          "group": "string",
          "inode": "string",
          "mtime": "2024-10-30T14:59:31.558Z",
          "mode": "string",
          "size": 0,
          "target_path": "string",
          "type": "string",
          "uid": 0,
          "owner": "string",
          "hash": {
            "md5": "string",
            "sha1": "string",
            "sha256": "string"
          }
        },
        "registry": {
          "key": "string",
          "value": "string"
        }
      },
      "module": {
        "name": "fim"
      }
    }
  ]
}' | jq
{
  "results": [
    {
      "id": "6xPU45IBKRnA5k4nQ6as",
      "result": "created",
      "status": 201
    }
  ]
}
{"results":[{"id":"PZf93ZIBfzyT-8mULNgI","result":"created","status":201}]}
```

</details>

<details><summary>Get FIM event</summary>

```console
(venv) gasti@gasti:~/work/wazuh$ curl -H "Content-Type: application/json" -ku admin:SecretPassword1% http://localhost:9200/wazuh-states-fim/_doc/6xPU45IBKRnA5k4nQ6as?pretty=true
{
  "_index" : "wazuh-states-fim",
  "_id" : "6xPU45IBKRnA5k4nQ6as",
  "_version" : 1,
  "_seq_no" : 0,
  "_primary_term" : 1,
  "found" : true,
  "_source" : {
    "agent" : {
      "id" : "01929571-49b5-75e8-a3f6-1d2b84f4f71a",
      "groups" : [
        "default",
        "group1",
        "group2"
      ]
    },
    "file" : {
      "attributes" : [
        "string"
      ],
      "name" : "string",
      "path" : "string",
      "gid" : 0,
      "group" : "string",
      "inode" : "string",
      "mtime" : "2024-10-30T14:59:31.558000+00:00",
      "mode" : "string",
      "size" : 0.0,
      "target_path" : "string",
      "type" : "string",
      "uid" : 0,
      "owner" : "string",
      "hash" : {
        "md5" : "string",
        "sha1" : "string",
        "sha256" : "string"
      }
    },
    "registry" : {
      "key" : "string",
      "value" : "string"
    }
  }
}
```

</details>

<details><summary>Try to send an event using an invalid module name</summary>

```console
(venv) gasti@gasti:~/work/wazuh$ curl -H "Authorization: Bearer $TOKEN" -H "User-Agent: test endpoint v5.0.0" -H "Agent-Groups: default,group1,group2" -H "Content-Type: application/json" -ks -X POST https://0.0.0.0:27000/api/v1/events/stateful -d '
{
  "events": [
    {
      "data": {},
      "module": {
        "name": "agent"
      }
    }
  ]
}' | jq
{
  "message": "('body', 'events', 0, 'module', 'name') input should be 'fim', 'inventory', 'sca', 'vulnerability' or 'command'",
  "code": 400
}
```

</details>

<details><summary>Try to send an event using an invalid module type</summary>

```console
(venv) gasti@gasti:~/work/wazuh$ curl -H "Authorization: Bearer $TOKEN" -H "User-Agent: test endpoint v5.0.0" -H "Agent-Groups: default,group1,group2" -H "Content-Type: application/json" -ks -X POST https://0.0.0.0:27000/api/v1/events/stateful -d '
{
  "events": [
    {
      "data": {},
      "module": {
        "name": "inventory",
        "type": "test"
      }
    }
  ]
}' | jq
{
  "message": "Invalid inventory module type. It must be 'network', 'package', 'process' or 'system'",
  "code": 400
}
```

</details>

<details><summary>Try to send an event using an invalid User-Agent</summary>

```console
(venv) gasti@gasti:~/work/wazuh$ curl -H "Authorization: Bearer $TOKEN" -H "User-Agent: test" -H "Agent-Groups: default,group1,group2" -H "Content-Type: application/json" -ks -X POST https://0.0.0.0:27000/api/v1/events/stateful -d '
{
  "events": [
    {
      "data": {},
      "module": {
        "name": "sca"
      }
    }
  ]
}' | jq
{
  "message": "Invalid User-Agent HTTP header value. It must follow the format '<name> <type> <version>'",
  "code": 400
}
```

</details>

<details><summary>Try to send an event with no User-Agent header</summary>

```console
(venv) gasti@gasti:~/work/wazuh$ curl -H "Authorization: Bearer $TOKEN" -H "Agent-Groups: default" -H "Content-Type: application/json" -ks -X POST https://0.0.0.0:27000/api/v1/events/stateful -d '
{
  "events": [
    {
      "data": {},
      "module": {
        "name": "sca"
      }
    }
  ]
}' | jq
{
  "message": "('header', 'user-agent') field required",
  "code": 400
}
```

</details>

<details><summary>Send event with no Agent-Groups header</summary>

```console
(venv) gasti@gasti:~/work/wazuh$ curl -H "Authorization: Bearer $TOKEN" -H "User-Agent: test endpoint v5.0.0" -H "Content-Type: application/json" -ks -X POST https://0.0.0.0:27000/api/v1/events/stateful -d '
{
  "events": [
    {
      "data": {},
      "module": {
        "name": "sca"
      }
    }
  ]
}' | jq
{
  "results": [
    {
      "id": "8RPt45IBKRnA5k4n-aYD",
      "result": "created",
      "status": 201
    }
  ]
}
```

</details>

<details><summary>Get indexed event</summary>

```console
(venv) gasti@gasti:~/work/wazuh$ curl -H "Content-Type: application/json" -ku admin:SecretPassword1% http://localhost:9200/wazuh-states-sca/_doc/8RPt45IBKRnA5k4n-aYD?pretty=true
{
  "_index" : "wazuh-states-sca",
  "_id" : "8RPt45IBKRnA5k4n-aYD",
  "_version" : 1,
  "_seq_no" : 1,
  "_primary_term" : 1,
  "found" : true,
  "_source" : {
    "agent" : {
      "id" : "01929571-49b5-75e8-a3f6-1d2b84f4f71a",
      "groups" : [ ]
    }
  }
}
```

</details>

### CODE REVIEW

**Review by RamosFe — DISMISSED** [review]
LGTM 🥇

**Review by fdalmaup — CHANGES_REQUESTED** [review]
The PR can be used to discuss some points related to the events before the merge:
- We need to check with the Agent team the information to be provided related to the `operation` inside an event to define if new endpoints are required (it would involve the creation of new issues)
- The `events` field in the body might contain multiple objects, which would be entirely loaded in memory for each request. We should propose a limit to the number of events or consider whether these need to be received as a stream ([Request.stream()](https://fastapi.tiangolo.com/reference/request/?h=stream#fastapi.Request.stream)).

**Comment by GGP1** [comment]
>We need to check with the Agent team the information to be provided related to the operation inside an event to define if new endpoints are required (it would involve the creation of new issues)

I left a message in the channel so we can discuss this with the rest of the teams. If necessary, we can create new issues based on what we conclude there.

> The events field in the body might contain multiple objects, which would be entirely loaded in memory for each request. We should propose a limit to the number of events or consider whether these need to be received as a stream ([Request.stream()](https://fastapi.tiangolo.com/reference/request/?h=stream#fastapi.Request.stream)).

I agree with this, we need either to limit the requests size or consume large bodies using a stream. The second option is more elaborate because we need to parse bytes into Python objects and that could be tricky.

That being said, I think this is something we should discuss for the feature complete implementation and that has to be at the API level instead of on a single endpoint.

I have created the issue https://github.com/wazuh/wazuh/issues/26675 to investigate this.

**Review by fdalmaup — APPROVED** [review]
LGTM!

**Pull request merged**
