### PR TITLE
Remove profile prefixes

### PR DESCRIPTION
**Pull request by GGP1**
|Related issue|
|---|
|Closes https://github.com/wazuh/wazuh/issues/20752 |

## Description

Removes the profile prefixes from the AWS configuration values.

## Configuration options

<details><summary>Credentials</summary>

```console
root@wazuh-master:/# cat /root/.aws/credentials
[default]
aws_access_key_id=foo
aws_secret_access_key=bar
region=us-east-1

[dev]
aws_access_key_id=foo
aws_secret_access_key=bar
region=us-east-1

[test]
aws_access_key_id=foo
aws_secret_access_key=bar
region=us-east-1
```

</details>

<details><summary>Configuration</summary>

```console
root@wazuh-master:/# cat /root/.aws/config
[default]
region=us-east-1
max_attempts=10
retry_mode=standard
s3.max_concurrent_requests = 20
s3.max_queue_size = 500
proxy.host = localhost
proxy.port = 8080
signature_version = s3v4

[profile dev]
region=us-east-1
max_attempts=5
retry_mode=standard
s3.max_concurrent_requests = 10
s3.max_queue_size = 1000
proxy.host = localhost
proxy.port = 8080
signature_version = s3v4

[profile test]
region=us-east-1
max_attempts=7
retry_mode=standard
s3.max_concurrent_requests = 15
s3.max_queue_size = 1200
proxy.host = localhost
proxy.port = 8080
signature_version = s3v4
```

</details>

## Logs/Alerts example

<details><summary>Profile 'default'</summary>

```console
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 /var/ossec/wodles/aws/aws-s3.py -b wazuh-xxx-cloudtrail -t cloudtrail -d2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Retries parameters found in user profile. Using profile 'default' retries configuration
DEBUG: Created Config object using profile: 'default' configuration
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/12/22
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/12/22
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/12/22
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
```

Configuration used

```console
DEBUG: {"region": "us-east-1", "max_attempts": "10", "retry_mode": "standard", "s3.max_concurrent_requests": "20", "s3.max_queue_size": "500", "proxy.host": "localhost", "proxy.port": "8080", "signature_version": "s3v4"}
```

</details>

<details><summary>Profile 'dev'</summary>

```console
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 /var/ossec/wodles/aws/aws-s3.py --aws_profile dev -b wazuh-xxx-cloudtrail -t cloudtrail -d2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Retries parameters found in user profile. Using profile 'profile dev' retries configuration
DEBUG: Created Config object using profile: 'profile dev' configuration
DEBUG: +++ Table does not exist; create
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/12/22
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/12/22
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/12/22
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
```

Configuration used

```console
DEBUG: {"region": "us-east-1", "max_attempts": "5", "retry_mode": "standard", "s3.max_concurrent_requests": "10", "s3.max_queue_size": "1000", "proxy.host": "localhost", "proxy.port": "8080", "signature_version": "s3v4"}
```

</details>

<details><summary>Profile 'test'</summary>

```console
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 /var/ossec/wodles/aws/aws-s3.py --aws_profile test -b wazuh-xxx-cloudtrail -t cloudtrail -d2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Retries parameters found in user profile. Using profile 'profile test' retries configuration
DEBUG: Created Config object using profile: 'profile test' configuration
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/12/22
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/12/22
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on xxxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxxx/CloudTrail/us-west-1/2023/12/22
DEBUG: +++ No logs to process in bucket: xxxx/us-west-1
DEBUG: +++ DB Maintenance
```

Configuration used

```console
DEBUG: {"region": "us-east-1", "max_attempts": "7", "retry_mode": "standard", "s3.max_concurrent_requests": "15", "s3.max_queue_size": "1200", "proxy.host": "localhost", "proxy.port": "8080", "signature_version": "s3v4"}
```

</details>

## Tests

<details><summary>AWS unit tests</summary>

```console
(venv10) gasti@pop-os:~/work/wazuh$ python3 -m pytest wodles/aws --disable-warnings
================================================= test session starts =================================================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.3.0
rootdir: /home/gasti/work/wazuh/wodles
configfile: pytest.ini
plugins: asyncio-0.18.1, tavern-1.23.5, trio-0.7.0, html-2.1.1, aiohttp-1.0.4, metadata-3.0.0
asyncio: mode=auto
collected 639 items                                                                                                   

wodles/aws/tests/test_aws_bucket.py ........................................................................... [ 11%]
............................................................................................................... [ 29%]
.......................                                                                                         [ 32%]
wodles/aws/tests/test_aws_s3.py ..................                                                              [ 35%]
wodles/aws/tests/test_aws_service.py ....                                                                       [ 36%]
wodles/aws/tests/test_cloudtrail.py ..                                                                          [ 36%]
wodles/aws/tests/test_cloudwatchlogs.py .....................................................                   [ 44%]
wodles/aws/tests/test_config.py ..............................................................................  [ 56%]
wodles/aws/tests/test_guardduty.py .................                                                            [ 59%]
wodles/aws/tests/test_inspector.py ......                                                                       [ 60%]
wodles/aws/tests/test_load_balancers.py ............                                                            [ 62%]
wodles/aws/tests/test_s3_log_handler.py ................                                                        [ 64%]
wodles/aws/tests/test_server_access.py .................................                                        [ 70%]
wodles/aws/tests/test_sqs_message_processor.py ........                                                         [ 71%]
wodles/aws/tests/test_sqs_queue.py .......                                                                      [ 72%]
wodles/aws/tests/test_tools.py ..................................                                               [ 77%]
wodles/aws/tests/test_umbrella.py ......                                                                        [ 78%]
wodles/aws/tests/test_vpcflow.py ...........................                                                    [ 82%]
wodles/aws/tests/test_waf.py .......                                                                            [ 84%]
wodles/aws/tests/test_wazuh_integration.py .................................................................... [ 94%]
..................................                                                                              [100%]

================================================= 639 passed in 2.39s =================================================
```

</details>

### CODE REVIEW

**Review by EduLeon12 — DISMISSED** [review]
LGTM!

**Review by Selutario — COMMENTED** [review]
Looks good. I'm just curious about this you mentioned in the PR description:

> In https://github.com/wazuh/wazuh/issues/20352, we added the possibility of using either [dev] or [profile dev], but now only the latter is accepted. **Furthermore, using --aws_profile default is no longer supported.**

I tried it and seems to be working yet:
```
# /var/ossec/wodles/aws/aws-s3 --bucket wazuh-aws-wodle-cloudtrail --aws_profile default --aws_account_alias test-feature-cloudtrail --only_logs_after 2022-JAN-01 --type cloudtrail --debug 2
DEBUG: +++ Debug mode on - Level: 2
pydev debugger: warning: trying to add breakpoint to file that does not exist: /home/selu/Git/wazuh/api/test/integration/mapping/_test_mapping.py (will have no effect)
DEBUG: Retries parameters found in user profile. Using profile 'default' retries configuration
DEBUG: Created Config object using profile: 'profile default' configuration
DEBUG: +++ Working on REDACTED - us-west-1
DEBUG: +++ Marker: AWSLogs/REDACTED/CloudTrail/us-west-1/2023/09/06/REDACTED_CloudTrail_us-west-1_20230906T1755Z_2CqtXDyI0zFiYm1J.json
DEBUG: +++ No logs to process in bucket: REDACTED/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on REDACTED - us-west-1
DEBUG: +++ Marker: AWSLogs/REDACTED/CloudTrail/us-west-1/2022/01/01
DEBUG: +++ No logs to process in bucket: REDACTED/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on 567970947422 - us-west-1
DEBUG: +++ Marker: AWSLogs/567970947422/CloudTrail/us-west-1/2023/01/25/REDACTED_CloudTrail_us-west-1_20211223T0000Z_HASDOtJxxxxxxxxx.json.gz
DEBUG: +++ No logs to process in bucket: 567970947422/us-west-1
DEBUG: +++ DB Maintenance
```

Is it correct? In any case, I like it more this way since it will be breaking for less people.

**Comment by GGP1** [comment]
> Looks good. I'm just curious about this you mentioned in the PR description:
> 
> > In #20352, we added the possibility of using either [dev] or [profile dev], but now only the latter is accepted. **Furthermore, using --aws_profile default is no longer supported.**
> 
> I tried it and seems to be working yet:
> 
> Is it correct? In any case, I like it more this way since it will be breaking for less people.

@Selutario I assumed that because of this line

```console
profile = f"profile {profile}" if profile is not None else 'default'
```

It would look for `[profile default]` instead of `[default]`. I also remember it failing when I tested it. It is possible that boto changed this behavior and now interprets them equally though. 

Did you use just `[default]` in the configuration? In any case, I also think it's better to keep it this way.

**Comment by Selutario** [comment]
I was wrong it seems. With this `~/.aws/config` file:
```CONFIG
# cat ~/.aws/config 
[default]
region=us-east-1
max_attempts=5
retry_mode=standard
s3.max_concurrent_requests = 10
s3.max_queue_size = 1000
proxy.host = localhost
proxy.port = 8080
signature_version = s3v4


[profile dev]
region=us-east-1
max_attempts=5
retry_mode=standard
s3.max_concurrent_requests = 10
s3.max_queue_size = 1000
proxy.host = localhost
proxy.port = 8080
signature_version = s3v4
``` 

This is the output:
```
# /var/ossec/wodles/aws/aws-s3 --bucket wazuh-aws-wodle-cloudtrail --aws_profile default --aws_account_alias test-feature-cloudtrail --only_logs_after 2022-JAN-01 --type cloudtrail --debug 2
DEBUG: +++ Debug mode on - Level: 2
No profile named: 'profile default' was found in the user config file
```

It works fine when `--aws_profile default` is not included as you mentioned. 

Would it make sense to keep [this part](https://github.com/wazuh/wazuh/pull/21042/files#diff-669e1379804c85b905c6d7c1df8772b88c695b4a452d1d35b4b92defb022379eL126-L130)? What's your opinion on this?
https://github.com/wazuh/wazuh/blob/e11c7a06959a5a215f872f9482890832c7170b7e/wodles/aws/wazuh_integration.py#L125-L130

**Comment by GGP1** [comment]
> Would it make sense to keep [this part](https://github.com/wazuh/wazuh/pull/21042/files#diff-669e1379804c85b905c6d7c1df8772b88c695b4a452d1d35b4b92defb022379eL126-L130)? What's your opinion on this?
> 
> https://github.com/wazuh/wazuh/blob/e11c7a06959a5a215f872f9482890832c7170b7e/wodles/aws/wazuh_integration.py#L125-L130

Leaving that part would make it fail because `profile` is not `None` so it will look for a `[profile default]` section. What we could do is 

```py
if profile is not None and profile != 'default':
    profile = f"profile {profile}"
else:
    profile = 'default'
```

This wouldn't let users to specify `[profile default]` in the configuration - since it will always fail - but that is not an issue since the AWS documentation suggests not to add the prefix in that case. 

I think it's better if we keep this specific behavior unchanged, Let me know if you agree and I will submit this change.

**Comment by GGP1** [comment]
> Would it make sense to keep [this part](https://github.com/wazuh/wazuh/pull/21042/files#diff-669e1379804c85b905c6d7c1df8772b88c695b4a452d1d35b4b92defb022379eL126-L130)? What's your opinion on this?

The AWS documentation suggests not to add the `profile` prefix to the `[default]` configuration section, so looking always for `[default]` I think is right thing to do. However, if the `default` profile is not configured, the error `No profile named: 'profile default' was found in the user config file` will be misleading since the user could interpret that it must add a `[profile default]` section. I think we should keep this behaviour unchanged but I would make the following change instead

```py
if profile is not None and profile != 'default': 
     if profile not in aws_config.sections(): 
         profile = f"profile {profile}" 
 else: 
     profile = 'default' 
```

**Comment by Selutario** [comment]
I think it's a great idea! :)

**Pull request merged**
