### PR TITLE
Decompress tar.xz vulnerability scanner database if found

### PR DESCRIPTION
**Pull request by MiguelazoDS**
|Related issue|
|---|
|#26524|

## Description 

This PR adds a decompression database step before starting the module if a tar.xz file exists in /tmp/wazuh-server

## DoD

<details><summary>Expand</summary>

- There's a tar.xz in the expected directory
- Target directory /var/lib does not contains any queue nor wazuh-server folder
- Compressed file contains legacy directory tree (queue as root folder)
- Vulnerability Scanner tool started
- After decompression, expected directory is found in /var/lib
- Unneeded files are removed.
image

- Decompression log messages.

</details>

## Update 

<details><summary>Expand</summary>

- Fix the wrong target library linking.
- UTs added.
- I don't see the issue with the guards and the convention file names
image
image
image
image
- I don't see the unneeded comments in the code

</details>

## Update 
image
image

### CODE REVIEW

**Comment by GabrielEValenzuela** [comment]
# Functional testing 🟢 

I made the compilation of this branch and created the `/tmp/wazuh-server` folder.
Then  copy the `vd_1.0.0_vd_4.x.0.tar.gz` files inside, and run

```bash
/wazuh/engine/build/source/vdscanner/tools/scanner/vdscanner_tool -s test.sock -l db.log
```

## Output log

```log
2024-10-31 15:16:16.776 113684:113684 databaseFeedManager.cpp:28 at DatabaseFeedManager(): info: Starting database file decompression.
2024-10-31 15:16:16.776 113684:113684 databaseFeedManager.cpp:44 at DatabaseFeedManager(): debug: Removing existent /var/lib/wazuh-server folder.
2024-10-31 15:16:16.778 113684:113684 databaseFeedManager.cpp:48 at DatabaseFeedManager(): debug: Starting XZ file decompression
2024-10-31 15:16:35.117 113684:113684 databaseFeedManager.cpp:52 at DatabaseFeedManager(): debug: Finishing XZ file decompression. Removing /tmp/wazuh-server/vd_1.0.0_vd_4.10.0.tar.xz.
2024-10-31 15:16:35.141 113684:113684 databaseFeedManager.cpp:59 at DatabaseFeedManager(): debug: Starting TAR file decompression.
2024-10-31 15:16:38.945 113684:113684 databaseFeedManager.cpp:62 at DatabaseFeedManager(): debug: Finishing TAR file decompression. Removing /tmp/wazuh-server/vd_1.0.0_vd_4.10.0.tar.
2024-10-31 15:16:39.821 113684:113684 scanOrchestrator.cpp:16 at ScanOrchestrator(): debug: Vulnerability scanner module started
```

```console
stat /var/lib/wazuh-server
  File: /var/lib/wazuh-server
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 259,6   Inode: 22282404    Links: 4
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-10-31 15:22:27.817915767 -0300
Modify: 2024-10-31 15:16:35.137389890 -0300
Change: 2024-10-31 15:16:39.629397039 -0300
 Birth: 2024-10-31 15:16:35.137389890 -0300
❯ ls /var/lib/wazuh-server
 vd   vd_updater
❯ ls /tmp/wazuh-server/
 vd_1.0.0_vd_4.8.0.tar.xz
```

- File `vd_1.0.0_vd_4.10.0.tar` removed ✔️ 
- File `vd_1.0.0_vd_4.8.0.tar` ignored ✔️ 
- Database decompressed  ✔️

**Review by GabrielEValenzuela — APPROVED** [review]
Testing 🟢 
Great work!

**Review by JavierBejMen — CHANGES_REQUESTED** [review]
I think this should be a separate module instead of being in the base module. I has interfaces and a well defined behaviour/scope so it should be no problem to structure it as its own module. The base module is intendeed to have simple and helper functionality to be used in the rest of the project.

**Review by JavierBejMen — CHANGES_REQUESTED** [review]
can we put the interfaces on the interface folder? take a look at another module as example please, we define the interfaces in a separate folder with a separate lib interface target like module::interface so other modules can only import the interfaces.

**Review by JavierBejMen — DISMISSED** [review]
LGTM

**Review by juliancnn — APPROVED** [review]
LGTM!

**Comment by MiguelazoDS** [comment]
# Update 

vdscanner test tool execution 
image

vdscanner logs
image

**Review by juliancnn — APPROVED** [review]
LGTM!

**Review by JavierBejMen — APPROVED** [review]
LGTM

**Review by sebasfalcone — APPROVED** [review]
LGTM

**Pull request merged**
