### PR TITLE
Create new statistics for better understanding of Wazuh manager

### PR DESCRIPTION
**Pull request by TomasTurina**
|Related issue|Documentation|Integration Tests|Manual Testing|
|---|---|---|---|
|https://github.com/wazuh/wazuh/issues/13099| https://github.com/wazuh/wazuh-documentation/pull/5503 | https://github.com/wazuh/wazuh-qa/pull/3271 |https://github.com/wazuh/wazuh-qa/issues/3113| 

## Description

This PR adds and improves the statistics of the Wazuh manager.

Now, global statistics in JSON format can be requested using the API for the following daemons:

- `wazuh-remoted`
- `wazuh-analysisd`
- `wazuh-db`

Also, agent's related statistics can be requested for the following daemons:

- `wazuh-remoted`
- `wazuh-analysisd`

Information related to the fields of the JSON can be found [here](https://github.com/wazuh/wazuh/issues/13100) and [here](https://github.com/wazuh/wazuh/issues/13102).

### Request / Response

All requests must point to the following sockets:

- `wazuh-remoted` -> `queue/sockets/remote`
- `wazuh-analysisd` -> `queue/sockets/analysis`
- `wazuh-db` -> `queue/db/wdb`

This is the request format expected for `getstats` query:

```json
{"version": 1, "origin": {"module": "api"}, "command": "getstats", "parameters": {}}
```

This is the request format expected for `getagentsstats` query:

```json
{"version": 1, "origin": {"module": "api"}, "command": "getagentsstats", "parameters": {"agents": [5, 7, 10]}}
```

In addition, the daemons now accept the `getconfig` in JSON format in the sockets described above. Example:

```json
{"version": 1, "origin": {"module": "api"}, "command": "getconfig", "parameters": {"section": "global"}}
```

> Note: To avoid having two sockets in `wazuh-remoted`, the socket `queue/sockets/request` will be deprecated and replaced by `queue/sockets/remote`.

This is the response format for `getstats`, `getagentsstats` and `getconfig` queries:

```json
{"error": 0, "data": {...}, "message": "ok"}
```

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [x] Package upgrade
- [x] Review logs syntax and correct language

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)

- [x] Retrocompatibility with older Wazuh versions
- [x] Working on cluster environments
- [x] The data flow works as expected (agent-manager-api-app)
- [x] Added unit tests (for new features)

### CODE REVIEW

**Review by sdvendramini — APPROVED** [review]
LGTM!

**Review by sdvendramini — APPROVED** [review]
LGTM!

**Review by sdvendramini — DISMISSED** [review]
LGTM!

**Review by sdvendramini — APPROVED** [review]
LGTM!

**Review by jmv74211 — APPROVED** [review]
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3113
- **Comments**:  https://github.com/wazuh/wazuh-qa/issues/3113#issuecomment-1290760650

**Review by vikman90 — APPROVED** [review]

**Pull request merged**
