### PR TITLE
Add raw Windows EventChannel support

### PR DESCRIPTION
**Pull request by tdrauncieal**
|Related issue|
|---|
|#17762|

It is intended to provide support for interpreting and processing Windows EventChannel events in a transparent way allowing to obtain these events directly from the `Windows Event Viewer` tool e.g. and to be able to compare them with those reported by wazuh (Dashboard) even to be able to test their flow using `wazuh-engine test...`

## Description
Regarding the development, it was necessary to make changes in the `logcollector` (agent side) changing the message that will later be processed.

current message structure extracted from the real one:
```json

{
  "Message": "The Telephony service entered the running state.",
  "Event": "<Event xmlns=http://schemas.microsoft.com/win/2004/08/events/event><System><Provider Name=Service Control Manager Guid={555908D1-A6D7-4695-8E1E-26931D2012F4} EventSourceName=Service Control Manager/><EventID Qualifiers=16384>7036</EventID><Version>0</Version><Level>4</Level><Task>0</Task><Opcode>0</Opcode><Keywords>0x80000000000000</Keywords><TimeCreated SystemTime=2023-07-07T19:05:29.000Z/><EventRecordID>1440</EventRecordID><Correlation/><Execution ProcessID=0 ThreadID=0/><Channel>System</Channel><Computer>test-PC</Computer><Security/></System><EventData><Data Name=param1>Telephony</Data><Data Name=param2>running</Data></EventData></Event>"
}

``` 
from now on only raw XML event is sent:
```xml

<Event xmlns=http://schemas.microsoft.com/win/2004/08/events/event>
	<System>
		<Provider Name=Service Control Manager Guid={555908D1-A6D7-4695-8E1E-26931D2012F4} EventSourceName=Service Control Manager/>
		<EventID Qualifiers=16384>7036</EventID>
		<Version>0</Version>
		<Level>4</Level>
		<Task>0</Task>
		<Opcode>0</Opcode>
		<Keywords>0x80000000000000</Keywords>
		<TimeCreated SystemTime=2023-07-07T19:05:29.000Z/>
		<EventRecordID>1440</EventRecordID>
		<Correlation/>
		<Execution ProcessID=0 ThreadID=0/>
		<Channel>System</Channel>
		<Computer>test-PC</Computer>
		<Security/>
	</System>
	<EventData>
		<Data Name=param1>Telephony</Data>
		<Data Name=param2>running</Data>
	</EventData>
</Event>

``` 
## Output
Some tests were placed here, mainly related to `wazuh-engine test` also real Window events too.

testing an extracted event
```shell
# wazuh-engine test --protocol_location "[115] (commandline-test) any->EventChannel" -q f -d < event.xml 
``` 
<details><summary>event.xml</summary>
<p>

```xml

<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4624</EventID><Version>2</Version><Level>0</Level><Task>12544</Task><Opcode>0</Opcode><Keywords>0x8020000000000000</Keywords><TimeCreated SystemTime='2023-07-11T17:14:07.5120744Z'/><EventRecordID>7733</EventRecordID><Correlation ActivityID='{58616339-b3b9-0001-a163-6158b9b3d901}'/><Execution ProcessID='732' ThreadID='3976'/><Channel>Security</Channel><Computer>DESKTOP-2GJHQ1J</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>S-1-5-18</Data><Data Name='SubjectUserName'>DESKTOP-2GJHQ1J$</Data><Data Name='SubjectDomainName'>WORKGROUP</Data><Data Name='SubjectLogonId'>0x3e7</Data><Data Name='TargetUserSid'>S-1-5-18</Data><Data Name='TargetUserName'>SYSTEM</Data><Data Name='TargetDomainName'>NT AUTHORITY</Data><Data Name='TargetLogonId'>0x3e7</Data><Data Name='LogonType'>5</Data><Data Name='LogonProcessName'>Advapi  </Data><Data Name='AuthenticationPackageName'>Negotiate</Data><Data Name='WorkstationName'>-</Data><Data Name='LogonGuid'>{00000000-0000-0000-0000-000000000000}</Data><Data Name='TransmittedServices'>-</Data><Data Name='LmPackageName'>-</Data><Data Name='KeyLength'>0</Data><Data Name='ProcessId'>0x2c0</Data><Data Name='ProcessName'>C:\Windows\System32\services.exe</Data><Data Name='IpAddress'>-</Data><Data Name='IpPort'>-</Data><Data Name='ImpersonationLevel'>%%1833</Data><Data Name='RestrictedAdminMode'>-</Data><Data Name='TargetOutboundUserName'>-</Data><Data Name='TargetOutboundDomainName'>-</Data><Data Name='VirtualAccount'>%%1843</Data><Data Name='TargetLinkedLogonId'>0x0</Data><Data Name='ElevatedToken'>%%1842</Data></EventData></Event>

``` 

</p>
</details> 

As can be seen, the event makes use of the specific Windows event decoders.

<details><summary>output made</summary>
<p>

```

DECODERS:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
  decoder/core-wazuh-message/0  ->  success                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    decoder/core-hostinfo/0  ->  failure                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
    decoder/core-ciscat/0  ->  failure                                                                                                           
    decoder/core-rootcheck/0  ->  failure
    decoder/core-windows/0  ->  success                                                                      
        decoder/integrations/0  ->  success                                                                                                                                                                                                                                                                                                                                                                                                          
                decoder/syslog/0  ->  failure                                                                                                                                                                                                                                                                                                                                                                                                        
                decoder/windows-json/0  ->  failure                                                                                                                                                                                                                                                                                                                                                                                                  
                decoder/windows-event-decoder/0  ->  success                                                                                                                                                                                                                                                                                                                                                                                         
                                decoder/windows-security/0  ->  success                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                              
RULES:                                                                                                                                                                                                                                                                                                                                                        
                                                                                       
                                                                                                             
OUTPUT:                       
                                                                                                                                                                                                                                                                                                                                                              
{                                                                                                                                                                                                                                                                                                                                                             
    "wazuh": {                                                                                                                                                                                                                                                                                                                                                
        "queue": 102,                                                                                                                                                                                                                                                                                                                                         
        "location": "[115] (commandline-test) any->EventChannel",                                                                                                                                                                                                                                                                                             
        "message": "<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4624</EventID><Version>2</Version><Level>0</Level><Task>12544</Task><Opcode>0</Opcode><Keywords>0x8020000000000000</Keywords><TimeCreated SystemTime='2023-07-11T17:14:07.5120744Z'/><EventRecordID>7733</EventRecordID><Correlation ActivityID='{58616339-b3b9-0001-a163-6158b9b3d901}'/><Execution ProcessID='732' ThreadID='3976'/><Channel>Security</Channel><Computer>DESKTOP-2GJHQ1
J</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>S-1-5-18</Data><Data Name='SubjectUserName'>DESKTOP-2GJHQ1J$</Data><Data Name='SubjectDomainName'>WORKGROUP</Data><Data Name='SubjectLogonId'>0x3e7</Data><Data Name='TargetUserSid'>S-1-5-18</Data><Data Name='TargetUserName'>SYSTEM</Data><Data Name='TargetDomainName'>NT AUTHORITY</Data><Data Name='TargetLogonId'>0x3e7</Data><Data Name='LogonType'>5</Data><Data Name='LogonProcessName'>Advapi  </Data><Data Name='AuthenticationPackageName'>Negotiate</Data><Data Name='WorkstationName'>-</Data><Data Name='LogonGu
id'>{00000000-0000-0000-0000-000000000000}</Data><Data Name='TransmittedServices'>-</Data><Data Name='LmPackageName'>-</Data><Data Name='KeyLength'>0</Data><Data Name='ProcessId'>0x2c0</Data><Data Name='ProcessName'>C:\\Windows\\System32\\services.exe</Data><Data Name='IpAddress'>-</Data><Data Name='IpPort'>-</Data><Data Name='ImpersonationLevel'>%%1833</Data><Data Name='RestrictedAdminMode'>-</Data><Data Name='TargetOutboundUserName'>-</Data><Data Name='TargetOutboundDomainName'>-</Data><Data Name='VirtualAccount'>%%1843</Data><Data Name='TargetLinkedLogonId'>0x0</Data><Data 
Name='ElevatedToken'>%%1842</Data></EventData></Event>",                                                                                                                       
        "origin": "EventChannel",                                                                                                                                                                                         
        "registered_ip": "any",                                                                              
        "decoders": [                                                                                                                                                                                                                                     
            "core-wazuh-message",                                                                                                                                                                                                                                                                                                                                                                                                                    
            "core-windows",                                                                                                                                                                                                                                                                                                                                                                                                                          
            "integrations",                                                                                                                                                                                                                                                                                                                                                                                                                          
            "windows-event-decoder",                                                                                                                                                                                                                                                                                                                                                                                                                 
            "windows-security"                                                                                                                   
        ],                                                    
        "source": "logcollector"                                                                                                                                                                                                                                                                   
    },                                                                                                       
    "agent": {                                                          
        "id": "115",                                                    
        "name": "commandline-test",                                     
        "type": "wazuh"                                                                                                                                                        
    },                                                                                                       
    "event": {                                                                                                                                                                                                                                                                                                                                                
        "original": "<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4624</EventID><Version>2</Version><Level>0</Level><Task>12544</Task><Opcode>0</Opcode><Keywords>0x8020000000000000</Keywords><TimeCreated SystemTime='2023-07-11T17:14:07.5120744Z'/><EventRecordID>7733</EventRecordID><Correlation ActivityID='{58616339-b3b9-0001-a163-6158b9b3d901}'/><Execution ProcessID='732' ThreadID='3976'/><Channel>Security</Channel><Computer>DESKTOP-2GJHQ
1J</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>S-1-5-18</Data><Data Name='SubjectUserName'>DESKTOP-2GJHQ1J$</Data><Data Name='SubjectDomainName'>WORKGROUP</Data><Data Name='SubjectLogonId'>0x3e7</Data><Data Name='TargetUserSid'>S-1-5-18</Data><Data Name='TargetUserName'>SYSTEM</Data><Data Name='TargetDomainName'>NT AUTHORITY</Data><Data Name='TargetLogonId'>0x3e7</Data><Data Name='LogonType'>5</Data><Data Name='LogonProcessName'>Advapi  </Data><Data Name='AuthenticationPackageName'>Negotiate</Data><Data Name='WorkstationName'>-</Data><Data Name='LogonG
uid'>{00000000-0000-0000-0000-000000000000}</Data><Data Name='TransmittedServices'>-</Data><Data Name='LmPackageName'>-</Data><Data Name='KeyLength'>0</Data><Data Name='ProcessId'>0x2c0</Data><Data Name='ProcessName'>C:\\Windows\\System32\\services.exe</Data><Data Name='IpAddress'>-</Data><Data Name='IpPort'>-</Data><Data Name='ImpersonationLevel'>%%1833</Data><Data Name='RestrictedAdminMode'>-</Data><Data Name='TargetOutboundUserName'>-</Data><Data Name='TargetOutboundDomainName'>-</Data><Data Name='VirtualAccount'>%%1843</Data><Data Name='TargetLinkedLogonId'>0x0</Data><Data
 Name='ElevatedToken'>%%1842</Data></EventData></Event>",                                                                                                                                                                                                                                                                                                     
        "module": "windows",                                                           
        "dataset": "security",                                                                                                                   
        "start": "2023-07-11T17:14:07.5120744Z",                                                                                                 
        "code": "4624",                                                                                      
        "id": "4624",                                                                  
        "kind": "event",                                                                                                                                                                                                  
        "provider": "Microsoft-Windows-Security-Auditing",                                                   
        "category": [                                                                                        
            "authentication"                                                                                 
        ],                                                                                                   
        "type": [                                                                                            
            "start"                                                                                                                              
        ],                                                                                                                                                                                                                                                                                         
        "action": "logged-in"                                                                                                                    
    },                                                                                                                                           
    "ecs": {                                                                                                                                     
        "version": "8.8"                                                                                                                         
    },                                                                                                                                           
    "host": {                                                                                                                                    
        "id": "115",                                                                                                                             
        "name": "DESKTOP-2GJHQ1J"                                                                                                                
    },                                                                                                                                           
    "log": {                                                                                                                                     
        "level": "Audit"                                                                                                                         
    },                                                                                                                                           
    "user": {                                                                                                                                    
        "id": "S-1-5-18",                                                                                                                        
        "target": {                                                                                                                              
            "id": "S-1-5-18",                                                                                                                    
            "name": "SYSTEM",                                                                                                                    
            "domain": "NT AUTHORITY"                                                                                                             
        },                                                                                                                                       
        "name": "SYSTEM",                                                                                                                        
        "domain": "NT AUTHORITY"                                                                                                                 
    },                                                                                                                                           
    "related": {                                                                                                                                 
        "user": [                                                                                                                                
            "SYSTEM",                                                                                                                            
            "DESKTOP-2GJHQ1J$"                                                                                                                   
        ]                                                                                                                                        
    },                                                                                                                                           
    "process": {                                                                                                                                 
        "pid": 704,                                                                                                                              
        "executable": "C:\\Windows\\System32\\services.exe",                                                                                     
        "name": "services.exe"                                                                                                                   
    }                                                                                                                                            
}                                                                                                                                                
``` 

</p>
</details> 

### Real Windows event
 
Windows EventChannel event showed on the `Event Viewer` tool:
![image](https://github.com/wazuh/wazuh/assets/93778492/353b3e85-1553-4a97-8dca-8a599756e2ec)

<details><summary>JSON message generated (geted from Dashboard)</summary>
<p>

```json
{
  "_index": "wazuh-alerts-5.x-2023.07.11",
  "_id": "WNEIRokBRHEmjzDvjMGq",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2023-07-11T17:38:31.740Z",
    "related": {
      "user": [
        "SYSTEM"
      ]
    },
    "agent": {
      "type": "wazuh",
      "hostname": "engine",
      "ephemeral_id": "09e19294-5ace-4684-9408-d4c6f169bd4b",
      "version": "7.10.2",
      "id": "004",
      "name": "DESKTOP-2GJHQ1J"
    },
    "ecs": {
      "version": "8.8"
    },
    "wazuh": {
      "message": "<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4672</EventID><Version>0</Version><Level>0</Level><Task>12548</Task><Opcode>0</Opcode><Keywords>0x8020000000000000</Keywords><TimeCreated SystemTime='2023-07-11T21:38:28.0642070Z'/><EventRecordID>7821</EventRecordID><Correlation ActivityID='{58616339-b3b9-0001-a163-6158b9b3d901}'/><Execution ProcessID='732' ThreadID='3092'/><Channel>Security</Channel><Computer>DESKTOP-2GJHQ1J</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>S-1-5-18</Data><Data Name='SubjectUserName'>SYSTEM</Data><Data Name='SubjectDomainName'>NT AUTHORITY</Data><Data Name='SubjectLogonId'>0x3e7</Data><Data Name='PrivilegeList'>SeAssignPrimaryTokenPrivilege     SeTcbPrivilege     SeSecurityPrivilege     SeTakeOwnershipPrivilege     SeLoadDriverPrivilege     SeBackupPrivilege     SeRestorePrivilege     SeDebugPrivilege     SeAuditPrivilege     SeSystemEnvironmentPrivilege     SeImpersonatePrivilege     SeDelegateSessionUserImpersonatePrivilege</Data></EventData></Event>",
      "origin": "EventChannel",
      "registered_ip": "any",
      "decoders": [
        "core-wazuh-message",
        "core-windows",
        "integrations",
        "windows-event-decoder",
        "windows-security"
      ],
      "source": "logcollector",
      "queue": 102,
      "location": "[004] (DESKTOP-2GJHQ1J) any->EventChannel"
    },
    "event": {
      "type": [
        "admin"
      ],
      "action": "logged-in-special",
      "start": "2023-07-11T21:38:28.0642070Z",
      "code": "4672",
      "kind": "event",
      "original": "<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4672</EventID><Version>0</Version><Level>0</Level><Task>12548</Task><Opcode>0</Opcode><Keywords>0x8020000000000000</Keywords><TimeCreated SystemTime='2023-07-11T21:38:28.0642070Z'/><EventRecordID>7821</EventRecordID><Correlation ActivityID='{58616339-b3b9-0001-a163-6158b9b3d901}'/><Execution ProcessID='732' ThreadID='3092'/><Channel>Security</Channel><Computer>DESKTOP-2GJHQ1J</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>S-1-5-18</Data><Data Name='SubjectUserName'>SYSTEM</Data><Data Name='SubjectDomainName'>NT AUTHORITY</Data><Data Name='SubjectLogonId'>0x3e7</Data><Data Name='PrivilegeList'>SeAssignPrimaryTokenPrivilege     SeTcbPrivilege     SeSecurityPrivilege     SeTakeOwnershipPrivilege     SeLoadDriverPrivilege     SeBackupPrivilege     SeRestorePrivilege     SeDebugPrivilege     SeAuditPrivilege     SeSystemEnvironmentPrivilege     SeImpersonatePrivilege     SeDelegateSessionUserImpersonatePrivilege</Data></EventData></Event>",
      "dataset": "security",
      "provider": "Microsoft-Windows-Security-Auditing",
      "module": "windows",
      "id": "4672",
      "category": [
        "iam"
      ]
    },
    "log": {
      "offset": 92887352,
      "file": {
        "path": "/var/ossec/logs/alerts/alerts-ECS.json"
      },
      "level": "Audit"
    },
    "host": {
      "hostname": "DESKTOP-2GJHQ1J",
      "name": "DESKTOP-2GJHQ1J",
      "os": {
        "name": "Microsoft Windows 10 Home",
        "version": "10.0.19045.3086",
        "type": "windows"
      },
      "mac": [
        "00:00:00:00:00:00",
        "1a:c9:b9:20:91:32:",
        "00:00:00:00:00:00:00:e0:",
        "1e:f1:ca:57:55:9c:"
      ],
      "ip": [
        "fe80::5efe:192.168.100.47",
        "fddb:338b:276a:0:6098:1064:9aa:eff0",
        "::1",
        "fddb:338b:276a:0:d013:f929:7c05:637c",
        "2803:9800:a036:8158:6098:1064:9aa:eff0",
        "192.168.100.47",
        "127.0.0.1",
        "2803:9800:a036:8158:d013:f929:7c05:637c",
        "fe80::d013:f929:7c05:637c",
        "2803:9800:a036:8158::a",
        "fe80::30e:77c3:6335:162",
        "2803:9800:a036:8158:a2d6:faf7:20ab:cfa2",
        "fddb:338b:276a:0:326:a5f4:ed8c:b844",
        "192.168.100.170",
        "fddb:338b:276a:0:a1b8:18e2:9f98:28a0",
        "2803:9800:a036:8158:a1b8:18e2:9f98:28a0"
      ],
      "id": "004",
      "architecture": "i686"
    },
    "user": {
      "id": "S-1-5-18",
      "name": "SYSTEM",
      "domain": "NT AUTHORITY"
    },
    "input": {
      "type": "log"
    }
  },
  "fields": {
    "event.start": [
      "2023-07-11T21:38:28.064Z"
    ],
    "@timestamp": [
      "2023-07-11T17:38:31.740Z"
    ]
  },
  "sort": [
    1689097111740
  ]
}

``` 

</p>
</details> 

## Tests
- Compilation without warnings in every supported platform
  - [X] Linux
  - [X] Windows
  - [ ] MAC OS X
- [X] Source installation
- [X] Package installation
- [X] Source upgrade
- [X] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

### CODE REVIEW

**Comment by LucioDonda** [comment]
In order for the full integration to work with this changes it's mandatory to update its manifest, resulting in:
```
name: integration/windows/0
decoders:
- decoder/windows-event-decoder/0
- decoder/windows-security/0
- decoder/windows-sysmon/0
- decoder/windows-powershell-operational/0
- decoder/windows-powershell/0
```
And also to delete the decoder `decoder/windows-json/0`

**Comment by tdrauncieal** [comment]
> In order for the full integration to work with this changes it's mandatory to update its manifest, resulting in:
> 
> ```
> name: integration/windows/0
> decoders:
> - decoder/windows-event-decoder/0
> - decoder/windows-security/0
> - decoder/windows-sysmon/0
> - decoder/windows-powershell-operational/0
> - decoder/windows-powershell/0
> ```
> 
> And also to delete the decoder `decoder/windows-json/0`

Fixed!
I was leave this JSON decoder thinking about of retro-compatibility.

**Comment by sempervictus** [comment]
Does this mean that we can custom-decode/process Windows events again like we could w/ OSSEC?

**Review by JcabreraC — APPROVED** [review]
LGTM !

The test:
```
The following tests FAILED:
	394 - ParameterEvaluation/GraphGetCommand.ParameterEvaluation/("{\"policy\":\"policy/wazuh/0\",\"type\": \"expressions\"}", "{\"status\":\"OK\",\n        \"content\":\"strict digraph G {\\n\\n    compound=true;\\n    fontname=\\\"Helvetica,Arial,sans-serif\\\";\\n    fontsize=12;\\n    node [color=\\\"#57abff\\... (Failed)
```
has been fixed in the PR #17232

**Review by JavierBejMen — APPROVED** [review]
LGTM

**Pull request merged**
