### PR TITLE
Moving ruleset testing project to the new ruleset location in the wazuh repository

### PR DESCRIPTION
**Pull request by DProvinciani**
|Related issue|
|---|
| #6914 |

## Description

This PR includes all the necessary changes to migrate the Wazuh ruleset testing project to the new folder that contains all the ruleset related files in the `wazuh` repository.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation
- [x] Package installation

### CODE REVIEW

**Review by palaciosjeremias — COMMENTED** [review]
Shouldn't we update references to contrib/ossec-testing too?
- **wazuh-logtest.py** and **testrule.c** refer to this folder in help messages.
- **src/Makefile** has an option **test-rules** to step at **/contrib/ossec-testing** and execute **runtest.py**. It seems to be obsolete, but we can update it now and conserve it for future use.

**Comment by DProvinciani** [comment]
Good catch @palaciosjeremias! Fixed! 

> Shouldn't we update references to contrib/ossec-testing too?
> 
> * **wazuh-logtest.py** and **testrule.c** refer to this folder in help messages.
> * **src/Makefile** has an option **test-rules** to step at **/contrib/ossec-testing** and execute **runtest.py**. It seems to be obsolete, but we can update it now and conserve it for future use.

**Review by pereyra-m — APPROVED** [review]
LGTM!

**Review by palaciosjeremias — APPROVED** [review]
LGTM!

**Review by vicferpoy — APPROVED** [review]
LGTM!

**Pull request merged**
