### PR TITLE
Small CIS changes that works on a recent set of AL2 instances

### PR DESCRIPTION
**Pull request by dj-wasabi**
|Related issue|
|---|
||

## Description

Have access to a large amount of recent Amazon Linux 2 instances and some checks where either invalid (command not found), invalid casings/typos and text related inconsistencies.

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

### CODE REVIEW

**Comment by dj-wasabi** [comment]
I don't know what to specify in tests and other parts, can someone help me with this?

**Comment by Dwordcito** [comment]
Hello team it seems that a user found problems in AL2! Let's take a look at their contribution!

@72nomada

**Comment by 72nomada** [comment]
There are some other changes to AL2 SCA Policy, we will review this and will decide to merge for 4.4.1 or wait to AL2 rework. Thanks, @dj-wasabi.

**Comment by dj-wasabi** [comment]
> 

Thank you!

**Comment by 72nomada** [comment]
Issue for this PR - https://github.com/wazuh/wazuh/issues/16946

**Pull request closed without merging**
