### PR TITLE
Added Engine metrics interface

### PR DESCRIPTION
**Pull request by JavierBejMen**
|Related issue|
|---|
|#25577|

Added Metrics interfaces:
- IMetric interface for individual instruments.
- IManager singleton interface for managing and accessing metrics.

### CODE REVIEW

**Review by juliancnn — APPROVED** [review]
LGTM!

**Review by NahuFigueroa97 — DISMISSED** [review]
LGTM!

**Comment by JcabreraC** [comment]
To get the PR approved, all checks must be successfully passed. A rebase with master is required for this to happen.

**Comment by JcabreraC** [comment]
Need fix: **Engine Coverage check / Engine Coverage check (pull_request)**

**Review by JcabreraC — CHANGES_REQUESTED** [review]
Need fix: **Engine Coverage check / Engine Coverage check (pull_request)**

**Review by JcabreraC — APPROVED** [review]
LGTM !

**Review by NahuFigueroa97 — APPROVED** [review]
LGTM!

**Pull request merged**
