### PR TITLE
Refactor symbolic links code and save resolved path only when follow is enabled

### LINKED ISSUE #6320: Bug reading FIM configuration using follow symbolic links.
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13 | FIM | Agent | Any | Any |

We have found an error that caused that after the first check of the status of the monitored symbolic links the entries corresponding to the directories `/usr/bin` and `/usr/sbin` were eliminated, content that should remain in DB since it was explicitly monitored with the directories `/usr/bin` and `/usr/sbin`, because of a bad reading of the configuration of the links `/bin` and `/sbin` in the default configuration:

```xml
    <!-- Directories to check  (perform all possible verifications) -->
    <directories>/etc,/usr/bin,/usr/sbin</directories>
    <directories>/bin,/sbin,/boot</directories>
```

With:
- `/bin -> /usr/bin`
- `/sbin -> /usr/sbin`

### PR DESCRIPTION
**Pull request by jesusjimsa**
| Related issue |
| ------------- |
| #6320         |

## Description

This pull request does a refactor of all the code involkved in symbolic links in FIM. Previously, FIM would store the link path in `syscheck.symbolic_links` and the resolved path in `syscheck.dir`, this modified what the user had configured. Now, all the configured paths are stored only in `syscheck.dir` and the resolved paths, if any, are stored in `syscheck.symbolic_links`.

Another fix, helped by the refactor, prevents from storing resolved paths if `follow_symbolic_link` is disabled, therefore fixing the original problem described in #6320.

This pull request closes #6320.

## Logs/Alerts example

This message has changed:

```
INFO: (6034): Updating the symbolic link from '/nono': '/linko' to '/otra'.
```

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [x] MAC OS X
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [x] Package upgrade
- [x] Review logs syntax and correct language
- [x] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)
- Memory tests for Windows
  - [x] Scan-build report

- [x] Retrocompatibility with older Wazuh versions

### CODE REVIEW

**Comment by jesusjimsa** [comment]
## Linux scan-build
```
scan-build: Removing directory '/tmp/scan-build-2020-11-16-145324-30021-1' because it contains no reports.
scan-build: No bugs found.
```

**Comment by jesusjimsa** [comment]
## Linux valgrind
```
==3624== HEAP SUMMARY:
==3624==     in use at exit: 282,023 bytes in 397 blocks
==3624==   total heap usage: 10,671 allocs, 10,274 frees, 4,522,712 bytes allocated
==3624==
==3624== 26 bytes in 3 blocks are definitely lost in loss record 32 of 123
==3624==    at 0x4C29F73: malloc (vg_replace_malloc.c:309)
==3624==    by 0x6090AF9: strdup (in /usr/lib64/libc-2.17.so)
==3624==    by 0x40A723: fim_scan (create_db.c:81)
==3624==    by 0x40E98B: start_daemon (run_check.c:190)
==3624==    by 0x41422A: main (main.c:279)
==3624==
==3624== 26 bytes in 3 blocks are definitely lost in loss record 33 of 123
==3624==    at 0x4C29F73: malloc (vg_replace_malloc.c:309)
==3624==    by 0x6090AF9: strdup (in /usr/lib64/libc-2.17.so)
==3624==    by 0x40A979: fim_scan (create_db.c:117)
==3624==    by 0x40E98B: start_daemon (run_check.c:190)
==3624==    by 0x41422A: main (main.c:279)
==3624==
==3624== 560 bytes in 1 blocks are possibly lost in loss record 103 of 123
==3624==    at 0x4C2C089: calloc (vg_replace_malloc.c:762)
==3624==    by 0x4012784: _dl_allocate_tls (in /usr/lib64/ld-2.17.so)
==3624==    by 0x5DF087B: pthread_create@@GLIBC_2.2.5 (in /usr/lib64/libpthread-2.17.so)
==3624==    by 0x4BE9EB: CreateThreadJoinable (pthreads_op.c:47)
==3624==    by 0x4BEA66: CreateThread (pthreads_op.c:62)
==3624==    by 0x413BDB: main (main.c:166)
==3624==
==3624== 560 bytes in 1 blocks are possibly lost in loss record 104 of 123
==3624==    at 0x4C2C089: calloc (vg_replace_malloc.c:762)
==3624==    by 0x4012784: _dl_allocate_tls (in /usr/lib64/ld-2.17.so)
==3624==    by 0x5DF087B: pthread_create@@GLIBC_2.2.5 (in /usr/lib64/libpthread-2.17.so)
==3624==    by 0x4BE9EB: CreateThreadJoinable (pthreads_op.c:47)
==3624==    by 0x4BEA66: CreateThread (pthreads_op.c:62)
==3624==    by 0x40E863: start_daemon (run_check.c:160)
==3624==    by 0x41422A: main (main.c:279)
==3624==
==3624== 560 bytes in 1 blocks are possibly lost in loss record 105 of 123
==3624==    at 0x4C2C089: calloc (vg_replace_malloc.c:762)
==3624==    by 0x4012784: _dl_allocate_tls (in /usr/lib64/ld-2.17.so)
==3624==    by 0x5DF087B: pthread_create@@GLIBC_2.2.5 (in /usr/lib64/libpthread-2.17.so)
==3624==    by 0x4BE9EB: CreateThreadJoinable (pthreads_op.c:47)
==3624==    by 0x4BEA66: CreateThread (pthreads_op.c:62)
==3624==    by 0x40E99A: start_daemon (run_check.c:193)
==3624==    by 0x41422A: main (main.c:279)
==3624==
==3624== 560 bytes in 1 blocks are possibly lost in loss record 106 of 123
==3624==    at 0x4C2C089: calloc (vg_replace_malloc.c:762)
==3624==    by 0x4012784: _dl_allocate_tls (in /usr/lib64/ld-2.17.so)
==3624==    by 0x5DF087B: pthread_create@@GLIBC_2.2.5 (in /usr/lib64/libpthread-2.17.so)
==3624==    by 0x4BE9EB: CreateThreadJoinable (pthreads_op.c:47)
==3624==    by 0x4BEA66: CreateThread (pthreads_op.c:62)
==3624==    by 0x40EA0A: start_daemon (run_check.c:201)
==3624==    by 0x41422A: main (main.c:279)
==3624==
==3624== 4,104 bytes in 1 blocks are possibly lost in loss record 118 of 123
==3624==    at 0x4C29F73: malloc (vg_replace_malloc.c:309)
==3624==    by 0x555B370: sqlite3MemMalloc (sqlite3.c:20790)
==3624==    by 0x555BCEE: mallocWithAlarm (sqlite3.c:24464)
==3624==    by 0x555BD85: sqlite3Malloc (sqlite3.c:24494)
==3624==    by 0x5569106: pcache1Alloc (sqlite3.c:45336)
==3624==    by 0x55693EB: sqlite3PageMalloc (sqlite3.c:45479)
==3624==    by 0x5578D7A: allocateTempSpace (sqlite3.c:61560)
==3624==    by 0x557AFFF: btreeCursor (sqlite3.c:63234)
==3624==    by 0x557B171: sqlite3BtreeCursor (sqlite3.c:63276)
==3624==    by 0x55956B7: sqlite3VdbeExec (sqlite3.c:81807)
==3624==    by 0x558EC1F: sqlite3Step (sqlite3.c:76693)
==3624==    by 0x558EDCA: sqlite3_step (sqlite3.c:76754)
==3624==    by 0x41CC99: fim_db_insert_data (fim_db.c:828)
==3624==    by 0x41D074: fim_db_insert (fim_db.c:923)
==3624==    by 0x40B5F1: fim_file (create_db.c:392)
==3624==    by 0x40B10B: fim_checker (create_db.c:284)
==3624==    by 0x40B3A6: fim_directory (create_db.c:348)
==3624==    by 0x40B1D8: fim_checker (create_db.c:299)
==3624==    by 0x40A787: fim_scan (create_db.c:83)
==3624==    by 0x40E98B: start_daemon (run_check.c:190)
==3624==
==3624== LEAK SUMMARY:
==3624==    definitely lost: 52 bytes in 6 blocks
==3624==    indirectly lost: 0 bytes in 0 blocks
==3624==      possibly lost: 6,344 bytes in 5 blocks
==3624==    still reachable: 275,627 bytes in 386 blocks
==3624==                       of which reachable via heuristic:
==3624==                         length64           : 272,048 bytes in 335 blocks
==3624==         suppressed: 0 bytes in 0 blocks
==3624== Reachable blocks (those to which a pointer was found) are not shown.
==3624== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==3624==
==3624== For lists of detected and suppressed errors, rerun with: -s
==3624== ERROR SUMMARY: 7 errors from 7 contexts (suppressed: 0 from 0)
```

**Comment by jesusjimsa** [comment]
helpspot@readdle.com

**Comment by jesusjimsa** [comment]
1a20f24 fixes the memory leak described in the previous comment.

**Comment by jesusjimsa** [comment]
## Windows scan-build
There is one bug found by scan-build, but it is in _start_agent.c_.
[scan-build-windows.zip](https://github.com/wazuh/wazuh/files/5559835/scan-build-windows.zip)

**Review by Molter73 — APPROVED** [review]
LGTM!

**Review by vikman90 — APPROVED** [review]

**Pull request merged**
