### PR TITLE
Add error message to agent-auth -i

### PR DESCRIPTION
**Pull request by jctello**
Using agent-auth -i with arguments make no sense and allowing its use may cause confusion to those trying to use the -I modifier.

### CODE REVIEW

**Comment by vikman90** [comment]
Hi @jctello,

According to the documentation:
```
  agent-auth: -[Vhdti] [-g group] [-D dir] [-m IP address] [-p port] [-A name] [-c ciphers] [-v path] [-x path] [-k path] [-P pass] [-G group] [-I IP address]
    -V          Version and license message
    -h          This help message
    -d          Execute in debug mode. This parameter
                can be specified multiple times
                to increase the debug level.
    -t          Test configuration
    -g <group>  Group to run as (default: ossec)
    -D <dir>    Directory to chroot into (default: /var/ossec)
    -m <addr>   Manager IP address
    -p <port>   Manager port (default: 1515)
    -A <name>   Agent name (default: hostname)
    -c          SSL cipher list (default: HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH)
    -v <path>   Full path to CA certificate used to verify the server
    -x <path>   Full path to agent certificate
    -k <path>   Full path to agent key
    -P <pass>   Authorization password
    -a          Auto select SSL/TLS method. Default: TLS v1.2 only.
    -G <group>  Set the group for centralized configuration
    -I <IP>     Set the agent IP address
    -i          Let the agent IP address be set by the manager connection
```

`-i` has no argument: it overwrites the manager's option _use_source_ip_ to `yes`, but lets the manager decide that IP.

On the other hand, `-I` allows the user to define the registration IP.

Cheers.

**Comment by vikman90** [comment]
Apologies, I did not explain good enough.

This line (https://github.com/wazuh/wazuh/pull/2489/files#diff-db04618c39ff9afee0cecd3b6ad7a46cR109)
```c
getopt(argc, argv, "VdhtG:m:p:A:c:v:x:k:D:P:a:I:i");
```

Selects the set of options. A colon (`:`) after any letter means that this option takes an argument.

`-i` has no trailing colon, so the option parser will never try to get a parameter.

In fact, if we run (on your branch):
```shellsession
$ ./agent-auth -i 192.168.33.1
2019/02/04 23:55:08 agent-auth: INFO: Started (pid: 5140).
```

The error "-i takes no argument" does not appear. After the last valid token, the option parser takes the rest of parameter as input parameters, like putting `--`.

So `getoptarg()` will not detect that `-i` has a parameter, it will simply continue parsing after `-i`. These two calls are equivalent:
```shellsession
$ ./agent-auth -m 1.2.3.4 -i a b c
$ ./agent-auth -m 1.2.3.4 a b c
```

`a b c` is simply discarded.

**Comment by jctello** [comment]
Oh, I see. 
Thank you very much for the explanation. I see it would make little sense to change that behaviour to add an error message.

**Comment by vikman90** [comment]
@jctello If you want to achieve so I recommend you this change instead, after the `getopt()` loop:

```diff
diff --git a/src/os_auth/main-client.c b/src/os_auth/main-client.c
index add33f6..dbdfca9 100644
--- a/src/os_auth/main-client.c
+++ b/src/os_auth/main-client.c
@@ -214,6 +214,10 @@ int main(int argc, char **argv)
         }
     }

+    if (optind < argc) {
+        mwarn("Extra arguments detected. They will be ignored.");
+    }
+
     if (debug_level == 0) {
         /* Get debug level */
         debug_level = getDefine_Int("authd", "debug", 0, 2);
```

## Example
```shellsession
$ ./agent-auth -m 192.168.1.1 -i 192.168.1.2
2019/02/05 07:00:08 agent-auth: WARNING: Extra arguments detected. They will be ignored.
2019/02/05 07:00:08 agent-auth: INFO: Started (pid: 7252).
```

Feel free to reopen this PR and make this change.

Best.

**Comment by jctello** [comment]
Great, this makes sense!

Thanks again Vik

**Pull request merged**
