### PR TITLE
Some issues solved in FIM

### PR DESCRIPTION
**Pull request by bah07**
|Related issue|
|---|
| [#5017](https://github.com/wazuh/wazuh/issues/5017), #5118, #5132 |
## Description

This PR includes some fixes solves in: 
- Fix segmentation fault in function RTCallBack [#5115](https://github.com/wazuh/wazuh/pull/5115)
- Change file open on OS_MD5_SHA1_SHA256_File function to non-blocking [#5018](https://github.com/wazuh/wazuh/pull/5018)

On the other hand, it also includes a fix that solves the compilation of unit tests in Windows systems described in #5137 

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [x] MAC OS X
- [x] Source installation
- [x] Package installation
- [x] Review logs syntax and correct language
- [x] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)
- Memory tests for Windows
  - [x] Scan-build report
  - [x] Coverity

- [x] Added unit tests (for new features)

### CODE REVIEW

**Comment by grg121** [comment]
@wazuhci run integration fim fim-non-scheduled ubuntu,centos agent_test 0

**Comment by wazuhci** [comment]
Check out integration results at [Jenkins-B220](https://jenkins-production.wazuh.info/job/test_integration/220/)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** b681644850bc4de84a9a30b8b775e16428015ac1
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2441/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2441/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2441/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2441.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2441/Analysis_dynamic_valgrind-v3.13.0-B2441.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** b681644850bc4de84a9a30b8b775e16428015ac1
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2442/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2442/ossec.log)
**Coverage:** 

```json
Lines executed:26.89% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2442/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2442.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2442/Analysis_dynamic_valgrind-v3.13.0-B2442.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** b681644850bc4de84a9a30b8b775e16428015ac1
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2445/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2445/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2445/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2445.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2445/Analysis_dynamic_valgrind-v3.13.0-B2445.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** b681644850bc4de84a9a30b8b775e16428015ac1
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2446/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2446/ossec.log)
**Coverage:** 

```json
Lines executed:26.92% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2446/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2446.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2446/Analysis_dynamic_valgrind-v3.13.0-B2446.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** b5fdb35981c99e7e9cdf8aef3eda34ba368f1333
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2451/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2451/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2451/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2451.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2451/Analysis_dynamic_valgrind-v3.13.0-B2451.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** b5fdb35981c99e7e9cdf8aef3eda34ba368f1333
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2452/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2452/ossec.log)
**Coverage:** 

```json
Lines executed:26.92% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2452/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2452.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2452/Analysis_dynamic_valgrind-v3.13.0-B2452.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** b5fdb35981c99e7e9cdf8aef3eda34ba368f1333
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2455/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2455/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2455/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2455.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2455/Analysis_dynamic_valgrind-v3.13.0-B2455.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** b5fdb35981c99e7e9cdf8aef3eda34ba368f1333
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2456/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2456/ossec.log)
**Coverage:** 

```json
Lines executed:26.92% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2456/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2456.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2456/Analysis_dynamic_valgrind-v3.13.0-B2456.log)

**Comment by bah07** [comment]
Server unit test:
```
100% tests passed, 0 tests failed out of 41
Total Test time (real) =   0.65 sec
```

Agent unit test:
```

100% tests passed, 0 tests failed out of 18
Total Test time (real) =   0.16 sec
```

Windows agent unit test:
```
100% tests passed, 0 tests failed out of 20
Total Test time (real) =   93.14 sec
```

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 0f609caa312e64b0a1ae76617dab388ccb0c9dc3
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2485/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2485/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2485/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2485.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2485/Analysis_dynamic_valgrind-v3.13.0-B2485.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 0f609caa312e64b0a1ae76617dab388ccb0c9dc3
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2486/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2486/ossec.log)
**Coverage:** 

```json
Lines executed:26.92% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2486/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2486.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2486/Analysis_dynamic_valgrind-v3.13.0-B2486.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 82d3d0259bfcfb547469d6d85efc86382bca1982
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2491/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2491/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2491/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2491.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2491/Analysis_dynamic_valgrind-v3.13.0-B2491.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 82d3d0259bfcfb547469d6d85efc86382bca1982
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2492/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2492/ossec.log)
**Coverage:** 

```json
Lines executed:26.89% of 3195

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2492/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B2492.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B2492/Analysis_dynamic_valgrind-v3.13.0-B2492.log)

**Pull request merged**
