### PR TITLE
Issue 11737 share download group deprecation

### PR DESCRIPTION
**Pull request by san1526**
|Related issue|
|---|
| #11737  |

## Description

Deprecating the ability to set agents groups from the shared_download 'files.yml' that was originally intended only to configure shared-configuration file downloads.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation

- Memory tests for Linux
  - [x] Scan-build report

### CODE REVIEW

**Comment by palaciosjeremias** [comment]
### Test results:
After the removal of group_source logic, the WDB_tester script was adapted and re-executed with successful result:
[WDB_tester.zip](https://github.com/wazuh/wazuh/files/7828650/WDB_tester.zip)

**Comment by san1526** [comment]
image

**Comment by san1526** [comment]
Trying to set an agent group by using the 'shared configuration' `files.yml` : 
image

now gives this error

> 2022/01/10 14:32:56 wazuh-remoted: INFO: File 'etc/shared/files.yml' changed. Reloading data
> 2022/01/10 14:32:56 wazuh-remoted: ERROR: Parsing file 'etc/shared/files.yml': unexpected identifier: 'agents' on line 6
> 2022/01/10 14:32:56 wazuh-remoted: ERROR: Parsing error on line 7: unexpected token

And the group for that agent after the keepalive is sent and the config was read is still in default
image

**Comment by san1526** [comment]
image

**Review by DProvinciani — APPROVED** [review]
Looks good!

**Pull request merged**
