### PR TITLE
Remove "Valid Accounts" Mitre technique from 5710

### PR DESCRIPTION
**Pull request by branchnetconsulting**
Rule 5710 is strictly focused on ssh login attempts using a non-existent account.  That does not sound like a "Valid Accounts" technique to me (T1078).  See: https://attack.mitre.org/techniques/T1078/
I recommend removing this Mitre mapping from 5710.

### CODE REVIEW

**Review by fabamatic — APPROVED** [review]

**Comment by branchnetconsulting** [comment]
I originally proposed the removal of the wrong Mitre mapping from rule 5710, and have now corrected it in this PR.  Please remove 
`<id>T1078</id>`
from rule 5710 which corresponds to the inapplicable "Valid Accounts" mapping.

**Review by fabamatic — APPROVED** [review]
LGTM

**Comment by branchnetconsulting** [comment]
Please review and commit this.  It really makes Wazuh's Mitre mapping look bad in this state.

**Review by ooniagbi — APPROVED** [review]
LGTM.

**Comment by ooniagbi** [comment]
Changes will be merged in 4.5.3

**Pull request closed without merging**
