### PR TITLE
Improve `DELETE /agents` performance

### LINKED ISSUE #8853: Improve DELETE /agents API request
## Environment settings
- Agents: 10000
- Workers: 5

## Description

Hi team,

According to the following comment https://github.com/wazuh/wazuh/issues/8325#issuecomment-850283199, the `DELETE /agents` endpoint suffers some scalability problems. This issue aims to optimize this endpoint as much as possible.

api.log:
```
2021/05/27 10:48:00 ERROR: Timeout executing API request
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 253, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 255, in execute_local_request
    raise exception.WazuhInternalError(3021)
wazuh.core.exception.WazuhInternalError: Error 3021 - Timeout executing API request
2021/05/27 10:48:00 INFO: wazuh 172.31.0.228 "DELETE /agents" with parameters {"agents_list": "all", "status": "all", "older_than": "0s"} and body {} done in 10.042s: 500
2021/05/27 10:48:10 ERROR: Timeout executing API request
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError
```

Response:

```
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "master": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 3021
}
```

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

### PR DESCRIPTION
**Pull request by vicferpoy**
|Related issue|
|---|
| closes #8853 |

## Description

Hello team,

This PR improves the performance of the `DELETE /agents` endpoint, allowing around 50k agent deletes without triggering the API timeout. As I pointed out in the issue, this would require a development at a lower level to allow passing list of agents to `authd`.

image

In addition, a temporary cache decorator was added to the framework. This could probably be applied to some critical code sections to improve performance, but it is not part of this issue. 

### Unit tests 
```
============================ 1590 passed, 14 warnings in 298.20s (0:04:58) =============================
(unittest-env) vicferpoy:~/Desktop/Git/wazuh/framework/wazuh (feature/8853-improve-delete-agents)$ 
(unittest-env) vicferpoy:~/Desktop/Git/wazuh/framework/wazuh (feature/8853-improve-delete-agents)$ python3 -m pytest . --disable-warnings
========================================= test session starts ==========================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/vicferpoy/Desktop/Git/wazuh/framework
plugins: cov-2.12.0, asyncio-0.15.1
collected 1590 items                                                                                   

core/cluster/dapi/tests/test_dapi.py .......................                                     [  1%]
core/cluster/tests/test_cluster.py ...................                                           [  2%]
core/cluster/tests/test_common.py .......                                                        [  3%]
core/cluster/tests/test_control.py .....                                                         [  3%]
core/cluster/tests/test_local_client.py .                                                        [  3%]
core/cluster/tests/test_utils.py .......                                                         [  3%]
core/cluster/tests/test_worker.py .................                                              [  4%]
core/tests/test_active_response.py ..............                                                [  5%]
core/tests/test_agent.py ....................................................................... [ 10%]
................................................................................................ [ 16%]
......                                                                                           [ 16%]
core/tests/test_cdb_list.py ......................................                               [ 19%]
core/tests/test_common.py .......                                                                [ 19%]
core/tests/test_configuration.py ....................................                            [ 21%]
core/tests/test_decoder.py ................                                                      [ 22%]
core/tests/test_input_validator.py ...                                                           [ 23%]
core/tests/test_logtest.py ..                                                                    [ 23%]
core/tests/test_manager.py ...............                                                       [ 24%]
core/tests/test_mitre.py .............                                                           [ 24%]
core/tests/test_pyDaemonModule.py ......                                                         [ 25%]
core/tests/test_results.py ........................................                              [ 27%]
core/tests/test_rootcheck.py ..........                                                          [ 28%]
core/tests/test_rule.py ......................                                                   [ 29%]
core/tests/test_stats.py ....                                                                    [ 30%]
core/tests/test_syscollector.py ...                                                              [ 30%]
core/tests/test_utils.py ....................................................................... [ 34%]
................................................................................................ [ 40%]
........................................................                                         [ 44%]
core/tests/test_vulnerability.py .                                                               [ 44%]
core/tests/test_wazuh_queue.py ..................                                                [ 45%]
core/tests/test_wazuh_socket.py ....................                                             [ 46%]
core/tests/test_wdb.py ......................                                                    [ 48%]
rbac/tests/test_auth_context.py ..                                                               [ 48%]
rbac/tests/test_decorators.py .................................................................. [ 52%]
.......................................                                                          [ 54%]
rbac/tests/test_default_configuration.py ....................................................... [ 58%]
                                                                                                 [ 58%]
rbac/tests/test_orm.py ......................................................                    [ 61%]
rbac/tests/test_preprocessor.py ...........                                                      [ 62%]
tests/test_active_response.py ............                                                       [ 63%]
tests/test_agent.py ............................................................................ [ 67%]
.................................                                                                [ 70%]
tests/test_cdb_list.py .....................................................                     [ 73%]
tests/test_ciscat.py .................................                                           [ 75%]
tests/test_cluster.py .......                                                                    [ 75%]
tests/test_decoder.py ...................................                                        [ 78%]
tests/test_group.py ........                                                                     [ 78%]
tests/test_logtest.py ......                                                                     [ 78%]
tests/test_manager.py ..................................                                         [ 81%]
tests/test_mitre.py .......                                                                      [ 81%]
tests/test_rootcheck.py .................................................                        [ 84%]
tests/test_rule.py ........................................................                      [ 88%]
tests/test_sca.py .......                                                                        [ 88%]
tests/test_security.py ......................................................................... [ 93%]
...                                                                                              [ 93%]
tests/test_stats.py ................                                                             [ 94%]
tests/test_syscheck.py ........................                                                  [ 95%]
tests/test_syscollector.py ............                                                          [ 96%]
tests/test_task.py ............................                                                  [ 98%]
tests/test_vulnerability.py ..........................                                           [100%]

============================ 1590 passed, 14 warnings in 302.94s (0:05:02) =============================
```

### Integration tests
```
Collected tests [1]:
test_agent_DELETE_endpoints.tavern.yaml


test_agent_DELETE_endpoints.tavern.yaml 
	 6 passed, 8 warnings

```

Regards,
Víctor

### CODE REVIEW

**Review by Selutario — DISMISSED** [review]
LGTM

**Review by davidjiglesias — CHANGES_REQUESTED** [review]
Have we tried to reuse authd socket connection? Is it possible?

We have to fully profile the code flow to understand what parts of the code are taking the most time.

```
        manager_status = get_manager_status()
        is_authd_running = 'wazuh-authd' in manager_status and manager_status['wazuh-authd'] == 'running'
```
The above piece of code is being executed for each agent in a multi-agent petition when the result should be always the same, can we cache it? Or context cache if caching is problematic to detect authd stopping

**Comment by vicferpoy** [comment]
## PR update

Hello team,

As @davidjiglesias commented in https://github.com/wazuh/wazuh/pull/8950#pullrequestreview-681747290, we could improve this endpoint a bit more.

Full information in the issue: https://github.com/wazuh/wazuh/issues/8853#issuecomment-860844702

**Review by Selutario — DISMISSED** [review]
LGTM

**Review by davidjiglesias — APPROVED** [review]

**Review by davidjiglesias — APPROVED** [review]

**Pull request merged**
