### PR TITLE
Engine - Replace all LOG_<level> macros with the corresponding LOG_<level>_L

### PR DESCRIPTION
**Pull request by NahuFigueroa97**
|Related issue|
|---|
|#25455|

##  Description
This issue focuses on the development and integration of a system rule in Wazuh-Engine to detect the creation or renaming of Doas configuration files on Linux systems, based on Sigma rule [T1548](https://github.com/SigmaHQ/sigma/blob/master/rules/linux/file_event/file_event_lnx_doas_conf_creation.yml). This is a technique commonly used for privilege escalation by modifying or creating `doas.conf` files. The objective is to create a detection rule that monitors such file events for signs of potential malicious activity.

### CODE REVIEW

**Review by juliancnn — CHANGES_REQUESTED** [review]
Can we change the variable names? `getLambdaName` is a std::string not a function. 
On the other hand, I see unnecessary and dangerous to create a pointer to the content of the std::string with `c_str()`, fmt should accept std::string and if not, we can modify the macro to solve this at compile time and if it is a string call c_str(), we avoid RAW pointers to memories that we do not handle.

**Review by juliancnn — APPROVED** [review]
LGTM!

**Review by JcabreraC — APPROVED** [review]
LGTM !

**Review by JavierBejMen — APPROVED** [review]
LGTM

**Comment by JcabreraC** [comment]
To get the PR approved, all checks must be successfully passed. A rebase with master is required for this to happen.

**Comment by JcabreraC** [comment]
Compile fail: https://github.com/wazuh/wazuh/actions/runs/10808466232/job/29981520670?pr=25584

**Review by JavierBejMen — APPROVED** [review]
LGTM

**Review by juliancnn — APPROVED** [review]
LGTM!

**Review by JcabreraC — APPROVED** [review]
LGTM !

**Pull request merged**
