### PR TITLE
Engine - cis-cat decoder

### PR DESCRIPTION
**Pull request by LucioDonda**
|Related issue|
|---|
|#13523|

## Description

As part of epic #13038 it is necessary to decode the cis-cat events.

To achieve this it was needed some tasks:
  - [x] design the decoder itself using the helpers needed
  - [x] check with cis-cat logs
  - [x] Create a set of events with those logs and consume them

### CODE REVIEW

**Comment by LucioDonda** [comment]
In order to test it in a more accurate environment, I'm uploading events and alerts generated on a ubuntu 16 agent.
[CIS-CAT_logsAndalerts.zip](https://github.com/wazuh/wazuh/files/9095927/CIS-CAT_logsAndalerts.zip)

**Review by juliancnn — APPROVED** [review]
LGTM!

**Review by LucioDonda — COMMENTED** [review]
LGTM

**Review by nmkoremblum — APPROVED** [review]
LGTM :)

**Pull request merged**
