### PR TITLE
Fix an integer overflow in the message counter at Remoted

### PR DESCRIPTION
**Pull request by vikman90**
|Related issue|
|---|
|#11485|

As detailed on #11485, we found an integer overflow hazard in the Remoted's socket counter table, that helps to invalidate incoming messages if the source agent got disconnected at the moment to dispatch the message.

This is caused by a double value casting: `uint64` → `int32` → `uint64`.

### Bug unfixed

All these are valid messages (they must not be dropped as their counter is greater than their socket's counter:

```
Success: message_counter (1) > connection_counter (0)
Success: message_counter (2) > connection_counter (0)
Success: message_counter (3) > connection_counter (0)
Success: message_counter (4) > connection_counter (0)
Failure: message_counter (3000000002) <= connection_counter (18446744072414584321)
```

The bug made `3000000001` (`uint64`) be cast to `-1294967295` (`int32`) and then cast back to `18446744072414584321` (`uint64`).

### Bug fixed

```
Success: message_counter (3000000004) > connection_counter (3000000002)
```

## Tests

- [x] The bug addressed can't be longer reproduced.

Even setting the global message counter to 3.000.000.000, agents now connect without a problem:

```
2022/01/27 13:06:27 wazuh-agentd: INFO: Trying to connect to server (172.27.169.161:1514/tcp).
2022/01/27 13:06:27 wazuh-agentd: INFO: (4102): Connected to the server (172.27.169.161:1514/tcp).
```

- [x] Agent connection stress test: #11976.

### CODE REVIEW

**Review by TomasTurina — COMMENTED** [review]
Just one suggestion, why don't we also change the data type of `size` to `size_t` in the `rem_fdlist_t` structure?

**Comment by vicferpoy** [comment]
# Testing the fix on a large environment

To test this fix, we reproduced the bug using a large environment with modified simulated agents that would **send a keepalive every 0.1 seconds** and then modifying the message counter with a script to reach its limit.

## Environment

- Cluster environment with 1 master node and 1 worker node.
- 5 real agents, reporting to the worker node.
- 5000 simulated agents, reporting to the worker node.

## Testing steps

1. Wait until all agents (both real and simulated) are connected and active.
2. Modify the message counter to force the overflow (before the fix).
3. Monitor agent statuses and last keepalives.
4. Try to connect new agents.

## Conclusion

**Before the fix**, the already connected agents would begin to disconnect after the `agents_disconnection_time` was reached. Connecting new agents was possible, but most of them would fail to do so and those which could, would eventually disconnect as well.

**After the fix**, no agents would disconnect and their keepalives would update regularly. New agents would remain active as well.

**NOTE:** It is important to keep in mind that with the modified simulated agents, `remoted` was receiving a huge number of messages and thus discarding lots of them. This situation could affect the outcome of new connections or real agents keepalives (as these send their keepalives every 10 seconds), but eventually everything ended up working as expected.

**Comment by vikman90** [comment]
> Just one suggestion, why don't we also change the data type of `size` to `size_t` in the `rem_fdlist_t` structure?

@TomasTurina we must declare the `list` array as `size_t` because we are assigning it values from `global_counter` ([secure.c](https://github.com/wazuh/wazuh/blob/46d8fb169a3bd34c599985016c5d894d2954df50/src/remoted/secure.c#L5839)), which is `size_t` ([secure.c](https://github.com/wazuh/wazuh/blob/46d8fb169a3bd34c599985016c5d894d2954df50/src/remoted/secure.c#L28)).

However, we are setting and comparing `size` with file descriptors ([netcounter.c](https://github.com/wazuh/wazuh/blob/46d8fb169a3bd34c599985016c5d894d2954df50/src/remoted/netcounter.c#L35)), which have type `int` as function [`accept()`](https://man7.org/linux/man-pages/man2/accept.2.html) returns. The file descriptor number is limited by the internal option [`remoted.rlimit_nofile`](https://github.com/wazuh/wazuh/blob/3a833c142983b83081d8208a6cbbab0620178f1d/etc/internal_options.conf#L187-L188), and ultimately by the operating system.

**Review by TomasTurina — COMMENTED** [review]
@vikman90 If that's the case, please change the `rem_initList` function to receive an integer as a parameter to initialize the size of the connections.

**Review by TomasTurina — APPROVED** [review]

**Review by davidjiglesias — APPROVED** [review]

**Pull request merged**
