### PR TITLE
Engine validate custom fields and documentation

### PR DESCRIPTION
**Pull request by NahuFigueroa97**
### **Description**  
Automate the validation of custom fields within the indexed events, ensuring that they are properly defined, and document them for reference. Key activities include:
- [x] **Custom Field Checks**: Validate that all expected custom fields are present and correctly indexed.
- [x] **Field Documentation**: Create a structured document outlining custom fields, their types, and their descriptions.
- [x] **Schema Updates**: Identify any new fields that should be added to the schema and correct any field typing errors.

### **Acceptance Criteria**  
- Automated validation of custom fields within indexed events.
- A documented reference of custom fields, including their types and descriptions.
- Identify and resolve any issues related to new fields or incorrect field typing.

### CODE REVIEW

**Review by JcabreraC — CHANGES_REQUESTED** [review]
Rebase branch to vuln-detector test

**Review by JavierBejMen — CHANGES_REQUESTED** [review]
I think we should remove the schema files engine-schema.json and wazuh-logpar-types.json  as we no longer maintain them here.

**Review by juliancnn — APPROVED** [review]
LGTM!

**Review by JavierBejMen — APPROVED** [review]

**Review by JcabreraC — DISMISSED** [review]
LGTM !

**Review by JcabreraC — APPROVED** [review]

**Review by JavierBejMen — APPROVED** [review]

**Pull request merged**
