### PR TITLE
Fix gcc 4.4.7 warning + old logcollector coverity

### PR DESCRIPTION
**Pull request by juliancnn**
|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/7140|

Hi Team,

This PR fixes the following 2 warnings that occur when compiling with gcc 4.4.7. They could be easily checked when building the rpm with Wazuh-Package.
Also fixes a null reference error discovered in logcollector by coverity.

```
    CC shared/pthreads_op.o
shared/labels_op.c: In function 'labels_parse':
shared/labels_op.c:101: warning: missing initializer
shared/labels_op.c:101: warning: (near initialization for 'flags.system')
    CC shared/queue_linked_op.o
```
```
    CC shared/utf8_op.o
    CC shared/validate_op.o
    CC shared/vector_op.o
shared/remoted_op.c: In function 'parse_uname_string':
shared/remoted_op.c:50: warning: missing braces around initializer
shared/remoted_op.c:50: warning: (near initialization for 'match[0]')
shared/remoted_op.c:50: warning: missing initializer
shared/remoted_op.c:50: warning: (near initialization for 'match[0].rm_eo')
    CC shared/version_op.o
    CC shared/wait_op.o
    CC shared/wazuhdb_op.o
```

## Update
This PR also fixes the following warnings in ubuntu 16 (gcc 5.4.0) on agent build in release mode

```
    CC wazuh_modules/wmodules.o
In file included from ./headers/shared.h:220:0,
                 from wazuh_modules/wmodules.h:19,
                 from wazuh_modules/wm_gcp.c:12:
wazuh_modules/wm_gcp.c: In function ‘wm_gcp_main’:
./headers/debug_op.h:41:33: warning: ‘save_ptr’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 #define mtdebug1(tag, msg, ...) _mtdebug1(tag, __FILE__, __LINE__, __func__, msg, ##__VA_ARGS__)
                                 ^
wazuh_modules/wm_gcp.c:162:11: note: ‘save_ptr’ was declared here
     char *save_ptr;
           ^
```

```
    CC wazuh_modules/agent_upgrade/agent/wm_agent_upgrade_agent.o
wazuh_modules/agent_upgrade/agent/wm_agent_upgrade_agent.c: In function ‘wm_upgrade_agent_search_upgrade_result’:
wazuh_modules/agent_upgrade/agent/wm_agent_upgrade_agent.c:241:9: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
         fgets(buffer, 20, result_file);
         ^

```

Regards,
Julian

## Tests

- Compilation without warnings in every supported platform
  - [X] Linux
  - [X] Windows
  - [ ] MAC OS X
- [X] Source installation
- [x] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [x] ~Review logs syntax and correct language~
- [x] ~QA templates contemplate the added capabilities~

- Memory tests for Linux
  - [x] Scan-build report
  - [ ] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [x] ~Dr. Memory~
  - [x] ~AddressSanitizer~
- Memory tests for Windows
  - [x] ~Scan-build report~
  - [ ] Coverity
  - [x] ~Dr. Memory~
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

### CODE REVIEW

**Review by DProvinciani — APPROVED** [review]
Looks good!

**Review by jnasselle — APPROVED** [review]
LGTM!

**Comment by jnasselle** [comment]
Hi @juliancnn !
Is there a possibility to fix the following as well? The next snippets were extracted from CI

### [ubuntu_18.04][agent]
```
    [34mCC[0m [33mwazuh_modules/wm_command.o[0m
    [34mCC[0m [33mwazuh_modules/wm_ciscat.o[0m
    [34mCC[0m [33mwazuh_modules/agent_upgrade/wm_agent_upgrade.o[0m
    [34mCC[0m [33mwazuh_modules/agent_upgrade/agent/wm_agent_upgrade_agent.o[0m
wazuh_modules/agent_upgrade/agent/wm_agent_upgrade_agent.c: In function 'wm_upgrade_agent_search_upgrade_result':
wazuh_modules/agent_upgrade/agent/wm_agent_upgrade_agent.c:241:9: warning: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Wunused-result]
--
    [34mCC[0m [33msyscheckd/db/fim_db.o[0m
    [34mCC[0m [33msyscheckd/db/fim_db_files.o[0m
    [34mCC[0m [33msyscheckd/db/fim_db_registries.o[0m
    [34mCC[0m [33msyscheckd/whodata/syscheck_audit.o[0m
syscheckd/whodata/syscheck_audit.c: In function 'audit_parse':
syscheckd/whodata/syscheck_audit.c:951:33: warning: ignoring return value of 'realpath', declared with attribute warn_unused_result [-Wunused-result]
```
### [ubuntu_16.04][agent]
```
    [34mCC[0m [33mwazuh_modules/wm_gcp.o[0m
In file included from ./headers/shared.h:220:0,
                 from wazuh_modules/wmodules.h:19,
                 from wazuh_modules/wm_gcp.c:12:
wazuh_modules/wm_gcp.c: In function 'wm_gcp_main':
./headers/debug_op.h:41:33: warning: 'save_ptr' may be used uninitialized in this function [-Wmaybe-uninitialized]
```
Those are the easy-to-fix group. The next challenge is to fix the ones introduced by gcc10 :)

Regards,
Nico

**Review by Lopuiz — APPROVED** [review]

**Review by TomasTurina — APPROVED** [review]

**Review by jnasselle — APPROVED** [review]
LGTM!

**Review by JcabreraC — APPROVED** [review]

**Pull request merged**
