### PR TITLE
Backport integrity clear fix

### LINKED ISSUE #13876: Integrity_check_clear not works [Backport to 4.4]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.x | RSync | Agent | Packages/Sources | OS version |

| Related issue |
|---|
| Backport of https://github.com/wazuh/wazuh/issues/13188 |

## Description

We have seen that the `integrity_check_clear` command isn't sent by syscollector when the database is empty. 

# Steps to reproduce
- Install only one hotfix.
- Start the Wazuh agent and wait until the manager database is updated.
- Shutdown the Wazuh agent and delete uninstall service pack
- Start the Wazuh agent and check that the command isn't sent.
- Also, check the manager database the entries are not removed.

# QA coverage
https://github.com/wazuh/wazuh-qa/issues/3008

### PR DESCRIPTION
**Pull request by Dwordcito**
|Related issue|
|---|
|Closes #13876 |

## Description

We have seen that the `integrity_clear` command isn't sent by syscollector when the database is empty. 

# Steps to reproduce
- Install only one hotfix.
- Start the Wazuh agent and wait until the manager database is updated.
- Shutdown the Wazuh agent and delete uninstall service pack
- Start the Wazuh agent and check that the command isn't sent.
- Also, check the manager database the entries are not removed.

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

### CODE REVIEW

**Review by jnasselle — APPROVED** [review]

**Comment by jnasselle** [comment]
# Address Sanitizer for Sysinfo test tool :green_circle: 
Amazon Linux 2 (RPM based on BerkeleyDB) log: 
[asan_al2.txt](https://github.com/wazuh/wazuh/files/8919383/asan_al2.txt)
Amazon Linux 2022 (RPM based on SQLite, using wazuh's librpm) log: 
[asan_al2022.txt](https://github.com/wazuh/wazuh/files/8919382/asan_al2022.txt)

**Comment by jmv74211** [comment]
## QA review

- **Type**: Manual testing.
- **Status**: Requested changes 🟡 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3008
- **Comments**: Everything seems to work properly, although it has been reported [in this issue](https://github.com/wazuh/wazuh/issues/14769) that the `DEBUG` line does not appear. It is requested that the case be reviewed and the appropriate fixes be added. There are also red PR checks, so for now the PR is blocked.

**Comment by Dwordcito** [comment]
> ## QA review
> 
>     * **Type**: Manual testing.
> 
>     * **Status**: Requested changes yellow_circle
> 
>     * **Testing issue**: [Validate `integrity_clear` 4.4 backport wazuh-qa#3008](https://github.com/wazuh/wazuh-qa/issues/3008)
> 
>     * **Comments**: Everything seems to work properly, although it has been reported [in this issue](https://github.com/wazuh/wazuh/issues/14769) that the `DEBUG` line does not appear. It is requested that the case be reviewed and the appropriate fixes be added. There are also red PR checks, so for now the PR is blocked.

@jmv74211 We will solve what you mention in another issue, since it is a feature to add the logging mechanism for this library. Said issue is in triage for a later release, since 4.4 is closed. Could you clarify if this issue is approved by QA? The checks are already green.

**Review by pereyra-m — DISMISSED** [review]

**Comment by Dwordcito** [comment]
After a talk with the QA team I have the approve for the merge. The logging mechanism initially goes to 4.5 depending on whether it is formally added to the todo list.

**Review by pereyra-m — APPROVED** [review]

**Pull request merged**
