### PR TITLE
Let FIM expand Windows wildcards

### LINKED ISSUE #2723: Wildcard (*) usage on syscheck
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.8.2 | Manager/Agent | Any | Unix/Windows |

---

Hello team,

Even if there is no documentation about wildcard usage on Syscheck configuration, wildcards (*) can be used, nevertheless they are not working properly.

**Unix:** Using wildcards (*) on Unix agents will expand the directories/subdirectories search as expected but any new directory that is created on realtime will requiere the agent to be restarted.

Examples using (*): 
`<directories check_all="yes">/opt/test/*</directories>`
`<directories check_all="yes">/opt/test/*/testSub/</directories>`

**Windows:** Using wildcards (*) on Windows is not working at all.

Examples using (*): 
`<directories check_all="yes">E:\test\*</directories>`
`<directories check_all="yes">E:\test\*\testSub\</directories>`

It will be nice for Syscheck to fully support wildcards. Proper documentation will be needed as well.

Cheers!

### PR DESCRIPTION
**Pull request by antoniomanuelfr**
|Related issue|
|---|
|#2723|

## Description
Hi team!

This PR aims to add the expansion of wildcards functionality to the Windows Agent. 
Closes #2723
## Configuration options
```xml
  <!-- File integrity monitoring -->
  <syscheck>
    <disabled>no</disabled>
    <!-- Frequency that syscheck is executed default every 12 hours -->
    <frequency>20</frequency>
    <!-- Default files to be monitored. -->
    <directories>c:\windows\a*</directories>
</syscheck>
```
### wazuh logs
```
2021/04/30 11:47:19 wazuh-agent: INFO: (6003): Monitoring path: 'c:\windows\AppCompat', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | scheduled'.
2021/04/30 11:47:19 wazuh-agent: INFO: (6003): Monitoring path: 'c:\windows\AppPatch', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | scheduled'.
2021/04/30 11:47:19 wazuh-agent: INFO: (6003): Monitoring path: 'c:\windows\addins', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | scheduled'.
2021/04/30 11:47:19 wazuh-agent: INFO: (6003): Monitoring path: 'c:\windows\asdfasdfas.txt', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | scheduled'.
2021/04/30 11:47:19 wazuh-agent: INFO: (6003): Monitoring path: 'c:\windows\assembly', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | scheduled'.
2021/04/30 11:47:19 wazuh-agent: INFO: Started (pid: 2640).
```
### Files and folders inside `C:\windows` that starts with  `a`
```

PS C:\Users\windows> dir C:\windows\a*
    Directory: C:\windows
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       14/07/2009      6:32                addins
d-----       14/07/2009      4:20                AppCompat
d-----       12/04/2011     10:10                AppPatch
d-r-s-       24/09/2019     16:34                assembly
-a----       10/03/2021     13:52              0 asdfasdfas.txt

```

- Compilation without warnings in every supported platform
  - [X] Windows
- [X] Source installation
- [X] Source upgrade
- Memory tests for Windows
  - [x] Scan-build report
  - [ ] Coverity
  - [x] Dr. Memory

### CODE REVIEW

**Review by jotacarma90 — COMMENTED** [review]
The PR and code are nice. Testing I have found that when using the wildcard "?", the empty string is accepted as a character, while in Linux, using glob, the empty string is not included. 
For the rest, I have made the necessary tests and everything is fine.

**Comment by antoniomanuelfr** [comment]
> The PR and code are nice. Testing I have found that when using the wildcard "?", the empty string is accepted as a character, while in Linux, using glob, the empty string is not included.
> For the rest, I have made the necessary tests and everything is fine.

We have been checking this behavior, and it looks like the function `FindFristFile` matches one character any times. To test this, I added the following warning in  `file_op.c:2103` 
```
mwarn("Expanded file %s", FindFileData.cFileName);
```
and with the following setup: 
```xml
    <directories check_all="yes" realtime="yes">c:\test?</directories>
```
```
PS C:\Users\windows> dir C:\test*
    Directory: C:\
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       12/05/2021     13:13                test
d-----       28/04/2021     10:01                test1
d-----       28/04/2021     10:48                test123
d-----       28/04/2021     10:48                test12543
d-----       12/05/2021     13:13                test2
d-----       12/05/2021     13:13                test3
-a----       27/04/2021     15:43              0 test1sadfasdfasdf.txt
```

And the `test` folder is expanded:
```
2021/05/12 13:19:37 wazuh-agent[2368] file_op.c:2103 at expand_win32_wildcards(): WARNING: Expanded file test
2021/05/12 13:19:37 wazuh-agent[2368] file_op.c:2103 at expand_win32_wildcards(): WARNING: Expanded file test1
2021/05/12 13:19:37 wazuh-agent[2368] file_op.c:2103 at expand_win32_wildcards(): WARNING: Expanded file test2
2021/05/12 13:19:37 wazuh-agent[2368] file_op.c:2103 at expand_win32_wildcards(): WARNING: Expanded file test
```

**Review by Molter73 — APPROVED** [review]
LGTM!

**Comment by antoniomanuelfr** [comment]
These are the result of the integration test (tier 0,1,2) in Jenkins:
[jenkins_report.zip](https://github.com/wazuh/wazuh/files/6492332/jenkins_report.zip)
There are 3 errors and 1 failure. After checking it, none of these errors are related to this PR as the errors are caused due to a permission error.
Checking it locally, the test with failures passed:
[report_deleted_diff.zip](https://github.com/wazuh/wazuh/files/6492469/report_deleted_diff.zip)
The tests with errors are failing locally, but it's not related to the changes introduced in this PR.

**Review by vikman90 — APPROVED** [review]

**Pull request merged**
