### PR TITLE
Fixes segfault when can not connect to wdb

### LINKED ISSUE #8913: Wazuh-analysisd segfault when processing logs without a previous successful connection to wdb (mitre)
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| master (4.3) >= | `wazuh-analysisd` | Manager | Any | GNU/Linux |

Hi Team!,

When `wazuh-analysisd` fails to connect to the `wdb` and get the data from the Mitre ATT&CK, the technique map is not initialized. 
Then, when processing any log that matches a rule with `<mitre>` label, a segmentation fault happens.
This is true for `wazuh-logtest`, and as well for `wazuh-analysisd`.

Steps to reproduce it:

1.  Stop Wazuh-Manager
```
systemctl stop wazuh-manager
```
2. Launch only `wazuh-analysisd`:
```
/var/ossec/bin/wazuh-analysisd -fd
```
3. Test the following log using `wazuh-logtest`:
```
Oct 15 21:07:00 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928
```

Regards,
Julian.

### PR DESCRIPTION
**Pull request by juliancnn**
|Related issue|
|---|
|Closes #8913 |

## Description

Hi team!,

When wazuh-analysisd fails to connect to the wdb and get the data from the Mitre ATT&CK, the technique map is not initialized.
This PR adds a check when getting the mitre technique from the map, avoiding the segfault.

### Master:
Valgrind report
```
==186723== Thread 3:
==186723== Invalid read of size 4
==186723==    at 0x2538A9: _os_genhash (hash_op.c:99)
==186723==    by 0x25424B: OSHash_Get (hash_op.c:381)
==186723==    by 0x122B1A: mitre_get_attack (mitre.c:240)
==186723==    by 0x14FAF1: Eventinfo_to_jsonstr (to_json.c:197)
==186723==    by 0x141B8C: w_logtest_process_log (logtest.c:217)
==186723==    by 0x14487D: w_logtest_process_request_log_processing (logtest.c:1068)
==186723==    by 0x14435F: w_logtest_process_request (logtest.c:993)
==186723==    by 0x141807: w_logtest_clients_handler (logtest.c:143)
==186723==    by 0x14136C: w_logtest_init (logtest.c:64)
==186723==    by 0x50C3608: start_thread (pthread_create.c:477)
==186723==    by 0x51FF292: clone (clone.S:95)
==186723==  Address 0x4 is not stack'd, malloc'd or (recently) free'd
```

[Valgrind master full report.log](https://github.com/wazuh/wazuh/files/6611419/Valgrind.master.log)

### PR: 
[scan build](https://github.com/wazuh/wazuh/files/6611403/scan.zip)
[Valgrind_Report.log](https://github.com/wazuh/wazuh/files/6611401/ValgrindPRs.log)

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] ~Windows~
  - [x] ~MAC OS X~
- [x] Source installation
- [x] ~Package installation~
- [x] Source upgrade
- [x] ~Package upgrade~
- [x] ~Review logs syntax and correct language~
- [x] ~QA templates contemplate the added capabilities~

- Memory tests for Linux
  - [x] Scan-build report
  - [ ] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [x] ~Dr. Memory~
  - [x] ~AddressSanitizer~
- ~Memory tests for Windows~
- ~Memory tests for macOS~

- [x] ~Retrocompatibility with older Wazuh versions~
- [x] ~Working on cluster environments~
- [x] ~Configuration on demand reports new parameters~
- [x] ~The data flow works as expected (agent-manager-api-app)~
- [x] ~Added unit tests (for new features)~
- [x] ~Stress test for affected components~

### CODE REVIEW

**Review by jnasselle — DISMISSED** [review]

**Review by jnasselle — COMMENTED** [review]
Will wait for wazuh/wazuh-qa#1421 merge and Jenkins checks for approval

**Review by JcabreraC — APPROVED** [review]
LGTM !

**Review by TomasTurina — DISMISSED** [review]
LGTM!

**Review by jnasselle — APPROVED** [review]

**Review by JcabreraC — APPROVED** [review]

**Review by TomasTurina — APPROVED** [review]
LGTM!

**Review by jnasselle — APPROVED** [review]

**Review by nmkoremblum — APPROVED** [review]
LGTM :)

**Pull request merged**
