### PR TITLE
Restored and renamed ossec-logtest

### PR DESCRIPTION
**Pull request by JcabreraC**
|Related issue|
|---|
|#7806|

## Description

Hello team,

This issue is to restore the `ossec-logtest` binary and rename it to `wazuh-logtest.legacy`

The reason is the new `wazuh-logtest` which is an `wazuh-analysisd` thread, does not have the functionality to test newly created files, due to the loading of the `wazuh-analysisd` configuration.

## Tests

- Compilation without warnings in every supported platform
  - [X] Linux
  - [X] ~Windows~
  - [X] ~MAC OS X~
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [x] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [X] ~Scan-build report~
  - [X] ~Coverity~
  - [X] ~Valgrind (memcheck and descriptor leaks check)~
  - [X] ~Dr. Memory~
  - [X] ~AddressSanitizer~
- Memory tests for Windows
  - [X] ~Scan-build report~
  - [X] ~Coverity~
  - [X] ~Dr. Memory~
- Memory tests for macOS
  - [X] ~Scan-build report~
  - [X] ~Leaks~
  - [X] ~AddressSanitizer~

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [X] ~Added unit tests (for new features)~
- [X] ~Stress test for affected components~

Regards.

### CODE REVIEW

**Comment by jnasselle** [comment]
## `runtest.py` execution
```
/runtests.py                                                                                                                                                        130 ↵
- [ File = ./tests/sudo.ini ] ---------
........

- [ File = ./tests/nextcloud.ini ] ---------
.......

- [ File = ./tests/su.ini ] ---------
.....

- [ File = ./tests/pfsense.ini ] ---------
..

- [ File = ./tests/pix.ini ] ---------
......................

- [ File = ./tests/openvpn_ldap.ini ] ---------
..

- [ File = ./tests/apache.ini ] ---------
............

- [ File = ./tests/syslog.ini ] ---------
......

- [ File = ./tests/sophos.ini ] ---------
........

- [ File = ./tests/postfix.ini ] ---------
..

- [ File = ./tests/pam.ini ] ---------
.....

- [ File = ./tests/checkpoint_smart1.ini ] ---------
..................

- [ File = ./tests/SonicWall.ini ] ---------
........

- [ File = ./tests/firewalld.ini ] ---------
..

- [ File = ./tests/mcafee_epo.ini ] ---------
.

- [ File = ./tests/cisco_ios.ini ] ---------
...............

- [ File = ./tests/iptables.ini ] ---------
........

- [ File = ./tests/apparmor.ini ] ---------
.....

- [ File = ./tests/squid_rules.ini ] ---------
..

- [ File = ./tests/oscap.ini ] ---------
................................

- [ File = ./tests/macos-sshd.ini ] ---------
.....................

- [ File = ./tests/exim.ini ] ---------
.....

- [ File = ./tests/panda_paps.ini ] ---------
........

- [ File = ./tests/sysmon.ini ] ---------
...

- [ File = ./tests/systemd.ini ] ---------
..

- [ File = ./tests/opensmtpd.ini ] ---------
.......

- [ File = ./tests/cimserver.ini ] ---------
..

- [ File = ./tests/api.ini ] ---------
.........

- [ File = ./tests/cpanel.ini ] ---------
.......

- [ File = ./tests/netscreen.ini ] ---------
....

- [ File = ./tests/web_rules.ini ] ---------
.....

- [ File = ./tests/sshd.ini ] ---------
...........................

- [ File = ./tests/auditd.ini ] ---------
.

- [ File = ./tests/paloalto.ini ] ---------
....

- [ File = ./tests/owlh.ini ] ---------
....

- [ File = ./tests/nginx.ini ] ---------
............

- [ File = ./tests/modsecurity.ini ] ---------
......

- [ File = ./tests/vsftpd.ini ] ---------
....

- [ File = ./tests/openldap.ini ] ---------
.........

- [ File = ./tests/cisco_asa.ini ] ---------
........................................................................................

- [ File = ./tests/rsh.ini ] ---------
..

- [ File = ./tests/dovecot.ini ] ---------
...............

- [ File = ./tests/ossec.ini ] ---------
.....

- [ File = ./tests/unbound.ini ] ---------


- [ File = ./tests/mailscanner.ini ] ---------
.

- [ File = ./tests/junos.ini ] ---------
...

- [ File = ./tests/samba.ini ] ---------
....

- [ File = ./tests/sophos_fw.ini ] ---------
..........

- [ File = ./tests/named.ini ] ---------
.....

- [ File = ./tests/web_appsec.ini ] ---------
...............................

- [ File = ./tests/proftpd.ini ] ---------
.......

- [ File = ./tests/dropbear.ini ] ---------
...

- [ File = ./tests/doas.ini ] ---------
....
```

**Review by jnasselle — CHANGES_REQUESTED** [review]
Nice work @JcabreraC! But after installing from this branch, `wazuh-logtest.ignore` file from sources was modified with the content of  `generic_wrapper.sh`. This should be fixed by adding a `.py` to wildcard command in `framework/Makefile`
image

Regards,
Nico

**Review by juliancnn — APPROVED** [review]

**Review by jnasselle — APPROVED** [review]
LGTM!

**Review by nmkoremblum — APPROVED** [review]
LGTM :)

**Pull request merged**
