### PR TITLE
Removing all references to the legacy vulnerability detector module

### LINKED ISSUE #21303: Remove all references of the legacy vulnerability detector module
## Description

The vulnerability detector module has been refactored and the code of the legacy module has been removed.
Nevertheless, there are still some references to the old module that should be removed.
Here are some items but a deep search should be done during the development of the issue in case some references are missing:

- `wazuh-db`: the `vuln_cves` table in `schema_agents.sql` and any query related to this table, the triggers of `sys_programs` table in `schema_agents.sql`, the **triaged** column of `sys_programs` and any query related to this column; and any reference to `vuln_cves` in the code and tests.
- Defines and log messages: all the messages related to the legacy module defined at `src/error_messages/debug_messages.h`, `src/error_messages/information_messages.h`, and `src/error_messages/error_messages.h`
- The legacy mechanism to run a vulnerability detector scan on demand (`src/wazuh_modules/wmcom.c` and related)
- Rules related to the legacy module (rule **515** at `ruleset/rules/0015-ossec_rules.xml` and related)
- All the references related to the framework (talk with the corresponding team)
- Analyze the counters related to vulnerability detector events (`w_inc_modules_vulnerability_decoded_events()` and related)
- The feeds related to offline feeds generation in `tools/vulnerability-detector` 

**Note**: if we remove the old vulnerabilities inventory, a user that performs an upgrade from v4.7.x to v4.8.0 would lose all the data but wouldn't see the results of the new scanner because the **syscollector** agent DBs are completely synced. This behavior must be confirmed with the product owner and a mechanism to re-scan the agents after the upgrade could be considered.

## DoD

- [x] #21564
- [x] Remove all the dangling references to the old module of the code.
- [x] Make sure everything keeps working as expected.
- [x] CI Pass

### PR DESCRIPTION
**Pull request by pereyra-m**
|Related issue|
|---|
|Closes #21303 |

## Description

This PR removes all the dead code that won't be required anymore now that the new vulnerability detector will be released:
- The `vuln_cves` table (legacy alerts inventory) and all the related methods to update it
- The `triaged` column from `sys_programs` and `sys_osinfo` 
- All the dangling messages
- All the related UT

Also, the agents' DB schema was updated with the column changes and the triggers removal.

## Tests

**Manual tests:**

A fresh installation was performed with the development branch, the manager (agent `000`) reports the packages and OS inventory as expected with no ERROR/WARNING messages.

The API endpoint `GET /manager/daemons/stats` works as expected (the vulnerability detector fields are no longer present).

**Upgrade tests:**

A Wazuh v4.7.2 manager was installed and two agents were connected (v3.13.6 and v4.7.2). After both were synced, the manager was upgraded with the development branch to verify the agents' DB schema upgrade:
- The DBs were upgraded to the last version without errors
- The logs only contains non related ERROR/WARNING messages (about the legacy vulnerability detector module and the non supported **syscollector** protocol for legacy agents)
- The OS and programs tables contain the expected data and the `triaged` column is no longer present

**Tests:**

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation
- [x] Source upgrade

- [x] Retrocompatibility with older Wazuh versions
- [x] The data flow works as expected (agent-manager-api-app)
- [x] Added unit tests (for new features)

- Decoder/Rule tests
  - [x] runtests.py executed without errors

<details><summary>Details</summary>
<p>

```

|Component |  Tested  |  Total   | Coverage |
| -------- | -------- | -------- | -------- |
|  Rules   |   1381   |   4383   |  31.51%  |
| Decoders |   125    |   170    |  73.53%  |


|          File           |  Passed  |  Failed  |  Status  |
|        --------         | -------- | -------- | -------- |
|./tests/proftpd.ini      |    7     |    0     |   ✅    |
|./tests/exim.ini         |    7     |    0     |   ✅    |
|./tests/squid_rules.ini  |    2     |    0     |   ✅    |
|./tests/sysmon_eid_3.ini |    10    |    0     |   ✅    |
|./tests/amazon_sec_lake.ini|    20    |    0     |   ✅    |
|./tests/checkpoint_smart1.ini|    18    |    0     |   ✅    |
|./tests/iptables.ini     |    9     |    0     |   ✅    |
|./tests/sysmon_eid_10.ini|    4     |    0     |   ✅    |
|./tests/SonicWall.ini    |    11    |    0     |   ✅    |
|./tests/panda_paps.ini   |    8     |    0     |   ✅    |
|./tests/fortiauth.ini    |    4     |    0     |   ✅    |
|./tests/openldap.ini     |    9     |    0     |   ✅    |
|./tests/f5_big_ip.ini    |    48    |    0     |   ✅    |
|./tests/sophos.ini       |    8     |    0     |   ✅    |
|./tests/opensmtpd.ini    |    7     |    0     |   ✅    |
|./tests/netscreen.ini    |    4     |    0     |   ✅    |
|./tests/rsh.ini          |    2     |    0     |   ✅    |
|./tests/arbor.ini        |    2     |    0     |   ✅    |
|./tests/web_rules.ini    |    10    |    0     |   ✅    |
|./tests/exchange.ini     |    2     |    0     |   ✅    |
|./tests/vuln_detector.ini|    2     |    0     |   ✅    |
|./tests/postfix.ini      |    2     |    0     |   ✅    |
|./tests/macos.ini        |    11    |    0     |   ✅    |
|./tests/samba.ini        |    4     |    0     |   ✅    |
|./tests/apparmor.ini     |    5     |    0     |   ✅    |
|./tests/test_osmatch_regex.ini|    6     |    0     |   ✅    |
|./tests/test_features.ini|    7     |    0     |   ✅    |
|./tests/pam.ini          |    5     |    0     |   ✅    |
|./tests/apache.ini       |    12    |    0     |   ✅    |
|./tests/fireeye.ini      |    3     |    0     |   ✅    |
|./tests/sysmon.ini       |    25    |    0     |   ✅    |
|./tests/dovecot.ini      |    15    |    0     |   ✅    |
|./tests/nginx.ini        |    12    |    0     |   ✅    |
|./tests/nextcloud.ini    |    8     |    0     |   ✅    |
|./tests/kernel_usb.ini   |    6     |    0     |   ✅    |
|./tests/paloalto.ini     |    16    |    0     |   ✅    |
|./tests/sysmon_eid_13.ini|    9     |    0     |   ✅    |
|./tests/ossec.ini        |    5     |    0     |   ✅    |
|./tests/test_osregex_regex.ini|    28    |    0     |   ✅    |
|./tests/cisco_ftd.ini    |    42    |    0     |   ✅    |
|./tests/sysmon_eid_1.ini |    63    |    0     |   ✅    |
|./tests/github.ini       |   324    |    0     |   ✅    |
|./tests/gitlab.ini       |    27    |    0     |   ✅    |
|./tests/fortimail.ini    |    6     |    0     |   ✅    |
|./tests/named.ini        |    5     |    0     |   ✅    |
|./tests/powershell.ini   |    32    |    0     |   ✅    |
|./tests/openvpn_ldap.ini |    2     |    0     |   ✅    |
|./tests/sysmon_eid_8.ini |    4     |    0     |   ✅    |
|./tests/cloudflare-waf.ini|    13    |    0     |   ✅    |
|./tests/huawei_usg.ini   |    3     |    0     |   ✅    |
|./tests/eset.ini         |    8     |    0     |   ✅    |
|./tests/test_expr_negation.ini|    56    |    0     |   ✅    |
|./tests/gcp.ini          |    31    |    0     |   ✅    |
|./tests/cpanel.ini       |    7     |    0     |   ✅    |
|./tests/pfsense.ini      |    2     |    0     |   ✅    |
|./tests/cisco_asa.ini    |    88    |    0     |   ✅    |
|./tests/systemd.ini      |    2     |    0     |   ✅    |
|./tests/web_appsec.ini   |    31    |    0     |   ✅    |
|./tests/sysmon_eid_11.ini|    28    |    0     |   ✅    |
|./tests/cisco_ios.ini    |    17    |    0     |   ✅    |
|./tests/pix.ini          |    22    |    0     |   ✅    |
|./tests/php.ini          |    2     |    0     |   ✅    |
|./tests/office365.ini    |   128    |    0     |   ✅    |
|./tests/fortigate.ini    |    45    |    0     |   ✅    |
|./tests/audit_scp.ini    |    8     |    0     |   ✅    |
|./tests/win_application.ini|    0     |    0     |   ✅    |
|./tests/fortiddos.ini    |    3     |    0     |   ✅    |
|./tests/cimserver.ini    |    2     |    0     |   ✅    |
|./tests/freepbx.ini      |    6     |    0     |   ✅    |
|./tests/overwrite.ini    |    10    |    0     |   ✅    |
|./tests/sshd.ini         |    49    |    0     |   ✅    |
|./tests/win_event_channel.ini|    8     |    0     |   ✅    |
|./tests/test_pcre2_regex.ini|    33    |    0     |   ✅    |
|./tests/glpi.ini         |    3     |    0     |   ✅    |
|./tests/api.ini          |    21    |    0     |   ✅    |
|./tests/dropbear.ini     |    3     |    0     |   ✅    |
|./tests/firewalld.ini    |    2     |    0     |   ✅    |
|./tests/mailscanner.ini  |    1     |    0     |   ✅    |
|./tests/owlh.ini         |    4     |    0     |   ✅    |
|./tests/sysmon_eid_20.ini|    2     |    0     |   ✅    |
|./tests/oscap.ini        |    32    |    0     |   ✅    |
|./tests/mcafee_epo.ini   |    1     |    0     |   ✅    |
|./tests/doas.ini         |    4     |    0     |   ✅    |
|./tests/junos.ini        |    3     |    0     |   ✅    |
|./tests/sudo.ini         |    8     |    0     |   ✅    |
|./tests/syslog.ini       |    6     |    0     |   ✅    |
|./tests/sophos_fw.ini    |    10    |    0     |   ✅    |
|./tests/vsftpd.ini       |    4     |    0     |   ✅    |
|./tests/sysmon_eid_7.ini |    6     |    0     |   ✅    |
|./tests/modsecurity.ini  |    6     |    0     |   ✅    |
|./tests/su.ini           |    5     |    0     |   ✅    |
|./tests/unbound.ini      |    0     |    0     |   ✅    |
|./tests/aws_s3_access.ini|    10    |    0     |   ✅    |
|./tests/test_static_filters.ini|    28    |    0     |   ✅    |
|./tests/auditd.ini       |    31    |    0     |   ✅    |
```

</p>
</details>

### CODE REVIEW

**Review by MiguelazoDS — COMMENTED** [review]
GJ @pereyra-m! 

I see some references still, but we can analyze them if they can be deleted. 

- MSU references in .gitignore file
- There's some description of vuldet in README.md
- wazuh/tests has some integration test (maybe ping QA?)
- .github/workflows/integration_test (revision)
- I think we can delete this VU_WM_NAME in wmodules.h
- Do you think we should keep the scripts in tools/vulnerability-detector? maybe ping the developers of those tools
- etc/ossec.conf has some mentions to vulnerability-detector legacy
- What about the whole vulnerability detector schema schema_vuln_detector.sql?
- wazuh-template.json?
- wazuh.sh there are references to the cve.db database
- 0505-vulns_rules.yml?
- Makefile, there is a reference (vulnerability_detector)
- Do you think the find_package is still useful? 
- Are you sure we can delete this w_inc_agent_vul_detector, w_inc_agent_vul_detector_time? Aren't they still valid for the refactor?
- We need this wdb_agents_get_hotfixes and this __wrap_wdb_agents_get_hotfixes?

**Comment by pereyra-m** [comment]
Thank you @MiguelazoDS!

I'll try to give you my thoughts about all the items:
- **MSU references in .gitignore file**: Good catch! Removed. It also makes me think of the `msu_name` column but it's out of scope.
- **There's some description of vuldet in README.md**: These references aren't specific to the legacy module, I'd leave them if you agree.
- **wazuh/tests has some integration test (maybe ping QA?)**: There are some legacy vuln-det tests in `.github/workflows/integration-tests-vulnerability_detector-tier-0-1.yml` and `.github/workflows/integration-tests-vulnerability_detector-tier-2.yml`. But they were skipped by the QA team, so I assumed they were going to remove them.
- **.github/workflows/integration_test (revision)**: same as above.
- **I think we can delete this VU_WM_NAME in wmodules.h**: this seems related to the configuration read methods. We could analyze this again.
- **Do you think we should keep the scripts in tools/vulnerability-detector? maybe ping the developers of those tools**: they were in the initial list of the issue. But I left them only because those links are still valid. Now, the new vulnerability detector will never use them. Removed.
- **etc/ossec.conf has some mentions to vulnerability-detector legacy**: Maybe this file isn't used anymore, but I removed it anyway. Thank you.
- **What about the whole vulnerability detector schema schema_vuln_detector.sql?**: Good catch, thank you!
- **wazuh-template.json?**: This file isn't related to the legacy vuln-det I think. 
- **wazuh.sh there are references to the cve.db database**: I'd leave them because of the upgrade process.
- **0505-vulns_rules.yml?**: We could analyze this. Because we currently use `ruleset/rules/0520-vulnerability-detector_rules.xml`. There is other file that seems old `ruleset/rules/0505-vuls_rules.xml` but in `src/init/wazuh/deprecated_ruleset.txt` we have `0520` instead of `0505`. I'll ask threat intel team.
- **Makefile, there is a reference (vulnerability_detector)**: You are right, thank you!
- **Do you think the find_package is still useful?**: Good question. I don't find a good use it for this right now, but I'd leave it for now if you ask me.
- **Are you sure we can delete this w_inc_agent_vul_detector, w_inc_agent_vul_detector_time? Aren't they still valid for the refactor?**: I removed them because they count the time `wazuh-db` takes processing the queries related to the table `vuln_cves` and now it doesn't exist. 
- **We need this wdb_agents_get_hotfixes and this __wrap_wdb_agents_get_hotfixes?**: We might need it soon in the new vulnerability detector.

**Comment by MiguelazoDS** [comment]
> Thank you @MiguelazoDS!
> 
> I'll try to give you my thoughts about all the items:
> 
>     * **MSU references in .gitignore file**: Good catch! Removed. It also makes me think of the `msu_name` column but it's out of scope.
> 
>     * **There's some description of vuldet in README.md**: These references aren't specific to the legacy module, I'd leave them if you agree.
> 
>     * **wazuh/tests has some integration test (maybe ping QA?)**: There are some legacy vuln-det tests in `.github/workflows/integration-tests-vulnerability_detector-tier-0-1.yml` and `.github/workflows/integration-tests-vulnerability_detector-tier-2.yml`. But they were skipped by the QA team, so I assumed they were going to remove them.
> 
>     * **.github/workflows/integration_test (revision)**: same as above.
> 
>     * **I think we can delete this VU_WM_NAME in wmodules.h**: this seems related to the configuration read methods. We could analyze this again.
> 
>     * **Do you think we should keep the scripts in tools/vulnerability-detector? maybe ping the developers of those tools**: they were in the initial list of the issue. But I left them only because those links are still valid. Now, the new vulnerability detector will never use them. Removed.
> 
>     * **etc/ossec.conf has some mentions to vulnerability-detector legacy**: Maybe this file isn't used anymore, but I removed it anyway. Thank you.
> 
>     * **What about the whole vulnerability detector schema schema_vuln_detector.sql?**: Good catch, thank you!
> 
>     * **wazuh-template.json?**: This file isn't related to the legacy vuln-det I think.
> 
>     * **wazuh.sh there are references to the cve.db database**: I'd leave them because of the upgrade process.
> 
>     * **0505-vulns_rules.yml?**: We could analyze this. Because we currently use `ruleset/rules/0520-vulnerability-detector_rules.xml`. There is other file that seems old `ruleset/rules/0505-vuls_rules.xml` but in `src/init/wazuh/deprecated_ruleset.txt` we have `0520` instead of `0505`. I'll ask threat intel team. UPDATE: this is related to the upgrade process and it should be kept.
> 
>     * **Makefile, there is a reference (vulnerability_detector)**: You are right, thank you!
> 
>     * **Do you think the find_package is still useful?**: Good question. I don't find a good use it for this right now, but I'd leave it for now if you ask me.
> 
>     * **Are you sure we can delete this w_inc_agent_vul_detector, w_inc_agent_vul_detector_time? Aren't they still valid for the refactor?**: I removed them because they count the time `wazuh-db` takes processing the queries related to the table `vuln_cves` and now it doesn't exist.
> 
>     * **We need this wdb_agents_get_hotfixes and this __wrap_wdb_agents_get_hotfixes?**: We might need it soon in the new vulnerability detector.

Hi @pereyra-m, 

- Referring to the wazuh-template.json I see it is very old https://github.com/wazuh/wazuh/commit/d6ea9b81b8195256018a03731728f2ef2ca8cd2a, but I don't have in mind the consequences of deleting that, so I think we could keep it. 
- I missed that case for wazuh.sh, good point!
- Perfect to keep 0505-vulns_rules.yml also!

Great! thanks for the clarifications.

**Review by MiguelazoDS — APPROVED** [review]

**Review by Selutario — APPROVED** [review]
LGTM, additional references on the framework and API side will be removed once [this PR](https://github.com/wazuh/wazuh/pull/21542) is merged. The same happens with the failing API test, which should be fixed as part of:
- https://github.com/wazuh/qa-integration-framework/pull/88

**Review by Selutario — COMMENTED** [review]
I opened a PR in qa-integration-framework since I realized that the statistics template was not updated:
- https://github.com/wazuh/qa-integration-framework/pull/89

I rerun the failed job, it should work now.

**Comment by sebasfalcone** [comment]
@Dwordcito All green and ready to be merged

**Pull request merged**
